### ISSUE TITLE
PHP readonly properties and inheritance cause error on hydration

### ISSUE THREAD

**Issue by chapterjason** [doctrine/doctrine2#10049]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.13.1

#### Summary

Using php readonly properties and inheritance (changing scope) causes an error while trying to set the property in the hydration process.

#### Current behavior

<details>
<summary>Error from the doctrine reproducer</summary>

```
PHP Fatal error:  Uncaught Error: Cannot initialize readonly property Chapterjason\DoctrineReadonlyReproducer\ValueObject\AggregatedRootId::$value from scope Chapterjason\DoctrineReadonlyReproducer\ValueObject\BookId in /[...]/doctrine-readonly-reproducer/vendor/doctrine/persistence/src/Persistence/Reflection/RuntimePublicReflectionProperty.php:59
Stack trace:
#0 /[...]/doctrine-readonly-reproducer/vendor/doctrine/persistence/src/Persistence/Reflection/RuntimePublicReflectionProperty.php(59): ReflectionProperty->setValue(Object(Chapterjason\DoctrineReadonlyReproducer\ValueObject\BookId), 'agri-632b6cb768...')
#1 /[...]/doctrine-readonly-reproducer/vendor/doctrine/persistence/src/Persistence/Reflection/TypedNoDefaultReflectionPropertyBase.php(64): Doctrine\Persistence\Reflection\RuntimePublicReflectionProperty->setValue(Object(Chapterjason\DoctrineReadonlyReproducer\ValueObject\BookId), 'agri-632b6cb768...')
#2 /[...]/doctrine-readonly-reproducer/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ReflectionReadonlyProperty.php(40): Doctrine\Persistence\Reflection\TypedNoDefaultRuntimePublicReflectionProperty->setValue(Object(Chapterjason\DoctrineReadonlyReproducer\ValueObject\BookId), 'agri-632b6cb768...')
#3 /[...]/doctrine-readonly-reproducer/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ReflectionEmbeddedProperty.php(81): Doctrine\ORM\Mapping\ReflectionReadonlyProperty->setValue(Object(Chapterjason\DoctrineReadonlyReproducer\ValueObject\BookId), 'agri-632b6cb768...')
#4 /[...]/doctrine-readonly-reproducer/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2753): Doctrine\ORM\Mapping\ReflectionEmbeddedProperty->setValue(Object(Chapterjason\DoctrineReadonlyReproducer\Entity\Book), 'agri-632b6cb768...')
#5 /[...]/doctrine-readonly-reproducer/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php(156): Doctrine\ORM\UnitOfWork->createEntity('Chapterjason\\Do...', Array, Array)
#6 /[...]/doctrine-readonly-reproducer/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php(63): Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator->hydrateRowData(Array, Array)
#7 /[...]/doctrine-readonly-reproducer/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(270): Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator->hydrateAllData()
#8 /[...]/doctrine-readonly-reproducer/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(758): Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll(Object(Doctrine\DBAL\Result), Object(Doctrine\ORM\Query\ResultSetMapping), Array)
#9 /[...]/doctrine-readonly-reproducer/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(768): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load(Array, NULL)
#10 /[...]/doctrine-readonly-reproducer/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(521): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->loadById(Array)
#11 /[...]/doctrine-readonly-reproducer/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(199): Doctrine\ORM\EntityManager->find('Chapterjason\\Do...', Array, NULL, NULL)
#12 /[...]/doctrine-readonly-reproducer/index.php(34): Doctrine\ORM\EntityRepository->find('agri-632b6cb768...')
#13 {main}
  thrown in /[...]/doctrine-readonly-reproducer/vendor/doctrine/persistence/src/Persistence/Reflection/RuntimePublicReflectionProperty.php on line 59
```

</details>

#### How to reproduce

Simplified reproducer [https://onlinephp.io/c/57532](https://onlinephp.io/c/57532):

```php
<?php

abstract class AggregateRootId implements Stringable
{
    public readonly string $value;

    final public function __construct(?string $value = null)
    {
        $this->value = $value ?? "test";
    }

    public function __toString(): string
    {
        return $this->value;
    }
}

final class BookId extends AggregateRootId
{
}

$ref = new ReflectionClass(BookId::class);
$instance = $ref->newInstanceWithoutConstructor();
$prop = $ref->getProperty('value');
$prop->setValue($instance, 'new-id');
```

I also created a reproducer with doctrine [https://github.com/chapterjason/doctrine-readonly-reproducer](https://github.com/chapterjason/doctrine-readonly-reproducer) but if you want I can make a reproducer with a pull request.

#### Expected behavior

The readonly property will be hydrated as expected.

**Comment by derrabus** [comment]
Confirmed. Would you be able to work on a fix?

**Comment by chapterjason** [comment]
I'm looking at that. I have an idea too, just have to try it out. Have also already looked at the [RFC](https://wiki.php.net/rfc/readonly_properties_v2)

**Comment by michnovka** [comment]
Acknowledging and confirming the issue, is there actually any meaningful use of readonly properties for entities? Readonly entities I get - you want them just hydrated and avoid any possibility of being modified. But enforcing this just on a field level seems only problematic. See my comment on the subject here - https://github.com/doctrine/orm/pull/10097#issuecomment-1273520863

**Comment by chapterjason** [comment]
Hey @michnovka, sure there are.

In DDD it can happen that your id is represented as a Value Object, which means it is immutable by definition.
Also, if you are working with a system that isn't a monolith, microservices, for example, you have your Ids (ULID/UUID/GUID) generated before you persist the entity.

Which my example above shows is this case:

```php

use Symfony\Component\Uid\Ulid;
use Doctrine\ORM\Mapping as ORM;

abstract class AggregateRootId implements Stringable
{
    /**
     * Public to be easily accessible and read-only to be immutable. 
     */
    #[ORM\Id]
    #[ORM\Column(name: 'id', type: 'string')]
    public readonly Ulid $value;

    final public function __construct(? Ulid $value = null)
    {
        $this->value = $value ?? new Ulid();
    }

    public function __toString(): string
    {
        return $this->value;
    }
}

#[ORM\Embeddable]
final class BookId extends AggregateRootId
{
}

#[ORM\Entity]
class Book
{
    #[ORM\Embedded(columnPrefix: false)]
    public BookId $id;

    public function __construct(?BookId $id = null)
    {
        $this->id = $id ?? new BookId();
    }
}
```

**Comment by michnovka** [comment]
@chapterjason thanks for the example. So what is the expected behavior when you do `EntityManager#delete()` on a persisted hydrated object? What should happen with the `Book::$id` field? And if the property were not readonly, what happens now in that case?

**Comment by chapterjason** [comment]
@michnovka As it is not managed anymore by the database, I wouldn't touch any of the properties. It isn't part of this issue. This is just a generic set of read-only properties in inheritance. It is already working in doctrine for simple classes but not for classes that use inheritance. (See #10059)

**Comment by michnovka** [comment]
@chapterjason seems like the solution is to use reflection property of the parent - https://onlinephp.io/c/5b461

But this will add some overhead to every hydration - we have to call `ReflectionProperty::getDeclaringClass` on every property and then compare it with the original `ReflectionClass` instance. Not sure how this works internally, if but I can imagine that initializing all these `ReflectionClass` objects does cost some CPU and memory.

**Comment by chapterjason** [comment]
@michnovka Performance are one of my concerns, too. As you can see in the PR I already changed the code. It will now only check the declaring class in case it is a readonly property. Thanks!
