### ISSUE TITLE
EntityNotFoundException after second flush when deleting item of ManyToMany relationship

### ISSUE THREAD

**Issue by klammbueddel** [doctrine/doctrine2#10060]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.13.2

#### Summary

Given two entities `$a` and `$b` of type `A` and `B`, referenced via `ManyToMany` relationship. If one of them is delete via `$entityManager->remove($a)`, a second call to `$entityManager->flush()` will result in an `EntityNotFoundException`.

#### Current behavior

During the first `flush()` `$a` is deleted from the database. Plus, it is removed from `$b->items`. This makes `$b->items` dirty. Next call to `flush()` will try to sync empty `$b->items` with the database by trying to delete `$a`, which is already removed, leading to the EntityNotFoundException.

#### How to reproduce

```
$a = new A();
$b = new B();
$b->items->add($a);
$a->items->add($b);

$this->em->persist($b);
$this->em->persist($a);
$this->em->flush();

$this->em->remove($a);
$this->em->flush();
$this->em->flush(); < throws EntityNotFoundException 
``` 

#### Expected behavior

I think `flush()` should sync the memory state to the database leaving all entites in a clean state. Multiple calls to `flush()` should always be possible without sideeffects.

**Comment by andreas-aeschlimann** [comment]
We encountered a similar error. What is the proper way to workaround this issue?

**Comment by klammbueddel** [comment]
Hard to tell. I think it depends on your context. If you know the behaviour you might want to catch the error or avoid double flushes. I think I kind of worked around it that way. Still I think it's worth being fixed appropriate.

**Comment by andreas-aeschlimann** [comment]
> Hard to tell. I think it depends on your context. If you know the behaviour you might want to catch the error or avoid double flushes. I think I kind of worked around it that way. Still I think it's worth being fixed appropriate.

We have some scenarios where flushes happen after flushes (initiated by post lifecycle events). The only workaround we have so far is disabling the lifecycle events temporarily for certain flushes. That said, our approach is probably not best practice (we are kinda new to Doctrine)...

**Comment by klammbueddel** [comment]
Sorry, I think I cant help you out here. Maybe some Doctrine pro can take a glimpse on this?

**Comment by derrabus** [comment]
We need a working reproducer or a failing tests to investigate the issue. The code in the issue description is incomplete because it references two entities `A` and `B` which you did not provide.

**Comment by klammbueddel** [comment]
Dear @derrabus, I already added a test to reproduce months ago: https://github.com/klammbueddel/orm/commit/32b5d3ea22013e8d4431d7d50875dc2d279e12fe

**Comment by mpdude** [comment]
Is this somehow related to #10486?

**Comment by klammbueddel** [comment]
Hi @mpdude,
Yes, it is the same issue. Your fix is resolving it!
Thank you 🚀

**Comment by mpdude** [comment]
So we need to get eyes on #10486
