### ISSUE TITLE
Support join tables in Doctrine Query Language

### ISSUE THREAD

**Issue by tessiancrow** [doctrine/doctrine2#10142]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

Why is it not possible to specify a table name in the ->createQueryBuilder, but rather a class? Join tables do not have their own class and if you want to make subqueries with DQL, for example, you have to rely on ->prepare. It would be cool to be able to use table names here as well.

**Comment by derrabus** [comment]
How do you map join tables if you don't have a class for them?

**Comment by tessiancrow** [comment]
In my specific case, there is no mapping to any class, because the join table is generated from the association.
