### ISSUE TITLE
Schema modification through loadClassMetadata event not being applied

### ISSUE THREAD

**Issue by awm1** [doctrine/doctrine2#10268]
### BC Break Report

When upgrading ORM from 2.13.3 to 2.13.4, a simple listener on loadClassMetadata event stops being effectively applied even it is still at least executed.

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.13.4

#### Summary

The event listener looks like:

`class MappingListener
{
    private $container;

    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
    }

    public function loadClassMetadata(LoadClassMetadataEventArgs $eventArgs)
    {
        $classMetadata = $eventArgs->getClassMetadata();
        $tableParams = $classMetadata->table;
        $tableName = $tableParams['name'];

        if (in_array($tableName, ['page', 'category'])) {
            $tableParams['schema'] = $this->container->getParameter('database_name_legacy');
        }
        $classMetadata->setPrimaryTable($tableParams);
    }
}`

#### Previous behavior

My Page and Category entities have been queried from legacy database schema as it was intended. Both default and legacy schema are accessible through one entity manager.

#### Current behavior

Now both entities are tried to be accessed through in default schema.

#### How to reproduce

Just through update from 2.13.3 to 2.13.4 . If I went through changes between those two releases, I don't see anything code related to loadClassMetadata event or $classMetadata->setPrimaryTable() call, just some related doc changes. I apologize myself but am I missing something?

**Comment by mpdude** [comment]
Can you provide a test case showing the failure?

**Comment by awm1** [comment]
I apologize, after doing some tests I figured out that this event works perfectly fine and my problem is metadata-cache related.
