### ISSUE TITLE
Disallow override of inherited property

### ISSUE THREAD

**Issue by michnovka** [doctrine/doctrine2#10289]
I came across https://github.com/doctrine/orm/pull/8348 and I found in current code we still have 

https://github.com/doctrine/orm/blob/b25561ad9623e1436f23241b180b6958d1a7e09c/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php#L2632-L2635

I think that this exception should be thrown here, don't you think? @beberlei

**Comment by mpdude** [comment]
I think pointing out configurations that are not officially supported and only work by chance is a good thing to do. Hopefully it works towards bringing down the number of bug reports for dubious use cases.

What about creating a PR for this? Are there tests already?

**Comment by mpdude** [comment]
#10470 solved this, please close
