### ISSUE TITLE
Apcu cache is used even if it is not enabled

### ISSUE THREAD

**Issue by aleksejs1** [doctrine/doctrine2#10310]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.13.x

#### Summary

In case of apcu extension exists, but not enabled Doctrine/ORM/Tools::createCacheInstance still creates ApcuCache or ApcuAdapter.
When someone try to write the cache "Failed to save key xxx of type Doctrine\ORM\Mapping\ClassMetadata." error appears.

#### Current behavior

When someone try to write the cache "Failed to save key xxx of type Doctrine\ORM\Mapping\ClassMetadata." error appears.

#### How to reproduce

Just an example:
Make the environment with existed disabled apcu extension.
Create doctrine migration with entityManager dependency.
Run doctrine:migration:status in cli.
Got "Failed to save key xxx of type Doctrine\ORM\Mapping\ClassMetadata." error.

#### Solution options

Change if statement in https://github.com/doctrine/orm/blob/2.13.x/lib/Doctrine/ORM/Tools/Setup.php#L239
from `} elseif (extension_loaded('apcu')) {`
to `} elseif (extension_loaded('apcu') && apcu_enabled()) {`
or `} elseif (extension_loaded('apcu') && ini_get('apc.enabled')) {`

**Comment by derrabus** [comment]
The proposed solution looks good to me, PR welcome.

**Comment by mpdude** [comment]
Fixed by #10311, right?
