### ISSUE TITLE
ValueObject Money custom type

### ISSUE THREAD

**Issue by Legion112** [doctrine/doctrine2#10335]
# The problem

1. Use of Money Value object to store USD, BTC, etc 

[The money library ](https://github.com/moneyphp/money) stores the amount as a string for example 1.89 USD is stored inside class Money as {amount: "189", currency: "USD"}
Storing the amount in the database as a string would prevent sorting them by value, the decimal type is more appropriate for this task. 
The problem is that I need to convert `amount: "189"`  to the database type as `1.89` and back. 
To be able to convert I need to know how many digits are after the decimal point for example bitcoin has 8 digits. This information could be retrieved from [this method](https://github.com/moneyphp/money/blob/c8eeeb1f7b7e6ca95490b94a301dc9cb8cb76c2d/src/Currencies.php#L26)

`1.89` BTC would need to be converted to `189000000` (Satoshi)
`1.89` ETH would need to be converted to `189000000000000000000` (Wei)
The bakc conversion should be possible as well: 
`189000000` BTC(Satoshi) => `1.89` BTC
`189000000000000000000`  ETH(Wei) => `1.89` ETH

## I see the problem above could be solved as follows:
1) To allow DI for custom DBAL type. 
2) To pass all parameters DBAL type to be able to convert the value base on the currency. 

## From the doctrine side the following change will be needed:

1. Remove final from \Doctrine\DBAL\Types\Type::__construct() to allow dependency injection.
2. Add array $parameters = [] to convertToDatabaseValue and convertToPHPValue

### Example of how it will be used.
https://github.com/Legion112/doctrine-embadable-share-column/blob/main/src/MoneyType.php and https://github.com/Legion112/doctrine-embadable-share-column/blob/main/src/Money.php

#### Why it is better to allow those manipulations on the ORM side? 
In case of not allowed to do the conversion on the ORM side, we are limited to storing the amount in a database as a string. Which potentially removes the following features: 

1. You can't sort my amount as it is a string, not a decimal value. 
2. You can't do aggregation sum, min, max, etc.

**Comment by Legion112** [comment]
Basically, I need a way to make some column values be shared by several embeddable objects. 
And collapsed embeddable objects to attribute name `total` instead of `total_amount`.  It's like specifying column name for each attribute of embeddable

**Comment by derrabus** [comment]
Sorry, but I have no idea what you're asking for.

**Comment by Legion112** [comment]
I am asking if is there a way to convert the object to two column value.
Is there a way to create a custom type which going to move to a two-column value?

Money contains the amount and the ticker.
The storage type for the amount should be decimal to allow manipulation with those with SQL.
But before saving the amount to the column with decimal type I need to convert its base on the currency.
For example:
I have the following object Money {amount: '100000000', currency: 'BTC'} - this is equivalent to 1 Bitcoin. 
During a conversation the object to database value I need to convert `100000000` to `1.00000000` and save it to the column with the name `amount` and BTC should be saved to another column `currency`. 
Saving them into different columns could be done via Embaddable I understand it. But during the conversation PHP -> database value I need to have access to `currency` (BTC) to know how many digit after decimal.

**Comment by Legion112** [comment]
Probably my type should be aware of other properties states during the conversation like bellow:
 <img width="1197" alt="image" src="https://user-images.githubusercontent.com/20613430/209088980-da98a863-becf-4ae4-abea-a3747a091b35.png">
This is just and idea what I would like to have from the ORM.

**Comment by Legion112** [comment]
I have updated the description of IDIA. 
In a few words I need the following: 

1. Remove **final** from \Doctrine\DBAL\Types\Type::__construct() to allow dependency injection. 
2. Add `array $parameters = []` to  `convertToDatabaseValue` and `convertToPHPValue`

Do you see any negative effect of introducing the extension to ORM API? 
I would create a merge request for that if it is fine to make such changes.

**Comment by Legion112** [comment]
The change would need to be done in [dbal](https://github.com/doctrine/dbal) and the ORM module...

**Comment by Legion112** [comment]
Hi, @Ocramius. I have found the following quote of yours:
> DBAL types are not designed for Dependency Injection.
>We explicitly avoided using DI for DBAL types because they have to stay simple.
> We’ve been asked many many times to change this behavior, but doctrine believes that complex data manipulation should NOT happen within the very core of the persistence layer itself. That should be handled in your service layer.

Could you share the link to this one so I could get to know more detail about it?  

Why does Dependency Injection assum complexity?

**Comment by derrabus** [comment]
All right, I'm closing this issue because all APIs that you want to change are DBAL ones. You're in the ORM repository here.

You might want to contribute to the discussion in doctrine/dbal#2841.

**Comment by Ocramius** [comment]
I don't have a link, but the type system of DBAL v2 (not sure about v3) uses the flyweight pattern, and is not suited for DI in its form.

**Comment by greg0ire** [comment]
Look at the DBAL repo, I've taken steps toward this. Might be on the latest branch, and the work is not finished IIRC
