### ISSUE TITLE
Psalm annotation is missing allowed ENUM values

### ISSUE THREAD

**Issue by kevinpapst** [doctrine/doctrine2#10356]
### Bug Report

Hey @derrabus, in your [recent commit](https://github.com/doctrine/orm/commit/1ad936a448e6841ee5bff988b2ab6fc0fd23e1d6#diff-4ee19c1ed755d34366c23e69ad18cca0ce4bf00228061d2854ccdbc59fb5835aR28) you added Psalm annotations:

https://github.com/doctrine/orm/blob/99a37d864ed810c8bebe46ce36d40adde8b8b1ec/lib/Doctrine/ORM/Mapping/GeneratedValue.php#L18-L30

Problem: `TABLE` and `UUID` are missing from the psalm annotation, while they are allowed in the ENUM.

My build is breaking, because I use `UUID` and phpstan now reports 
```
  26     Parameter $strategy of attribute class                       
         Doctrine\ORM\Mapping\GeneratedValue constructor expects      
         'AUTO'|'CUSTOM'|'IDENTITY'|'NONE'|'SEQUENCE', 'UUID' given.  
```
... I can send a PR, just want to make sure that this was not on purpose, was it?

**Comment by greg0ire** [comment]
Both are deprecated IIRC. I'm not saying it was on purpose, but that might explain it. You might want to dig into the git history.

**Comment by derrabus** [comment]
"recent" as in two months ago! 😅

I think the reason was that both missing strategies are deprecated and we didn't see a better way to make this issue bubble up in your static analysis.

`TABLE` doesn't even have an implementation and the `UUID` strategy is being removed from DBAL, iirc.

**Comment by kevinpapst** [comment]
It was [removed in 2018](https://github.com/doctrine/orm/pull/7330/files) ??? 

A bit odd: why does `#[ORM\GeneratedValue(strategy: 'UUID')]` not trigger any runtime deprecation?

Seems I have to say "Thank you 👍 " for reporting the deprecation in that rather unexpected way 😁

**Comment by derrabus** [comment]
There should be a runtime deprecation as well I believe, haven't checked though.
