### ISSUE TITLE
[FEATURE REQUEST] doctrine:mapping:import

### ISSUE THREAD

**Issue by snipershady** [doctrine/doctrine2#10366]
The `doctrine:mapping:import` command used to generate Doctrine entities from existing databases was deprecated by Doctrine in 2019 and it's no longer recommended to use it.

I'd like to see this feature implemented again based on PHP >=8 attributes

**Comment by beberlei** [comment]
This code was always brittle and usually worked only after tinkering a little with different edge cases so we really wanted to remove it for good.

If someone would take the code for this and release a third party library on top of Doctrine ORM, that would be a welcome addition, but its not going to be in core anymore.
