### ISSUE TITLE
Class inheritance without adding a new field breaks find (wrong SQL generated)

### ISSUE THREAD

**Issue by nunoplopes** [doctrine/doctrine2#10459]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | ?
| Version     | 2.14.1

#### Summary

I have an abstract class with 1 field. An inherited class adds no extra fields.
Doing a repository find of the inherited class generates wrong SQL.

#### Current behavior

Throws an exception (`Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such column: t0.name in Connection.php:60`) due to broken SQL that is generated.
The generated SQL is:
```sql
SELECT t1.name AS name_2 FROM GitHubRepository t1 WHERE t0.name = ?
```

The code looks like:
```php
/** @Entity */
abstract class Repository {
  /** @Id @Column(length=255) */
  public string $name;
}

/** @Entity */
class GitHubRepository extends \Repository {
  // no fields
}

// exception here:
$entityManager->find('GitHubRepository', $id);
```

In terms of tables, the table `GitHubRepository` has 1 column (name), and table `Repository` has no columns.

**Comment by nunoplopes** [comment]
Closing. I should be using `@MappedSuperclass`, not `@Entity`.

**Comment by mpdude** [comment]
I think that with #10431 (which is in the current `2.15.x-dev`), you should have been given a deprecation notice for a missing inheritance declaration, and in 3.0, it would have been a failure.
