### ISSUE TITLE
Add options (charset, collation) to DiscriminatorColumn to align it with Column options

### ISSUE THREAD

**Issue by janedbal** [doctrine/doctrine2#10462]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

As stated in [related dbal issue](https://github.com/doctrine/dbal/pull/5869#issue-1556699509), when trying to declare charset and collation for discriminator column, the only option to use is `columnDefinition` (which causes the migration issue described in the dbal issue). I believe that [DiscriminatorColumn](https://github.com/doctrine/orm/blob/2.14.1/lib/Doctrine/ORM/Mapping/DiscriminatorColumn.php) is not that much different from regular [Column](https://github.com/doctrine/orm/blob/2.14.1/lib/Doctrine/ORM/Mapping/Column.php) and it should support the same features.

**Comment by mattjanssen** [comment]
Was this resolved with https://github.com/doctrine/orm/pull/10601 ?
