### ISSUE TITLE
Possibility to define additional join conditions (join multiple columns based on static/fixed value)

### ISSUE THREAD

**Issue by Ninos** [doctrine/doctrine2#10487]
### Feature Request

Currently it is not possible to add an additional column (e.g. reference_type) for joining to specific table/entity based on reference_type. So using an entity for multiple parent entities is not possible without creating a column per entity.

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Code example

/Entity/MainExample1.php
```php
<?php

#[ORM\Entity]
#[ORM\Table]
class MainExample1
{
    #[ORM\Id]
    #[ORM\Column(type: 'uuid', unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    private ?Uuid $id = null;

    #[ORM\OneToMany(mappedBy: 'mainExample1', targetEntity: SubWithMultipleReferences::class, fetch: 'EXTRA_LAZY', orphanRemoval: true)]
    private iterable $subsWithMultipleReferences;
}
```

/Entity/MainExample2.php
```php
<?php

#[ORM\Entity]
#[ORM\Table]
class MainExample2
{
    #[ORM\Id]
    #[ORM\Column(type: 'uuid', unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    private ?Uuid $id = null;

    #[ORM\OneToMany(mappedBy: 'mainExample2', targetEntity: SubWithMultipleReferences::class, fetch: 'EXTRA_LAZY', orphanRemoval: true)]
    private iterable $subsWithMultipleReferences;
}
```

/Entity/SubWithMultipleReferences.php
```php
<?php

#[ORM\Entity]
#[ORM\Table]
class SubWithMultipleReferences
{
    #[ORM\Id]
    #[ORM\Column(type: 'uuid', unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    private ?Uuid $id = null;

    #[ORM\Column(type: 'string')]
    public ?string $referenceType = null;

    #[ORM\ManyToOne(targetEntity: MainExample1::class, inversedBy: 'subsWithMultipleReferences')]
    #[ORM\JoinColumn(name: 'reference_id', nullable: true, with: ['reference_type' => 'main_example_1'])]
    public ?MainExample1 $mainExample1;

    #[ORM\ManyToOne(targetEntity: MainExample2::class, inversedBy: 'subsWithMultipleReferences')]
    #[ORM\JoinColumn(name: 'reference_id', nullable: true, with: ['reference_type' => 'main_example_2'])]
    public ?MainExample2 $mainExample2;
}
```
I think it's enough to add an additional option `with` to `JoinColumn` attribute/method/..., which is adding an `JOIN::WITH` expression to join query. I think with small core changes this option should work out-of-the-box for different db types & in bi-directional way.

I'm willing to sponsor $500 for this feature implementation ❤️

**Comment by mpdude** [comment]
Am I right that your example shows how you solve it with different backreferences in `SubWithMultipleReferences` to point to either the one or other main entity type?

If you were using only one column in the `sub_with_multiple_references` table to refer to the `main_example`, how would you expect that column to be defined? In particular, how do you define the foreign key at the database level?

**Comment by Ninos** [comment]
@mpdude not completely, I want to use it in kind of this way instead of adding an own column per entity/table. e.g. think about a history/log entity, which wants to store the id of the original entity. Instread of creating x-attributes per entity to that log entity (which means x-columns), you only need to define `reference_id` & `reference_type`.

So from database perspective the foreign key should be a combination of `reference_id` and `reference_type`, `reference_type` describes e.g. the table name of mapped entity.

**Comment by mpdude** [comment]
How do you, in SQL, define a foreign key that references a table depending on the value of a particular column?

**Comment by Ninos** [comment]
Jipp seems not possible in SQL way.. The foreign key is mandatory?

**Comment by mpdude** [comment]
That is how relational databases maintain referential integrity and perform `ON {DELETE|CASCADE} ...` operations.

**Comment by Ninos** [comment]
OK I understand the restrictions, thx for clarification! So I'll solve it in another way :/

**Comment by mpdude** [comment]
If you like, I’ll take the money nonetheless 💸🤑

**Comment by Ninos** [comment]
Hahah I already donated $100 via GitHub sponsoring :)

**Comment by mpdude** [comment]
Is this related to your request? https://github.com/doctrine/orm/discussions/9928

**Comment by Ninos** [comment]
Oh yes, seems related 👍
