### ISSUE TITLE
Unable to find "App\Entity\Role" entity identifier associated with the UnitOfWork

### ISSUE THREAD

**Issue by specdrum-agc** [doctrine/doctrine2#10483]
### Bug Report

Unable to find "App\Entity\Role" entity identifier associated with the UnitOfWork

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.14.1

#### Summary

When I try to flush changes in one Entity, that related to deleted one, exception is thrown.

#### Current behavior

Somewhat works wrong when deleting ManyToMany relation and saving related entity after flushing these changes.

I investigated the problem and found out that removing entity inside of method `computeAssociationChanges` does not detect such changes and collection stays dirty.

#### How to reproduce

https://github.com/specdrum-agc/doctrine-bug (See Readme)

The main part of test case
```
        $role = $this->doctrine->getRepository(Role::class)->find(1);
        $user = $role->getUsers()->current();
        $user->setName('test');

        // Need for collection initialization
        $roles = $user->getRoles()->toArray();
        $entityManager->remove($role);
        $entityManager->flush();

        // Second flush fails
        $entityManager->flush();
```
The test case might be strange, but I have similar behavior in real application. I have second flush in different part of application than first.

#### Expected behavior

Second `flush` call do not throw exception.

**Comment by mpdude** [comment]
So you change the user that it has to be flushed, but the `roles` association still contains the role that has been deleted?

**Comment by specdrum-agc** [comment]
No, it doesn't. Only in collection's snapshot.
This is the point that state of collection comes into invalid state. When second flush in progress, UnitOfWork sees that and try to persist that change, but it was persisted in first flush.

**Comment by mpdude** [comment]
Did this work in previous ORM versions?

**Comment by specdrum-agc** [comment]
I had 2.11.3 version installed, there was the same issue.

**Comment by mpdude** [comment]
I am not sure what the expected behaviour would be, but #10485 provides a failing test for the time being.

**Comment by specdrum-agc** [comment]
@mpdude  Thank you very much for adding test case for this issue! It reproduces the mentioned behavior. But looks like you are left excess comma on line 20. Test log says about it.

**Comment by mpdude** [comment]
#10486 might be a fix

**Comment by mpdude** [comment]
Duplicate: #10060
