### ISSUE TITLE
LimitSubqueryWalker performance issue with DISTINCT

### ISSUE THREAD

**Issue by goetas** [doctrine/doctrine2#10553]
### Feature Request
|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary
 `\Doctrine\ORM\Tools\Pagination\LimitSubqueryWalker` Adds a `DISTINCT` keyword to paginate with no side effects queries that potentially contain multiple occurrences because of a join table that adds additional rows...

See https://github.com/doctrine/orm/blob/f82485e651763fbd1b34879726f4d3b91c358bd9/lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryWalker.php#L69

The `DISTINCT` might be expensive in some cases. 

In some cases it is known (not by doctrine but by the developer writing the query) that despite having joins, they are not adding extra rows, thus `DISTINCT` will not remove any row.

I would like to add a way into `LimitSubqueryWalker` to not use the distinct keyword.

Would it be acceptable something as this:

```php
$AST->selectClause->isDistinct  =  !$query->hasHint('opt_out_distinct') || !$query->getHint('opt_out_distinct');
```

in this way when writing the query, it would be possible to set the `opt_out_distinct` to skip the `DISTINCT`.

```php
$query->setHint('opt_out_distinct', true);
```
What do you think? is it acceptable?

A similar issue was reported in API platform in https://github.com/api-platform/api-platform/issues/792

If yes i can prepare a PR.

**Comment by nkrovex** [comment]
This opportunity must be present. I came across a similar issue.

**Comment by beberlei** [comment]
@goetas it would be fine to have this yes, a query hint would be a good way. Make sure to add it as constant on the paginator and prefix with paginate, paginate_disable_distinct for example

**Comment by goetas** [comment]
Here you go https://github.com/doctrine/orm/pull/10970

**Comment by goetas** [comment]
https://github.com/doctrine/orm/pull/10970 has been merged
