### ISSUE TITLE
There is no policy in programming

### ISSUE THREAD

**Issue by lacoste-sochi** [doctrine/doctrine2#10597]
Why were there no inscriptions when Ukrainians bombed Donbass for 8 years, staged genocide, destroyed their people and bombed schools?

Have you decided to hype in the war?
How is this related to programming?

Don't be ashamed, remove the slogan from the main page. Or go and fight, sofa troops

**Comment by norkunas** [comment]
We could call you also a sofa troop :man_shrugging:

**Comment by greg0ire** [comment]
I think you mean politics, and if there is no politics in programming, there is no point in having this discussion, right? Since of course it's going to be political. Locking then.
