### ISSUE TITLE
Provide an interface for BaseLifecycleEventArgs childs

### ISSUE THREAD

**Issue by tebaly** [doctrine/doctrine2#10615]
https://github.com/doctrine/orm/blame/2.14.x/UPGRADE.md#L61

### BC Break Report

BaseLifecycleEventArgs

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.14.1

#### Summary

Hello. Please provide an interface

```php

    public function getSubscribedEvents(): array
    {
        return [
            Events::prePersist,
            Events::preUpdate,
        ];
    }

    public function preUpdate(PreUpdateEventArgs $args): void # <-- PreUpdateEventArgs
    {
        $this->index($args, false); # <--
    }

    public function prePersist(PrePersistEventArgs $args): void # <-- PrePersistEventArgs
    {
        $this->index($args, true); # <--
    }

    public function index($args, $skipOverwriteInitial): void # <-- [????????] $args ?
    {
        $entity = $args->getObject();
        if (!$entity) {
            return;
        }
        $this->entityDateUpdater->updateFields($entity, $skipOverwriteInitial);
    }
```

### Previously all types were LifecycleEventArgs

Right now I can't determine the type for `$args` in `index` method :(

**Comment by derrabus** [comment]
> BC Break Report

For a deprecation that you don't agree with? Seriously?

> Right now I can't determine the type for `$args` in `index` method :(

It's `PreUpdateEventArgs | PrePersistEventArgs`.

**Comment by tebaly** [comment]
> It's `PreUpdateEventArgs | PrePersistEventArgs`.

Let's have the full version of your beautiful code

```php
public function index(PrePersistEventArgs | PreUpdateEventArgs | PreRemoveEventArgs | PostPersistEventArgs | PostUpdateEventArgs | PostRemoveEventArgs | PostLoadEventArgs $args, $skipOverwriteInitial): void
```

# Seriously?
