### ISSUE TITLE
Deleted entity is causing "A new entity was found through the relationship" exception in the case of multiple flush() calls

### ISSUE THREAD

**Issue by forgie1** [doctrine/doctrine2#10718]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.15.1

#### Summary

Deleted entity is perceived as new after first `EM::flush()` call.
Therefore potentially causing this exception in the future EM::flush() calls:
```
Doctrine\ORM\ORMInvalidArgumentException
A new entity was found through the relationship
```

Example use case could be deleting many interconnected entities in batches.
This is currently no possible to do without  throwing `ORMInvalidArgumentException`. No other EM::flush() call will succeed.

#### Expected behavior

Deleted should stay deleted "forever".

**Comment by derrabus** [comment]
Why is the current behavior causing an issue for you? Can you provide steps to reproduce your problem?

**Comment by forgie1** [comment]
You are right, our `onFlush` event was the problem, I'm closing the issue and MR.
