### ISSUE TITLE
Stateless getInsertSQL()

### ISSUE THREAD

**Issue by PsmaDev** [doctrine/doctrine2#10710]
Sorry, I think I did not explane correctly issue https://github.com/doctrine/orm/issues/10709
I change table prefix in middelware during each reqest, and it works perfect with UPDATE and SELECT.
Problem cause getInsertSQL() has check 
`if ($this->insertSql !== null) {
            return $this->insertSql;
        }`
So, it sets once and next requests keeps the same, If i check methodata it is ok, it's changed.

**Comment by beberlei** [comment]
You described the problem perfectly well, but as I mentioned changing the metadata of a class after the EntityManager was used is just not supported. This has nothing to do with UDPATE and SELECT working. 

Please stop opening new issues for this. You need to find another solution for your use-case.
