### ISSUE TITLE
Calling distinct() on QueryBuilder does not update state correctly

### ISSUE THREAD

**Issue by macroparts** [doctrine/doctrine2#10784]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.14.3

#### Summary

When calling distinct() on a Query builder after getQuery(), then a subsequent getQuery() would ignore the distinct query part.

#### Current behavior

See summary

#### How to reproduce

1. Use the QueryBuilder and create any non-distinct query.
2. Call getQuery() on the QueryBuilder
3. Call distinct() on the QueryBuilder
4. Call getQuery() on the QueryBuilder again

#### Expected behavior

The second getQuery() call should return a Query using the distinct keyword.

**Comment by greg0ire** [comment]
Looks like it would be fixed by adding `$this->state = self::STATE_DIRTY` inside `distinct()`… are you up to send a PR?

**Comment by macroparts** [comment]
@greg0ire hope I was following your contribution guidelines correctly. I will appreciate a review of my PR.

**Comment by greg0ire** [comment]
> Version | 2.x.x

What version are you using, precisely?

**Comment by macroparts** [comment]
2.14.3 is currently used in my project and I was hoping to get a fix for that version but I can also aim for an upgrade and submit a fix for 2.15.x

**Comment by greg0ire** [comment]
Please do, 2.14.x is no longer maintained.
