### ISSUE TITLE
Close migrated issues that only link to PRs

### ISSUE THREAD

**Issue by mpdude** [doctrine/doctrine2#10810]
Back in the days Jira was used, tickets were created for GitHub PRs that were opened. Later on, those tickets were migrated to GH issues.

I think those issues add no value and I don't see what kind of discussion might have taken place in them. After all, we still have the PRs (either open or closed).

So, my suggestion is to close the following issues:

https://github.com/search?q=repo%3Adoctrine%2Form+%22automatically+through+a+github+pull%22+is%3Aopen&type=issues

Using the `gh` CLI, it might be possible to achieve this with:

` gh api -X GET search/issues -f q='repo:doctrine/orm is:open "automatically through a GitHub pull"' | jq .items[].html_url | xargs -n1 gh issue close`

**Comment by greg0ire** [comment]
Is that different than https://github.com/doctrine/orm/issues?q=+is%3Aopen+%22automatically+through+a+github+pull%22 ? There is a bulk action in the UI we can use to close.

**Comment by mpdude** [comment]
Bulk action? 🤩

I was not aware of that. Seems I spend too much time on the CLI.

**Comment by greg0ire** [comment]
Done.
