### ISSUE TITLE
Dummy title instead of actual title

### ISSUE THREAD

**Issue by filippovicari426** [doctrine/doctrine2#10836]
Hi I wanted to let you know about this minor issue. In these pages every other title is Dummy Title
https://www.doctrine-project.org/projects/doctrine-orm/en/2.15

**Comment by greg0ire** [comment]
:open_mouth:

**Comment by greg0ire** [comment]
Now I understand your comment @SenseException ! I thought I had not commit the change in the sidebar in https://github.com/doctrine/orm/pull/10824#issuecomment-1627829663 :facepalm:

**Comment by greg0ire** [comment]
Thanks for reporting it. I think https://github.com/doctrine/doctrine-website/actions/runs/5526467336/jobs/10088183684 will fix it.

**Comment by greg0ire** [comment]
Fixed. Phew. Thanks for saving us me more embarrassment :pray:

**Comment by filippovicari426** [comment]
> Fixed. Phew. Thanks for saving us me more embarrassment 🙏

@greg0ire we are all humans after all 😊was the least I could do to contribute to this project
