### ISSUE TITLE
EntityManagerInterface has no #3/$lockVersion param in find method

### ISSUE THREAD

**Issue by mvorisek** [doctrine/doctrine2#10858]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | n/a
| Version     | 2.15.14 (latest)

#### Summary

I have found this inconsistency during abstracting entity manager type declaration from EntityManager to EntityManagerInterface.

#### Current behavior

Currently, in 2.15.x, EntityManager has the following find method prototype: https://github.com/doctrine/orm/blob/v2.5.14/lib/Doctrine/ORM/EntityManager.php#L377 and no find method prototype in EntityManagerInterface.

Given:
- Entity manager decorator has $lockVersion param: https://github.com/doctrine/orm/blob/v2.5.14/lib/Doctrine/ORM/Decorator/EntityManagerDecorator.php#L178
- and in 3.x the $lockVersion param is declared in the EntityManagerInterface interface: https://github.com/doctrine/orm/blob/3.0.x/lib/Doctrine/ORM/EntityManagerInterface.php#L133

it seems the entity manager does support $lockVersion param officially and a missing find method prototype (with <span>#</span>3/$lockVersion param) in EntityManagerInterface is a mistake.

#### Expected behavior

2.x EntityManagerInterface should declare find method with <span>#</span>3/$lockVersion param (as 3.x does).

**Comment by derrabus** [comment]
> 2.x EntityManagerInterface should declare find method with #3/$lockVersion param (as 3.x does).

This will break each and every userland implementation of the interface out there which is exactly why we won't add the parameter in a minor release.

**Comment by mvorisek** [comment]
I understand the possible BC break, on the other side, `EntityManagerInterface` cannot be currently used to replace `EntityManager` impl. type as it is incomplete.

Can the `find` method prototype be added as phpdoc above the interface to make both worlds happy?

**Comment by derrabus** [comment]
If that fixes your problem, why not.

**Comment by mvorisek** [comment]
I was just about to add `@method` phpdoc, but how to specify templated return using `@method`?

**Comment by mvorisek** [comment]
I was just about to add `@method` phpdoc, but how to specify templated return using `@method`?

@ondrejmirtes is that possible with phpstan?
