### ISSUE TITLE
Identity Map issue since 2.16.0 upgrade

### ISSUE THREAD

**Issue by jenkoian** [doctrine/doctrine2#10867]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.16.0

#### Summary

Noticed two issues when testing the upgrade to 2.16.0, both related to https://github.com/doctrine/orm/pull/10785

I've created a repository here to provide examples/reproducers of the issues: https://github.com/jenkoian/doctrine-issue

#### Previous behavior

Issue 1: Entities could be (re)created should the entity be removed from the database.
Issue 2: Proxy entities could be used after the creation of an entity

#### Current behavior

Issue 1: If an entity is deleted from the database, if we attempt to re-create it (and it exists in the identity map) we will get an error.
Issue 2: Attempts to get values from a proxy of an entity will fail due to the proxy not equaling the entity in the identity map.

#### How to reproduce

Checkout this repository: https://github.com/jenkoian/doctrine-issue
Follow the steps in the README.

**Comment by alexander-schranz** [comment]
Think this is also related to the issue I reported https://github.com/doctrine/orm/issues/10820

**Comment by mpdude** [comment]
Issue 1: You’re creating an inconsistency by deleting the entity in the database outside of the EM‘s control. The EM still has to assume the entity exists, and that the object instance in the identity map is the only legitimate object representing it. 

Depending on what you’re trying to achieve, try `clear()`ing the EM or tell it to detach the old object.

**Comment by mpdude** [comment]
Issue 2: You’re creating a proxy instance outside of the EM's visibility. Now there are two objects that claim to represent the particular entity. 

In the ORM, a particular entity instance (= identity, ID) is always represented by exactly one object, object identity (`===`) is guaranteed.

The EM rejects this situation as soon as it learns about it. Previously, this went unnoticed and caused corruptions in internal state management structures.

Use `EntityManager::getReference()` if you don’t want to enforce a full entity load.

**Comment by alexander-schranz** [comment]
Not sure in which pull request but it seems like this issue is fixed: 

<img width="635" alt="Bildschirmfoto 2024-01-29 um 10 45 46" src="https://github.com/doctrine/orm/assets/1698337/bf2c7cde-8bd6-455e-8a4a-0b11ff47b427">

If somebody have more information please let me know which PR this fixed. It seems to be somewhere in th 2.16.1 release.

This Issue can be closed.

**Comment by jenkoian** [comment]
Thanks for checking @alexander-schranz I've just done the same and it looks like 2.16.1 fixed it as you mentioned, so something within https://github.com/doctrine/orm/compare/2.16.0...2.16.1 but like you unsure exactly
