### ISSUE TITLE
`EntityManager::find()` calls `UnitOfWork::registerManaged()` twice and that causes Change Detection to fail

### ISSUE THREAD

**Issue by eXsio** [doctrine/doctrine2#10880]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.16.0

#### Summary

I have a Symfony 5.4 based Application that uses Framework Extra Bundle and its Param Converter feature. After upgrading from 2.15.3 to 2.16.0 Doctrine has stopped detecting Entity Changes in Entities loaded by the ParamConverter, due to the new logic introduced by this commit: https://github.com/doctrine/orm/commit/01a14327d2404885897961851659b467ec966d74

After some snooping I've found out, that the `UnitOfWork::registerManaged()` is actually called twice:
- from the line 2805: https://github.com/doctrine/orm/blame/2.16.x/lib/Doctrine/ORM/UnitOfWork.php#L2875

- from the line 3038: https://github.com/doctrine/orm/blame/2.16.x/lib/Doctrine/ORM/UnitOfWork.php#L3038

The second call rewrites previously loaded/hydrated Entity and sets the `UnitOfWork::$originalEntityData` property to `[]`. This causes the change detection to fail, because the UoW is not able to correctly compare the Actual Data to the Original Data.

The Framework Extra Bundle uses the `EntityManager::find()` method under the hood, so I wouldn't blame the lib for the failure. The fact is that Doctrine has altered it's behavior significantly because of that change.

#### Previous behavior

when an Entity wired by the ParamConverter was changed, Doctrine has correctly detected changes made in the Entity.

#### Current behavior

Doctrine doesn't detect changes in the Entities wired by the ParamConverter.

#### How to reproduce

1. Create a Symfony 5.4 Application with Framework Extra Bundle
2. Autowire an Entity to a Controller
3. change the Entitie's state and save
4. change detection fails

I am not sure if this is the case for every such configuration, but I am positive that the `UnitOfWork::registerManaged` method can be called twice for a single `createEntity` method call.

#### Suggested Fix

Any tampering with not calling the `UnitOfWork::registerManaged()` a second time has caused the ORM to blow up in some other place. However, modifying the `UnitOfWork::registerManaged()` method itself to not allow to overwrite the Entity seems to have helped:

```
   public function registerManaged($entity, array $id, array $data)
    {
        $oid = spl_object_id($entity);
        //don't allow to overwrite Entity once it has been registered
        if(array_key_exists($oid, $this->entityIdentifiers)) {
            return;
        }
        ....
```

P.S.

This is not the only regression caused by this change. I can also see multiple tickets that point to this change as a culprit. Don't mean to tell you how to do things, but this seems like a very impactful and drastic change for a minor release.

**Comment by pich** [comment]
+1

**Comment by mpdude** [comment]
Can you provide the two code paths that ultimately lead to `UnitOfWork::registerManaged()` being called twice?

Do both calls come from the same `createEntity` invocation?

Also, are the two links correct that refer to the UoW?

**Comment by mpdude** [comment]
I have tried your reproduce steps but cannot see a problem.

Please provide stack traces for both invocations of `registerManaged()`, and also share the version of FrameworkBundle for completeness.

**Comment by mpdude** [comment]
The second invocation you mentioned can only come into play when there is something with associations going on. Does the entity loaded through the ParamConverter reference back to itself?

**Comment by eXsio** [comment]
1. Yes, both calls were originated by the same `createEntity()` method invocation
2. Framework Extra Bundle version is `v6.2.10`
3. There are 3 Entities at play:
  - `Process`
  - `ProcessStage`
  - `ProcessOwner`
4. The relations between the Entities are: 
  - The `ProcessOwner` has a FK to the `Process` (ManyToOne)
  - The `Process` has a FK to the `ProcessOwner` (OneToOne)
  - The `ProcessStage` has a FK to the `Process` (ManyToOne) - single Process can have multiple Stages. The relation is bidirectional.
  - The `Process` has a FK to `ProcessStage` (OneToOne) - the FK to a Current Process Stage (`$currentStage` field)

The Entity that is found by the ParamConverter is the `ProcessOwner`. The logic is about advancing the `Process` to the next Stage. The Controller logic, after applying some business validations, sets the new `$currentStage` to reflect that a Process has been moved forward.

The re-assignment of the `Process::$currentStage`, alhough completed in PHP, is not detected by the Change Detector, because 
 upon loading the `Process` via the `createEntity()` method the `registerManaged()` is called twice - once correctly, and once with an empty array for `$data`

I realize that the Entity hierarchy is not the greatest, but this is a legacy code riddled with inheritance as decisions that seemed to be logical at the time.

Having that said this was working flawlessly (the Project is 7 years old) up until 2.16.0.

**Comment by mpdude** [comment]
When is the `Process` being loaded and `createEntity` being called - does that happen from within the ParamConverter?

Did I get it right that the ParamConverter is fetching a `ProcessOwner`? Does that have the `Process` as a proxy (lazy load)?

Are there any extra configuration settings like fetch=EAGER or so?

**Comment by mpdude** [comment]
@eXsio I've been trying to add a reproduce test in #10884, but still unsuccessful – the test passes.

Feel free to open a PR against https://github.com/mpdude/doctrine2/tree/reproducer-10880 to show where it fails. For now, I'd assume the ParamConverter and Symfony or the FrameworkBundle don't have anything to do with it.

We need a test that passes on 2.15.x and fails on 2.16.0 to proceed.

**Comment by eXsio** [comment]
OK, I will try to recreate this during the following week and submit a PR, thanks for trying :)

**Comment by eXsio** [comment]
Hello

I've created a PR with a working reproduction:
https://github.com/mpdude/doctrine2/pull/3

My Branch forked from your repo proves that it doesn't work:
https://github.com/eXsio/doctrine2/tree/gh-10880-reproduction-2-16-0
https://github.com/eXsio/doctrine2/commit/7ea8474736e8325a142b0c0c7b80eb8d74aab673

I've created a second branch to make sure that the exact same thing worked on 2.15.3 and, in fact, I was right:
https://github.com/eXsio/doctrine2/tree/gh-10880-reproduction-2-15-3
https://github.com/eXsio/doctrine2/commit/1f9aa8e847a3fb463ae5805d9c082fd0e4b38716

The whole thing seems to be about inheritance. If change the `GH10880BaseProcess` definition to

```
/**
 * @ORM\MappedSuperClass
 * @ORM\Table(name="processes")
 * @ORM\DiscriminatorMap({
 *  "process" = "GH10880Process"
 * })
 */
class GH10880BaseProcess
```

It magically starts to work on 2.16.0. The thing is, that in my Application I have multiple inheritors of the `GH10880BaseProcess` so I need to have the Single Table Inheritance working, and it was working on 2.15.3.

**Comment by eXsio** [comment]
P.S.

One Clarification: the `registerManaged()` calls do not originate from the same `createEntity()` call after all.

After adding some `var_dump` calls to the `UnitOfWork` I can see the following call sequence:

```
string(71) "CREATE ENTITY: Doctrine\Tests\ORM\Functional\Ticket\GH10880ProcessOwner"
string(66) "CREATE ENTITY: Doctrine\Tests\ORM\Functional\Ticket\GH10880Process"
string(70) "REGISTER MANAGED - Doctrine\Tests\ORM\Functional\Ticket\GH10880Process"
string(22) "$data parameter value:"
array(4) {
  ["id"]=>
  int(1)
  ["parentObject"]=>
  string(1) "1"
  ["current_stage"]=>
  int(2)
  ["parent_object_id"]=>
  int(1)
}
string(71) "CREATE ENTITY: Doctrine\Tests\ORM\Functional\Ticket\GH10880ProcessStage"
string(71) "CREATE ENTITY: Doctrine\Tests\ORM\Functional\Ticket\GH10880ProcessStage"
string(71) "CREATE ENTITY: Doctrine\Tests\ORM\Functional\Ticket\GH10880ProcessStage"
string(70) "REGISTER MANAGED - Doctrine\Tests\ORM\Functional\Ticket\GH10880Process"
string(22) "$data parameter value:"
array(0) {
}
```


Hope this helps.
