### ISSUE TITLE
Mapping Exception: Entity has to be part of discriminator map - but IS

### ISSUE THREAD

**Issue by fpolli** [doctrine/doctrine2#10885]
I just today got this error and cannot get past it. The entity it tells me has to be part of the discriminator map of the root entity IS part of the discriminator map.

Here is the inheriting class definition:
```
namespace App\Entities\Default;

use Doctrine\ORM\Mapping as ORM;
use Exception;

#[ORM\Entity]
class Text extends Content {
```
And here is the Content class:

```

namespace App\Entities\Default;

#[ORM\Entity]
#[ORM\Table(name: "content")]
#[ORM\InheritanceType('SINGLE_TABLE')]
#[ORM\DiscriminatorColumn(name: 'genre', type: 'string')]
#[ORM\DiscriminatorMap([
  'text' => Text::class,


```
This has all been this way for weeks. No problem. I have not changed anything even remotely close to relevant. I updated my class map (Composer), cleared caches, cleared browser cache and cookies, and nothing has helped.

_Originally posted by @fpolli in https://github.com/doctrine/orm/discussions/10882_

**Comment by fpolli** [comment]
Found the error. A global search and replace had messed up the discriminator map

**Comment by mpdude** [comment]
@fpolli so, could you please close this issue?
