### ISSUE TITLE
Attributes are not read from parent class

### ISSUE THREAD

**Issue by simPod** [doctrine/doctrine2#10902]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.16

#### Summary

Before I dig into creating PR I want to know whether it's the indented design that attributes are not read from extended classes

#### Current behavior

```php
#[Table('t')]
abstract class A {}

// this does not inherit `Table` attribute
class Entity extends A {}
```

#### How to reproduce

Snippet above is sufficient

#### Expected behavior

The `Table` attribute to be inherited.

**Comment by derrabus** [comment]
> I want to know whether it's the indented design

Yes.
