### ISSUE TITLE
AbstractPlatform::getSequenceNext ValSQL is not supported by platform

### ISSUE THREAD

**Issue by UtechtDustin** [doctrine/doctrine2#10921]
### Bug Report
We use Doctrine version 2.15.3 with Symfony 6.3.

#### Summary

Doctrine figures out wrong strategy for id generation.

#### Current behavior
We got the issue (We already got that quite often) that we can't save new entities and got the following error in the log file.

```
[2023-08-17T06:47:34.378069+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception: "Operation 'Doctrine\DBAL\Platforms\AbstractPlatform::getSequenceNext
ValSQL' is not supported by platform." at /var/www/gda/V1.2/vendor/doctrine/dbal/src/Exception.php line 21 {"exception":"[object] (Doctrine\\DBAL\\Exception(code: 0):
Operation 'Doctrine\\DBAL\\Platforms\\AbstractPlatform::getSequenceNextValSQL' is not supported by platform. at /var/www/gda/V1.2/vendor/doctrine/dbal/src/Exception.ph
p:21)"} []
```

In our Entities we use the generated Strategy from the maker bundle, which is the default value `AUTO`.
```
#[ORM\Id]
#[ORM\GeneratedValue]
#[ORM\Column]
private ?int $id = null;
```

Our database configuration looks like this:
```
DATABASE_URL="mysql://xxx:xxx@127.0.0.1:3306/gda?serverVersion=mariadb-10.11.3&charset=utf8mb4"
```
In the [documenation](https://symfony.com/doc/current/reference/configuration/doctrine.html#doctrine-dbal-configuration) is an hint that in newer versions we should move `mariadb` to the end so we also tried
```
DATABASE_URL="mysql://xxx:xxx@127.0.0.1:3306/gda?serverVersion=10.11.3-mariadb&charset=utf8mb4"
```

I don't understand why it tries to use the  `SEQUENCE` if we configured `mariadb/mysql` which should be `IDENTITY` by default as [documentated](https://www.doctrine-project.org/projects/doctrine-orm/en/2.16/reference/basic-mapping.html#identifier-generation-strategies).

#### How to reproduce

I'm not sure, it randomly starts to use the other strategy.

#### Expected behavior

Doctrine should  figure out the correct strategy.

**Comment by UtechtDustin** [comment]
We got this issue 5 times in the last few day's (on production systems)!
As workaround we defined the strategy so hopfully symfony will not try to guess it and throw the exception.

**Comment by derrabus** [comment]
Can you tell us what versions of PHP and Doctrine DBAL you are using? And MariaDB 10.11 is actually the database being used?

Can you isolate a reproducer for this issue, e.g. a small application as a GitHub repo?

**Comment by UtechtDustin** [comment]
Sure, we are using PHP 8.2 with DBAL Version 3.6.4.
MariaDB 10.11 is correct, we use `VERSION()` to figure it out, as documented here: https://www.doctrine-project.org/projects/doctrine-dbal/en/current/reference/configuration.html#mariadb

Currently i don't have time to create a example repository, if i find some time i will do that (which is quite hard because the exception will be thrown randomly, sometime it takes 5 days, sometimes we got it again after 2 days).
But it's quite easy, configure `DATABASE_URL` as examplained above and just persist and flush an entity.  

Just a side question, is the full string e.g. `10.11.2-MariaDB-1:10.11.2+maria~ubu2204` needed (documented by doctrine) or is  `10.11.2-mariadb` enough (documented by symfony) ?

Thank you for the quick reply!

**Comment by UtechtDustin** [comment]
I'm not sure but could this an issue of our deployment ?
We have a gitlab runner which creates a new folder with the version (git tag), install and build the dependencies (composer + npm), copy the .env.local file of the last version to the latest version and lastly we change the symlink to the new version.

Is it possible that we have a bad timing or something and the cache will be generated with the .env file instead ?
That would explain why it works for a while after a cache clear.

**Comment by derrabus** [comment]
> Just a side question, is the full string e.g. `10.11.2-MariaDB-1:10.11.2+maria~ubu2204` needed (documented by doctrine) or is `10.11.2-mariadb` enough (documented by symfony) ?

If you specify a version string, the DBAL will parse that string as if it were returned from the server. This is why we recommend to use the version string as the server would report it. But the shorter version will probably work as well.

**Comment by derrabus** [comment]
> Is it possible that we have a bad timing or something and the cache will be generated with the .env file instead ? That would explain why it works for a while after a cache clear.

Don't know. Maybe.

The error looks like DBAL chooses the wrong platform, but I don't know why that happens. And without a reproducer, I have no way of finding out.

**Comment by UtechtDustin** [comment]
Okay, thank you for the information.  
An reproducer repository is not useful, because the error will be thrown randomly.  
So.. lets close this issue, if the issue will be thrown again i will check if there was an deployment and i try to debug that.
