### ISSUE TITLE
Docblock parameter `$where` in docblock for `andWhere` does not have a counterpart in signature parameter list

### ISSUE THREAD

**Issue by ging-dev** [doctrine/doctrine2#10936]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.16.2

#### Summary
Docblock parameter $where in docblock for andWhere does not have a counterpart in signature parameter list:

https://github.com/doctrine/orm/blob/d81afdb6e3454007477ac00b8c98481c6f99af0f/lib/Doctrine/ORM/QueryBuilder.php#L1164-L1168

Although it does not cause errors, it will cause confusion for the IDE:

![image](https://github.com/doctrine/orm/assets/42226341/217cec87-6aae-424d-b284-ead68d26a946)

**Comment by derrabus** [comment]
This will be addressed in 3.0.
