### ISSUE TITLE
Please reopen #8739

### ISSUE THREAD

**Issue by twisted1919** [doctrine/doctrine2#10950]
Hello,

Issue #8739 has been closed without it being fixed.  

I don't understand how a library so popular as Doctrine can ignore such a huge problem like described in #8739.

I don't have enough experience with Doctrine to pick it up and draft a fix for it, if I had, I would have done it already.

The above issue also speaks about a fix. This fix is not applicable in all situations, and in some cases, like when using Api-Platform, it requires workarounds, which is not something we're keen introducing in our apps.

Thank you.

**Comment by derrabus** [comment]
> Issue #8739 has been closed without it being fixed.

I've reopened the issue for you.

> I don't have enough experience with Doctrine to pick it up and draft a fix for it, if I had, I would have done it already.

If the issue described in #8739 is such a "huge problem" for you, you're the best person to contribute a fix. Please give it a try. If you need guidance, you can always ask questions in https://github.com/doctrine/orm/discussions or the comments of that ticket. You can also open a draft PR with failing tests and a maybe a first implementation of a fix and ask for advice on how to complete it.
