### ISSUE TITLE
Argument #1 ($sql) must be of type string, null given

### ISSUE THREAD

**Issue by mikaeldelsol** [doctrine/doctrine2#11068]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.17.0

#### Previous behavior

```php
public function findDuplicates(string $anyId, string $anyService, ?string $id = null)
{
    $qb = $this->createQueryBuilder('e');
    $qb->where('t.anyId = :any_id')
        ->andWhere('t.anyService = :any_service')
        ->setParameter('any_id', $anyId, Types::STRING)
        ->setParameter('any_service', $anyService, Types::STRING)
    ;
    if (null !== $id) {
        $qb->andWhere('t.id <> :id')->setParameter('id', $id, Types::STRING);
    }

    return $qb->getQuery()->getResult();
}
```
Normally returns an array, empty or not.

#### Current behavior

Running this same code produces this error:
```
Uncaught PHP Exception TypeError: "Doctrine\DBAL\Connection::executeQuery(): Argument #1 ($sql) must be of type string,
null given, called in /app/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php on line 33"
at /app/vendor/doctrine/dbal/src/Connection.php line 1071
```

From what I observed, the SingleSelectExecutor::__construct method is not called.
#### How to reproduce

Both case:
- no opcache
- no apc cache
- project build with docker and deployed in a kubernetes cluster

Working case:
doctrine/orm:2.16.2

Broken case:
doctrine/orm:2.17.0

#### How to "fix"
Run command `bin/console cache:clear`

From what I observed, the SingleSelectExecutor::__construct method is then called.

**Comment by greg0ire** [comment]
Please only make bug reports for the latest possible versions. 2.17.1 is out (and fixes your bug).
