### ISSUE TITLE
Cache problem in console environment?

### ISSUE THREAD

**Issue by jkabat** [doctrine/doctrine2#11074]
Recently I had to use event subscriber for console command and during production build Im facing following error:

`
Doctrine\DBAL\Connection::executeQuery(): Argument #1 ($sql) must be of type string, null given, called in /app/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php on line 33
`

Which makes no sense....
I cant replicate it on DEV environment, but while playing with prod and debug I've seen another problem:

`Failed to save key "9f5815e4271a13bd1b91eb911a8bb2da" of type Doctrine\ORM\Query\ParserResult: Cache key "9f5815e4271a13bd1b91eb911a8bb2da" has non-serializable "Doctrine\ORM\Query\ParserResult" value.`

Can these two errors be related? 

|    Q        |   A
|------------ | ------
| Version     | 2.17.0

Symfony v5.4.31

**Comment by greg0ire** [comment]
Please use 2.17.1

**Comment by jkabat** [comment]
@greg0ire for some reason Im still getting the same error, trying to isolate when, as it is not happing all the time:
![image](https://github.com/doctrine/orm/assets/6071927/f471bfc3-76fb-4268-ad84-c42394bcf4a8)

Im using the latest version of doctrine ORM v2.17.1

**Comment by greg0ire** [comment]
If you want to reproduce it in dev, try using `APP_DEBUG=false`

**Comment by jkabat** [comment]
The fact, that I do not see 500 responses on loadbalancer means that the error is most probably happening during KernelEvents::TERMINATE. On local simulation of PROD there is no such error only warnings of that type:

`php.WARNING: User Notice: serialize(): " {"exception":"[object] (ErrorException(code: 0): User Notice: serialize(): \" at /var/www/html/vendor/symfony/var-exporter/Internal/Exporter.php:175)"} []
`

Application is not using serialize, and without DEBUG I do not get enough context to find the problem. Will take a look once again later...

**Comment by greg0ire** [comment]
That would be when serializing a result cache entry to put it in your cache. Are you using the php files cache?

**Comment by jkabat** [comment]
@greg0ire yes I do. Any idea how to get the content of what is going to be serialized?

**Comment by greg0ire** [comment]
Use a try/catch inside the file mentioned in the error message?

**Comment by jkabat** [comment]
I have tried to debug it. My finds are following:

* error occurs on this line, so the error message I have mentioned  (and in the log) is malformed... https://github.com/symfony/var-exporter/blob/v6.3.6/Internal/Exporter.php#L175
* when I debugged it and logged the $n value it has written into log several empty strings in the loop

Content of the $sleep was:
```php
{
  "sqlStatements":false,
  "queryCacheProfile":false,
  "Doctrine\ORM\Query\Exec\MultiTableUpdateExecutorcreateTempTableSql":2,
  "Doctrine\ORM\Query\Exec\MultiTableUpdateExecutordropTempTableSql":3,
  "Doctrine\ORM\Query\Exec\MultiTableUpdateExecutorinsertSql":4,
  "Doctrine\ORM\Query\Exec\MultiTableUpdateExecutorsqlParameters":5,
  "Doctrine\ORM\Query\Exec\MultiTableUpdateExecutornumParametersInUpdateClause":6
}
```

EDIT: conversion of the $n variable to string seems to throw the other error, or cannot be converted because of the special chars

**Comment by greg0ire** [comment]
To be quite honest it behaves exactly a lot like if you were still using 2.17.0 so if I were you, I would triple check that I really did the upgrade, by using `composer show doctrine/orm`. Also, you might want to upgrade `var-exporter` as well, there have been improvement to handle weird things I did in 2.17.0.

**Comment by jkabat** [comment]
@greg0ire thats exactly what I have done... by upgrading to 2.17.1 the first error of the issue has gone

![image](https://github.com/doctrine/orm/assets/6071927/84946b80-1136-4729-98c4-f309fb9d3ce9)

I have even compared the orm vendor with the downloaded archive.

**Comment by jkabat** [comment]
@greg0ire maybe the problem is that the var-exporter fix is not in 6.3 version. Will try to downgrade.

EDIT: it is not even in 5.4 branch... so what can be done?
https://github.com/symfony/symfony/pull/52618

**Comment by greg0ire** [comment]
Regarding your `composer show`, OK this seems correct, so this must be a different issue, but with the same symptoms.

Can you try 6.4.0-RC2, just to see if your issue will be fixed?

**Comment by jkabat** [comment]
I have tried the fix and of course it solves the problem. I will downgrade meanwhile. When the stable version of var-exporter is available, I will upgrade back again. Thank you for taking time to investigate with me.

Issue can be closed.
