### ISSUE TITLE
BackedEnum type with interface validation mismatch 

### ISSUE THREAD

**Issue by vitxd** [doctrine/doctrine2#11119]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.17.1

#### Summary

After upgrading to version 2.17.1 I've encountered this validation error:

```
$ bin/console doctrine:schema:validate

[FAIL] The entity-class App\Entity\CertificateEvent mapping is invalid:
 * The field 'App\Entity\CertificateEvent#type' has the property type 'App\Enum\EventType' that differs from the metadata field type 'string' returned by the 'string' DBAL type.
```

#### Previous behavior
Schema validation pass

#### Current behavior
Schema validation fails

#### How to reproduce

```php
interface EventType
{
}

enum CertificateEventType: string implements EventType
{
}
```

the mapping is:
```xml
<entity name="App\Entity\CertificateEvent">
    <field name="type" type="string" column="type" enum-type="App\Enum\CertificateEventType" nullable="false" />
```

CertificateEvent looks like:
```php
class CertificateEvent extends CaseEvent
{
    public function __construct(
        CertificateEventType $type
    ) {
      parent::__construct($case, $type);
    }
```

```php
abstract class CaseEvent
{
    public function __construct(
        protected EventType $type,
    ) {
```

**Comment by greg0ire** [comment]
Cc @yceruto

**Comment by yceruto** [comment]
Sorry, I'm unable to reproduce it.

The error message reports that the metadata field type is "string," which should match the backing type in this case: https://3v4l.org/lDs2P.

Can you create a failing test case for it?

By the way, implementing an interface makes no difference in this context.

**Comment by greg0ire** [comment]
@yceruto I think the issue is that `CertificateEvent` inherits `$type` from the abstract class, which uses a property typed as `EventType`. `CertificateEventType` is just the type of the constructor parameter, which Doctrine does not analyse.

**Comment by yceruto** [comment]
Oh, I see. So, in that case I think we could add another validation check to know if the property type is a parent of the mapped enum type, and if so, skip it.

I will check if it's possible to refactor the current conditions to include this special case.
