### ISSUE TITLE
Single Table Inheritance - issue

### ISSUE THREAD

**Issue by fico7489** [doctrine/doctrine2#11127]
This is example from documentation:

https://www.doctrine-project.org/projects/doctrine-orm/en/2.17/reference/inheritance-mapping.html#design-time-considerations

```
#[Entity]
#[InheritanceType('SINGLE_TABLE')]
#[DiscriminatorColumn(name: 'discr', type: 'string')]
#[DiscriminatorMap(['person' => Person::class, 'employee' => Employee::class])]
class Person
{
    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'persons')]
    private Collection $users;
}

#[Entity]
class Employee extends Person
    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'employees')]
    private Collection $users;
}
```

Is it possible to have both relations with **inversedBy** like this:

```
#[Entity]
class User
{
    #[ORM\ManyToMany(targetEntity: Person::class, inversedBy: 'users')]
    private Collection $persons;
    
    #[ORM\ManyToMany(targetEntity: Employee::class, inversedBy: 'users')]
    private Collection $employees;
}
```

What is suggestions for achieve this?

**Comment by greg0ire** [comment]
> This is example from documentation

I'm confused… the page you linked does not mention `$users` at all, does it? :thinking:

**Comment by fico7489** [comment]
it is extended example based on documentation example

**Comment by yard-mschwartz** [comment]
Your example seems bugged to me

* Why would `Employee` need `private Collection $users;` when `Person` (its parent) already has `private Collection $users;`?
* Also, why do you have `mappedBy: 'employees'` in `Person`, and `mappedBy: 'persons'` in `Employee`?

**Comment by fico7489** [comment]
@yard-mschwartz  

thanks for response

yes, you are right it was buggy, I now replaced mappedBy.

yes, Person (its parent) already has private Collection $users; but that relation is not working inside Employee because 
mappedBy is **persons**, not **employees**

I am looking for some king of mechanism to change mappedBy for that relation inside Employee.
