### ISSUE TITLE
MappingException with report_fields_where_declared: true

### ISSUE THREAD

**Issue by BackNot** [doctrine/doctrine2#11129]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.17.1

#### Summary
With the option report_fields_where_declared I get error 
```
Duplicate definition of column 'id' on entity 'App\Entity\A' in a field or discriminator column mapping.
```

#### Reproduce 

I updated the doctrine recipe and set this option to true:
```
report_fields_where_declared: true
```

I have the following class hierarchy:

```
[ORM\Table(name: "`classa`")]
#[ORM\Entity(repositoryClass: "App\Repository\ARepository")]
#[ORM\HasLifecycleCallbacks]
class A extends B 
{

   ... 
}

```

```
#[ORM\Table(name: "`classb`")]
#[ORM\Entity(repositoryClass: "App\Repository\BRepository")]
#[ORM\HasLifecycleCallbacks]
#[ORM\InheritanceType("JOINED")]
#[ORM\DiscriminatorColumn(name: "dType", type: Types::STRING)]
class B extends C
{
  
    ....
}
```
```
abstract class C 
{
     #[Id, ORM\GeneratedValue(strategy: 'AUTO')]
    #[ORM\Column(name: 'id', type: Types::INTEGER)]
    protected ?int $id = null;
}
```

I understand that with this setting if I have the property "id" both in my parent and child the error will be shown. But currently I just inherit it and I do not overwrite it anywhere.

If I drop class C and put this field in class B this error is not triggered.

**Comment by derrabus** [comment]
cc @mpdude

**Comment by mpdude** [comment]
The C class contains mapping information but is not an entity nor a mapped superclass. Is that correct?

**Comment by mpdude** [comment]
Also, you’re relying on an autogenerated discriminator map?

**Comment by BackNot** [comment]
Yes, to both questions.

**Comment by mpdude** [comment]
Are you aware that this is not a supported way of configuration?

Out of curiosity, may I ask why you’re doing it that way?

**Comment by BackNot** [comment]
I didn't know that it was not supported. I have entities that have the same set of 3-4 properties and schema and I thought that I can reuse it. Thanks for the info.

**Comment by mpdude** [comment]
Maybe a mapped superclass helps?

**Comment by mpdude** [comment]
See the second yellow box at https://www.doctrine-project.org/projects/doctrine-orm/en/2.17/reference/inheritance-mapping.html#inheritance-mapping

**Comment by BackNot** [comment]
I can confirm that mapped superclass solved my problem. I am going to close the issue.
