### ISSUE TITLE
Pass parameters from column mapping to custom type

### ISSUE THREAD

**Issue by antman3351** [doctrine/doctrine2#11156]
### Feature Request
|    Q        |   A
|------------ | ------
| New Feature | yes ( I think )
| RFC         | no idea
| BC Break    | yes

#### Summary

I would like to be able to pass parameters from the column mapping to the custom type.
Is there a reason it's not ( I couldn't find a way ) / shouldn't be implemented ? or just there hasn't been a need ?

e.g.
`#[ORM\Column( name: 'foo', type: 'custom', options: [ 'foo' => 'bar' ] )]`

```PHP
abstract class Type
{
    public function convertToDatabaseValue($value, AbstractPlatform $platform, ?array $options )
    {
         return $value;
    }

    public function convertToPHPValue($value, AbstractPlatform $platform, ?array $options )
    {
        // if $options['foo']... do something...
        return $value;
    }
}
```

Would it be just the case of adding the parameter to `Doctrine\ORM\Internal\Hydration\AbstractHydrator::hydrateColumnInfo` and then passing it along in `Doctrine\ORM\Internal\Hydration\AbstractHydrator::hydrateRowData` and who ever extends it ?

edit: Set BC Break to yes as the child type classes would need to add the parameter. unless you don't declare the parameter in the the  parent class, the child class declares it as optional and the caller just passes the options in anyway but that seems messy. 

Thanks,
Antonio

**Comment by mpdude** [comment]
Might be the same request as in #11121

**Comment by antman3351** [comment]
You're right! I did search for same request I guess not well enough.  I'll close this and comment on the other request.
