### ISSUE TITLE
orderBy not being respected

### ISSUE THREAD

**Issue by brian-codes** [doctrine/doctrine2#11163]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | 2.17.2

#### Summary

I have a relationship between Threads and Messages. One thread can contain many Messages. Using XML mapping there is an orderBy entry stating the collection of messages should be ordered by their created at date. This works correctly on v2.16.3 but open upgrading to 2.17.2 this is no longer respected and the collection of messages is ordered by it's UUID.

#### Current behavior

orderBy entry not being respected and instead sorting the collection by UUID

#### How to reproduce

Use QueryBuilder to get a collection of Threads.

```
    <entity repository-class="App\ThreadRepository" name="App\Thread" table="threads">
        <one-to-many field="messages" target-entity="App\Message" mapped-by="thread" fetch="EAGER">
            <order-by>
                <order-by-field name="createdAt"/>
            </order-by>
        </one-to-many>
    </entity>
```

```
    <entity repository-class="App\MessageRepository" name="App\Message" table="messages">
        <field name="createdAt" type="datetime" column="created_at"/>
        <many-to-one field="thread" target-entity="App\Thread" inversed-by="messages"/>
    </entity>
```

```
    $qb = $this->getEntityManager()->createQueryBuilder();

    $qb
    ->select('thread')
    ->from(Thread::class, 'thread');

    return $qb->getQuery()->getResult();
```

#### Expected behavior

orderBy entry to be respected and order the collection by the stated field.

**Comment by mpdude** [comment]
Could you please check whether it is specific for the XML mapping and/or using fetch=EAGER?

**Comment by grossmannmartin** [comment]
the same problem occurs with annotation mapping (learned the hard way today 😆 )

**Comment by greg0ire** [comment]
@grossmannmartin are you using `fetch=EAGER`?

**Comment by grossmannmartin** [comment]
Yes, Yes I was. 
In the end, I rewrote it without EAGER and that resolved my issue.

**Comment by greg0ire** [comment]
Then it is probably caused by https://github.com/doctrine/orm/pull/8391, Cc @beberlei

**Comment by Alvaro948** [comment]
Tested con 2.18.0, does not work:

```php
#[ORM\OneToMany(mappedBy: 'parent', targetEntity: VariableEntity::class, fetch: 'EAGER')]
#[ORM\OrderBy(value: ['name' => 'ASC'])]
private Collection $variables;
```

**Comment by cttboehme** [comment]
We have hit the same problem of the `orderBy` attribute not being respected.
And yes, the suspected #8391 is the cuprit.
In particular, this line is at fault:

https://github.com/beberlei/doctrine2/blob/ec74c83845231fa913b387a9cc1589d5586d0e0e/lib/Doctrine/ORM/UnitOfWork.php#L3182C1-L3183C1

If I change this to:

```
$found = $this->getEntityPersister($targetEntity)->loadAll([$mappedBy => $entities], $mapping['orderBy']);
```

all is well again (at least for our simple case).

**Comment by brian-codes** [comment]
Thankyou @tomasz-ryba @greg0ire
