### ISSUE TITLE
DoctrineSetup is missing

### ISSUE THREAD

**Issue by simPod** [doctrine/doctrine2#11217]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.0.0

#### Summary

https://github.com/doctrine/orm/blob/7527b788dec9b9003e75004ed65c0dcb3753c70e/UPGRADE.md?plain=1#L496

This says there's DoctrineSetup class

<img width="818" alt="image" src="https://github.com/doctrine/orm/assets/327717/2efb7c88-0d54-43cb-828d-ad14345df64f">

#### Current behavior

The class does not exist

**Comment by derrabus** [comment]
#11218

**Comment by simPod** [comment]
Orm setup is missing create default annotation driver method 🤔

**Comment by greg0ire** [comment]
Yeah, we removed annotations in favor of attributes.

https://github.com/doctrine/orm/blob/7527b788dec9b9003e75004ed65c0dcb3753c70e/UPGRADE.md?plain=1#L162-L168
