### ISSUE TITLE
How can I make entities from a existing database without the command 'doctrine:mapping:import'

### ISSUE THREAD

**Issue by siburuxue** [doctrine/doctrine2#11245]
![852237ed7c06f5de3ae9d185fdefb9dc](https://github.com/doctrine/orm/assets/15135780/32d603a0-d495-465e-8472-bd3584793937)
In the database that has 188 tables and in the symfony 7.0 , doctrine/orm version is 3.0 how can I make entities automatically？
 Is there any other way to finish it with out the import command?

**Comment by beberlei** [comment]
Three approaches:

* You can copy adapt the code from `EntityGenerator` and `DatabaseDriver` from the latest 2.x branch to build a command for yourself that does the generation. It should only be those two classes
* Directly work with `SchemaManager`, `listTables` and so on to pipe this metadata into https://docs.laminas.dev/laminas-code/ for code generation.
* Buy a tool that does it for you, such as Skipper18 and their database import: https://www.skipper18.com/help/how-to-use/getting-started/database-import/

**Comment by siburuxue** [comment]
> Three approaches:
> 
> * You can copy adapt the code from `EntityGenerator` and `DatabaseDriver` from the latest 2.x branch to build a command for yourself that does the generation. It should only be those two classes
> * Directly work with `SchemaManager`, `listTables` and so on to pipe this metadata into https://docs.laminas.dev/laminas-code/ for code generation.
> * Buy a tool that does it for you, such as Skipper18 and their database import: https://www.skipper18.com/help/how-to-use/getting-started/database-import/

In the three approaches, they may not make entities to fit the symfony7 project, and in the symfony project's entities, it uses attribute to depict the private variables ,not annotation.
Is it possible to be back in the feature?

**Comment by siburuxue** [comment]
> Three approaches:
> 
> * You can copy adapt the code from `EntityGenerator` and `DatabaseDriver` from the latest 2.x branch to build a command for yourself that does the generation. It should only be those two classes
> * Directly work with `SchemaManager`, `listTables` and so on to pipe this metadata into https://docs.laminas.dev/laminas-code/ for code generation.
> * Buy a tool that does it for you, such as Skipper18 and their database import: https://www.skipper18.com/help/how-to-use/getting-started/database-import/

Yesterday I have completed this function using App\Command\DoctrineMappingImportCommand. In the process of writing the code, I found that there does not seem to be a lot of descriptive information in the attribute. Is this the reason why this command was deleted in the later version?

**Comment by siburuxue** [comment]
> Three approaches:
> 
> * You can copy adapt the code from `EntityGenerator` and `DatabaseDriver` from the latest 2.x branch to build a command for yourself that does the generation. It should only be those two classes
> * Directly work with `SchemaManager`, `listTables` and so on to pipe this metadata into https://docs.laminas.dev/laminas-code/ for code generation.
> * Buy a tool that does it for you, such as Skipper18 and their database import: https://www.skipper18.com/help/how-to-use/getting-started/database-import/

https://phpzlc.com/blog/1708078971641-4d1418d6765f4-93

**Comment by siburuxue** [comment]
> Three approaches:
> 
> * You can copy adapt the code from `EntityGenerator` and `DatabaseDriver` from the latest 2.x branch to build a command for yourself that does the generation. It should only be those two classes
> * Directly work with `SchemaManager`, `listTables` and so on to pipe this metadata into https://docs.laminas.dev/laminas-code/ for code generation.
> * Buy a tool that does it for you, such as Skipper18 and their database import: https://www.skipper18.com/help/how-to-use/getting-started/database-import/

[doctrine-helper](https://github.com/siburuxue/doctrine-helper)
