### ISSUE TITLE
Fix broken assert(is_numeric($sql)) in DateAddFunction and DateSubFunction

### ISSUE THREAD

**Issue by ondrejmirtes** [doctrine/doctrine2#11240]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.0

#### Summary

I'm working on ORM 3 and DBAL 4 support on phpstan-doctrine, and I have this test case:

```php
				SELECT		DATE_ADD(m.datetimeColumn, m.intColumn, \'day\'),
							DATE_ADD(m.stringNullColumn, m.intColumn, \'day\'),
							DATE_ADD(m.datetimeColumn, NULLIF(m.intColumn, 1), \'day\'),
							DATE_ADD(\'2020-01-01\', 7, \'day\')
				FROM		QueryResult\Entities\Many m
```

Doctrine crashes on this line: https://github.com/doctrine/orm/blob/5a40b99e11a0de532eb866f062dccad20da19add/src/Query/AST/Functions/DateAddFunction.php#L74

The `$sql` value is: `m0_.intColumn`.

I think the `assert` assumption is wrong, as `interval` does not have to refer to a scalar value, but can be a column as well. The job of this part of the codebase is to just generate the correct SQL query to execute against the database.

Same problem is in DateSubFunction too.

#### Current behavior

```
assert(): assert(is_numeric($sql)) failed
```

#### Expected behavior

It should work and generate the right SQL.

**Comment by derrabus** [comment]
That looks like a valid bug. PR welcome if someone wants to give it a try before I find the time.

**Comment by ondrejmirtes** [comment]
I'm trying: https://github.com/doctrine/orm/pull/11243
