### ISSUE TITLE
getAssociationMappedByTargetField on the owning side of a relation fails in 3.0

### ISSUE THREAD

**Issue by stof** [doctrine/doctrine2#11250]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.0.0

#### Summary

Calling `Doctrine\ORM\Mapping\ClassMetadata::getAssociationMappedByTargetField` on a relation which is not an inverse side of a relation does not work anymore in 3.0

#### Previous behavior

In 2.x, the method returned `null` for such cases.

#### Current behavior

this assertion fails: https://github.com/doctrine/orm/blob/9acc70d5b8be55a6ac33e5c7313a124fa90dbe21/src/Mapping/ClassMetadata.php#L2467

#### How to reproduce

I found this when investigating a support question in the Symfony Slack channel. This BC break affects ApiPlatform: https://github.com/api-platform/core/blob/8a35ee20c7aaf03b5a3d96baf920e2c99c5ae0fd/src/Doctrine/Orm/Metadata/Resource/DoctrineOrmLinkFactory.php#L70

To reproduce it, call `getAssociationMappedByTargetField` for a field being the owning side of a relation.

**Comment by derrabus** [comment]
cc @greg0ire

**Comment by Fl0-dev** [comment]
To avoid the problem, downgrade doctrine/orm while waiting for a correction

**Comment by greg0ire** [comment]
> In 2.x, the method returned null for such cases.

That's a violation of the contract in persistence. The ORM CM class should have a signature compatible with that of the persistence CM class. It is documented to always return a string: https://github.com/doctrine/persistence/blob/e7cf418cafe83a75f7a7096cc9fa890b201d28f1/src/Persistence/Mapping/ClassMetadata.php#L126-L131

I think we should replace the assertion with a `LogicException` , advising callers to check with `isAssociationInverseSide` before attempting to call `getAssociationMappedByTargetField`, and add a deprecation about that on 2.19.x

**Comment by greg0ire** [comment]
- Deprecation: https://github.com/doctrine/orm/pull/11309
- Exception: https://github.com/doctrine/orm/pull/11308

**Comment by ZeinMansor** [comment]
The solution resolved the association error but still getting  the following error 

php version: `8.2`
symfony version: `6.4`
symfony cli version: `5.8.11`
doctrine/orm version: `3.1.x-dev (latest one)`
api-platform/core version:  `^3.2`

## Error message

```bash
Context: Calling Doctrine\ORM\Mapping\ClassMetadata::getAssociationMappedByTargetField() with "ro
!!    le", which is the owning side of an association.

!!    Problem: The owning side of an association has no "mappedBy" field.

!!    Solution: Call Doctrine\ORM\Mapping\ClassMetadata::isAssociationInverseSide() to check first in .
!!     (which is being imported from "C:\zein_workspace\FAST\fast-api-v2\config/routes/api_platform.yam
!!    l"). Make sure there is a loader supporting the "api_platform" type.
```

### Role class

```php
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ApiResource]
class Role
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 64)]
    private ?string $name = null;

    #[ORM\OneToMany(targetEntity: User::class, mappedBy: 'role')]
    private Collection $users;



    public function __construct()
    {
        $this->users = new ArrayCollection();
    }
    
/// etc

}


```

### User Class

```php
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ApiResource]
class User
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $firstName = null;


    #[ORM\ManyToOne(targetEntity: Role::class, inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: false, name: "role_id", referencedColumnName: "id")]
    private ?Role $role = null;


    public function __construct()
    {
    }

   // etc
}
```
### i am following the example provided by doctrine project documentation page [here](https://www.doctrine-project.org/projects/doctrine-orm/en/3.0/reference/association-mapping.html#one-to-many-bidirectional)




### is there anything i am missing?

**Comment by greg0ire** [comment]
@ZeinMansor you need to address this inside API platform. If you can't, then report this to API platform.
