### ISSUE TITLE
Column precision is not specified

### ISSUE THREAD

**Issue by ben29** [doctrine/doctrine2#11251]
Hi.
I update to last version of doctrine/ORM (3.0)

using Symfony last version.

Getting error:

`php bin/console doctrine:schema:update --force --complete`

> In InvalidColumnDeclaration.php line 17:
>                                  
>   Column "fee" has invalid type  
>                                  
> 
> In ColumnPrecisionRequired.php line 18:
>                                      
>   Column precision is not specified  
>                                      
> 
> 

    #[ORM\Column(name: 'fee', type: 'decimal', precision: 2, scale: 2, unique: false, nullable: false)]
    #[Assert\NotBlank]
    private string $fee = '0.0';

Also
remove the "precision: 2," will not help.

something wrong with decimal type.

**Comment by ben29** [comment]
any kind of update?

@derrabus - sorry to tag you, but can you help ?

**Comment by derrabus** [comment]
That declaration looks suspicious to me. Doesn't the precision have to be greater than the scale? Apart from that, feel free to dig a little into the issue. I don't have time to do that at the moment.

**Comment by ben29** [comment]
before version 4
I didn’t put the precision,
only the scale and its working.
something happen with the decimal.

**Comment by derrabus** [comment]
Yes, precision and scale are both mandatory now.

**Comment by ben29** [comment]
Ok. But it’s not working…
No matter what I try.

**Comment by ben29** [comment]
I try also:

```
    #[ORM\Column(name: 'fee', type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $fee = '0';
```

the error:

> 
> In InvalidColumnDeclaration.php line 17:
>                                  
>   Column "fee" has invalid type  
>                                  
> 
> In ColumnPrecisionRequired.php line 18:
>                                      
>   Column precision is not specified  


I think maybe it doesn't accept the precision at all.
