### ISSUE TITLE
Ignore orderBy in UOW eagerLoadCollections() method

### ISSUE THREAD

**Issue by lewbor** [doctrine/doctrine2#11381]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.19.1

#### Summary

When using a collection eager loading (UnitOfWork::eagerLoadCollections method), #[OrderBy] attribute  on collection is ignoring now. In line 
`$found = $this->getEntityPersister($targetEntity)->loadAll([$mappedBy => $entities])`
it must be 
`$found = $this->getEntityPersister($targetEntity)->loadAll([$mappedBy => $entities], $mapping['orderBy']);`

**Comment by tomasz-ryba** [comment]
It's an older problem already discussed here #11163 and seems to be related to changes introduced with #8391

**Comment by beberlei** [comment]
Fixed by https://github.com/doctrine/orm/pull/11422
