### ISSUE TITLE
2.19.7 breaks entity parameters when set from query-builder to native-query

### ISSUE THREAD

**Issue by ro0NL** [doctrine/doctrine2#11594]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.19.7

#### Summary

Given `(AbstractQuery) $qb->execute($qb->getParameters())`, if one of the parameters is a proxy entity, since 2.19.7 it produces:

```
Object of class Proxies\__CG__\... could not be converted to string
```

**Comment by ro0NL** [comment]
We have a native query (`$native = $entityManager->createNativeQuery()`)

We then transfer original QB parameters to the native one;

```
foreach ($qb->getParameters() as $k => $p) {
    $native->setParameter($index, $p->getValue(), $p->getType());
    $index++;
}
```

I believe it's incompatible API, but im not sure about the related commit here.

**Comment by greg0ire** [comment]
[A native query you say?](https://github.com/doctrine/orm/pull/11543)

> im not sure about the related commit here.

Try reverting the one in my link please.

**Comment by ro0NL** [comment]
Thanks! We're skipping `processParameterValue` now, thus `getSingleIdentifierValue`

**Comment by ro0NL** [comment]
The triggering call is `$qb->setParameter('products', $products)`, where $products is an array of entities

**Comment by greg0ire** [comment]
It's unclear to me if you've tried reverting the commit or not.

**Comment by ro0NL** [comment]
@greg0ire sorry!

yes, commenting out

```
//            if ($parameter->typeWasSpecified()) {
//                $parameters[$name] = $parameter->getValue();
//                $types[$name]      = $parameter->getType();
//
//                continue;
//            }
```

100% solves it.

I dont think it should be part of a patch release.

**Comment by ro0NL** [comment]
Of course, im also curious if we can maintain the current compatibility, since we rely on default infered typing.

**Comment by stof** [comment]
What is `$p->getType()` in your case ?

**Comment by ro0NL** [comment]
```
Doctrine\ORM\Query\Parameter {#19011 ▼
  -name: "products"
  -value: array:1 [▶]
  -type: 102
  -typeSpecified: false
}
```

But after transfering from QB to native query, it becomes:

```
      -type: 102
      -typeSpecified: true
```

So we ignore typeSpecified, which is an implementation bug on our side. Unless it should be considered in `Parameter::getType` actually ...

**Comment by ro0NL** [comment]
possible userland patch:

```diff
- $native->setParameter($index, $p->getValue(), $p->getType());
+ $native->setParameter($index, $p->getValue(), $p->typeWasSpecified() ? $p->getType() : null);
```

**Comment by ro0NL** [comment]
i've applied the userland patch. Let's consider this an edge case, till further notice :)
