### ISSUE TITLE
`findBy` with more than 2100 parameters generates an error in SQL Server

### ISSUE THREAD

**Issue by bsauvajon26** [doctrine/doctrine2#11603]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | No
| Version     | 2.11

#### Summary

`findBy` with more than 2100 parameters generates an error in SQL Server due to its limitation on the number of parameters in an `IN` clause.

#### Current behavior

Error:
An exception occurred while executing a query: SQLSTATE[IMSSP]: Tried to bind parameter number 2101.  SQL Server supports a maximum of 2100 parameters.

#### How to reproduce

On MSSQL

private EntityRepository $doctrineRepository;
$ids = [1,2,... ,2101];
$this->doctrineRepository->findBy(['id' => $ids ])

#### Expected behavior
Doctrine should handle cases where the number of parameters exceeds 2100.

**Comment by derrabus** [comment]
How should the ORM work around this limitation?

**Comment by bsauvajon26** [comment]
In our case: Split the query into multiple smaller queries, each with a maximum of 2100 parameters, and then aggregate the results.

But it may be complicated if there are more than one condition

**Comment by derrabus** [comment]
… and close to impossible if you want to sort the result.

**Comment by derrabus** [comment]
tbh, my favorite solution would be to close this as a won't fix. Maybe we can document the limitation and possible workarounds.

**Comment by greg0ire** [comment]
> |    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.11

Is this accurate? Did you just upgrade from 2.10 (or lower?) to 2.11 and hit this bug?

**Comment by bsauvajon26** [comment]
This is not a BC break. I made a mistake when submitting the issue. 
Thanks for your answer

**Comment by derrabus** [comment]
Thank you for submitting the issue though. And if you have an idea how to document this limitation, please submit a PR for our documentation.
