### ISSUE TITLE
New `SqlWalker` deprecation missing in its releases and in UPGRADE file for 3.3.0

### ISSUE THREAD

**Issue by janedbal** [doctrine/doctrine2#11690]
### Bug Report

New [SqlWalker deprecation](https://github.com/doctrine/orm/pull/11188) ([commit](https://github.com/doctrine/orm/commit/39d2136f466187a8d1169c1fc307ebd8244a0e1a)) is not present in its releases:
- [3.3.0 release](https://github.com/doctrine/orm/releases/tag/3.3.0)
- [2.20.0 release](https://github.com/doctrine/orm/releases/tag/2.20.0) 
- [3.3.0 upgrade file](https://github.com/doctrine/orm/blob/3.3.0/UPGRADE.md) 
- [2.20.0 upgrade file](https://github.com/doctrine/orm/blob/3.3.0/UPGRADE.md#add-doctrineormqueryoutputwalker-interface-deprecate-doctrineormquerysqlwalkergetexecutor) (properly present)

**Comment by greg0ire** [comment]
Can you send a PR for 3.30?

Regarding releases, we don't usually document deprecations that are just a byproduct of something else in them.

**Comment by janedbal** [comment]
Yes: https://github.com/doctrine/orm/pull/11693
