### ISSUE TITLE
Allows `doctrine/persistence` v4

### ISSUE THREAD

**Issue by llaville** [doctrine/doctrine2#11714]
#### What

Latest release of `doctrine/orm` v3.3 still requires [`doctrine/persistence`](https://github.com/doctrine/orm/blob/3.3.x/composer.json#L34) version greater than 3.3.1 but not allow latest version 4.0

Both are PHP 8.1 compatible

#### Why

Is there any reason, or just forgotten ?

**Comment by greg0ire** [comment]
v3.3 will never allow persistence v4, since v3.3 is in maintenance mode.
On the other hand, v3.4 already supports v4: https://github.com/doctrine/orm/pull/11533
It just needs a release, but since 3.3 is only one month old, I don't feel like releasing 3.4 just yet. Why are you in such a hurry?

**Comment by llaville** [comment]
@greg0ire No I'm not in a hurry. 
I've just noticed that persistence v4 was released and was not installed when I've begun my migration in my project https://github.com/llaville/php-compatinfo-db/issues/140#issuecomment-2464948008 that's all !

**Comment by greg0ire** [comment]
Ok well sorry, but I don't plan releases with due dates and things like that. It just happens when I have time to work on it. If you want things to move forward, the best way is contribute.
