### ISSUE TITLE
Why doctrine failed to save the key?

### ISSUE THREAD

**Issue by profesionalaiesam** [doctrine/doctrine2#11742]
### Bug Report

|    Q                                        |   A
|-------------------------------------------- | ------
| Version                                     | 2.16.2
| Previous Version if the bug is a regression | x.y.z

#### Summary

Why do you think it happens? Sometimes in prod it just doesn't save the key correctly.

#### Current behavior

![image](https://github.com/user-attachments/assets/0c2e9ec0-97b3-4618-8058-07f500fb046a)

#### How to reproduce

I don't know how to reproduce this

**Comment by greg0ire** [comment]
With the details you've provided, all I can say is this looks like a `symfony/cache` problem. Also, you should update your packages before you file bug reports, 2.16.x is no longer supported.
