### ISSUE TITLE
@OrderBy annotation does not apply

### ISSUE THREAD

**Issue by tszymanek** [doctrine/doctrine2#5539]
As stated in my [stackoverflow question](http://stackoverflow.com/questions/34122195/sort-arraycollection-with-orderby-annotation-issue) there appears to be a bug causing the ArrayCollection to be unsorted when I'm retrieving the entity with `find(1)`. The whole thing miraculously works when I use `findOneBy(array('id' => 1))`. Please check the link mentioned above for further detail. 

Hope I wrote this in the right section and it's going to be resolved. Best regards

**Comment by dlancea** [comment]
This might be related to Issues #4256 and #4739 .

Try removing `fetch="EAGER"`

**Comment by guilhermeblanco** [comment]
Closing as a duplicate of #4256
