### ISSUE TITLE
Cache component generates too long filename for encrypted filesystem

### ISSUE THREAD

**Issue by korotovsky** [doctrine/doctrine2#5541]
I have `Ubuntu 14.04.2 LTS` with encrypted filesystem. It's known limitation, but I think Doctrine should work on such configurations.

As a result doctrine generates cache on each request.

```
rename(/data/www/sf2-app/app/cache/dev/annotations/3a/swaplxj6AI,/data/www/sf2-app/app/cache/dev/annotations/3a/5b5b435d4564737465725c42756e646c655c41707042756e646c655c456e746974795c557365725c557365722466697273744e616d65405b416e6e6f745d5d5b315d.doctrinecache.data): File name too long
Context: { "type":2,"file": "/data/www/sf2-app/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php", "line":254,"level":28928,"scream":true}
```

**Comment by beberlei** [comment]
Please open issue on github.com/doctrine/cache

**Comment by korotovsky** [comment]
@beberlei I thought about it before posting this issue, but I can't:

![screenshot from 2015-12-10 11 33 54](https://cloud.githubusercontent.com/assets/104727/11710752/8135df4c-9f32-11e5-9a0f-47901c361b84.png)

**Comment by smoench** [comment]
@beberlei but there isn't any possibility (jira down and github issues are diasabled) :smiley:

**Comment by guilhermeblanco** [comment]
<img width="1011" alt="screen shot 2015-12-10 at 10 22 23 am" src="https://cloud.githubusercontent.com/assets/208883/11719265/f2ec825e-9f27-11e5-8f0b-b118592a4ebf.png">

WTF!?

**Comment by guilhermeblanco** [comment]
Anyway... I disabled and re-enabled Issues (it might be a GH issue).
Check if it shows it for you now... =)

**Comment by korotovsky** [comment]
@guilhermeblanco It works :) Thanks.

**Comment by beberlei** [comment]
@korotovsky sorry my mistake, i saw it this morning and enabled it.
