### ISSUE TITLE
error when table namespace (schema) contains a hyphen (-)

### ISSUE THREAD

**Issue by kolesar-andras** [doctrine/doctrine2#5545]
I build Laravel project, test environment had schema was named "web-test" in postgresql. I have set database search_path to "web-test", everything worked in Laravel except changing column definitions. Migration code contains this line:

	$table->text('notes')->nullable()->change();

Migration gives error:

	[Doctrine\DBAL\Schema\SchemaException]   
	There is no column with name 'notes' on table 'reports'.

There is a column named notes in the table. I have checked Doctrine\DBAL\Schema\Table why does it throw Doctrine\DBAL\Schema\SchemaException. Dumped $_columns property in method hasColumn but it was an empty array.

I have changed schema name to "webtest" and renaming column worked.

**Comment by Ocramius** [comment]
I don't see `web-test` in any of the examples above.

A few questions:

 - is this an actual ORM bug? Are you using the ORM or just DBAL?
 - can this be reproduced with just the DBAL test suite?

**Comment by kolesar-andras** [comment]
Schema name "web-test" does not appear in the code because it comes from environment variable. It is also not visible in the error messages because DBAL gets only the table name "reports" without schema.

Laravel uses only DBAL, now I found https://github.com/doctrine/dbal repository, I think this issue should be reported there. Agree?

**Comment by Ocramius** [comment]
Yes, but we need more details on how to reproduce it *outside* the context of laravel.

Closing here meanwhile.

**Comment by kolesar-andras** [comment]
I have made tests in DBAL, localized the problem, made a solution that satisfies tests and created a pull request.

**Comment by Ocramius** [comment]
@kolesar-andras thanks!
