### ISSUE TITLE
Expression builder doesn't convert boolean value to 0 or 1.

### ISSUE THREAD

**Issue by tomazahlin** [doctrine/doctrine2#5546]
I am using query builder and the expression builder to create a query.

```php
$qb->andWhere($qb->expr()->eq('a.property', false));
```

Generates: `"WHERE ... a.property = "` (without any value)

While 
```php
$qb->andWhere($qb->expr()->eq('a.property', true));
```

Generates: `"WHERE a.property = 1"`

And 
```php
$qb->andWhere($qb->expr()->eq('a.property', 0));
```

Generates: `"WHERE a.property = 0"`

The property is annotated as boolean and doctrine knows it is boolean too. Any suggestions?

Thank you.

**Comment by Ocramius** [comment]
This is expected behavior: the query builder is a string builder, and it doesn't care about the types of the passed in parameters: it just converts them to strings in the end.

What you are supposed to do with any parameter is to use parameter binding instead:

```php
$qb->andWhere($qb->expr()->eq('a.property', ':propertyCheck'));
$qb->setParameter('propertyCheck', false);
```

**Comment by tomazahlin** [comment]
Thank you for the help, sounds fine.
