### ISSUE TITLE
Doctrine2 entitiy generation with periods in mysql column name broken

### ISSUE THREAD

**Issue by edvallie** [doctrine/doctrine2#5560]
One of my MySQL tables has a field with a period in the name. Reversing the schema and generating entities with:

php app/console doctrine:mapping:import --force AppBundle xml --verbose
php app/console doctrine:mapping:convert annotation ./src
php app/console doctrine:generate:entities AppBundle

The third command fails because the generated entity has a peroid in the variable name that is interpretted as concatenation.

[2015-12-17 13:49:01] php.CRITICAL: Fatal Parse Error: syntax error, unexpected '.', expecting ',' or ';' {"type":4,"file":"/var/www/myapplication/src/AppBundle/Entity/Webtools.php","line":53,"level":-1,"stack":[]}

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Parse Error: syntax error, unexpected '.', expecting ',' or ';'

Line 53 of Webtools.php, generated by:
    private $lots.id;

**Comment by edvallie** [comment]
Forgot to mention:

        "symfony/symfony": "2.7.*",
        "doctrine/orm": "^2.4.8",
        "doctrine/doctrine-bundle": "~1.4",

**Comment by Majkl578** [comment]
EntityGenerator is going to be removed in Doctrine 3.0, sorry for no response and thanks for reporting.
