### ISSUE TITLE
MSSQL Doesn't support grouping by an aliased variable

### ISSUE THREAD

**Issue by gnat42** [doctrine/doctrine2#5567]
The following SQL is invalid for SQL SRV.

```
SELECT YEAR(someDate) as theYear FROM tablename GROUP BY theYear
```

However this is valid

```
SELECT YEAR(someDate) as theYear FROM tablename GROUP BY YEAR(someDate)
```

Unfortunately due to #5561  you cannot write a DQL query like the above. Also because of that SQL difference queries now need to care about the platform unless doctrine would take the variable and substitute the calculation instead for SQL SRV.

**Comment by zeroedin-bill** [comment]
You can use a named native query to accomplish this.

See http://docs.doctrine-project.org/en/latest/reference/native-sql.html#named-native-query
