### ISSUE TITLE
entityGenerator bugs

### ISSUE THREAD

**Issue by poolerMF** [doctrine/doctrine2#5568]
hello ... I'm trying to make custom ClassMetadataInfo .. and then generate entity

when I map oneToOne or oneToMany, there is automatically added joinColumns in mapping ...

in EntityGenerator, function generateAssociationMappingPropertyDocBlock -> 

```
if (isset($associationMapping['joinColumns']) && $associationMapping['joinColumns']) {
    .... generating @JoinColumns ...
}
```

generating @JoinColumns should by ONLY in manyToOne or manyToMany  association type ...

**Comment by poolerMF** [comment]
next bug .. there is missing indexBy (in oneToMany association type)
in EntityGenerator, in function generateAssociationMappingPropertyDocBlock:

there should be:

            if (isset($associationMapping['indexBy'])) {
                $typeOptions[] = 'indexBy="' . $associationMapping['indexBy'] . '"';
            }

**Comment by Majkl578** [comment]
EntityGenerator is going to be removed in Doctrine 3.0, sorry for no response and thanks for reporting.
