### ISSUE TITLE
Validating DateTime with NoObjectFound in Zend Doctrine

### ISSUE THREAD

**Issue by adarshkhatri** [doctrine/doctrine2#5574]
I am trying to validate my datetime in zend but no luck so far.

This is my function:

    private function addHolidayFilter()
        {
            $entityManager = $this->getEntityManager();

            ////////allocatedate is datetime type in db
            $this->form->getInputFilter()->get('allocatedate')->getValidatorChain()->attach(
                new NoObjectExistsValidator(array(
                    'object_repository' => $entityManager->getRepository('Holiday\Entity\Holiday'),
                    'fields'            => array('holidaydate'), ///////holidaydate is also datetime type in db
                    'messages' => array(
                        'objectFound' => $this->getTranslatorHelper()->translate('You cannot choose this date. It is holiday.'),
                    ),
                ))
            );
        }

**What I am trying to achieve?**

I have got a holiday in my `table 1` and while adding data to `table 2`, I would like to check if chosen date exist in `table 1`.

If exist, throw custom message, else call add controller function.

However this is throwing me this message:

> Fatal error: Call to a member function format() on string in
> /Applications/XAMPP/xamppfiles/htdocs/skeleton/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/DateTimeType.php
> on line 53

**I am not sure if this is the right place to ask this qst. And this might not be a issue at all.**
I had asked this qst in stackoverflow as well: http://stackoverflow.com/questions/34435198/validating-datetime-in-zend-doctrine

**Comment by Ocramius** [comment]
The information you supplied is incomplete: what is the stack trace for
that error?
Also, I'm not sure if you can use the NoObjectExistsValidator, as it will
use strict comparison internally (if I remember correctly)

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by adarshkhatri** [comment]
Thank you for quick reply.

That's all the error message I am receiving, it's fatal error.

**Scenario**
I believe when this looks for `Holiday/Entity/Holiday` entity table for datetime, it returns data as string, not an object, and `format()` function is called in `doctrine/dbal/lib/Doctrine/DBAL/Types/DateTimeType.php
on line 53` needs obviously object.

I can confirm that I need to compare strictly with the holiday so that I will not allow users to choose that date.

Is there any other way to achieve this in Doctrine/ZF2?

**Comment by Ocramius** [comment]
Hi,

On 26 December 2015 at 12:04, Adarsh Khatri <notifications@github.com>
wrote:

> I believe when this looks for Holiday/Entity/Holiday entity table for
> datetime, it returns data as string, not an object, and format() function
> is called in doctrine/dbal/lib/Doctrine/DBAL/Types/DateTimeType.php


Believing won't bring you anywhere: please get the complete stack trace.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by Ocramius** [comment]
Also, just realized that this is not an issue, therefore closing here: please ask for further help on the stackoverflow question that you linked above.
