### ISSUE TITLE
Compabibility with php 5.4 broken

### ISSUE THREAD

**Issue by emil-nasso** [doctrine/doctrine2#5588]
The documentation in this repository states that doctrine is for php 5.4+.

This patch adds usage of `::class`, which breaks 5.4 compatibility. `::class` is a php 5.5 feature. 

The patch: https://github.com/doctrine/common/commit/3a5d93325b243b0c66405a9f6500ff8ac6fe8464
`::class` documentation: http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class

**Comment by beberlei** [comment]
That is not a bug, doctrine/common is depending on PHP 5.5 starting with version 2.6

**Comment by emil-nasso** [comment]
Thanks for helping out. I fixed it. The problem was on my side.

For future reference, if anyone finds this, i was running php 5.6 when i was building the application and 5.4 when i was running it. the build installed dependencies for php 5.6, which (obviously) broke the application.
