### ISSUE TITLE
Wrong $saveMode parameter documentation in SchemaTool::updateSchema

### ISSUE THREAD

**Issue by dcb** [doctrine/doctrine2#5596]
In `Doctrine\ORM\Tools\SchemaTool::updateSchema` the documentation states that "If $saveMode is set to true the command is executed in the Database, else SQL is returned.". That is wrong since the method never returns anything.
What actually happens when `$saveMode` is true is that the method calls `toSaveSql` instead of `toSql` in `SchemaDiff` which produces a non-destructive update. The details can be found in the documentation of `Doctrine\DBAL\Schema\SchemaDiff::toSaveSql()`. This is very useful, for example, when you want to do a partial update of the schema, you need `$saveMode` set to true otherwise `updateSchema` would drop all the tables not included in the update, learned that the hard way.

**Comment by deeky666** [comment]
Yeah this seems to be a copy/paste issue from `getUpdateSchemaSql()`

**Comment by deeky666** [comment]
Noticing that also `getUpdateSchemaSql()` is wrong as is it oppositely states it will execute commands in DB eventually which is not true either.

**Comment by Ocramius** [comment]
Done via #5597
