### ISSUE TITLE
ORM Quoting Strategy

### ISSUE THREAD

**Issue by simon-adams** [doctrine/doctrine2#5607]
When using Oracle as a platform and having a long column name like 'h_and_s_check_via_visit_only', the getColumnAlias is trimming the name down after it has been concatenated with the counter. Resulting in an alias that now starts with an underscore, which I believe in oracle can only start with a letter, subsequently throwing an 'ORA-00911: invalid character' exception.

**Comment by Ocramius** [comment]
This can probably be fixed by making sure that [`DefaultQuoteStrategy#getColumnAlias()`](https://github.com/doctrine/doctrine2/blob/196ea2d0c512dda56ebcbdf7a1535d20cbc2ad43/lib/Doctrine/ORM/Mapping/DefaultQuoteStrategy.php#L158) doesn't generate a name with an underscore first.


Requires failing test cases.

**Comment by Jodaille** [comment]
Hello,
we also have a case of big name tables on Oracle ... :-)

> An exception occurred while executing 'SELECT a.* FROM (SELECT t0.CLI_CODE AS CLI_CODE_1, t0.CLI_ZZ_PER_DEP_SOC_CODE_CREAT AS _ZZ_PER_DEP_SOC_CODE_CREAT_151 FROM XN_CLI t0 WHERE t0.CLI_CODE IN (?, ?)) a WHERE ROWNUM <= 1' with params ["788766"]:

> ORA-00911: invalid character

We have made a bad hack to prevent aliases names starting by _ : 

    --- vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/DefaultQuoteStrategy.php	2016-02-16 15:22:45.000000000 +0100
    +++ vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/DefaultQuoteStrategyMine.php	2016-02-16 15:22:39.000000000 +0100
    @@ -157,6 +157,7 @@
             $columnName = substr($columnName, -$platform->getMaxIdentifierLength());
             $columnName = preg_replace('/[^A-Za-z0-9_]/', '', $columnName);
             $columnName = is_numeric($columnName) ? '_' . $columnName : $columnName;
    +        $columnName = str_replace('_','',$columnName);

             return $platform->getSQLResultCasing($columnName);
         }

We did not find now how to change the default quote strategy in ZF2 config.

**Comment by ostrolucky** [comment]
In Doctrine 3.x, everything is quoted, so this should be resolved

**Comment by cobhimself** [comment]
Is there a reason why this can't be handled in 2.x? Waiting for the 3.0 milestone to have this fixed is killing my upgrade progress.

**Comment by ostrolucky** [comment]
Yes. It's a BC break.
