### ISSUE TITLE
Doctrine Error Handling while Executing Multiple Queries

### ISSUE THREAD

**Issue by feridmovsumov** [doctrine/doctrine2#5608]
I have an schema sql file (with syntax error) including multiple queries for settings database

example.sql
```sql
CREATE TABLE IF NOT EXISTS `example` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` text COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;


CREATExxxxxxxxxx TABLE IF NOT EXISTS `example2` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` text COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;
```
example.php
```php
$sqlContent = file_get_contents("example.sql");
$stmt = $conn->prepare($sqlContent);
$result = $stmt->execute();
```

execute method doesn't throw any exception even that my sql is incorrect. it documentation says it returns false on failure but it returns true.

How should I do exception hanling here? How can I check if my query has an error?

I asked question on StackOverflow: http://stackoverflow.com/questions/34766314/doctrine-error-handling-while-executing-multiple-queries

**Comment by deeky666** [comment]
Closing this as duplicate in favour of https://github.com/doctrine/dbal/issues/2299 which is the right place for the discussion.
