### ISSUE TITLE
doing raw sql with createNativeQuery

### ISSUE THREAD

**Issue by BardiaAfshin** [doctrine/doctrine2#5611]
I'm trying to create a raw sql query , I get the error

```php
Cannot evaluate expression
```

source code:
```php
$rs = new Doctrine\ORM\Query\ResultSetMapping;
$query = $em->createNativeQuery('SELECT alpha*_2_code FROM my_table', $rsm);
```

help?

**Comment by deeky666** [comment]
@BardiaAfshin the SQL looks from. `alpha*_2_code` usually is not a valid identifier if unquoted. Also where do you get the error? Is it a Doctrine or database error and which database are you using?

**Comment by Ocramius** [comment]
I just checked: there is no such string coming out of the DBAL or ORM: closing as `Invalid`

**Comment by Ocramius** [comment]
To clarify: yes, this is the database throwing an error (rightfully so)
