### ISSUE TITLE
Ordering by an added field in SQL Server, and paginating

### ISSUE THREAD

**Issue by Alsciende** [doctrine/doctrine2#5616]
When using the QueryBuilder on a SQL Server database, a query that looks like

```
$qb = $this->doctrine->createQueryBuilder();
$qb->select('d');
$qb->from('AppBundle:Decklist', 'd');
$qb->addSelect('(1+d.nbVotes)/2 AS HIDDEN popularity');
$qb->orderBy('popularity', 'DESC');
$qb->setFirstResult(0);
$qb->setMaxResults(30);
$qb->distinct();
$this->getPaginator($qb->getQuery());
```

will be converted into:

```
SELECT * FROM (
SELECT 
		DISTINCT d0_.id AS id_0, 
		/* fields cut for clarity */
		(1 + d0_.nb_votes) / 2 AS sclr_12
		ROW_NUMBER() OVER (ORDER BY sclr_12 DESC) AS doctrine_rownum 
	FROM decklist d0_
) AS doctrine_tbl 
WHERE doctrine_rownum BETWEEN 1 AND 30 
ORDER BY doctrine_rownum
```

(actual value of "popularity" changed for the sake of simplicity)

But SQL Server doesn't support aliases in the OVER (ORDER BY) syntax, and throws an error

```
SQLSTATE[42S22]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'sclr_12'.
```

**Comment by deeky666** [comment]
@Alsciende this could possibly have been fixed by https://github.com/doctrine/dbal/pull/818. Please upgrade DBAL to at least `2.5.3` and see if the issue still is there. Thanks.

**Comment by Alsciende** [comment]
Updated to 2.5.3 and it worked like a charm. Thank you so much!

**Comment by deeky666** [comment]
You are very welcome ;)

**Comment by zeroedin-bill** [comment]
:sweat_smile:
