### ISSUE TITLE
Not escaped keywords in insert statement

### ISSUE THREAD

**Issue by osavchenko** [doctrine/doctrine2#5618]
I catch error:
`An exception occurred while executing 'INSERT INTO product_attribute (multiple, limit, attribute_id, product_attribute_block_id) VALUES (?, ?, ?, ?)' with params [0, null, 1, null]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'limit, attribute_id, product_attribute_block_id) VALUES (0, NULL, 1, NULL)' at line 1} `
I have column named `limit` and it's not escaped in this request.
Database: MySQL 5.6.

If this is a bug I can fix it and create PR if it will be useful.

**Comment by Ocramius** [comment]
Please refer to http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/limitations-and-known-issues.html#identifier-quoting-and-legacy-databases
