### ISSUE TITLE
"Class 'Doctrine\Tests\OrmFunctionalTestCase' not found" when trying to run PHPUnit

### ISSUE THREAD

**Issue by StanleySathler** [doctrine/doctrine2#5620]
Guys, since I'm new as developer, I'm trying to participate on Open Source community.

I have here a Xubuntu 14.04, 64-bits. Already installed Apache2, MySQL and PHP5 (5.5.9). After forked the repository, I'm trying to run the unit tests... it is my first time with them.

I've been following [these instructions](https://github.com/StanleySathler/doctrine2/tree/master/tests), but when I type **$ phpunit Doctrine/Tests/ORM/Functional/Locking/GearmanLockTest.php**, I get this error:

_PHP Fatal error:  Class 'Doctrine\Tests\OrmFunctionalTestCase' not found in /var/www/html/doctrine2/tests/Doctrine/Tests/ORM/Functional/Locking/GearmanLockTest.php on line 14_

I think that I'm missing something, because I already checked this class and its namespace and, theoretically, it exists.

Could someone help me? And I am sorry if I am making a foolish mistake.

**Comment by Ocramius** [comment]
@StanleySathler 

```sh
git clone git@github.com:doctrine/doctrine2.git
cd doctrine2
composer install
./vendor/bin/phpunit
```

Try that :-)

**Comment by Ocramius** [comment]
Also, obviously requires patching those docs, I suppose :-\

**Comment by StanleySathler** [comment]
@Ocramius 

I installed composer and its packages, but I don't have any idea of how patch these docs. Is it something like a class mapper? Could you send me any link that could me teach more about it?

**Comment by Ocramius** [comment]
@StanleySathler if that snippet I gave you works (tests run), then you can simply edit [`tests/README.markdown`](https://github.com/doctrine/doctrine2/blob/a4d84e0cd8cc4ea1b99f4fd7d1d560f3fbe27c30/tests/README.markdown) and send it back at us (you can edit it directly from the github UI)

**Comment by Jean85** [comment]
I've done it ;)

**Comment by Ocramius** [comment]
Linking #5623

**Comment by StanleySathler** [comment]
Ocramius, the snippet didn't work. I'll try Jean's suggestions and I'll back with feedback.

**Comment by Jean85** [comment]
@StanleySathler , my snippet is the same, I just added that you need to install at least SQLite to have a green test suite to start with.

**Comment by lcobucci** [comment]
@Ocramius do we need to update anything here regarding this issue?

**Comment by Ocramius** [comment]
No, this is dealt with in https://github.com/doctrine/doctrine2/pull/5623
