### ISSUE TITLE
possible to skip adding field to entity?

### ISSUE THREAD

**Issue by BardiaAfshin** [doctrine/doctrine2#5624]
I have a one to many relationship. On the many side of the table, there's a field that's not implemented in the actual entity. I would like to skip adding the field to the entity, and do a lookup on in via raw sql.

example:
customer => order
one => many

Is this possible with query builder?

```php
        $qb->leftJoin('Orders', 'oso', 'WITH', 'oso.order = c.id');


        $qb->andWhere('oso.some_field IN (:customerOrders')
            ->setParameter('some_field', [1,2,3] );
```

**Comment by backbone87** [comment]
This report is not an issue about the development of doctrine. Please use the mailing list or IRC http://www.doctrine-project.org/community.html for questions regarding the usage of doctrine.

PS Yes the query builder can be used for your problem

**Comment by Ocramius** [comment]
Hydrating fields for specific DQL queries is not supported: either a field is mapped or it is completely ignored by the orm.

Closing as `Invalid` here, as this is not an issue, but a help request.

**Comment by backbone87** [comment]
Now i understood his question, he want to impose a condition on an unmapped field of the entity table. This is still possible by using native SQL and a custom ResultSetMapping. http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/native-sql.html
