### ISSUE TITLE
Downgrade (wrong release marked as latest)

### ISSUE THREAD

**Issue by thexpand** [doctrine/doctrine2#5642]
I updated doctrine via composer, and the versions of all doctrine dependencies have downgraded.

> Updating dependencies (including require-dev)
  - Installing ocramius/proxy-manager (1.0.2)
  - Removing symfony/console (v3.0.1)
  - Installing symfony/console (v2.8.2)
  - Removing doctrine/dbal (v2.5.4)
  - Installing doctrine/dbal (v2.4.5)
  - Installing doctrine/migrations (v1.3.0)
  - Removing doctrine/orm (v2.5.4)
  - Installing doctrine/orm (v2.4.8)
  - Removing doctrine/doctrine-module (0.10.0)
  - Installing doctrine/doctrine-module (1.0.0)
  - Removing doctrine/doctrine-orm-module (0.9.2)
  - Installing doctrine/doctrine-orm-module (0.5.6)

As far as I can see, for the DBAL you have marked v2.4.5 as [Latest release](https://github.com/doctrine/dbal/releases)

Additionaly, when I try to run `orm:schema-tool:update` from the CLI, I get an error:

>   [Symfony\Component\Console\Exception\CommandNotFoundException]
There are no commands defined in the "orm:schema-tool" namespace.

I checked and I have the `DoctrineModule` and `DoctrineORMModule` enabled, so it's not that.

**Comment by Ocramius** [comment]
This looks like an issue with `DoctrineModule` and `DoctrineORMModule`. I would try reporting the issue [there first](), as the ORM itself doesn't have the dependencies you listed above (except for DBAL).
