### ISSUE TITLE
MySQL - schema can be created with reserved keyword but will produce an error when using it

### ISSUE THREAD

**Issue by lbayerl** [doctrine/doctrine2#5647]
Having a column definition like

    /**
     * @ORM\Column(type="integer")
     */
    private $interval;

using _schema:update_ will produce an SQL statement using **'interval'** - including apostrophes.
This will successfully create the schema.

But when using this column after schema creation with DQL (e.g. persist and flush a new object) it will produce an SQL statement using **interval** without apostrophes.
This will throw a SQL error as _interval_ is a reserved keyword with MySQL.

This looks inconsistent to me.

**Comment by Ocramius** [comment]
Please see http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/limitations-and-known-issues.html#identifier-quoting-and-legacy-databases

Closing as `Can't fix`

**Comment by lbayerl** [comment]
Sorry, should have seen this :-(

**Comment by Ocramius** [comment]
@lbayerl 
![arnold](https://cloud.githubusercontent.com/assets/154256/12821091/36780c9e-cb62-11e5-8584-ffb64438a7f2.jpg)
