### ISSUE TITLE
No result was found for query although at least one row was expected.

### ISSUE THREAD

**Issue by bocharsky-bw** [doctrine/doctrine2#5649]
Does it normal behaviour if I get `NoResultException` exception though I call `getOneOrNullResult()` method?

```php
$qb->getQuery()->getOneOrNullResult(Query::HYDRATE_SINGLE_SCALAR);
```

I expected to get `null` if result not found due to `getOneOrNullResult()` method name, but got a `NoResultException` exception instead.

**Comment by Ocramius** [comment]
@bocharsky-bw this is the expected result if you have an empty resultset (no rows). Having a resultset like `[[null]]` wouldn't throw this exception.

Closing as invalid.
