### ISSUE TITLE
Doctrine 1 JIRA not migrated

### ISSUE THREAD

**Issue by mh-ovos** [doctrine/doctrine2#5661]
Since it seems nobody from the maintainers are taking a look at doctrine1 issues, I am posting it here.
Please can you make an exception and take a look at this issue:
https://github.com/doctrine/doctrine1/issues/71 - Doctrine 1 JIRA not migrated and it's also removed from doctrine-project.org/jira

**Comment by Ocramius** [comment]
Not a doctrine2 issue. Doctrine1 is indeed un-maintained, so anything revolving around it is outside our scope/area of interest.

Please avoid cross-posting - if @beberlei didn't respond then it means that he simply didn't have the time to do so.

**Comment by beberlei** [comment]
@mh-ovos Doctrine 1 is not maintained for 5 years now, i am sorry for the inconvenience of not migrating it, but we are not putting any effort into this version anymore.

**Comment by mh-ovos** [comment]
@beberlei Of course I understand. Since it's officially unmaintained for years you have full right to take everything off the Internet concerning doctrine1, and I am grateful for all good things you have done to keep it alive, incl. migrating doctrine1 repo to github. I only hoped that JIRA for doctrine1 is not gone for good (deleted), only inaccessible, so that it could be restored for short time, so that me or some other people could download the contents of it for maintenance purposes.
My apologies for adding this as an issue here, I just wanted to get an answer from you if what I am asking for would be even possible.
