### ISSUE TITLE
EntityGenerator - table annotation is not for superClass

### ISSUE THREAD

**Issue by poolerMF** [doctrine/doctrine2#5688]
entity for example:

```
/**
* Book
*
* @ORM\MappedSuperclass
*/
class Book {
    ....
}
```

EntityGenerator will make:

```
/**
* Book
*
* @ORM\Table(name="book")
* @ORM\MappedSuperclass 
*/
class Book
{
    ...
}
```

there should not be **@ORM\Table(name="book")**

**Comment by Majkl578** [comment]
EntityGenerator is going to be removed in Doctrine 3.0, sorry for no response and thanks for reporting.
