### ISSUE TITLE
Syntax error of ArrayCache.php

### ISSUE THREAD

**Issue by mamkkl** [doctrine/doctrine2#5701]
Since I updated to 2.4.8, my program throws a syntax error:

```
Parse error: syntax error, unexpected '[' in D:\websites\qtsa.devprj.com\wcms\vendor\doctrine\cache\lib\Doctrine\Common\Cache\ArrayCache.php on line 38
```

I found line 38 is defining an array variable private $data = []. Since my PHP is 5.3.24 and the [] format only supports in php 5.4 and above, so it doesn't work. However, the packagist of composer shows doctrine/orm 2.4.8 only requires 5.3.2 and above.

**Comment by Ocramius** [comment]
What version of doctrine/cache did you upgrade to?

**Comment by mamkkl** [comment]
According to Version.php, it is 1.7-dev, however, I didn't require doctrine/cache separately, here is my composer.json

"require": {
        "doctrine/orm": "2.4.8",
        "swiftmailer/swiftmailer": "5.4.1",
        "phpseclib/phpseclib": "2.0.1",
        "maennchen/zipstream-php": "0.3.1",
        "phpoffice/phpexcel": "1.8.1",
        "symfony/event-dispatcher": "2.8.3",
        "oyejorge/less.php": "~1.5",
        "twig/twig": "~1.0",
        "paypal/buttonmanager-sdk-php": "*"
    }

**Comment by Ocramius** [comment]
@mamkkl please check your `composer.lock` for the `doctrine/cache` version in use

**Comment by mamkkl** [comment]
@Ocramius it's a dev-master

**Comment by Ocramius** [comment]
`doctrine/cache` `dev-master` explicitly [states that the required PHP version is at least 5.5](https://github.com/doctrine/cache/blob/e0ef9e9833ca024d251e77e8d82a00ca92b0aa71/composer.json#L16)

**Comment by mamkkl** [comment]
@Ocramius I know that, however, isn't that composer will solve the dependency of "doctrine/orm" for me? since i just require "doctrine/orm": "2.4.8", isn't that will load the right dependency for juset 2.4.8?

**Comment by Ocramius** [comment]
@mamkkl if you run `composer update` on a machine that supports PHP 5.5, and then deploy in a PHP 5.3 environment, then you will obviously have a crash.

**Comment by Ocramius** [comment]
Also: please gist the section of your `composer.lock` that references `doctrine/cache`: `dev-master` is not a valid source or dist reference

**Comment by mamkkl** [comment]
i see update on php 5.5 and run 5.3 is my problem. Thank you
