### ISSUE TITLE
ArrayHydrator metadataCache undefined index

### ISSUE THREAD

**Issue by Jurigag** [doctrine/doctrine2#5710]
Hello. I have a problem that in metadataCache my class dont exist, but if i get class metadata directly from entity manager then it exists. Im using windows xp and php 5.3(yea i know.... its ancient). Doctrine is working on symfony 2.6, it occurs in dev enviroment so there is no in-memory cache like apc etc.

```
in vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ArrayHydrator.php at line 133   -
                }
                $relationAlias = $this->_rsm->relationMap[$dqlAlias];
                $parentClass   = $this->_metadataCache[$this->_rsm->aliasMap[$parent]]; // this is this line
                $relation      = $parentClass->associationMappings[$relationAlias];
```

**Comment by Ocramius** [comment]
Was this supposed to be closed? What is the resolution?

**Comment by Jurigag** [comment]
Well it was my problem, mistake in code when defineing ResultSetMappingBuilder.
