### ISSUE TITLE
Allow setting priority on listeners/subscribers

### ISSUE THREAD

**Issue by Wilt** [doctrine/doctrine2#5712]
I am not sure since it is hard to find any documentation on this. But it seems like both the Listeners and the Subscribers don't allow to set a priority. This would be a very useful addition.

If it is somehow possible to do this it would be good to add an example to the documentation.

**Comment by Ocramius** [comment]
It is not supported by our event system. If you need to support this, wrap your event handlers in a "priority-aware" event handler.

If you need this sort of functionality, consider providing a more extensive feature request in https://github.com/doctrine/common/issues

**Comment by Wilt** [comment]
OK thanks!
