### ISSUE TITLE
How hard is to add support for Sybase?

### ISSUE THREAD

**Issue by reypm** [doctrine/doctrine2#5720]
@Ocramius Hi there, in the company I am working on we use Sybase and as far as I know Doctrine2 doesn't support it and also will not work on this so how hard is to add support for this DB? Where I can find some docs about? Any has tried something like this on the past?

**Comment by kimhemsoe** [comment]
If i remember correct sqlserver is based based on sybase so i could maybe be an idea to start to look there first.

Then you should create a driver and etc for doctrine dbal and make the tests pass.

A word of caution, the chances of your work to be merged before dbal 3.0 is slim to none and the interfaces will change for dbal 3.0. So if you do proceed with this you will need to port and also maintain it for 3.0 as we do not have the knowledge to maintain it.

If you are ok with these terms you are very much welcome to create a WIP PR for dbal for 2.x where we will answer any question you may have to the best of our knowledge.

**Comment by Ocramius** [comment]
While the idea is good, it cannot live in core: the user-base is too narrow to actually maintain it actively and consider it a benefit for the community.

If you need support for sybase, please consider writing an external adapter by re-using the sqlanywhere or sqlserver adapters (depending on which one fits the use-case best).

**Comment by Ocramius** [comment]
Closing as `invalid`, as this is a `doctrine/dbal` issue instead.

**Comment by reypm** [comment]
@Ocramius can you reopen this bug and move to `doctrine/dbal` instead? I would like to continue this discussion with @kimhemsoe in there. Also you're talking about sqlanywhere and sqlserver adapters, where I can find those? @kimhemsoe where I can find the SQL driver? Could you point me on the right place?

**Comment by reypm** [comment]
@kimhemsoe @Ocramius nvm about the sqlanywhere and sqlserver I just found them on `doctrine/dbal`

**Comment by Ocramius** [comment]
@reypm please re-open on `doctrine/dbal` yourself once you checked if the sqlanywhere adapter works for you ;-)

**Comment by Deltachaos** [comment]
I have implemented support for SAP Sybase ASE in doctrine/dbal#2347

I also would volunteer to maintain it in the doctrine project.
