### ISSUE TITLE
getReference caches proxy

### ISSUE THREAD

**Issue by fabioginzel** [doctrine/doctrine2#5738]
Example:

```php
  $usuario = $this->em->getReference('Application\Entity\Usuario', $facebookId);
  
 $usuario = $this->usuarioRepository->find($notExistsId);
  if ($usuario)
     echo "found";
```

Always return "found" even if the entity does not exist, because it returns the cached proxy

**Comment by Ocramius** [comment]
That's expected behavior: what kind of behavior were you expecting, and why?

**Comment by fabioginzel** [comment]
I have expected that since $notExistsId doesnt exist it would return null

**Comment by Ocramius** [comment]
That means that you could potentially have two instances of the same `Application\Entity\Usuario` inside your `UnitOfWork`, which breaks one of the base invariants of the ORM

**Comment by Ocramius** [comment]
Note that `getReference` should only ever be used if you are 100% sure that the record will exist, but you do not want to load it immediately
