### ISSUE TITLE
namespace and class naming

### ISSUE THREAD

**Issue by Hikingyo** [doctrine/doctrine2#5741]
When i'm using cli to generate entities from database into yaml with a namespace, i don't have the expected. Exemple with namespace myns and a table named User, it produce mynsUser.dcm.yml file with a mynsUser class instead of myns.User.dcm.yml and myns\User. The generated entity is mynsUser without namespace and fail to generate proxy class.

**Comment by roji430** [comment]
the same issue with me anybody have solution please

**Comment by Ocramius** [comment]
The YAML driver is deprecated, therefore closing as "won't fix" here.
