### ISSUE TITLE
Remove entities in one query?

### ISSUE THREAD

**Issue by MacDada** [doctrine/doctrine2#5743]
In my entity I do `$this->someArrayCollection->clear()`.

It makes a lot separate delete queries, while it could:
- a.) remove all the associated records "blindly": `delete from SomeArrayCollection where TheRoot.id = ?`
- b.) remove all "currently known" associated records: `delete from SomeArrayCollection where SomeArrayCollection.id IN (?)`

I've seen [the blog post explaining, why inserts go in separate queries](http://www.doctrine-project.org/2009/08/07/doctrine2-batch-processing.html#update), but I would argue, that multi-delete could be implemented:

> this syntax is only supported on mysql and newer postgresql versions

Which is probably most of the use cases. For databases that do not support this feature, separate queries could go as they do now.

>  there is no easy way to get hold of all the generated identifiers in such a multi-insert when using AUTO_INCREMENT or SERIAL and an ORM needs the identifiers for identity management of the objects

I agree, it's bad for inserts. But no problem for deletes (?)

> insert performance is rarely the bottleneck of an ORM

Again, I agree. But, in my case, I need to delete XX/XXX records in one request. I could do this "manually" in the repository, but I believe it is the root entity's concern to remove associated objects. And an entity ofc should not talk to a repository.

> These are the reasons why it is not worth the effort to implement an abstraction that performs multi-inserts on mysql and postgresql in an ORM.

I agree for inserts. But it could be worth it to get nicer deletes. Doctrine allows me to concentrate on my entities and do things in a clean OOP-manner. I think this is one of those things, that would make Doctrine even better at doing what dev expect of it.

**Comment by kiler129** [comment]
I know it's a very old question, however I just found it via Google. 

The reason Doctrine doesn't implement it is you cannot implement many mechanisms when database does batch operation. Think about for example logging of deletes on events - doctrine needs to have the data and thus you cannot just blindly remove using single query.

**Comment by Ocramius** [comment]
Closing as `can't fix` - @kiler129 described this quite well. 

These operations can be performed via DQL or SQL when safe to do so (you will need to call `EntityManager#clear()` after deleting objects that may be in your `UnitOfWork`).
