### ISSUE TITLE
AnnotationDriver handles field mappings differently

### ISSUE THREAD

**Issue by dylanschoenmakers** [doctrine/doctrine2#5744]
A problem with a mapped superclass led me to this piece of code that conditionally maps fields in the `loadMetadataForClass` method in the AnnotationDriver. See commit 09a48a896eb3adfb1569beafab8566b69167b01e

``` php
    public function loadMetadataForClass($className, ClassMetadata $metadata)
    {
…
        // Evaluate annotations on properties/fields
        /* @var $property \ReflectionProperty */
        foreach ($class->getProperties() as $property) {
            if ($metadata->isMappedSuperclass && ! $property->isPrivate()
                ||
                $metadata->isInheritedField($property->name)
                ||
                $metadata->isInheritedAssociation($property->name)
                ||
                $metadata->isInheritedEmbeddedClass($property->name)) {
                continue;
            }
```

Other drivers like yaml or xml don't have these conditions, or not that I can see. Does anyone have more information about this or has encountered the same problems with overriding field mappings with annotations?

**Comment by ostrolucky** [comment]
See referenced issue DDC-34 = https://github.com/doctrine/doctrine2/issues/4198

**Comment by mpdude** [comment]
👀 needed regarding this in #10455
