### ISSUE TITLE
Order by NULL on grouped selects

### ISSUE THREAD

**Issue by whyte624** [doctrine/doctrine2#5757]
It would be good to be able to add `ORDER BY NULL` expression on queries that have `GROUP BY` part.
As it mentioned in [Mysql docs](http://dev.mysql.com/doc/refman/5.7/en/order-by-optimization.html):

> If a query includes GROUP BY but you want to avoid the overhead of sorting the result, you can suppress sorting by specifying ORDER BY NULL.

**Comment by PezCoder** [comment]
Can anyone help in how this can be achieved in doctrine ? 
I've looked into custom dql functions but that are not helpful as they can be used inside other functions like select, where etc.

We somehow need a way to override the addOrderBy function as it doesn't except 'NULL' OR NULL as parameter. Tried both.

**Comment by Ocramius** [comment]
This is a micro-optimisation that only makes sense in MySQL. We only provide support for cross-platform available features.

Closing as `won't fix`.
