### ISSUE TITLE
Unnecessary decimal updates

### ISSUE THREAD

**Issue by Bordovsky** [doctrine/doctrine2#5764]
Hi. I would like to make pull request, but when I tried add my branch/code I got 403 response. I will add code here, since it is nothing huge. I hope you don't mind.

When working around decimals in php, they change type. Since doctrine see them as strings and we works with them as numbers. It leads into unnecessary change set values in persisting which doesn't do any real change.

Workaround in entities seems difficult so I added few lines of code into UnitOfWork and it works, and pass all tests. I suppose others wouldn't mind if change set contained only real changes.

Here is code, it belongs on line 665 in UnitOfWork.php:

                if (array_key_exists($propName,$class->fieldMappings)) {
                    if ($class->fieldMappings[$propName]['type'] === 'decimal') {
                        if ($orgValue == $actualValue) {
                            continue;
                        }
                    }
                }

**Comment by Ocramius** [comment]
The field is supposed to be a string, unless you actually can afford losing precision.

Comparing types always happens with strict comparison: if you want to avoid an update, then cast the value back to a `string` or use a custom type (if you can afford playing with dangerous precision).
