### ISSUE TITLE
Manage Relations on different entity managers

### ISSUE THREAD

**Issue by marcoalbarelli** [doctrine/doctrine2#5769]
I'm trying to map entities on different entity managers and perform, mapping also `ManyToOne` and `ManyToMany` relations between them
Given this pseudo mapping
```
/* @Entity */
class Author {
   /* @ORM\OneToMany(targetEntity="BlogBundle\Entity\Post",mappedBy="author")
   protected $posts
```
```
/* @Entity */
class Post {
   /* @ORM\ManyToOne(targetEntity="AuthorsBundle\Entity\Author")
   protected $author
```

and this config:
```
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   '%database_driver%'
                host:     '%database_host%'
                port:     '%database_port%'
                dbname:   '%database_name%'
                user:     '%database_user%'
                password: '%database_password%'
                charset:  UTF8
            authors:
                driver:   '%database_driver2%'
                host:     '%database_host2%'
                port:     '%database_port2%'
                dbname:   '%database_name2%'
                user:     '%database_user2%'
                password: '%database_password2%'
                charset:  UTF8

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    BlogBundle:  ~
            authors:
                connection: authors
                mappings:
                    AuthorsBundle: ~
                    custom_mapping: ***
                        type: annotation
                        prefix: BlogBundle\Entity
                        dir: "%kernel.root_dir%/../src/BlogBundle/Entity"
                        is_bundle: false
```

What I need is Authors to reside on $em A and Posts to reside on $em B (different servers, not in a cluster, possibly different vendors)

Up to now I managed to map two different connections as per Symfony's tutorial:
http://symfony.com/doc/current/cookbook/doctrine/multiple_entity_managers.html
Too bad that example doesn't cover my case since it also covers retrieving a simple entity from an entity manager. (no relations)
In fact when creating the tables for the `authors` $em the `Post` table gets created as well, while I want that to reside only in the `default` $em

*** removing this conf node triggers a 
```  
  [Doctrine\Common\Persistence\Mapping\MappingException]                                                    
  The class 'BlogBundle\Entity\Post' was not found in the chain configured namespaces AuthorsBundle\Entity 
``` 
exception when trying to create the schema for the `authors` $em

The `databasename.tablename` hack doesn't work for my case since databases may not be on the same server

I stumbled in this SO answer which seems to suggest that I'm trying to achieve something that's not possible, but there's some grey area I'd like to sort out before moving to a different solution, also that answer is almost 3yo so some magic might have happened in the meantime :)
http://stackoverflow.com/questions/11463517/using-relationships-with-multiple-entity-managers

**Comment by Ocramius** [comment]
Closing, as this is not an issue.

As I commented on stackoverflow, there is no new approach to this: keep references between mappers by identifier, not object instance.
