### ISSUE TITLE
Add expressions in annotations-reference to the Index 

### ISSUE THREAD

**Issue by FlashBlack** [doctrine/doctrine2#5774]
What you think about it?

```sql
@ORM\Index(name="index_name", columns={"DATE(date_column)"})
```
It should be useful to add indexes with the expressions.

**Comment by Ocramius** [comment]
@FlashBlack expressions in indexes are only supported by very few platforms. You should instead just code the index definitions in your DB migrations.

**Comment by FlashBlack** [comment]
Yep, this is a better way.

Thank you!
