### ISSUE TITLE
[documentation] Missing Embedded and Embeddable anotations in annotations reference index

### ISSUE THREAD

**Issue by Maks3w** [doctrine/doctrine2#5786]
`@Embedded` and `@Embeddable` annotations are missing from the annotations reference index.

http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/tutorials/embeddables.html
http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/annotations-reference.html

**Comment by Ocramius** [comment]
Handled via #5813
