### ISSUE TITLE
Generated table/class names quoted for keywords

### ISSUE THREAD

**Issue by dohpaz42** [doctrine/doctrine2#5795]
I originally, and erroneously, posted this issue to DBAL (https://github.com/doctrine/dbal/issues/2370). In a nutshell, when I use the name 'user' for a table, when I go to generate the entity schema and classes, the name of the files and class generated for user end up quoted. I understand that Doctrine means to quote the keyword in SQL queries to avoid ambiguity on the database, but it feels like this quoting leaked a little too far by naming my files (literally) '"user".yml' and '"user".php'.

**Comment by ostrolucky** [comment]
You are not supposed to put into CLI names in quotes. Furthermore, command for generating entities has been deprecated.
