### ISSUE TITLE
Generating Entities from Yml file 

### ISSUE THREAD

**Issue by roji430** [doctrine/doctrine2#5803]
i am new to doctrine... created yml file with name XYZ.Model.User.dcm.yml inside my condig directory
and i run orm:generate-enities command to generate Entities in XYZ\Model\ directory but i got XYZ\Model\XYZ\Model\User.php instead of XYZ\Model\User.php

**Comment by Ocramius** [comment]
Heya,

That's normal: doctrine generates entities in a PSR-0 compliant directory structure, and includes the full namespace in the path.

**Comment by Ocramius** [comment]
Actually, re-opening to clarify.

What does your yaml file look like exactly, and what the entity look like? What are their paths too?

**Comment by Majkl578** [comment]
EntityGenerator is going to be removed in Doctrine 3.0, thanks for reporting.
