### ISSUE TITLE
SQLite error when using query parameter in DATE_ADD parameters

### ISSUE THREAD

**Issue by XitasoChris** [doctrine/doctrine2#5825]
When using a query parameter in DATE_ADD parameters, the generated SQL does not work with SQLite.

Example: Create a DQL query that contains the following code: 

`DATE_ADD(CURRENT_DATE(), :numberOfMonths, 'MONTH')`

Generated SQL on SQLite platform:

`DATE(CURRENT_DATE,'+? MONTH')`

When this SQL query is then run on SQLite, the following error is thrown:

> SQLSTATE[HY000]: General error: 25 bind or column index out of range

**Comment by martijngastkemper** [comment]
When executing that query directly in a SQLite console there's no error. So the error is caused by prepared statements. I think the problem is that parameters surrounded by quotes are handled as a string. [This Stackoverflow question](https://stackoverflow.com/questions/12588043/sqlite-3-pdo-statements-failing-in-php) shows an example and the solution. The solution for that question won't apply for this query, because quotes are required by ``DATE()`` function in SQLite.

I searched for solutions for this problem, but I couldn't find it.

**Comment by lcobucci** [comment]
@XitasoChris could you please send us a failing test case that reproduces that behaviour? It would help us a lot to identify and fix the issue you're describing.

You can find examples on https://github.com/doctrine/doctrine2/tree/388afb46d0cb3ed0c51332e8df0de9e942c2690b/tests/Doctrine/Tests/ORM/Functional/Ticket

**Comment by XitasoChris** [comment]
Sorry for the delay. I got around to implementing a test case last weekend and it turns out that it does not fail. Maybe this issue has already been fixed either in doctrine or in SQLite. Accordingly, I'm closing this issue.

Test case below for future reference.

> <?php
> 
> declare(strict_types=1);
> 
> namespace Doctrine\Tests\ORM\Functional\Ticket;
> 
> use Doctrine\ORM\Annotation as ORM;
> use Doctrine\Tests\OrmFunctionalTestCase;
> 
> /**
>  * @group DDC-5825
>  */
> class DDC5825Test extends OrmFunctionalTestCase {
>     protected function setUp() : void
>     {
>         parent::setUp();
> 
>         if ($this->em->getConnection()->getDatabasePlatform()->getName()
> !== 'sqlite') {
>             $this->markTestSkipped('Test case only fails on SQLite.');
>         }
> 
>         $this->schemaTool->createSchema(
>             [
>             $this->em->getClassMetadata(DDC5825SimpleEntity::class),
>             ]
>         );
>     }
> 
>     protected function tearDown() : void
>     {
>         parent::tearDown();
> 
>         $this->schemaTool->dropSchema(
>             [
>             $this->em->getClassMetadata(DDC5825SimpleEntity::class),
>             ]
>         );
>     }
> 
>     public function testDateAdd() : void
>     {
>         $dql   = 'SELECT x
>             FROM ' . __NAMESPACE__ . '\DDC5825SimpleEntity x
>             WHERE x.value = DATE_ADD(CURRENT_DATE(), :numberOfMonths, \'MONTH\')';
>         $result = $this
>             ->em
>             ->createQuery($dql)
>             ->setParameter("numberOfMonths", 4)
>             ->getResult();
> 
>         self::assertEmpty($result);
>     }
> }
> 
> /**
>  * @ORM\Entity
>  * @ORM\Table(name="ddc-5825-simple-entity")
>  */
> class DDC5825SimpleEntity
> {
>     /**
>      * @ORM\Id
>      * @ORM\Column(type="integer", name="simple-entity-id")
>      * @ORM\GeneratedValue(strategy="AUTO")
>      */
>     public $id;
> 
>     /** @ORM\Column(type="datetime", name="simple-entity-value") */
>     public $value;
> 
>     /**
>      * @param \DateTime $value
>      */
>     public function __construct($value)
>     {
>         $this->value = $value;
>     }
> }
