### ISSUE TITLE
Slow query logging

### ISSUE THREAD

**Issue by Slavenin** [doctrine/doctrine2#5829]
Hi!
Doctrine supports slow query log?

**Comment by Ocramius** [comment]
Doctrine supports logging via the [`SQLLogger`](https://github.com/doctrine/dbal/blob/1c6f63dff60f1f8c073087833edae2da96d37287/lib/Doctrine/DBAL/Logging/SQLLogger.php#L32).

In-depth analysis of query performance is up to the db layer, though.
