### ISSUE TITLE
Add a way to keep parameters when temporarily disabling a filter

### ISSUE THREAD

**Issue by winzou** [doctrine/doctrine2#5844]
Hi,

When we enable a filter for the first time, we can set a parameter to it, that's great.

The issue is for the usecase of temporarily disable a filter. Let's say I have a filter A with parameter X. It is enabled and configured. Then I want to execute a specific query without this filter (by disabling it first, then enabling it back). As of today, if I do `disable(A)` then `enable(A)`, I will loose the value of my parameter X.

There should be a way to temporarily disable a filter and keep its parameters when enabling it back.

Especially that, when I manually save the value of my parameter X, I get a quoted version of it:

```
$filter->setParameter('id', 5);
$filter->getParameter('id'); // string '5' (3 caracters, including the quotes)
```

It makes it not so clean to temporarily disable filters.

Thanks!

**Comment by nnmer** [comment]
Was facing similar problem, but solution appears pretty simple.
we have a service which configure our filter. so right after you toggle your filter - call service manually again to setup needed variables etc.

**Comment by Ocramius** [comment]
Closing: the solution provided by @nnmer is indeed correct.
