### ISSUE TITLE
Default query cache using wrong object

### ISSUE THREAD

**Issue by lcobucci** [doctrine/doctrine2#5854]
On the fix of PHP 7 [bug](https://bugs.php.net/bug.php?id=72174), `ReflectionProperty#getValue()` is now raising a `Notice` when accessing an undefined property. That change revealed a false positive on ORM tests!

As you can see [here](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Cache/DefaultQueryCache.php#L266) the `DefaultQueryCache` is always trying to fetch data from `$entity` even when the association is not with that object (the test is failing because `DefaultQueryCache` is trying to get the `country` from the `City` instead of the `State`).

**How to reproduce:** execute the test suite while running PHP 7.0.7

**Comment by Ocramius** [comment]
@lcobucci can you take a look at #5856? It fixes the issue, but also disables some of the SLC caching happening during hydration of multi-level DQL fetch-joins.

**Comment by lcobucci** [comment]
@Ocramius I totally forgot to do a follow up on this issue here.

I'd say it's fixed, let's close it?
