### ISSUE TITLE
Remove ability to `clear($entityName)`

### ISSUE THREAD

**Issue by Ocramius** [doctrine/doctrine2#5855]
As it currently stands, it is possible to generate potentially broken entity graphs when clearing single entities.

Here's an example of possibly broken code (that we can't fix):

``` php
$a = new A;
$b = new B;
$c = new C;

$a->b = $b;
$b->c = $c;

$em->persist($a);
$em->persist($b);
$em->persist($c);

$em->clear(C::class);
```

This particular example creates an `a->b->c` chain, and clearing `c` causes the `b->c` association to try and save an association of a non-managed entity.

From what I can see from questions/bugs being raised, as well as common usage patterns, `clear($entityName)` is typically used in batch processing operations, while it causes havoc when used within an OLTP application.

We have two paths to fix this:
- support the feature, but refuse to `clear($entityName)` when the graph is broken (potentially very expensive, as we'd need to traverse all managed associations)
- remove the feature, ignoring the `$entityName` parameter completely

As for the performance issues arising from this, I don't think the concerns are relevant at the moment, since long running processes can rely on the second level cache to avoid bombing the database with data that is assumed to be stable (this assumption is made when not clearing specific entities).

**Comment by Ocramius** [comment]
Note: this is only one of the many possibly buggy behaviors of `clear($entityName)`. Other generally broken scenarios are:

 * `clear(get_class($someProxy))` (implementation fault)
 * `clear($rootOfAnInheritance)` (not contemplated at all, at the moment)

**Comment by Ocramius** [comment]
@popy-dev I agree and I counter with a request for a patch, if you have time/will

**Comment by popy-dev** [comment]
> I counter with a request for a patch
That's super effective. I'll give it a try in the next days.
Although the conclusion I wanted to reach was the opposite :/

**Comment by Ocramius** [comment]
@popy-dev we're not going back on this - only `clear()` (no arguments) will remain as a way to detach entities. Dealing with partial graphs is something we can't do without an amount of effort that is out of our range/capabilities, and well below the 10% use-case.

**Comment by popy-dev** [comment]
> Dealing with partial graphs is something we can't do without an amount of effort

I understand this. My take on the topic is that, unless persist, merge, and remove are removed aswell, partial graphs will still exist. I also understand that you won't going back on a decision made more than a year earlier just because a flower-stranger necro an issue.

Still, I'm happy and honored to have an opportunity to contribute to this wonderfull ORM, even if it means for me that I'll never upgrade to 3.0. I'll write the PR asap.

**Comment by Ocramius** [comment]
`merge` is gone too, as far as I remember

**Comment by popy-dev** [comment]
Indeed :

https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/EntityManager.php#L331

And ```detach``` too. Looks like it's too late for e to contribute :)

**Comment by hacfi** [comment]
I'm not too happy about this change as it limits the possibilities. I have a project where 40,000 entities (`events`) get imported in a console command from a couple of hundred sources. They have related entities that get preloaded (`locations`, `cities` etc.)..about 10,000 items. With the current `clear($entityName)` method the job needs 6 minutes. If I don't clear after each data source it takes 25 minutes. Loading 10,000 entities again and again also isn't great.

I rather have the possiblity of a broken entity graph than this limitation!

**Comment by beberlei** [comment]
@hacfi we will provide alternative APIs, we haven't gotten around it yet. This change is targeting master, which at the moment is highly unstable.

**Comment by hacfi** [comment]
Perfect - that sounds great! I thought this was just getting dropped without a replacing functionality.
