### ISSUE TITLE
OnToMany reflexive relationship

### ISSUE THREAD

**Issue by ajax13** [doctrine/doctrine2#5869]
Hello,

How can I make a **OneToMany** for a reflexive association?

![reflexive relationship](https://cloud.githubusercontent.com/assets/2513194/15968209/465da42a-2f2b-11e6-9d0d-aea777e27753.gif)

> Class A{
/**
   @ORM\OneToMany(targetEntity="A", mappedBy="A")
**/
private $arrayOfA
}

Thanks!

**Comment by JCMais** [comment]
```php
class Node
{
    /** @ORM\Id 
     * @Column(type="integer")
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    //...

    /**
     * @ORM\ManyToOne(targetEntity="Node", inversedBy="children")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity="Node", mappedBy="parent")
     */
    private $children;
}
```

**Comment by ajax13** [comment]
Thank you so much for your swift reply!
