### ISSUE TITLE
OnDelete={"REMOVE"}, Bug?

### ISSUE THREAD

**Issue by lukasz18dg** [doctrine/doctrine2#5877]
Good day.
This is my first speech in this "forum", so I apologize in advance if I break any rules of procedure. I was looking for, I have not found.
I have about this problem:
This code works on a SQLite database:

```php
        /**
         * @ORM\ManyToMany(targetEntity="Druzyna", inversedBy="wynikFK")
         * @ORM\JoinTable(name="tablica_Druzyn",
         *     joinColumns={@ORM\JoinColumn(name="wynik_id", referencedColumnName="id", onDelete="REMOVE")},
         *     inverseJoinColumns={@ORM\JoinColumn(name="druzyna_id", referencedColumnName="id", onDelete="REMOVE")}
         *     )
         */
        private $tablicaDruzyn;
```

The same for MySQL database does not work.
Symfony console, it only returns me this error:
"Invalid foreign key action: REMOVE"
Did I do something?
As you can see, the code earlier, I have a table Many to many on both sides can be accessed. How removal work, it removes the one hand and on the other hand, unfortunately unexplained reasons, is in Table 3, specially created for the lot of many. So I used onDelete = "REMOVE" to me was the part that was in relation to what was removed. But I do not want to act this for MYSQL.

**Comment by Ocramius** [comment]
it's `onDelete="CASCADE"`
