### ISSUE TITLE
DQL:  large data set and deep nested object

### ISSUE THREAD

**Issue by ajax13** [doctrine/doctrine2#5879]
Hello every one,

I have a DQL query for deeply nested object with a large data set, the query takes a lot to be executed. 
So I wonder of there is a way to define the value of max deep level (of nested attributes) to be searched/returned?

Thx!

**Comment by lcobucci** [comment]
Do you really need to load all those objects? Can't you just use sql?

**Comment by ajax13** [comment]
I want ot de

**Comment by lcobucci** [comment]
But you can deal with objects by using the native query api and just loading the objects you need...

What are you building that you need to load that large dataset?

**Comment by ajax13** [comment]
If I do like you said, it will cost me the I/O Database Server time(for every object I need), besides every object I load contains many nested other attributes(objects).

And yes I have a large dataset, but I Think the problem is with the nested Objects :/

**Comment by lcobucci** [comment]
Sorry I don't follow... You mapped a lot of nested objects in doctrine, asks for them be loaded eagerly and you want doctrine to limit the loading of the objects. 

It sounds like a modelling issue or maybe that you want to use objects to do a database work.

**Comment by lcobucci** [comment]
Could you provide a gist with your mapping and the dql you're using so we could help you better?

**Comment by ajax13** [comment]
Thank you  very much , actually I find the too nested entity. I am going to eleminate it from my entity I don't  racking my brains anymore! 
Unfortunate, there is not a function to specifiy a maximum level for DQL :S

**Comment by Ocramius** [comment]
Closing here: this is a question for the mailing list or stackoverflow, not an issue to be reported, sorry.
