### ISSUE TITLE
DBAL Types: Problem with PHP 7.x with strict types & nullable relations

### ISSUE THREAD

**Issue by mikemirten** [doctrine/doctrine2#5881]
The case:
PHP 7.0.7 with declared strict types.
Custom GUID type which serves as an ID of entities.

If **nullable** related property of an entity referenced to a target entity with custom primary ID type contains no referenced object, it causes an exception due to ```convertToDatabaseValue()``` with strictly should return a string: _"Return value of ...\GuidType::convertToDatabaseValue() must be of the type string, null returned"_.

Possible solution: do not convert null-values or to add something like ```convertNullValues(): bool``` method into abstract Type class to be able choose behaviour.

Thank you.

**Comment by Ocramius** [comment]
Not part of this repository.

Closing as `invalid`, sorry.

**Comment by mikemirten** [comment]
I'm sorry about that. Reopened the issue in the doctrine/dbal repo.
Thank you.
