### ISSUE TITLE
special case for inheritance mapping

### ISSUE THREAD

**Issue by videni** [doctrine/doctrine2#5893]
There is a special case for inheritance mapping  I think, I  have  3 customer entities,  CustomerC extends CustomerB , CustomerB extend CustomerA, all of them are mapped to a single table, there is no need to use a discriminator , for I will only use CustomerC to get data from database.  I add orm definition for these classes, all of them are mapped-supper-class, and their table is the same . in this case,  the [inheritance mapping](http://doctrine-orm.readthedocs.io/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html) is just used to separate properties in different class, it seems reasonable to do so, the limitation below is not needed.

>A mapped superclass cannot be an entity, it is not query-able and persistent relationships defined by a mapped superclass must be unidirectional (with an owning side only). 

right now , is it possible to do this?  I tried but failed,  it might be something I did wrong.

**Comment by Ocramius** [comment]
A mapped superclass is a non-entity. It is not a "real thing", so it cannot really extend from a concrete  entity by definition.

The simplest solution to avoid problems like this one is to simply make your intermediate ancestor `abstract`, so it cannot be instantiated, yet you will be able to extend from it and have actual entities as subclasses.

You will still have to map it as entity and have entries for it in the inheritance map.
