### ISSUE TITLE
getter name exception

### ISSUE THREAD

**Issue by RomainSanchez** [doctrine/doctrine2#5895]
Hi i encountered an exception with how doctrine automatically calls getters and setters.My entity has a collection of "species" and as the word is spelled species in the singular and plural doctrine is not happy with my method names.It is looking for specieses or specy.What is the best workaround

**Comment by guilhermeblanco** [comment]
Create a test on http://github.com/doctrine/inflector project and address the issue there... =)

**Comment by Ocramius** [comment]
Note: doctrine does not call getters or setters ;-)

Is this about the entity generator?

**Comment by RomainSanchez** [comment]
Right, my bad.I'll look into Symfony's PropertyAccessor?

**Comment by Ocramius** [comment]
@RomainSanchez if this is a runtime concern, then yes, you need to check there :-)

Closing here as `invalid`
