### ISSUE TITLE
Issue with Metadata

### ISSUE THREAD

**Issue by ChrisWesterfield** [doctrine/doctrine2#5900]
Hi,

I upgraded to the latest version of doctrine currently.
I'm using symfony 3 in combination with the snc redis cache system.
Everytime I enable the metadata cache the entities are mixed up with each other.
I don't really know where to start searching.
I also tried to enable the doctrine cache system with the same results.

The result is always an exception like this:

An exception occurred while executing 'SELECT t0.key_handle AS key_handle_1, t0.public_key AS public_key_2, t0.certificate AS certificate_3, t0.counter AS counter_4, t0.id AS id_5, t0.name AS name_6, t0.created AS created_7, t0.updated AS updated_8, t0.active AS active_9, t0.user_id AS user_id_10, t0.log_created_by AS log_created_by_11, t0.log_updated_by AS log_updated_by_12 FROM acl_role_user_map t0 WHERE t0.user_id = ?' with params [1]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.key_handle' in 'field list'

But the entity does not contain these fields.
Please help me.
This is bugging me already for 4 days in a row.
If somebody has an solution, I'll appreceate it :)

thanks for the help

**Comment by Ocramius** [comment]
First of all, closing, as this isn't an issue, but a help request. We can keep discussing after it's closed tho.

1. an upgrade requires a full metadata cache wipe: make sure you did that
2. see what DQL or ORM interaction produces this sort of query
3. try reproducing that same query in isolation

**Comment by ChrisWesterfield** [comment]
Ok
after searching a couple hours more I could narrow it down and find the issue that lies behind my problems.
I'm currently using php 7.0.8 from the dotdeb repositories with installed igbinary.
it seems that if the igbinary is installed and enabled doctrine meta caches fall back in using igbinary store the data.
Igbinary currently isn't running stable under php7 and breaks meta data caching.
after I uninstalled it everything was operational again.
:)
thanks for you help
