### ISSUE TITLE
SQLITE Autoincrement

### ISSUE THREAD

**Issue by sebka** [doctrine/doctrine2#5901]
doctrine: 2.5.4
sqlite: 3

The [docs](http://docs.doctrine-project.org/en/latest/reference/basic-mapping.html#identifier-generation-strategies) are talking about, that this annotation should result in an SQLITE Autoincrement ID field:
```
    /**
     * @var int
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
```
The id is created, but the autoincrement flag is not checked in the sqlitedb..

if i insert an new entity on a fresh db it will have id 1
if i delte this entity and create a new entity afterwards, the new entity will also have the id 1

do i miss somethis or is this a bug in doctrine?

**Comment by Ocramius** [comment]
@sebka is this supposed to be closed? What is the resolution? Why?

**Comment by sebka** [comment]
i closed it, becouse i think it was the wrong place.
i opened the issue @ https://github.com/doctrine/dbal/issues/2426
