### ISSUE TITLE
PrePersist Event is fired with an Invalid entity

### ISSUE THREAD

**Issue by moroine** [doctrine/doctrine2#5916]
Hi,

I'm writing an issue as my PR from 22th December (https://github.com/doctrine/doctrine2/pull/5570).

The **PRE_PERSIST** event is fired when persisting a new entity. As merging a new entity come down to persisting it, when expect the same behavior on both operations.

The fact is when using merge instead of persist, the **uow** fire the **PRE_PERSIST** event with an empty entity instead of the entity as it will be persist.

I really think my PR is ready to merge with unit test who check two line changes. If anyone could take a look on it, it would be great !

Thank You.

**Comment by Ocramius** [comment]
There are loads of PRs that need attention. I realize that it is frustrating to not have feedback on them, but opening new issues only increases the noise. I added the milestone to it, and it will be merged before releasing.
