### ISSUE TITLE
Doctrine doesnt escape "match"

### ISSUE THREAD

**Issue by Levitas** [doctrine/doctrine2#5919]
hey

If i have an entity called "Match" in the table "match" doctrine wont escape it.
Im using Doctrine with symfony2

**Comment by Ocramius** [comment]
This is a known issue, as by default doctrine does not quote identifiers. See http://doctrine-orm.readthedocs.io/projects/doctrine-orm/en/latest/reference/limitations-and-known-issues.html#identifier-quoting-and-legacy-databases
