### ISSUE TITLE
Wrong behaviour of flush($entity) ?

### ISSUE THREAD

**Issue by danionut90** [doctrine/doctrine2#5921]
both $entityA and $entityB have changes

$em->computeChangeSet($entityA);

$em->flush($entityB); -> the changes from $entityB and also $entityA will be saved to db.

Is this normal ?

**Comment by Ocramius** [comment]
`flush($entity)` does not mean that `$entity` will be the only change to be committed. It is a performance optimization that forces the entity manager to only compute changes on the given `$entity`, but previous computed changes will still apply.
