### ISSUE TITLE
Many-to-one mapping to primary-key, foreign-key, not supported?

### ISSUE THREAD

**Issue by Jacco-V** [doctrine/doctrine2#5927]
I'm trying to create a mapping for a scenario that looks, in simplified form, like:

![zqwjf](https://cloud.githubusercontent.com/assets/19333579/16700139/9ec68a9e-4558-11e6-8359-7a08876f8e56.jpg)

Note: *the above ERD is simplified, in reality the circular reference consists of a chain of 5 tables.*

My mappings look like:

```xml
<entity name="User" table="users">
   <id name="userId" type="int" column="userId"/>
   <!-- other fields -->
   <many-to-one field="domain" target-entity="Domain" fetch="LAZY">
      <join-columns>
         <join-column name="domainId" referenced-column-name="domainId"/>
         <join-column name="groupId" referenced-column-name="groupId"/>
      </join-columns>
   </many-to-one>
   <many-to-one field="group" target-entity="Group" fetch="LAZY">
      <join-column name="groupId" referenced-column-name="groupId"/>
   </many-to-one>
</entity>

<entity name="Domain" table="domains">
   <id name="domainId" type="int" column="domainId"/>
   <!-- other fields -->
   <many-to-one field="group" target-entity="Group" fetch="LAZY">
      <join-column name="groupId" referenced-column-name="groupId"/>
   </many-to-one>
</entity>

<entity name="Group" table="groups">
   <id name="groupId" type="int" column="groupId"/>
   <!-- other fields -->
</entity>
```
When attempting to use the above, I get the error:

`UnitOfWork.php line 2649: Undefined index: groupId`

I understand where this error comes from: Doctrine expects to find the field `groupId` defined on entity `Domain`, but there is no such field, because it is mapped by the foreign entity `group` on `Domain`.

<br>
I tried changing the mapping for entity `User` to point to the `group` field (instead of `groupId`) on the `Domain` entity:

```xml
<entity name="User" table="users">
   <id name="userId" type="int" column="userId"/>
   <!-- other fields -->
   <many-to-one field="domain" target-entity="Domain" fetch="LAZY">
      <join-columns>
         <join-column name="domainId" referenced-column-name="domainId"/>
         <join-column name="group" referenced-column-name="groupId"/>
      </join-columns>
   </many-to-one>
   <many-to-one field="group" target-entity="Group" fetch="LAZY">
      <join-column name="groupId" referenced-column-name="groupId"/>
   </many-to-one>
</entity>
```

But that gives me the error:
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.group' in 'field list'`

which leads me to believe that this last option does not seem to be the intended solution.

<br>
So, given that [UnitOfWork:2624](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/UnitOfWork.php#L2624) says: '`// TODO: Is this even computed right in all cases of composite keys?`', I wondered if the many-to-one relation I'm trying to map is supported by Doctrine?

If so, how?

**Comment by Ocramius** [comment]
The problem is actually much simpler: 

 * your entity `Domain` has `domainId` as primary key
 * `User#domain` references `domainId` + `groupId`. This is not the primary key.

**Comment by Jacco-V** [comment]
In SQL, there is no requirement that says you can only join on primary keys. We are deliberately joining on a second (non-primary key) column to guarantee referential integrity across a chain of joins.

So, whatever you would like to label it, it is not an [Invalid] request.

**Comment by Ocramius** [comment]
This is not SQL, these are POPOs that reference each other. At low level, this happens via identifiers only, and will stay like that, as a constraint, within the ORM's semantics.

That still doesn't prevent you from manually defining a foreign key via a DB migration script.
