### ISSUE TITLE
Doctrine superclass inheritance - indexes are not inherited

### ISSUE THREAD

**Issue by nacholibre** [doctrine/doctrine2#5928]
```
/**
 * @MappedSuperclass
 * @Table(indexes={@Index(name="idx", columns={"name"})})
 */
class BaseSuperClass
{
    /** @Column(type="string") */
    protected $name;

    // ... more fields and methods
}

/** @Entity */
class EntitySubClass extends BaseSuperClass
{
    /** @Id @Column(type="integer") */
    private $id;

    // ... more fields and methods
}
```

Name index is not inherited from `BaseSuperClass`, it there any way to achieve this?

**Comment by Ocramius** [comment]
@Table is not valid on a mappedsuperclass.

**Comment by nacholibre** [comment]
Okay, but is there any way to achieve this?

**Comment by alexgurrola** [comment]
@nacholibre One could only hope.

**Comment by alexgurrola** [comment]
@nacholibre or @Ocramius, Did you find a way to inherit indexes with a mapped superclass?  I have tons of entities that would benefit from such a structure.

**Comment by Ocramius** [comment]
> Did you find a way to inherit indexes with a mapped superclass?

Listeners - simply attach a listener that, when the metadata loads, adds the indexes to all classes that are instance of a certain mapped superclass.

**Comment by ThomasLandauer** [comment]
I posted a full solution for the listener suggested by @Ocramius at https://stackoverflow.com/a/60029840/1668200
