### ISSUE TITLE
Allow override of fetch for associations

### ISSUE THREAD

**Issue by patrick-mcdougle** [doctrine/doctrine2#5934]
There's currently no way to change the fetch mode after the association has been added to the mapping. In the case when a 3rd party creates a mapping for a collection that is mapped extra lazy, there's no way to change it to be eagerly fetched instead in application level code.

I suggest adding this to the association-overrides options.

Thoughts?

**Comment by Ma27** [comment]
I think adding this to the following method and extending the annotation should do the job: https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php#L2140-L2182

**Comment by Ocramius** [comment]
Handled in #5938 :+1:
