### ISSUE TITLE
Embeddable object cannot be used as query parameter

### ISSUE THREAD

**Issue by mishal** [doctrine/doctrine2#5936]
We have an embeddable object which represents geographic coordinate. When using this object as query parameter with custom DBAL type Doctrine tries to load identifier for this object, which does not exist, because embeddables are simple DTO objects (as per doc).

Error with stack trace:

    Error: Call to a member function getValue() on null

    vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php:732
    vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2920
    vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:429
    vendor/doctrine/orm/lib/Doctrine/ORM/Query.php:371
    vendor/doctrine/orm/lib/Doctrine/ORM/Query.php:321
    vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:974
    vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:928

**Comment by Ocramius** [comment]
Can you turn this into a failing test case?

**Comment by mishal** [comment]
yes, I'm working on it.

**Comment by mishal** [comment]
I used embeddables found in the tests models, not sure if its acceptable.

**Comment by Ocramius** [comment]
@mishal can you open a PR with the fix? Seems legit, but may need to do some adjustments. Once the PR is open, we can review it :-)

**Comment by mishal** [comment]
PR created #5937

**Comment by Ocramius** [comment]
Thanks! Closing this issue as duplicate :-)
