### ISSUE TITLE
Can't use doctrine:generate:entities when embedded is used

### ISSUE THREAD

**Issue by SacreFrancis** [doctrine/doctrine2#5939]
I have an Entity: User, who is using an embedded propertry : Gender.

And I have an error when i use bin/console doctrine:generate:entities

> [Symfony\Component\Debug\Exception\ContextErrorException]
> Notice: Trying to get property of non-object
> Exception trace:
> () at var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php:3252
> Symfony\Component\Debug\ErrorHandler->handleError() at var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php:3252
> Doctrine\ORM\Mapping\ClassMetadataInfo->inlineEmbeddable() at var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:200
> Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata() at var/www/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:332
> Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata() at var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:78
> Doctrine\ORM\Mapping\ClassMetadataFactory->loadMetadata() at var/www/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:225
> Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor() at var/www/vendor/doctrine/doctrine-bundle/Mapping/DisconnectedMetadataFactory.php:193
> Doctrine\Bundle\DoctrineBundle\Mapping\DisconnectedMetadataFactory->getMetadataForClass() at var/www/vendor/doctrine/doctrine-bundle/Mapping/DisconnectedMetadataFactory.php:79
> Doctrine\Bundle\DoctrineBundle\Mapping\DisconnectedMetadataFactory->getClassMetadata() at var/www/vendor/doctrine/doctrine-bundle/Command/GenerateEntitiesDoctrineCommand.php:106
> Doctrine\Bundle\DoctrineBundle\Command\GenerateEntitiesDoctrineCommand->execute() at var/www/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:256
> Symfony\Component\Console\Command\Command->run() at var/www/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:831
> Symfony\Component\Console\Application->doRunCommand() at var/www/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:186
> Symfony\Component\Console\Application->doRun() at var/www/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
> Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at var/www/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:117
> Symfony\Component\Console\Application->run() at var/www/bin/console:29

**Comment by nnmer** [comment]
same issue
symfony 2.8.8

**Comment by nnmer** [comment]
working. Have to specify a **columnPrefix**

**Comment by Majkl578** [comment]
EntityGenerator is going to be removed in Doctrine 3.0, thanks for reporting and sorry for no response.
