### ISSUE TITLE
doctrine:generate:entities and anonymous class

### ISSUE THREAD

**Issue by kralmichal** [doctrine/doctrine2#5943]
Hi,

Suppose I have an Entity like this one

``` php
class MyEntity {

    protected $myObject;

    public function getMyObject() {
        if( $this->myObject ) {
            return $this->myObject;
        }

        return new class {
            public function getId() {
                return NULL;
            }
        };
    }
}
```

when running `bin/console doctrine:generate:entities`  you will get 
`[Symfony\Component\Debug\Exception\ContextErrorException]  Notice: Uninitialized string offset: 1`

**Comment by Ocramius** [comment]
Can you please run it in isolation, or provide a full trace? I don't think that we currently support anonymous classes within the entity generator.

**Comment by kralmichal** [comment]
``Exception trace:
 () at /home/michal/www/project/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/EntityGenerator.php:823
 Symfony\Component\Debug\ErrorHandler->handleError() at /home/michal/www/project/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/EntityGenerator.php:823
 Doctrine\ORM\Tools\EntityGenerator->parseTokensInEntityFile() at /home/michal/www/project/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/EntityGenerator.php:373
 Doctrine\ORM\Tools\EntityGenerator->writeEntityClass() at /home/michal/www/project/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/EntityGenerator.php:347
 Doctrine\ORM\Tools\EntityGenerator->generate() at /home/michal/www/project/vendor/doctrine/doctrine-bundle/Command/GenerateEntitiesDoctrineCommand.php:133
 Doctrine\Bundle\DoctrineBundle\Command\GenerateEntitiesDoctrineCommand->execute() at /home/michal/www/project/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /home/michal/www/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:860
 Symfony\Component\Console\Application->doRunCommand() at /home/michal/www/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:192
 Symfony\Component\Console\Application->doRun() at /home/michal/www/project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:92
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/michal/www/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:123
 Symfony\Component\Console\Application->run() at /home/michal/www/project/app/console:27
``

**Comment by Majkl578** [comment]
EntityGenerator is going to be removed in Doctrine 3.0, thanks for reporting.

**Comment by kralmichal** [comment]
Thanks for reply.
