### ISSUE TITLE
ArrayCollection vs PersistentCollection

### ISSUE THREAD

**Issue by Michal-sk** [doctrine/doctrine2#5946]
I was following along: http://doctrine-orm.readthedocs.io/projects/doctrine-orm/en/latest/reference/association-mapping.html#initializing-collections and initialize my references as `ArrayCollections`. For the getters i have a return typehint aswell for `ArrayCollection`. But it seems that the collections are of the type `PersistentCollection`. I have seen that the `PersistentCollection` does implement the `Collection` interface, so should i than use that?

`must be an instance of Doctrine\Common\Collections\ArrayCollection, instance of Doctrine\ORM\PersistentCollection returned`

**Comment by Michal-sk** [comment]
So yeah, basically answered my own question. Just use the `Collection` interface for typehinting. When instantiating the relations in the `construct` use the `ArrayCollection` which implements the `Collection`.

**Comment by Ocramius** [comment]
@Michal-sk consider patching the docs at https://github.com/doctrine/doctrine2/blob/master/docs/en/reference/association-mapping.rst, should you have suggestions :-)
