### ISSUE TITLE
OneToOne with a join table

### ISSUE THREAD

**Issue by Michal-sk** [doctrine/doctrine2#5949]
So i know it's not a real join table, and i am aware that this should be refactored. But for now this is what i got put on my lap and have to work with.

We have a tables: `element`, `option`, `chosen`. The `chosen` is actually just a join table between the `Element` and `Option`, on a OneToOne. Sure there is some additional data in that `chosen` table, but its actually irrelevant and never used.

When i now try to use a OneToOne with the join table:
```php
Class Element
{
    //...
    /**
     * @var Option
     * @ORM\OneToOne(targetEntity="Foo\Domain\Entity\Option\Option", fetch="LAZY")
     * @ORM\JoinTable(name="thun_chosen",
     *     joinColumns={@ORM\JoinColumn(name="f_wonelement_id", referencedColumnName="id")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="f_optie_id", referencedColumnName="id", unique=true)}
     *     )
     */
    private $chosenOption;
```
(as with the table structure, don't look at the fields).

But this returns me a nice SQL error `Column not found: 1054 Unknown column 't0.chosenOption_id' in 'field list' `.

Any suggestions would be appreciated. For now i'm thinking of adding an additional object `Chosen` and work with that.  But that's only if there are no other methods.

**Comment by Michal-sk** [comment]
Used the `Chosen` object way.

**Comment by marchenko-am** [comment]
Hi. Can you explain how you organized your "Chosen object way"?
Unfortunately, I dont understand how you resolved this.
I have simillar problem.

**Comment by Michal-sk** [comment]
@marchenko-am as stated in my latest paragraph. I have created a new object called Chosen and used that instead of the JoinTable annotation.
