### ISSUE TITLE
Association not escaping fieldname

### ISSUE THREAD

**Issue by Michal-sk** [doctrine/doctrine2#5952]
``` php
class Option
{
    /**
     * @var int
     * @ORM\Column(name="`group`", type="smallint")
     */
    private $group;

    /**
     * @var Collection
     * @ORM\ManyToMany(targetEntity="Acme\Domain\Entity\Option\Option", inversedBy="dependingOptions")
     * @ORM\JoinTable(
     *     name="acme_opties_relaties",
     *     joinColumns={@ORM\JoinColumn(name="id_a", referencedColumnName="id")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="id_b", referencedColumnName="id")}
     * )
     */
    private $requiredOptions;

    /**
     * @var Collection
     * @ORM\ManyToMany(targetEntity="Acme\Domain\Entity\Option\Option", mappedBy="requiredOptions")
     */
    private $dependingOptions;

    /**
     * @param Relation $r
     * @return Criteria
     */
    private function getRelationCriteria(Relation $relation): Criteria
    {
        return Criteria::create()->where(
            Criteria::expr()->eq('soort', $relation->getValue())
        );
    }

    public function getRequiredOptions()
    {
        return $this->requiredOptions->matching($this->getRelationCriteria(Relation::get(Relation::DEPEND)));
    }
}
```

Now just loading a `Option`, everything is fine. But when calling `Option::getRequiredOptions()` the `group` field name is not escaped.

**Comment by Michal-sk** [comment]
Tough when changing the annotation to:
```php
    /**
     * @var Group
     * @ORM\Column(name="`notexitinggroup`", type="smallint")
     */
    private $group;
```

i get a SQL error that the field can not be found, tough in the error i see the field is not escaped.

**Comment by Deltachaos** [comment]
@Michal-sk are you able to write a test that reproduces this issue?

**Comment by Michal-sk** [comment]
sure

**Comment by Deltachaos** [comment]
@Michal-sk would be grate if you create a PR that contains this test. A fix could then be build against the test.

**Comment by Michal-sk** [comment]
Ok, maybe you could tell more about the idea behind the tests? I am a bit overwhelmed and not sure where to start when looking in the tests folder

**Comment by deeky666** [comment]
Isn't it responsibility of `QuotingStrategy` to deal with that? IMO escaping of join columns has to be done in userland by a `QuotingStartegy`. We had issues like this a lot before already.

**Comment by Michal-sk** [comment]
The group column is not a join column it self. It is just a column in the table. But when calling a association of the option (ManyToMany self-referenceing) the escape quotes are removed from the associations.

**Comment by Michal-sk** [comment]
Ok after more testing This has to do with `matching`. When i just return the association everything is fine:
```php

    public function getDependingOptions()
    {
        return $this->requiredOptions;//->matching($this->getRelationCriteria(Relation::get(Relation::DEPEND)));
    }
```

but when i use matching it does not escape the fields properly,

**Comment by Michal-sk** [comment]
Is there maybe a difference betwee Sqlite and MySQL? When i play around with `ManyToManySelfReferentialAssociationTest` and the `ECommerceProduct`, i added a `group` property and that does seem to be quoted / escaped

**Comment by ostrolucky** [comment]
In Doctrine 3.x, everything is quoted by default, which solves this issue
