### ISSUE TITLE
prefix code with spaces in EntityGenerator

### ISSUE THREAD

**Issue by poolerMF** [doctrine/doctrine2#5955]
hello

class **EntityGenerator**, function **prefixCodeWithSpaces**

old condition:

```
if ( ! empty($value)) {
...
}
```

suggested condition:

```
if ( ! empty($value) && $value != "\r") {
...
}
```

**Comment by Ocramius** [comment]
The fact that you have`\r` in the codebase seems weird. What would the
reason for the change be?

**Comment by poolerMF** [comment]
I have custom EntityGenrator, with custom templates ... and now I see the difference ...
I use WINDOWS, so my line separator is CRLF mode

so, becouse someone should have CRLF line separator

**Comment by Ocramius** [comment]
@poolerMF you should pretty much always get rid of CRLF, and set up your editor, as well as GIT, to strip them.

While I get that it would be interesting in supporting CRLF, I see little point in it, since we'd just support a bad practice then.

**Comment by Ocramius** [comment]
@beberlei can you take a look at this, please?

**Comment by Majkl578** [comment]
EntityGenerator is going to be removed in Doctrine 3.0, thanks for reporting.
