### ISSUE TITLE
New record after findBy

### ISSUE THREAD

**Issue by frank-herbert** [doctrine/doctrine2#5969]
Doctrine is creating a new record after when you get the results using "findBy".

```php
$collection = $this->em
    ->getRepository("MyBundle:MyEntity")
    ->findBy(array('Status' => null));

foreach ($collection as $item) {
    $item->setTimestamp(\DateTime::createFromFormat('U.u', microtime(true)));
    $item->setStatus('DONE');

    $this->em->persist($item);
    $this->em->flush();
}
```

**Comment by Ocramius** [comment]
That's not sufficient information to debug your issue. What is being created? What do `setTimestamp` and `setStatus` do? Is `$item` a managed entity at all times? Are sub-entries created?

**Comment by frank-herbert** [comment]
Thank you for your help, Ocramius. 

$item was empty before Doctrine persist().

My mistake. Sorry.
