### ISSUE TITLE
Wrong return type of getResult()

### ISSUE THREAD

**Issue by giginos** [doctrine/doctrine2#5971]
Hi Folks,
i've found a wrong return type in a core method.
Should be fixed to improve work with IDEs.

**Affected file:** https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/AbstractQuery.php

**Affected method:**
public function getResult($hydrationMode = self::HYDRATE_OBJECT)

**To be changed:**
The tag "@return array" should be set to "@return mixed" or something suitable.

Regards,
Rafael

**Comment by Ocramius** [comment]
@giginos you can edit https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/AbstractQuery.php and send the change back to us directly :-)

**Comment by Ocramius** [comment]
Handled in #5972
