### ISSUE TITLE
[Feature-Request] OneToOne EXTRA_LAZY inverseSide

### ISSUE THREAD

**Issue by boesing** [doctrine/doctrine2#5981]
Hey there,

got the following Entities:

```
/**
 * @ORM\Entity()
 * @ORM\Table(name="foo")
 */
class Foo 
{

   /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue
     *
     * @var integer
     */
    private $id;

    /**
     * @ORM\OneToOne(
     *  targetEntity="Bar",
     *  mappedBy="foo",
     *  fetch="EXTRA_LAZY"
     * )
     *
     * @var Bar|null
     */
    private $bar;
}
```

```
/**
 * @ORM\Entity()
 * @ORM\Table(name="bar")
 */
class Bar 
{

  /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue
     *
     * @var integer
     */
    private $id;

    /**
     * @ORM\OneToOne(
     *  targetEntity="Foo",
     *  inversedBy="bar",
     *  fetch="EAGER"
     * )
     * @ORM\JoinColumn(name="foo_id", onDelete="cascade", nullable=true)
     * @var Foo|null
     */
    private $bar;
}
```

If I now fetch the `Foo` entity by using its Repository, I will get the `Foo` entity with LEFT JOINED `Bar` entity, even if I define `EXTRA_LAZY`. I tried to define `EXTRA_LAZY` in `Bar` Entity aswell, but it has no effect.

Is that an expected bahavior?

I would expect that if I load the `Bar` entity, the `Foo` entity is always loaded aswell because of `EAGER` fetch mode, but if I load the `Foo` entity, the `Bar` entity is not loaded until I change the fetch mode.

**Comment by yurybykov** [comment]
OneToOne supports only EAGER and LAZY and not support EXTRA_LAZY.
http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/annotations-reference.html#annref-onetoone

**Comment by boesing** [comment]
@yurybykov I converted this issue to a feature request
