### ISSUE TITLE
SimpleObjectHydrator produces wrong values with inheritance table and simple array type 

### ISSUE THREAD

**Issue by w3sami** [doctrine/doctrine2#5989]
I am getting empty array instead of array with some values, since SimpleObjectHydrator converts the value with convertToPHPValue

line 129 $value = $type->convertToPHPValue($value, $this->_platform);

this doesent play well with the null check below

line 134:
// Prevent overwrite in case of inherit classes using same property name (See AbstractHydrator)
            if ( ! isset($data[$fieldName]) || $value !== null) {
                $data[$fieldName] = $value;
            }

since arrayType->convertToPHPValue  returns [] when null, resulting in a leak from the wrong left joined table.

solution is easy, dont use the converted value in the if, but instead a raw value.

eg line 125 + $rawValue = $value;
and
136: if ( ! isset($data[$fieldName]) || $rawValue !== null) {

sorry I don't have time to write a pr with tests

**Comment by Ocramius** [comment]
> since arrayType->convertToPHPValue returns [] when null, resulting in a leak from the wrong left joined table.

Seems like an issue with the array type, rather than with the ORM itself?

**Comment by w3sami** [comment]
SimpleObjectHydrator is the file with the problem, type is ok imo. Same
issue is with eg json array type. Hydrator compares with type converted
version not raw value.
For me it makes sense that null is empty array for array type.

**Comment by w3sami** [comment]
bumb! this is actually a quite serious bug, as it renders all our entities with joined inheritance + (json/)array type useless!!

**Comment by Ocramius** [comment]
The fix in #6004 seems good, besides minor cleanup needed :-)

**Comment by Ocramius** [comment]
Fixed in #6004, thanks @w3sami and @cvuorinen!
