### ISSUE TITLE
[Inheritance] Ignore unknown discriminators

### ISSUE THREAD

**Issue by fancyweb** [doctrine/doctrine2#5997]
The problem is simple : if you have a discriminator in your table field that is not mapped anymore in your Doctrine configuration, you cannot load the entity nor collections of this entity. You will trigger the `HydrationException::invalidDiscriminatorValue` exception.

IMO, Doctrine should ignore unknown discriminators or execute the queries with a condition to select only rows with known discriminators.

I already started working on this for personal reasons, should it be the default Doctrine behavior ?

**Comment by lcobucci** [comment]
IMO the ORM shouldn't be responsible for this.
You have invalid data and it doesn't know how to process it, so you should be the one to migrate your invalid data to a valid one.

**Comment by Ocramius** [comment]
Pretty much what @lcobucci said. If you want to filter invalid discriminators from the ORM, then you'd probably want to use a view.

Closing: this is a limitation of the ORM that is intentional (otherwise there wouldn't be an exception there anyway ;-) )
