### ISSUE TITLE
Mocking Paginator

### ISSUE THREAD

**Issue by matiux** [doctrine/doctrine2#5999]
Hi,
I need to test a service that accepts a `Doctrine\ORM\Tools\Pagination\Paginator` object.
I wouldn't use the real repository in the test class. Rather I'd like to mock Paginator with some result so that I can pass it to my service. 

I'm looking for the examples in the source code but I still not find them.

Can someone supply some examples to mock Paginator?

Thanks

**Comment by Ocramius** [comment]
A Paginator is just an iterator: you can type-hint against that, usually.

**Comment by matiux** [comment]
Thanks @Ocramius,
what do you mean with "type-hint against that" ?

**Comment by lcobucci** [comment]
`Paginator` implements `IteratorAggregate` (that extends `Traversable`). So you can use `Traversable` as type-hint and pass any iterator you want (instead of mocking Paginator class).

**Comment by matiux** [comment]
Thanks,
I'm was also able to create a mock:

```
        $config = m::mock(Configuration::class);
        $config->shouldReceive('getDefaultQueryHints')->andReturn([]);
        $config->shouldReceive('isSecondLevelCacheEnabled')->andReturn(false);

        $em = m::mock(EntityManager::class);
        $em->shouldReceive('getConfiguration')->andReturn($config);

        $query = m::mock(new Query($em));
        $query->shouldReceive('getFirstResult')->andReturn(1);

        $paginator = m::namedMock('Paginator', 'Doctrine\ORM\Tools\Pagination\Paginator');
        $paginator->shouldReceive('count')->atMost(1)->andReturn(count($results));
        $paginator->shouldReceive('getQuery')->atMost(1)->andReturn($query);
        $paginator->shouldReceive('getIterator')->atMost(1)->andReturn(new \ArrayIterator($results));
```

**Comment by Ocramius** [comment]
That is all waaaaaay too specific mocking of implementation details. Refrain from doing that: it is just making your tests fragile, hard to read and an overall no-value-added.

See what @lcobucci said instead.

Closing here: thought it was on the mailing list, but it's on the tracker, and the tracker is for issues ;-)

**Comment by matiux** [comment]
I have a doubt. Using Traversable object, how can I have, for example `getFirstResult()` method? My service (that accepts `Paginator` object), needs to access to `Query` in `Paginator` to get the first result

Thanks

**Comment by Ocramius** [comment]
You'd inject the query and the paginator separately then. Getting the query from the paginator is usually a bad idea...

**Comment by matiux** [comment]
Paginator is based on the query. You can simply get the query with `$paginator->getQuery()`. Passing Paginator and Query separately is a redundant way. My 2 cents.

```
public function foo(Paginator $p, Query $q) {
}

public function foo(Paginator $p) {

$q = $p->getQuery();
}
```

I don't think that the second approach it's wrong :)

**Comment by Ocramius** [comment]
The second approach is wrong because you are assuming that the query that
you retrieve is the same one you gave in. No guarantee on this comes from
that API.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by matiux** [comment]
According to this logic, from the repository I need to return non only `Doctrine\ORM\Tools\Pagination\Paginator` but also `Doctrine\ORM\Query`

**Comment by Ocramius** [comment]
Or just the iterator. If you want the first result only, you can traverse
the operator only to its first element. Throwing a query object around is
mostly trouble.

**Comment by matiux** [comment]
There is a mistake. getFirstResult() doesn't return the first item of the collection. It returns the offset of the query.

... LIMIT 40 OFFSET 81

It is the parameter that you can set in the query doctrine with $queryBuilder->setFirstResult($offset);

This paramater there isn't in the Paginator object
