### ISSUE TITLE
Unable to autowire argument index 0 ($em) for EntityRepository

### ISSUE THREAD

**Issue by KIVagant** [doctrine/doctrine2#6021]
Hello.

I trying to inject one of my Entity Repository as argument of the service constructor in Symfony 2.  And I got the problem:

```
Unable to autowire argument index 0 ($em) for for the service "autowired.*\*\*Repository".
 If this is an object, give it a type-hint. Otherwise, specify this argument's value explicitly.
```

I found [this commit](https://github.com/doctrine/doctrine2/commit/dbd3fa4501ba062e749c2227bec4ac5934699df5) than can help to fix this.

Unfortunately, this commit is present only [in the master](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/EntityRepository.php#L64) but not in the [2.5 branch](https://github.com/doctrine/doctrine2/blob/2.5/lib/Doctrine/ORM/EntityRepository.php#L64).

Can you fix this problem in 2.6 version?

**Comment by mvrhov** [comment]
If this really is a bug it could be back-ported to 2.7 which is the lowest version still supported.

**Comment by KIVagant** [comment]
I am not an expert with Doctrine's workflow. Please, decide what is more correctly to do.

**Comment by mvrhov** [comment]
Oh. Sorry. I thought this is in symfony2.

**Comment by KIVagant** [comment]
Yes, I caught the bug in Symfony2, but the real problem in the EntityManager constructor

**Comment by albertboada** [comment]
No news on this? Why is the type hint on master since 2 years ago but not on the 2.x branches?

**Comment by Ocramius** [comment]
Because 2.6 was not released, and we don't get to do a release ATM due to
work.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by Majkl578** [comment]
2.6.0 has just been released. Closing, this wasn't really a bug in Doctrine (autowiring of mixed parameter should be explicit).
