### ISSUE TITLE
getQueryResult

### ISSUE THREAD

**Issue by DonCallisto** [doctrine/doctrine2#6023]
Why don't add the following API to `QueryBuilder`?

```
public function getQueryResult($hydrationMode = null)
{
    return $this->getQuery()->getResult($hydrationMode);
}
```

That way Law of Demeter is not broken and is easier to write tests mocking `QueryBuilder`.

Other way I need to create a mock of `Query` (and, perhaps, it's not possibile with Prophecy as `Query` is final) so it force me to "dig" into collaborator structure.

Any thoughts?

**Comment by guilherme90** [comment]
Yes, I'm having the same problem with mock the Query object (it is not possible to create fake objects with final signature). And when I do this with AbstractQuery, it gives a constructor error.

How can we solve this?

**Comment by Ocramius** [comment]
Please don't mock the QueryBuilder or Query objects: use real instances
there.

**Comment by guilherme90** [comment]
Okay thanks.
