### ISSUE TITLE
(hibernate / jpa) @Where - How to obtain a subset of a collection?

### ISSUE THREAD

**Issue by marcos-rocha** [doctrine/doctrine2#6030]
How can I obtain a subset of a larger collection?
What I want do to is  filter a oneToMany using "clause x = y".

Example:
```php
class Foo {

 @ORM\OneToMany(targetEntity="EntityA", ...)
 private $listOfA;

 @ORM\OneToOne(targetEntity="EntityA", ...)
@Where(clause="main=true and age > 10"), main and age are EntityA properties
 private $singleA;
}
```
Please, visit the link:
http://docs.jboss.org/hibernate/stable/annotations/reference/en/html_single/#entity-hibspec-collection

Thanks.

**Comment by Ocramius** [comment]
Not supported by doctrine2: you will have to use the criteria API at runtime (see `PersistentCollection#matching()`)
