### ISSUE TITLE
How to create a unique lowercase index?

### ISSUE THREAD

**Issue by atkrad** [doctrine/doctrine2#6039]
Hi,
How to create a unique lowercase index in schema?

**Comment by Ocramius** [comment]
Use the `@UniqueConstraint` mapping (or equivalent, depending on mapping format)

**Comment by atkrad** [comment]
@Ocramius I know, But I want create index based on lower case for example:
`CREATE UNIQUE INDEX lower_case_username ON users ((lower(username)));`

**Comment by Ocramius** [comment]
That's not supported, since it's a DB-specific feature (indexes on functions applied to columns): use a DB migration.

**Comment by atkrad** [comment]
@Ocramius Thank you.
