### ISSUE TITLE
APCu over APC breaks ORM?

### ISSUE THREAD

**Issue by andig** [doctrine/doctrine2#6044]
I've recently upgraded to PHP 7 and switched `ApcCache` with `ApcuCache`. Apparently from doing this, my application fails to load. This happens whenever I set either or

				$config->setMetadataCacheImpl($cache);
				$config->setQueryCacheImpl($cache);

once `ApcuCache` is used loading the page just stalls (running on Apache/OSX). I have not yet found where it stalls, might well be an apcu rather than ORM issue.

**Comment by holtkamp** [comment]
Never had problems with it, currently running:

- development:
 - PHP: 7.0.11
 - APCu: 5.1.5 
- Heroku:
 - PHP 7.0.10
 - APCu: 5.1.5

Maybe you can send your APCu settings? You can use [this file](https://github.com/krakjoe/apcu/blob/master/apc.php) to get insight in your configuration.

**Comment by Ocramius** [comment]
May also want to know what it breaks. Try isolating the behavior, then turn it into a test?

**Comment by andig** [comment]
Sorry guys- not a doctrine issue. Event loading the testfile stalls with php 7.0.10 and apcu 5.1.5. I'll head over to https://github.com/krakjoe/apcu for further troubleshooting.

**Comment by andig** [comment]
For sake of completeness: fixed by reinstalling php 7.0.11 and apcu 5.1.5 both using homebrew plus reboot. Weirdo...
