### ISSUE TITLE
[doc] Repository method count does not exist

### ISSUE THREAD

**Issue by mcorteel** [doctrine/doctrine2#6060]
The [documentation](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/working-with-objects.html#by-simple-conditions) references a convenience method of entity repositories named `count`.

Like this comment on stackoverflow states, it would be a great addition to the `EntityRepository`, but it doesn't actually exist ([reference](http://www.doctrine-project.org/api/orm/2.5/class-Doctrine.ORM.EntityRepository.html)).

**Comment by lcobucci** [comment]
@mcorteel that method is available for 2.6 and not 2.5.x

**Comment by mcorteel** [comment]
Then I think it should be mentioned in the documentation. Shouldn't it?

**Comment by Ocramius** [comment]
Fairly sure that those docs aren't referencing the correct branch... To be checked in https://github.com/doctrine/doctrine-website-sphinx, I suppose.

**Comment by yannickl88** [comment]
Is this still an issue? As far as I can tell the docs are not referencing any branch directly (via a link or some sorts).

Would an acceptable fix for this to add a line to the current docs that the `count` method has been added in 2.6 suffice? I.e.,:

> _New in version 2.6._
> 
> Additionally, you can just count the result of the provided conditions when you don't really need the data:
> ```php
>     <?php
>     // Check there is no user with nickname
>     $availableNickname = 0 === $em->getRepository('MyProject\Domain\User')->count(['nickname' => 'nonexistent']);
> ```

**Comment by mcorteel** [comment]
Yes, that would fix it!

**Comment by Ocramius** [comment]
Moved to https://github.com/doctrine/doctrine-website-sphinx/issues/149 - closing here
