### ISSUE TITLE
Custom mapping types confuse Doctrine identifying schema changes

### ISSUE THREAD

**Issue by Aerendir** [doctrine/doctrine2#6077]
As told in the title, I've created two custom mapping types.

Now, each time I run the schema validation, Doctrine thinks the field that use those custom types have to be updated.

I've described the problem in full details on [StackOverflow](http://stackoverflow.com/questions/39921887/doctrine-always-tells-me-the-database-isnt-in-sync-after-using-two-custom-mapp).

I don't know if this is a fault of mine or a Doctrine's one, so I'm writing this issue.

Thank you.

**Comment by Aerendir** [comment]
[This solved the problem](http://stackoverflow.com/a/39922217/1399706).

Simply by adding this function:

```php
    /**
     * {@inheritdoc}
     */
    public function requiresSQLCommentHint(AbstractPlatform $platform)
    {
        return !parent::requiresSQLCommentHint($platform);
    }
```

**Comment by Ocramius** [comment]
Sufficient:

```php
    /**
     * {@inheritdoc}
     */
    public function requiresSQLCommentHint(AbstractPlatform $platform)
    {
        return true;
    }
```

**Comment by Aerendir** [comment]
@Ocramius , yes, sufficient... But the editor told me I were not calling the parent method and I don't like alerts. The result is the same.

**Comment by Ocramius** [comment]
That's a false positive - don't blindly trust the editor.

**Comment by Aerendir** [comment]
Eh eh, yes, I know, but anyway it alerts me and have, as told, I don't like alerts. So, if I can"solve" them, I do, so I know what really has to have attention reserved...
