### ISSUE TITLE
 Associations - threat empty string as null and do not load related entity

### ISSUE THREAD

**Issue by majkel89** [doctrine/doctrine2#6099]
Is it possible to configure doctrine to use null, `empty string` and/or `zero` as actual `null value` so that related entity is not loaded and `Doctrine\ORM\EntityNotFoundException` is not thrown.

I have external database that i have no control over that uses empty strings to to mark null value.

````php
class ParentEntity {
    /**
     * @var ChildEntity
     * @ORM\ManyToOne(targetEntity="ChildEntity", fetch="EAGER")
     * @ORM\JoinColumn(name="child_id")
     */
    private $child;
}

$parent = new ParentEntity;
$parent->getChild(); // Doctrine\ORM\EntityNotFoundException is thrown when child_id equals ''
````

**Comment by Ocramius** [comment]
Big explanation at https://stackoverflow.com/questions/15502408/doctrine-2-use-default-0-values-instead-of-null-for-relation

Closing here. `NULL` means `NULL`, other things are not `NULL`, and won't be supported, as we'd just be opening a can of worms about FK integrity support in different RDBMSs
