### ISSUE TITLE
how to generate-entities or convert-mapping make the fields not named as lowercase

### ISSUE THREAD

**Issue by akmumu** [doctrine/doctrine2#6102]
in my databases,that,s all the camlcase fields
i need is not 
```
class Order
{
    /**
     * @var integer
     *
     * @ORM\Column(name="orderId", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $orderid;
```
and need  `private $orderid` is `$orderId`
well, i hope `@ORM\Table(name="order",` will be come 
![image](https://cloud.githubusercontent.com/assets/3242526/19716952/e5a8a260-9b90-11e6-89b5-d5b85efe9de0.png)

because order in mysql is a ...

thanks a lot

**Comment by Ocramius** [comment]
The generated entities are just some sort of point where to start from. The generator is only going to get you this far.

If you need to customize the entities after code generation, you'll have to do so manually.

**Comment by akmumu** [comment]
@Ocramius thanks
