### ISSUE TITLE
Minor docblock issue ResultSetMappingBuilder

### ISSUE THREAD

**Issue by arjank** [doctrine/doctrine2#6106]
The docblock of `ResultSetMappingBuilder::addJoinedEntityFromClassMetadata()` in the 2.5 branch (and all previous 2.x branches) indicates that $relation should be an object. But the parameter is passed as-is to `ResultSetMapping::addJoinedEntityResult()` which expects it to be a string (that has been updated in commit cb31798). Would it be possible to backport commit 5481e0f from master to (at least) the 2.5 branch so the docblock correctly indicates what is expected?

**Comment by Ocramius** [comment]
Sorry, not going to backport documentation issues: simply not worth the additional time.
