### ISSUE TITLE
how Ignoring field when inserting data with Doctrine ORM

### ISSUE THREAD

**Issue by akmumu** [doctrine/doctrine2#6114]
i got `SQLSTATE[23000]: Integrity constraint violation: 1048 Unknown error 1048` error,
this because my table has too many fileds, some of that i hope doctrine will ignore that when insert,but i got many null.

**Comment by Ocramius** [comment]
Don't map it in your entity, and it will not be persisted.

**Comment by akmumu** [comment]
@Ocramius if i do not map these, i can not use getXXX,and setXXX

**Comment by Ocramius** [comment]
Yes, either that or set defaults on the entity fields. DB-side generated
fields are not supported.
