### ISSUE TITLE
static method on EntityManager makes impossible to override entityManager class

### ISSUE THREAD

**Issue by wolfwolker** [doctrine/doctrine2#6115]
the last line of this method is return new EntityManager(...), so if you try to override this class you need to copy/paste the whole method for only this purpose. This is mentioned here http://stackoverflow.com/questions/8138962/is-there-a-way-to-specify-doctrine2-entitymanager-implementation-class-in-symfon and in some other sOverflow's topic

I think a solution could be end this method with return new static(...) instead.

Sorry if this topic is duplicated,  I wasn't able to found it either in issues nor pr section.

**Comment by Ocramius** [comment]
You should either use an EntityManagerDecorator, or re-implement the
EntityManagerInterface.
