### ISSUE TITLE
PHP7 compatibility issue

### ISSUE THREAD

**Issue by anacicconi** [doctrine/doctrine2#6132]
Hello,

I'm upgrading my project to php7 and I'm using a report generated by phpcs with PHPCompatibility. I got two errors related to the bundle and I would like to know if this is something you decided not to change because it can't cause any damage or we should provide a PR. 

I'm using doctrine 2.4.8 but I just checked in the repository and the master branch contains the same code. Here are the errors:

    FILE: .../orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
    ----------------------------------------------------------------------
    FOUND 2 ERRORS AFFECTING 2 LINES
    ----------------------------------------------------------------------
   917 | ERROR | 'clone' is a reserved keyword introduced in PHP version
     |       | 5.0 and cannot be invoked as a function (T_CLONE)
     |       | (PHPCompatibility.PHP.ForbiddenNamesAsInvokedFunctions.Found)
   942 | ERROR | 'clone' is a reserved keyword introduced in PHP version
     |       | 5.0 and cannot be invoked as a function (T_CLONE)
     |       | (PHPCompatibility.PHP.ForbiddenNamesAsInvokedFunctions.Found)

I think that deleting the parenthesis and maybe assigning the value first to a variable will correct it. 

Is anybody already using the bundle with php7? Can you give me a feedback?

**Comment by lcobucci** [comment]
@anacicconi the parenthesis are indeed not needed but there's no problem at all. You can check here too: https://3v4l.org/chnBj

**Comment by Ocramius** [comment]
Closing as invalid.

**Comment by anacicconi** [comment]
Ok, thanks for your answer @lcobucci.
