### ISSUE TITLE
Quoted table name attribute is not propagated through inheritance mapping

### ISSUE THREAD

**Issue by NoiseByNorthwest** [doctrine/doctrine2#6133]
In case of single table inheritance, the quoted parent table will have its children ClassMetaData built without quoted table name attribute contrary to parent ClassMetaData.
This happens here https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php#L2294
It seems that the following logic is missing to propagate quoted table name attribute:

```php
if (isset($table['quoted']) && $table['quoted'] === true) {
    $this->table['quoted'] = true;
}
```

**Comment by ostrolucky** [comment]
In Doctrine 3.x, everything is quoted by default, which solves this issue
