### ISSUE TITLE
Your proxy directory "data/DoctrineORMModule/Proxy" must be writable

### ISSUE THREAD

**Issue by swoopfx** [doctrine/doctrine2#6144]
any time i upload an image and call that image whose link is situated in a database i get this error , Though the application works fine on my Windows 10 OS, upon deployment to my ubuntu server it show  Your proxy directory "data/DoctrineORMModule/Proxy" must be writable with the foloowing explanation 
#0 /usr/local/zend/var/apps/http/imapp.cloudapp.net/80/1.0.8.0_132/vendor/doctrine/common/lib/Doctrine/Common/Proxy/ProxyGenerator.php(299): Doctrine\Common\Proxy\Exception\UnexpectedValueException::proxyDirectoryNotWritable('data/DoctrineOR...')
#1 /usr/local/zend/var/apps/http/imapp.cloudapp.net/80/1.0.8.0_132/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php(220): Doctrine\Common\Proxy\ProxyGenerator->generateProxyClass(Object(Doctrine\ORM\Mapping\ClassMetadata), 'data/DoctrineOR...')
#2 /usr/local/zend/var/apps/http/imapp.cloudapp.net/80/1.0.8.0_132/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php(119): Doctrine\Common\Proxy\AbstractProxyFactory->getProxyDefinition('Web\\Entity\\Even...')
#3 /usr/local/zend/var/apps/http/imapp.cloudapp.net/80/1.0.8.0_132/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2698): Doctrine\Common\Proxy\AbstractProxyFactory->getProxy('Web\\Entity\\Even...', Array)
#4 /usr/local/zend/var/apps/http/imapp.cloudapp.net/80/1.0.8.0_132/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php(147): Doctrine\ORM\UnitOfWork->createEntity('Web\\Entity\\Even...', Array, Array)
#5 /usr/local/zend/var/apps/http/imapp.cloudapp.net/80/1.0.8.0_132/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php(69): Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator->hydrateRowData(Array, Array)
#6 /usr/local/zend/var/apps/http/imapp.cloudapp.net/80/1.0.8.0_132/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(147): Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator->hydrateAllData()
#7 /usr/local/zend/var/apps/http/imapp.cloudapp.net/80/1.0.8.0_132/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(888): Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll(Object(Doctrine\DBAL\Driver\PDOStatement), Object(Doctrine\ORM\Query\ResultSetMapping), Array)
#8 /usr/local/zend/var/apps/http/imapp.cloudapp.net/80/1.0.8.0_132/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(181): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->loadAll(Array, Array, 30, NULL)
#9 /usr/local/zend/var/apps/http/imapp.cloudapp.net/80/1.0.8.0_132/module/Web/src/Web/Service/EventWebService.php(48): Doctrine\ORM\EntityRepository->findBy(Array, Array, 30)
#10 /usr/local/zend/var/apps/http/imapp.cloudapp.net/80/1.0.8.0_132/module/Web/src/Web/Controller/EventerController.php(64): Web\Service\EventWebService->getEventGalleryEvents()
#11 /usr/local/zend/var/apps/http/imapp.cloudapp.net/80/1.0.8.0_132/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Web\Controller\EventerController->eventGalleryAction()
#12 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#13 /usr/local/zend/var/apps/http/imapp.cloudapp.net/80/1.0.8.0_132/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#14 /usr/local/zend/var/apps/http/imapp.cloudapp.net/80/1.0.8.0_132/vendor/zendframework/zend-eventmanager/src/EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /usr/local/zend/var/apps/http/imapp.cloudapp.net/80/1.0.8.0_132/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#16 /usr/local/zend/var/apps/http/imapp.cloudapp.net/80/1.0.8.0_132/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#17 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#18 /usr/local/zend/var/apps/http/imapp.cloudapp.net/80/1.0.8.0_132/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#19 /usr/local/zend/var/apps/http/imapp.cloudapp.net/80/1.0.8.0_132/vendor/zendframework/zend-eventmanager/src/EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#20 /usr/local/zend/var/apps/http/imapp.cloudapp.net/80/1.0.8.0_132/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#21 /usr/local/zend/var/apps/http/imapp.cloudapp.net/80/1.0.8.0_132/public/index.php(17): Zend\Mvc\Application->run()

**Comment by Ocramius** [comment]
Please do read your error messages: the directory on the deployment system is not writable.

**Comment by sushrest** [comment]
@Ocramius, is there anyways we can use aws s3 bucket for Proxy directory?

**Comment by Ocramius** [comment]
Don't think so: if you need to avoid writing proxies somewhere, use `AUTOGENERATE_EVAL`, which, while slower, should work in almost every environment.
