### ISSUE TITLE
Flushed changes not rolling back

### ISSUE THREAD

**Issue by chinmayshah24** [doctrine/doctrine2#6150]
What is the real purpose of `flush` in doctrine? I am unable to use it in services properly. The changes are committed to the database regardless of any exceptions in processing. Should we just be using `persist` wrapped in a `transactional` block? This is my pseudo code:

    $em->getConnection()->beginTransaction();
    try{
    
        $q = new ABC\Entity\DEF();
        //fill it up...        
        $em->persist($q);
        $em->flush();
    
        throw new Exception("def");
    
    
    } catch (Exception $ex) {
    
        $em->getConnection()->rollBack();
    }

Same with the `transactional` closure. Basically the same as [this][1] approach in the docs. I mean it's there in the docs, and i am trying that. What am i doing wrong?

I don't even need to use `commit`. What's going on?

Is this a bug?

  [1]: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/transactions-and-concurrency.html#approach-2-explicitly

**Comment by Ocramius** [comment]
> The changes are committed to the database regardless of any exceptions in processing.

No, a transaction will be rolled back if a flush fails: https://github.com/doctrine/doctrine2/blob/b06dcb89b379252ebe26ed3913b2226a8fb8ebdd/lib/Doctrine/ORM/UnitOfWork.php#L402-L409

Same goes for the [`EntityManager#transactional()`](https://github.com/doctrine/doctrine2/blob/b06dcb89b379252ebe26ed3913b2226a8fb8ebdd/lib/Doctrine/ORM/EntityManagerInterface.php#L79-L80) API. You can find the implementation at https://github.com/doctrine/doctrine2/blob/b06dcb89b379252ebe26ed3913b2226a8fb8ebdd/lib/Doctrine/ORM/EntityManager.php#L240-L245

**Comment by chinmayshah24** [comment]
My table was a MyISAM, as you suspected in the other thread

**Comment by Ocramius** [comment]
Discussion reference: https://github.com/doctrine/doctrine2/issues/5759#issuecomment-263044242
