### ISSUE TITLE
Entity generator: PHP7 templates and strict types

### ISSUE THREAD

**Issue by Soullivaneuh** [doctrine/doctrine2#6154]
PHP7 is now here from a while and come with strict types.

I like the generator command, but it would be great to have a more flexible template, for PHP7 and strict type for example.

What do you think? Maybe we can propose multiple templates as an option.

Also, I didn't check if this already exists, but it could be useful to be able to add our custom templates onto the generator.

**Comment by Ocramius** [comment]
Doesn't need fixing IMO: tweaking the generated code is what you probably
want to do here.

**Comment by Soullivaneuh** [comment]
> tweaking the generated code is what you probably
want to do here.

What do you mean? Can we properly alternate the generator?

**Comment by Ocramius** [comment]
No, just edit the produced files, manually.

**Comment by Stelian** [comment]
@Ocramius, would you accept a PR with version checks and generate the proper code if the version is 7? I would also see some benefit in that since copy / pasting generated entities is a pain.

**Comment by Ocramius** [comment]
@Stelian most likely. The code generator is not BC compliant, so we can likely generate whatever fits the current best practices.

We can also apply it all the time now, as per #5884

**Comment by Stelian** [comment]
@Ocramius, I would leave the default as is and introduce support for something like a --strict_types switch that would generate them accordingly (argument types, return types). Does that make any sense? Not sure if imposing strict types for everyone is acceptable.

**Comment by Ocramius** [comment]
@Stelian no flags please, we just go with the new approach instead. Users that don't want the `declare` statement can drop it (same discussion for adding it, but I didn't drop PHP 5 support yet, sorry @Soullivaneuh!)

**Comment by Stelian** [comment]
@Ocramius, ack, will pick up this one since it's actually faster to fix generated code in my case :)

**Comment by Ocramius** [comment]
Remember that I whip people that don't write tests ;-)

**Comment by Stelian** [comment]
Will write the tests in a different branch just because i have a thing for ... never mind.

**Comment by Soullivaneuh** [comment]
> No, just edit the produced files, manually.

Well, what is the goal of the generator if we can't use it?

It would be a great addition to, at laest, add a possibility to pass custom templates to your generator and/or override the service IMHO.

**Comment by Ocramius** [comment]
> Well, what is the goal of the generator if we can't use it?

Quickly scaffolding entity classes when importing legacy projects. Most folks abuse it by just generating entities at every DB change instead.

**Comment by Majkl578** [comment]
EntityGenerator is going to be removed in Doctrine 3.0 and 2.6 is feature-complete, thanks for reporting.
