### ISSUE TITLE
Postgres 9.5, where on a json field

### ISSUE THREAD

**Issue by Crapal** [doctrine/doctrine2#6169]
Hi,

Working with doctrine 2.4 and symfony 2.8, I got a json field in a postgres table i want to filter in.
->andWhere("r.data->>'adresse' LIKE :adresse")->setParameter('adresse', 'test');

Got this error : [Syntax Error] line 0, col 88: Error: Expected Literal, got '>'

Doctrine don't want me to use this json operator : https://www.postgresql.org/docs/9.5/static/functions-json.html

**Comment by Ocramius** [comment]
That's not valid DQL. You probably want to run an SQL query?
