### ISSUE TITLE
Do not use doctrine namer

### ISSUE THREAD

**Issue by lazaro3487** [doctrine/doctrine2#6172]
Hello every one in the list. Is there any way to not use a namer because I have a database in MySQL but when I validate my entities, al foreign key constraint names and index namaes are changed by doctrine.

Regards.

**Comment by Ocramius** [comment]
@lazaro3487 this is currently not supported nor on the "nice to have" list, since FK names are generally not very important. My suggestion is to generate migrations via [`doctrine/migrations`](https://github.com/doctrine/migrations/), then customize the SQL there.
