### ISSUE TITLE
Window functions

### ISSUE THREAD

**Issue by ymarillet** [doctrine/doctrine2#6175]
Hello everyone,

Does anyone know if there is any plan to make [window functions](https://drill.apache.org/docs/sql-window-functions-introduction/) available in Doctrine ?

**Comment by Ma27** [comment]
doctrine supports many SQL database platforms and it seems as not each of them supports window functions, so it's unlikely that doctrine will provide native support for that.

If you'd like to do vendor-specific queries, there are two options:

- use a native query and hydrate manually (http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/native-sql.html)
- write your own DQL extension which makes this feature available in DQL queries (http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/dql-user-defined-functions.html)

**Comment by Ocramius** [comment]
Indeed, just go with SQL when doing this sort of stuff.

Closing here as `Can't Fix`
