### ISSUE TITLE
Subquery Error: Expected =, <, <=, <>, >, >=, !=, got 'LIKE' 

### ISSUE THREAD

**Issue by johnzuk** [doctrine/doctrine2#6182]
I have a mysql query:
```sql
SELECT COUNT(c.id) FROM company c WHERE (SELECT MIN(u.surname) FROM contact u WHERE u.company_id = c.id) LIKE '%a%'
```
it works perfectly. If i try to transfer it in to doctrine like that:
```php
$this->getDoctrine()->getManager()
            ->getRepository('XYZBundle:Company')
            ->createQueryBuilder('c')
            ->select('COUNT(c.id)')
            ->where("(SELECT MIN(u.surname) FROM XYZBundle:Contact u where u.id = c.id) LIKE '%a%'")
            ->getQuery()
            ->getResult();
```
doctrine throw 
`QueryException: [Syntax Error] line 0, col 136: Error: Expected =, <, <=, <>, >, >=, !=, got 'LIKE' '`
If i change **LIKE** into **=** subquery works. But i need LIKE, how can i do that?

**Comment by lcobucci** [comment]
@johnzuk it sounds like you don't need DQL here, native SQL is your friend too.

**Comment by johnzuk** [comment]
This is the only part of more complicated example. I want to use doctrine with DQL for that but i dont know if it is some doctrine bug or maybe i do something wrong

**Comment by lcobucci** [comment]
@johnzuk I'm not sure if `(subquery) LIKE *` is a valid statement for all platforms supported by `doctrine/dbal` and that might be the reason why you cannot use it. Maybe @Ocramius can clarify that.

In the meantime we could talk about this:

> I want to use doctrine with DQL

Why do you want to use DQL in that query? You're just doing a `COUNT()` statement.

**Comment by johnzuk** [comment]
It is only example. I want to create more complicated query with more columns and with three joins something like that:

```php
$this->getDoctrine()->getManager()
            ->getRepository('ServalCRMBundle:Company')
            ->createQueryBuilder('c')
            ->select('
            c.name, 
            c.street,
            (SELECT MIN(u.surname) FROM ServalCRMBundle:Contact u where u.id = c.id) surname,
            (SELECT MIN(p.date) FROM ServalCRMBundle:CompanyProducts p WHERE p.company = c.id) AS end_date')

            ->where("(SELECT MIN(x.surname) FROM ServalCRMBundle:Contact x where u.id = c.id) LIKE '%a%'")
            ->orderBy("end_date", 'desc')
            ->getQuery()
            ->getResult();
```
But if the only way to do this is create native SQL i will create it.

**Comment by Ocramius** [comment]
Subqueries in the `SELECT` clause are not allowed in DQL. The first query (original post) can probably be refactored with `EXISTS()`, although a bit messy.

You can check the complete EBNF of the DQL language at http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html#ebnf
