### ISSUE TITLE
Immutable Entities

### ISSUE THREAD

**Issue by davidbarratt** [doctrine/doctrine2#6183]
Is there a way to have immutable entities? My problem is that for instance if you create an entity and then persist it, Doctrine wants to set the id of the object. 

Is there a way to have the persist method return a new object with the id on it?

**Comment by lcobucci** [comment]
@davidbarratt if you want that you should not use a generated ID.

Maybe using an UUID would be better for you, you set it upfront (e.g. constructor) and the ORM would only use that value.

**Comment by davidbarratt** [comment]
@lcobucci well that's an interesting solution I hadn't considered. I suppose objects loaded from the database just overload the properties on creation? Or do they need setters?

**Comment by JCMais** [comment]
@davidbarratt reflection is used, no need for setters: https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/UnitOfWork.php#L2578

**Comment by davidbarratt** [comment]
@JCMais ok great! so the only feature that is really missing, is being able to use auto generated ids, but it's good to know there is a workaround.

**Comment by davidbarratt** [comment]
Or rather... I should say that you cannot use immutable entities with `@GeneratedValue()` since that would mutate your class, correct?

**Comment by lcobucci** [comment]
> Or rather... I should say that you cannot use immutable entities with @GeneratedValue() since that would mutate your object, correct?

Indeed, generated identifiers are also configured via reflection but in the end it would change the state of the object after it's creation (which removes the whole immutable idea).

**Comment by lcobucci** [comment]
With that said we'll close this as `invalid` 😉

**Comment by davidbarratt** [comment]
@lcobucci I guess the only way around that would be for Doctrine to generate / return a new object? Can I open a feature request for an option to force Doctrine to do this?

**Comment by lcobucci** [comment]
@davidbarratt the ORM is not responsible for creating a new object, it just gets an object that the user created and persists it (following the provided mapping).

You can definitely open the feature request but I don't think it would be implemented/accepted. The idea couples your domain to a detail (persistence), which is not something good when talking about object oriented design and architecture.
It would also push some extra complexity to the ORM, which is something that we always try to avoid 😃.

**Comment by davidbarratt** [comment]
@lcobucci which is worse, the coupling (domain to a detail), or mutable data in OOP?

**Comment by lcobucci** [comment]
@davidbarratt IMHO coupling (specially when talking about your domain). Mutability creates complexity which is not necessarily a problem.

**Comment by Ocramius** [comment]
Actually very simple to implement: use `@Entity(readOnly=true)` :-)

The rest (API-wise) is up to you, sorry.
