### ISSUE TITLE
[BUG] Incorrect handling of ManyToMany relation with unique constraint

### ISSUE THREAD

**Issue by aivus** [doctrine/doctrine2#6186]
It happens in case of using ManyToMany relation and using unique=true constraint.

`collectionUpdates` has updates, where add new relation item before remove old.
It causes error:
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'UNIQ_C978869F4584665A'
```

https://github.com/doctrine/doctrine2/blob/cd1a5fcadce6cd5fe3ee17360503d73e82852339/lib/Doctrine/ORM/UnitOfWork.php#L388

Workaround: change order of getting entities

See failing tests here:
https://github.com/doctrine/doctrine2/pull/6185

**Comment by aivus** [comment]
It could be fixed by adding different methods `deleteRow` and `insertRow` instead of `update` to `CollectionPersister`. But it affects interface and could be fixed only in the next version.

But I'm not sure about efficiency of this.

**Comment by Ocramius** [comment]
Closing as `invalid` as per https://github.com/doctrine/doctrine2/pull/6185#issuecomment-268925556
