### ISSUE TITLE
Weird entity naming in cli "orm:convert:mapping"

### ISSUE THREAD

**Issue by ifif14** [doctrine/doctrine2#6187]
Due to strtolower

in 
protected function getClassNameForTable($tableName)
in 
DatabaseDriver

table names from DB in camel case will be entities like "Userpasshistory"

**Comment by Ocramius** [comment]
That is normal when converting from snake case to StudlyCaps: seems
expected to me.

**Comment by ifif14** [comment]
yes, table names in snake_case will be StudlyCaps, which is okay. but StudlyCase table names will be capitalized lower cases php class names. I would expect here, that table like ShopProduct will be class ShopProduct and not Shopproduct as current, since it's OOP convention. 

At first I was looking at NamingStrategy to adjust this and ended up extending EntityGenerator and DatabaseDriver.
Maybe it makes sense to delegate this, alongside with column -> field conversion into NamingStrategy interface?

**Comment by Ocramius** [comment]
Seems unnecessary, when some manual tweaking on the mappings is sufficient.

Consider that mapping import operations are only to be applied once, when importing legacy schemas.

Closing as `won't fix`, since it is not primary focus.
