### ISSUE TITLE
PHP 7.1 nullable types in proxies doesn't supports

### ISSUE THREAD

**Issue by osavchenko** [doctrine/doctrine2#6188]
In PHP 7.1 was implemented [nullable types feature](http://php.net/manual/en/migration71.new-features.php#migration71.new-features.nullable-types), but proxy classes doesn't support it. Am I right or I miss something?

**Comment by lcobucci** [comment]
@osavchenko did you see our [latest release](https://github.com/doctrine/doctrine2/releases/tag/v2.5.6)? Are you using it?

**Comment by osavchenko** [comment]
Yes, I'm on it

**Comment by osavchenko** [comment]
Let me provide some example:

Proxy class:

```php
<?php

namespace Proxies\__CG__\HeadHunterBundle\Entity\Dictionaries;

class Area extends \AppBundle\Entity\Dictionaries\Area implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * {@inheritDoc}
     */
    public function setParent(\AppBundle\Entity\Dictionaries\Area $area): \AppBundle\Entity\Dictionaries\Area
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', [$area]);

        return parent::setParent($area);
    }
}
```

Original class:
```php
<?php

namespace AppBundle\Entity\Dictionaries;

class Area
{
   /**
     * Set Parent
     *
     * @param Area|null $area
     *
     * @return Area
     */
    public function setParent(?Area $area): Area
    {
        $this->parent = $area;

        return $this;
    }
}
```

**Comment by osavchenko** [comment]
sorry!
I'm on `doctrine/common` 2.6.2 because I'm using `doctrine/doctrine-bundle` (latest) :(

**Comment by lcobucci** [comment]
No worries! I'll just close this issue as `invalid` since it's not related to the ORM 😉

**Comment by osavchenko** [comment]
Thank you!
