### ISSUE TITLE
Select association id column w/o join

### ISSUE THREAD

**Issue by podorozhny** [doctrine/doctrine2#6199]
Hello!

Are there ways to select association column without extra join?

For example, I have 2 entities:

```
User
    id
    name
    group (column name: group_id)
    ...

Group
    id
    name
    ...
```

and want to select `user.groupId` without joining table `groups`.

Something like:

``` php
$queryBuilder = $this->createQueryBuilder('user');

$queryBuilder->select('user.id AS id')
    ->addSelect('user.name AS name')
    ->addSelect('user.group AS group_id');

$users = $queryBuilder->getQuery()->getArrayResult();
```

Thanks.

**Comment by podorozhny** [comment]
Oops, look like [IDENTITY()](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html#dql-functions) function is what I've been searching for,

**Comment by mrself** [comment]
Strange, but it turned out to be difficult to find such question in google. Though it is very useful feature.
