### ISSUE TITLE
UpdateCommand don't see Primary Keys in current Oracle database when CONSTRAINT_NAME differs from INDEX_NAME

### ISSUE THREAD

**Issue by stoccc** [doctrine/doctrine2#6206]
the UpdateCommand in Doctrine\ORM\Tools\Console\Command\SchemaTool
doesn't see currently defined Primary Keys in tables in Oracle (OCI8) if the name of the Constraint differs from the name of the Index (this always happens if you create on the DB a primary key constraint on a field that has already a unique index or when you perform a full Database Copy throught Oracle SQL developer and then try to execute the UpdateCommand - this was my case).

This bug causes the following SQL statements to be executed for every table in such a condition when executing the UpdateCommand
```
DROP INDEX sys_c009749277;
ALTER TABLE TABLE1 ADD PRIMARY KEY (id);
```

this is related to https://github.com/doctrine/dbal/pull/889 https://github.com/doctrine/dbal/issues/1234

**Comment by Ocramius** [comment]
Handled in doctrine/dbal#2686
