### ISSUE TITLE
Void return type should not be set in a proxy class.

### ISSUE THREAD

**Issue by strayobject** [doctrine/doctrine2#6221]
Any void return type in the entity class will cause a fatal error through a proxy class copying it over.

> PHP Fatal error:  A void function must not return a value in [...]

Entity code:
```
    /**
     * @ORM\PreUpdate
     */
    public function setUpdatedAtValue(): void
    {
        $this->updatedAt = new \DateTime();
    }
```
Proxy code:
```
    public function setUpdatedAtValue(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAtValue', []);

        return parent::setUpdatedAtValue();
    }
```

I might just be doing things wrong though.

**Comment by lcobucci** [comment]
Can you please check `doctrine/commons` version (as mentioned on https://github.com/doctrine/doctrine2/issues/6203#issuecomment-269640869 and https://github.com/doctrine/doctrine2/issues/6188#issuecomment-268538517)?

**Comment by strayobject** [comment]
I see, I'm running an outdated version then. 
`"name": "doctrine/common","version": "v2.6.2",`

Is it possible to run the new version, whilst still using symfony?

**Comment by Majkl578** [comment]
You will need doctrine/common ^2.7.1 for this to work properly. This is becaude doctrine/dbal still has no release that supports newer doctrine/common. Temporary workaround: `composer require doctrine/common 2.7.1 as 2.6.99`.
Duplicate of #6203, #6176, #6157, #6156.

**Comment by strayobject** [comment]
Awesome, thank you. I will close this then. :+1:
