### ISSUE TITLE
type aliases in entityGenerator

### ISSUE THREAD

**Issue by poolerMF** [doctrine/doctrine2#6224]
https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Tools/EntityGenerator.php#L166

why is TYPE:DECIMAL as string ? it should be float (https://www.phpdoc.org/docs/latest/guides/types.html)
there is also missing Type::FLOAT

**Comment by Ocramius** [comment]
Decimals are always mapped as strings, as floating point numbers are unsafe when dealing with precise numbers, since rounding is applied (the fun stuff coming from [`IEEE-754`](https://en.wikipedia.org/wiki/IEEE_floating_point)).

**Comment by poolerMF** [comment]
as I see in code .. those aliases are only for phpDoc
so still, it should be float, not string

**Comment by Ocramius** [comment]
No conversion is applied for decimal types, so you will get a string: https://github.com/doctrine/dbal/blob/b9b6714494c646946a0cd3d2be57a239aff977a3/lib/Doctrine/DBAL/Types/DecimalType.php#L52

**Comment by poolerMF** [comment]
so .. in DB I will have column of type float ... and when I call gettype($column) I will get "string"

I understand, that in conversion it should make fun stuff .. but this problem should be solved another way (now, I do not know how)

I checked other bigger projects using doctrine, and in property doc block, they had float too

maybe real value should be string(for avoiding problems), but property constructor for doc type shoudl be float ... EntityGenerator::$typeAlias is ONLY for phpDoc variable type

**Comment by Ocramius** [comment]
> is ONLY for phpDoc variable type

Pretty much all PHP code written before 7.0 relies on the promise that the docblock is not just a docblock, but also a promise of type invariance.

That said, you should use your custom type if you want a userland `float` or `double` instead of a `string`.
