### ISSUE TITLE
Entity name with namespace change mapping

### ISSUE THREAD

**Issue by mirekratman** [doctrine/doctrine2#6230]
When I create a query builder by using entity classname like:

```php
$this->entityManager
            ->getRepository($entity->getClassName())
            ->createQueryBuilder($entity->getClassName())`
```
```php
$entity->getClassName();//   ->   Cds\\Library\\Mysql\\Entity\\CdsDomain
```

and add a ordering
```php
$dql->orderBy(
                sprintf(
                    '%s.%s',
                    $entity->getClassName,
                    $somestring
                ),
                $order->getParam('dir', 'string')
            );
```

doctrine create the query (example)
```sql
SELECT c0_.name AS name_0, c0_.id AS id_1, c0_.safeDelete AS safeDelete_2, c0_._created AS _created_3, c0_._modified AS _modified_4, c0_._deleted AS _deleted_5, c0_.domain AS domain_6 FROM CdsDomain c0_ WHERE c0_.safeDelete <> 1 ORDER BY c0_.id ASC LIMIT 10
```

when will use entity classname without namespace 
```php
$entity->getClassName();//   ->   CdsDomain
```

query looks:
```sql
'SELECT c0_.name AS name_0, c0_.id AS id_1, c0_.safeDelete AS safeDelete_2, c0_._created AS _created_3, c0_._modified AS _modified_4, c0_._deleted AS _deleted_5, c0_.server AS server_6 FROM CdsDomain c0_ WHERE c0_.safeDelete <> 1 LIMIT 10
```

difference is 
```sql
c0_.domain AS domain_6` instead of right `c0_.server AS server_6
```

Annotation mapping look like this
```php
    /**
     * @ORM\ManyToOne(targetEntity="Cds\Library\Mysql\Entity\CdsServer", inversedBy="domain", fetch="EAGER")
     * @ORM\JoinColumn(name="server", referencedColumnName="id", nullable=false)
     */
    protected $server;
```

**Comment by Ocramius** [comment]
@mirekratman I don't understand `"when will use entity classname without namespace"`. What do you mean by "use" here? What is the `$entity->getClassName()` call?

**Comment by mirekratman** [comment]
@Ocramius Hi, $entity->getClassName() just return classname of entity simply using 

`return (string)get_class($this);` which returns `Cds\\Library\\Mysql\\Entity\\CdsDomain`

Regarding - "when will use"  - wanted to say that problem happens when method ->orderBy() gets as a $sort parameter a strng which contains classname with namespace `Cds\\Library\\Mysql\\Entity\\CdsDomain` instead of a simple string like `CdsDomain`.

I will prepare a simple entities and service to show the problem and will share a link here.

**Comment by lcobucci** [comment]
@mirekratman but why are you using the class name as alias name on the query builder?

**Comment by mirekratman** [comment]
@lcobucci good question - I can use any string like `abc` of course, I've just used classname.
Strange thing is Ive already did a separate unit tests but there I cannot simulate the issue yet.
In my project problem still exists - thats Ive also double checking my project.

**Comment by mirekratman** [comment]
The unit test (exact copy of the entities/repositories and method from service) can be fount here - https://github.com/mirekratman/tests - it passes corectly the test. The method with existing issue in my project is located in $this->domainService->getWrong(....). Still looking how to replicate this.

**Comment by mirekratman** [comment]
Because Ive tried many times to replicate this issue and I couldnt do it, please close the ticket.
When I will find what is the problem then share more info in new ticket.
Thank you
