### ISSUE TITLE
No error thrown upon fail when using schema-creation tool

### ISSUE THREAD

**Issue by fridde** [doctrine/doctrine2#6233]
I'm trying to find the reason why the command line utility `vendor/bin/doctrine orm:schema-tool:drop` as well as `update` throws an `ERROR: application encountered an error and can not continue. Unable to log error.`

This error message seems to be generated by [this line in Tracy/Debugger](https://github.com/nette/tracy/blob/master/src/Tracy/Debugger.php#L294) due to a non-set catchable error `$e` (correct me if I'm wrong) and the unhelpful message is rather frustrating.

`drop` and `update` have worked like a charm before I had to reinstall my OS and there's probably just  some false assumption in my configuration of the Entity Manager (which works otherwise), but when there's no error information, the search is a mess.

Therefore: Any guesses where the interaction between doctrine and Tracy fails? Can we improve error reporting for the Command Line Tools?

**Comment by Ocramius** [comment]
No clue what tracy is nor does, but the standard CLI from doctrine has a verbosity flag that can be used via `-vvv`.

Closing as invalid - please report this on tracy instead.

**Comment by fridde** [comment]
Thanks, you sent me in the right direction! And sorry for the inconvenience.

I was under the false impression that Doctrine internally was using [Tracy](https://github.com/nette/tracy), since the error message was rather unique to Tracy (according to google) and, yes, I found I still had it enabled on my local server. 

After running the schema tool with the verbosity flag my bug became plain obvious.

**Comment by Ocramius** [comment]
https://www.youtube.com/watch?v=4QWfrxYt9DQ
