### ISSUE TITLE
Cache problem with php 7.1 nullable types

### ISSUE THREAD

**Issue by Kearny** [doctrine/doctrine2#6235]
Doctrine cache generator doesn't report the nullable option : check the following print screen : 

![pasted_image_at_2017_01_15_10_45_pm](https://cloud.githubusercontent.com/assets/5919114/21966506/f745f044-db74-11e6-8186-f9049d0ee0be.png)

`public function getPhone(): ?string`

become 

`public function getPhone(): string`

which is a problem.

Thanks for taking care of that, and thanks for the great job done with doctrine !

**Comment by Ocramius** [comment]
Make sure that you re-generate the proxies once you upgraded to `doctrine/common` `2.7.*`. This was already fixed ;-)

**Comment by Kearny** [comment]
Hey, thanks for the answer. I use doctrine with symfony but I can't see a doctrine/common in my composer.json. Is it this that I should change ?

`"doctrine/orm" : "^2.5"`

**Comment by Ocramius** [comment]
Just run a `composer update` and check your `composer.lock` for the installed `doctrine/common` version.

**Comment by Kearny** [comment]
I don't have anything updated for now, based on composer.lock I stick with "version": "v2.6.2".

I guess I just should wait.

**Comment by Ocramius** [comment]
Please do check the version you have installed, before reporting an issue ;-)

**Comment by Kearny** [comment]
Yes sorry.
