### ISSUE TITLE
Multiple tables on single entity (unique schema)

### ISSUE THREAD

**Issue by PillowPillow** [doctrine/doctrine2#6240]
Hello. We have an issue with our current doctrine setup. 
We would like to map a unique entity to multiple generated tables. 
I know that's not a standard usage but our constraint necessitate some optimizations and we need to split our tables by account.

We tried to update the repository table name by calling *setPrimaryTable* on the classMetadata property before each queries. However, it seems that we can't update the table after the first execution.

Working example :
````php
<?php
	//...
	$em = $this->getDoctrine()->getManager();
	$productM = $em->getRepository('DataBundle:Product');
	$classMetaData = $em->getClassMetadata('DataBundle:Product');
	
	
	$classMetaData->setPrimaryTable(['name' => 'product_copy']);
	$productM->findAll(); // select * from product_copy;
````

Problematic case :
````php
<?php
	//...
	$em = $this->getDoctrine()->getManager();
	$productM = $em->getRepository('DataBundle:Product');
	$classMetaData = $em->getClassMetadata('DataBundle:Product');
	
	$productM->findAll(); // select * from product;
	
	$classMetaData->setPrimaryTable(['name' => 'product_copy']);
	$productM->findAll(); // select * from product;
````
 Is there a proper solution to handle this case to be compliant with the doctrine philosophy? Is it at least possible?
 
 We saw an other "solution" digging into the Gidmo code, using the AST walkers but that can only handle the select cases, not the other CRUD operations.
 
````php
<?php
	class FromWalker extends SqlWalker {
	
		public function walkRangeVariableDeclaration($rangeVariableDeclaration)
		{
			$sql = parent::walkRangeVariableDeclaration($rangeVariableDeclaration);
			// replace the table name by a custom one
			return $sql;
		}
		
	}
```` 

Thanks for your attention.
Best regards

Nicolas

**Comment by Ocramius** [comment]
Modifying metadata at runtime is simply not supported, as the metadata details may be cached within the various ORM components.

You may, though, create multiple metadata instances, each for a different class/interface, and then make the reflection details point at a single class.

This will still fail to correctly work with managed instances though.

Closing as `can't fix`.

**Comment by bululu** [comment]
Hello,
     I had the same problem and i was able to workaround it with $em->clear();
     to clear the cache so the table would refresh

//...
	$em = $this->getDoctrine()->getManager();
	$productM = $em->getRepository('DataBundle:Product');
	$classMetaData = $em->getClassMetadata('DataBundle:Product');
	
	$productM->findAll(); // select * from product;
	
        $em->clear();

	$classMetaData->setPrimaryTable(['name' => 'product_copy']);
	$productM->findAll(); // select * from product;
