### ISSUE TITLE
Doctrine\ORM\Version::VERSION not up to date

### ISSUE THREAD

**Issue by PetrHeinz** [doctrine/doctrine2#6246]
I have noticed that constant Doctrine\ORM\Version::VERSION is not up to date in v2.5.5 and v2.5.6

See:
https://github.com/doctrine/doctrine2/blob/v2.5.4/lib/Doctrine/ORM/Version.php - correct 2.5.4
https://github.com/doctrine/doctrine2/blob/v2.5.5/lib/Doctrine/ORM/Version.php - incorrect 2.5.5-DEV
https://github.com/doctrine/doctrine2/blob/v2.5.6/lib/Doctrine/ORM/Version.php - incorrect 2.5.5-DEV

**Comment by Ocramius** [comment]
Urgh, I hate that silly version thing. I never remember to update it :-\

**Comment by PetrHeinz** [comment]
I would recommend automation of releasing new versions (for commiting two changes of Version.php and creating a tag) - that would solve it in the future.

**Comment by Ocramius** [comment]
We have that, I just didn't use it because of the huge amount of
repositories I work with, so I forget which ones have automation, and which
don't.

**Comment by Majkl578** [comment]
Closing this, as of Doctrine 3.0 there won't be any Version class needing manual updates.
