### ISSUE TITLE
Problem on doctrine website projects documentations

### ISSUE THREAD

**Issue by murilolobato** [doctrine/doctrine2#6258]
The documentation link for MongoDB abstraction layer is broken at http://www.doctrine-project.org/projects.html. And if I click on the title, and go to http://www.doctrine-project.org/projects/mongodb.html, the links there are broken too, there, all "Lateste version" links are broken.

**Comment by Ocramius** [comment]
Please report on https://github.com/doctrine/doctrine-website-sphinx
