### ISSUE TITLE
Add column to table without related property on its entity

### ISSUE THREAD

**Issue by steffenbrem** [doctrine/doctrine2#6266]
I wanted to implement multi tenancy for an existing project using Doctrine without changing their metadata files or subclassing their models to add an extra field. Would it be easy/possible to extend Doctrine in a way that it adds a specific column to the table of an entity without having a property on that entity that represents that column? This way the models stay intact and you could use a SQL filter to filter down on that column to achieve multi tenancy.

Are there people who implemented something similar or have tips on how this can be done with Doctrine ORM?

**Comment by Ocramius** [comment]
You'd just add a column in a manual migration: this is not something that can be done in the metadata API, since every field expects a matching reflection field.

**Comment by steffenbrem** [comment]
Thanks for the fast response, wow! 😄

**Comment by lcobucci** [comment]
@steffenbrem sometime ago I've created something based on `Doctrine\DBAL\Sharding\PoolingShardConnection` and a custom `Doctrine\DBAL\Sharding\ShardChoser\ShardChoser` to implement multitenancy but I had a different schema for each tenant (with the same mapping) and everything worked just fine.
