### ISSUE TITLE
Why method chaining is allowed by default in generated entities?

### ISSUE THREAD

**Issue by Kwadz** [doctrine/doctrine2#6275]
Is there a good reason to allow method chaining by default in generated entities?

```
class Product
{
    public function setName($name)
    {
        $this->name = $name;

        return $this; // Why this is by default?
    }
}
```

I think this feature should only be present when it is needed. I there is no reason to have it by default, I'd like to make it configurable. What do you think about that?

**Comment by Ocramius** [comment]
@Kwadz I would rather just drop it: it's a bad practice, but it seems like many rely on it (yes, we tried dropping it before).

Closing here - possible change for 3.x, but we'd split the entity generator out anyway, so I'm closing this one as `won't fix`

**Comment by Kwadz** [comment]
Sorry, I just realized: "but it seems like many rely on it (yes, we tried dropping it before)."
