### ISSUE TITLE
Provide a way to extend EntityGenerator

### ISSUE THREAD

**Issue by ywg** [doctrine/doctrine2#6277]
There is currently no way to extend the `EntityGenerator`.
You can make custom types but the stubs methods will always be generic getters and setters. Which can, with certain types be really innapropriate.

It would be really useful to have a way to interact with `EntityGenerator->generateEntityStubMethods`.

**Comment by Ocramius** [comment]
Not gonna happen: there are other components for this (such as https://github.com/zendframework/zend-code), as well as IDEs that can generate methods for you.

The code generator in doctrine ORM is just meant to get you kickstarted once at the beginning of a project, and then you are supposed to edit the code yourself, manually.

Ref: https://github.com/symfony/symfony-docs/issues/5070
Ref: https://github.com/doctrine/DoctrineBundle/issues/412
Ref: https://github.com/doctrine/doctrine2/pull/5733

**Comment by ywg** [comment]
Ok, I get it. But still if I can't customize the stubs for my custom type is there a way to prevent the incorrect getters/setters being generated ?

Let's take a practical example, if I got a `Set` datatype I'll want `add`, `remove` and `get` methods. But the entity generator will keep on adding a `set` method. What's the best practice here ?

**Comment by Ocramius** [comment]
> What's the best practice here ?

@ywg grepping the `set` methods, then removing manually
