### ISSUE TITLE
UniqueEntity break introduced

### ISSUE THREAD

**Issue by trsteel88** [doctrine/doctrine2#6283]
I can't create an issue on Doctrine Bridge so I'm doing it here.

There was recently a change to the UniqueEntity Validator: https://github.com/symfony/doctrine-bridge/commit/40941a3b7d6d6158ade63bc37bb09f260bd2202f

This has changed it's behaviour. It used to "return" if any value was null. Now, it continues if a value is null.

This means that if you have 1 null value and 1 non null value, it only matches the criteria to the single value.

I think this is quite a big BC break. Would love to get some feedback on this change.

**Comment by Ocramius** [comment]
Please report it on https://github.com/symfony/symfony: we have no control over it here.
