### ISSUE TITLE
partials and shared objects between queries

### ISSUE THREAD

**Issue by eventhorizonpl** [doctrine/doctrine2#6289]
Hi,

I don't know if it's a bug or optimization feature.

Lets say that I've got a Post entity and User entity.

In one query I do something like this:

`
    ->select('partial p.{id,slug,title}, partial pu.{id,username}')
    ->from('Post', 'p')
    ->leftJoin('p.user', 'pu')
`

and I've got another query in the same action and I do something like this

`
    ->select('partial u.{id,username,slug}')
    ->from('User', 'u')
`

The problem is that in result list of second query I'm getting a 1 user without slug. This object looks like it was taken from Post query.

I guess that it's caused by some internal doctrine optimization. But I don't know if it's a feature or a bug.

Without using partial queries you will not notice any problem.

Best regards,
Michal

**Comment by Ocramius** [comment]
This is normal, since the partial objects that were hydrated stay in memory after the first query, and won't be re-hydrated.

I suggest taking an alternate approach: https://ocramius.github.io/blog/doctrine-orm-optimization-hydration/

Closing as `invalid`

**Comment by eventhorizonpl** [comment]
ok, thanks!
