### ISSUE TITLE
Doctrine Criteria does not support for limiting based on the relation of a relation

### ISSUE THREAD

**Issue by trickeyone** [doctrine/doctrine2#6290]
When attempting to use the `Collection#matching` that limits the returned value based on the relation of the entity's relation, you get an error saying that the field couldn't be found. It looks like this is because the field parser doesn't support the dot-separated field syntax.

```
Undefined property: SecondEntity::$creator.manager
```

```php
class FirstEntity
{
    /**
     * @var Collection
     *
     * @ORM\OneToMany(targetEntity="SecondEntity", mappedBy="parent")
     */
    protected $children;

    public function getByCreatorManager(User $manager)
    {
        $criteria = Criteria::create();
        $expr = Criteria::expr();
        $criteria->where(
            $expr->eq('creator.manager', $manager)
        );

        return $this->children->matching($criteria)->toArray();
    }
}

class SecondEntity
{
    /**
     * @var FirstEntity
     *
     * @ORM\ManyToOne(targetEntity="FirstEntity", inversedBy="children")
     */
    protected $parent;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="User")
     */
    protected $creator;
}

class User
{
    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="user", inversedBy="team")
     */
    protected $manager;

    /**
     * @var User[]
     *
     * @ORM\OneToMany(targetEntity="User", mappedBy="manager")
     */
    protected $team;
}
```

**Comment by Ocramius** [comment]
The syntax `foo.bar.baz` only applies to embeddable fields at the time of this writing: not to associations.

Closing as `invalid`

**Comment by trickeyone** [comment]
@Ocramius I don't understand how this is invalid? When using the Collections Criteria, there are definitely times when you would want to filter based of a child object or value. If I'm needing to filter child objects that only have a specific relation (i.e. in my above example, a specific manager), why wouldn't you want to support the dot-notation of `creator.manager`?

**Comment by Ocramius** [comment]
> filter based of a child object or value

That would be an embeddable: associations are not sub-fields of an entity.

The `foo.bar.baz.tab.taz.tar.war.wab.dab` association traversal approach *can* be implemented, but it is a massive piece of work (multi-month, considering all scenarios that could go wrong), since the persisters are unable to traverse associations, and filtering is done on persisters at the moment.

**Comment by georgemilojevic** [comment]
Im running this same issue today, this is still not supported?
