### ISSUE TITLE
Escape colons in DoctrineNamespaceCacheKey[<cache namespace>]

### ISSUE THREAD

**Issue by Dadibom** [doctrine/doctrine2#6296]
Using the redis cache driver, I want to be able to use doctrine: as my namespace, as this will turn doctrine into a folder thus keeping redis browsable. However, as the colon is not escaped, this key stops working:  DoctrineNamespaceCacheKey[doctrine:]

**Comment by Ocramius** [comment]
@Dadibom can you report this on doctrine/cache please?

Also, not sure if this shouldn't simply be reported as redis issue...
