### ISSUE TITLE
UuidGenerator::generate takes redundant $entity parameter

### ISSUE THREAD

**Issue by aalaap** [doctrine/doctrine2#6298]
Why does the `UuidGenerator::generate` method require the `EntityManager` as well as the entity if it simply uses the former to generate the code on the database server? The actual entity isn't used at all, so, not only is it wasteful, it may also permeate a false sense of relevancy to the uniqueness.

    public function generate(EntityManager $em, $entity)
    {
        $conn = $em->getConnection();
        $sql = 'SELECT ' . $conn->getDatabasePlatform()->getGuidExpression();
        return $conn->query($sql)->fetchColumn(0);
    }

Source: https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Id/UuidGenerator.php

To avoid any confusion or assumption, I suggest the removal of the `$entity` argument.

**Comment by lcobucci** [comment]
@aalaap that parameter is there to respect the [`AbstractIdGenerator`](https://github.com/doctrine/doctrine2/blob/e4704beaf9fad5a521fe7592dec382ae209b3cc1/lib/Doctrine/ORM/Id/AbstractIdGenerator.php#L33) interface and it's used on different id generators (like the [`AssignedGenerator`](https://github.com/doctrine/doctrine2/blob/e4704beaf9fad5a521fe7592dec382ae209b3cc1/lib/Doctrine/ORM/Id/AssignedGenerator.php)) so we can't remove it.

**Comment by lcobucci** [comment]
Closing as `won't fix`.

**Comment by aalaap** [comment]
@lcobucci Fair enough. Can it be made an optional argument?

**Comment by aalaap** [comment]
@lcobucci Fair enough.
