### ISSUE TITLE
Non-deterministic tests

### ISSUE THREAD

**Issue by mbeccati** [doctrine/doctrine2#6302]
I've had a CI failure last night in master, running on PHP 7.1 + Postgres:

```
24-Feb-2017 04:37:47 	1) Doctrine\Tests\ORM\Functional\ManyToManyBasicAssociationTest::testMatchingWithLimitAndOffset
24-Feb-2017 04:37:47 	Failed asserting that two strings are equal.
24-Feb-2017 04:37:47 	--- Expected
24-Feb-2017 04:37:47 	+++ Actual
24-Feb-2017 04:37:47 	@@ @@
24-Feb-2017 04:37:47 	-'Developers_1'
24-Feb-2017 04:37:47 	+'Developers_0'
```

Re-running the build brought it back to green, so I've had a quick look at the test itself.

It seems that this test (and possibly others?) depends on the order in which rows are returned to be predetermined and stable, which we all know is not guaranteed by the SQL standard, without an explicit `ORDER BY`.

**Comment by guilhermeblanco** [comment]
@mbeccati I'm working purely on `develop` branch (read as Doctrine 3) and I've fixed this issue in https://github.com/doctrine/doctrine2/commit/680e0eb973c91be95a016ba6d8b90f085fc46af3
