### ISSUE TITLE
ObjectHydrator and ArrayHydrator fail on multiple inheritance with empty simpleArray

### ISSUE THREAD

**Issue by fullbl** [doctrine/doctrine2#6303]
Hi,

I have an entity named A, which is extended on multi table inheritance by B and C.

Both have a property called $user, which is a simple string on B and a simple_array on C.

If I load the object by query builder with the repository of A and get an object of type B, I could get an empty array, even if I'm expecting a string. This is because AbstractHydrator is setting first non null value from all the joined tabled after translating it into php. Null is converted into array in SimpleArrayType convertToPHPValue function.

An easy solution could be to check for the value to be null BEFORE assigning it, as for #5989

**Comment by dengm129** [comment]
#5989

**Comment by Ocramius** [comment]
Handled in #6304
