### ISSUE TITLE
DQL expression comparison casts boolean to integer

### ISSUE THREAD

**Issue by podorozhny** [doctrine/doctrine2#6306]
Hello.

```php
$queryBuilder = $this->createQueryBuilder('o');

$expr = $queryBuilder->expr();

echo $queryBuilder->where($expr->eq('o.approved', true))->getQuery()->getDQL();
```

This code will throw an exception if database is postgtres.

```
An exception occurred while executing 'SELECT ... WHERE b0_.approved = 1'

SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: boolean = integer
LINE 1: ... WHERE b0_.approved = 1 ...
^
HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

If I change `$expr->eq('o.approved', true)` with `$expr->in('o.approved', [true])` - it will work, because of [this](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Query/Expr.php#L448).

Maybe this place should also use _quoteLiteral function? 
https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Query/Expr/Comparison.php#L98

**Comment by Ocramius** [comment]
As you can see from the method signatures, left and right side of the operator constructor must be strings.

Closing as `invalid`
