### ISSUE TITLE
@ORM\GeneratedValue(strategy="UUID") documentation should suggest column types

### ISSUE THREAD

**Issue by tarjei** [doctrine/doctrine2#6312]
Hi, it seems to me that the correct columntype for this datatype in mysql is 
`@ORM\Column(type="string", length="36")` but if that is the case for all databases I do not know. Would it be possible to document what the correct datatype should be?

I also found this interesting post[1] that suggests storing uuids as a binary field. Have you considered supporting that?

1. http://mysqlserverteam.com/storing-uuid-values-in-mysql-tables/ 

Kind regards,
Tarjei

**Comment by Ocramius** [comment]
`CHAR(36)` is mostly inefficient, since a UUID is just a 128 bit integer. Please refer to https://github.com/ramsey/uuid-doctrine for further guidance

**Comment by tarjei** [comment]
Ok, so the UUID method in native doctrine should not be used?

Regards

**Comment by Ocramius** [comment]
The generator strategy can be used, but it makes little sense, since UUIDs are designed so that they can be generated before DB persistence

**Comment by wuethrich44** [comment]
@Ocramius I would like to change my primary keys to UUID but I'm not quite sure which doctrine type I should use. [This library](https://github.com/ramsey/uuid-doctrine) stores the UUID as well as `CHAR(36)` so I'm a bit confused.

Could you provide an example how you use UUID as primary keys in your entities?

**Comment by AlessandroMinoccheri** [comment]
Last time @wuethrich44 I have used this code:

```
/**
     * @var \Ramsey\Uuid\Uuid
     *
     * @ORM\Id
     * @ORM\Column(name="id", type="guid")
     * @ORM\GeneratedValue(strategy="UUID")
     * @Expose()
     */
    private $id;
```

**Comment by Ocramius** [comment]
You'd probably use the UUIDBinaryType
