### ISSUE TITLE
EntityGenerator do not see columnPrefix mapping

### ISSUE THREAD

**Issue by gander** [doctrine/doctrine2#6314]
### doctrine/orm v2.5.6

Problem is here (wrong variable name):
http://www.doctrine-project.org/api/orm/2.5/source-class-Doctrine.ORM.Tools.EntityGenerator.html#1731

```php
    protected function generateEmbeddedPropertyDocBlock(array $embeddedClass)
    {
// ...
            if (isset($fieldMapping['columnPrefix'])) {
                $embedded[] = 'columnPrefix=' . var_export($embeddedClass['columnPrefix'], true);
            }
// ...
    }
```

Inside method do not exist variable `$fieldMapping`, should be used `$embeddedClass` instead.

**Comment by Majkl578** [comment]
EntityGenerator is going to be removed in Doctrine 3.0, sorry for no response and thanks for reporting.
