### ISSUE TITLE
set "on update cascade" in xml do noting  

### ISSUE THREAD

**Issue by zhang122562** [doctrine/doctrine2#6332]
I set "ON UPSATE CASCADE" in the xml,but it dosen't wok! 
 The "ON DELETE SET NULL" work well. 
 I just follow the demo in the tutorial.
 The following is my code in xml.
`<many-to-one target-entity="User" field="engineer" inversed-by="assignedBugs">
 <join-column name="engineer_id" referenced-column-name="id" on-delete="SET NULL" on- update="CASCADE"/>
</many-to-one>`

**Comment by Ocramius** [comment]
`on-update` is no longer supported and will not be re-introduced in the future.
