### ISSUE TITLE
orphanRemoval doesn't work on OneToOne bidirectional association

### ISSUE THREAD

**Issue by yurybykov** [doctrine/doctrine2#6334]

**Comment by szymach** [comment]
Hello,
Can you share some code? Maybe you simply have wrong entity mapping.

**Comment by Ocramius** [comment]
Closing as `incomplete` due to missing tests.

**Comment by yurybykov** [comment]
UPD.
It was my mistake of understanding how OneToOne relation work. I tryed remove relation from inverse side. For everybody with same please read the doc at http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/unitofwork-associations.html
