### ISSUE TITLE
[RFE] More verbose QueryException

### ISSUE THREAD

**Issue by gnat42** [doctrine/doctrine2#6336]
First off - I don't mind submitting a PR for this. Just checking if there's a chance it could be accepted if I did the work.

I have a situation where more than likely an issue somewhere other than doctrine is causing a tooFewParameters query exception. The issue is that this only occurs in production and is more than likely a specific browser + symfony form bug. The problem is, I get the error message talking about too few parameters, but without any additional context. 

I'd like to propose that the QueryException include either the DQL or SQL query that has issue as context. This would help me track down the source of the issue.

Thoughts?

**Comment by Ocramius** [comment]
There's already an open PR about this somewhere: need to dig that one up
first.

**Comment by gnat42** [comment]
I see. I searched the open issues but didn't find anything - though I didn't search the PRs.. I'll do that now.
