### ISSUE TITLE
Can I filter by Doctrine Discriminator Map column?

### ISSUE THREAD

**Issue by DavidGarciaCat** [doctrine/doctrine2#6337]
Hello,

I am getting an error when I try to run a `SELECT` query `WHEN` the column used is the `Doctrine Discriminator Map`. I think this error is caused because my `Entity` has not a `@ORM\Column` annotation due the Discriminator Map is defined with the `Entity` instead of the properly.

Is there a way to run a `SELECT` adding a `WHERE` clause that is targeting a Discriminator Map column?

Thanks,

**Comment by Majkl578** [comment]
Yes, using the `INSTANCE OF` operator, see [an example in documentation](http://doctrine-orm.readthedocs.io/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html#dql-select-examples).
But this is an issue tracker to report bugs and so, not a forum to ask questions. 😕

**Comment by DavidGarciaCat** [comment]
Hi @Majkl578 - Thanks for the quick response, and sorry for the inconvenience
