### ISSUE TITLE
Database columns that start with a number create invalid entities

### ISSUE THREAD

**Issue by VersatilityWerks** [doctrine/doctrine2#6342]
When using symfony's doctrine command line command to generate entities from an existing database, if a column starts with a number, it creates a property in the entity that starts with that number which is invalid PHP and causes errors. I suggest either a) throwing an error during generation for the user to change the column name or b) converting that number to the word (2 = two).

**Comment by szymach** [comment]
Entity generator is being removed (check an issue I [submitted](https://github.com/doctrine/doctrine2/issues/6418)), so I doubt this will be resolved.

**Comment by Ocramius** [comment]
There will always be impedance between what DBs support in identifier names, and what the ORM can pick for names.

This is one of those scenarios where you will simply need to manually define an entity, as any decision taken by the ORM may just lead to field naming collisions (replacing spaces with `_`, prefixing columns starting with invalid names, etc).

Closing as `won't fix`. Thanks @szymach for linking #6418
