### ISSUE TITLE
Is it possible to detect exactly which database constraint was violated during exception handling?

### ISSUE THREAD

**Issue by BabakMN** [doctrine/doctrine2#6347]
I'd like to know if it's possible to detect which constraint was violated during a constraint violation exception?

Or alternatively, which column(s) was involved.

The use case is for when multiple unique constraints are placed on a table and then an insert fails because of a violation.

For complete error handling you would need to know exactly which constraint was involved in the violation.

This can be done by doing a string search on the text of the error message however I'm wondering if a better solution is available.

**Comment by Ocramius** [comment]
The error message already provides this information: this is not something
that the ORM should do, but rather your rdbms.
