### ISSUE TITLE
Custom sql and migrations

### ISSUE THREAD

**Issue by TheSaturn** [doctrine/doctrine2#6348]
Hello!
How to execute custom sql code when applying migrations? I see only shema instance and no db connection.
I want to add index with its length

**Comment by Ocramius** [comment]
`$this->addSql()`

**Comment by TheSaturn** [comment]
Not working
I tried:
`$table->addUniqueIndex(['`principaluri`(90)', '`uri`(90)'], 'addressbook_index');`
Output: '`principaluri\`(90)'

**Comment by Ocramius** [comment]
As I just said, use `addSql` ;-)

**Comment by TheSaturn** [comment]
ah. Project used own implementation of migrations. That is why I don't have function addSql
