### ISSUE TITLE
Floats in $orgValue are strings in UnitOfWork::computeChangeSet

### ISSUE THREAD

**Issue by curiosity26** [doctrine/doctrine2#6366]
The `$actualValue` held in the entity is a valid float/double but the value held in the `$orgValue` is a string.

![image](https://cloud.githubusercontent.com/assets/4050934/24373203/99222dd6-12fe-11e7-9a8e-8eeaf8ac8d0f.png)

Causes this assertion to fail in UnitOfWork on line 668:

```PHP
                // skip if value haven't changed
                if ($orgValue === $actualValue) {
                    continue;
                }
```

Here's the field referenced in the entity:

```PHP
/**
     * @var float
     * @ORM\Column(type="decimal", scale=2, precision=16, options={"default"=0})
     * @JMS\Type("double")
     * @JMS\Expose()
     */
    protected $totalDisposableIncome = 0.00;
```

The Database is PostgreSQL 9.6.

**Comment by lcobucci** [comment]
@curiosity26 `float` and `decimal` are different types for storages and DBAL. If you want to have a float and deal with floating-point precision you should use `@ORM\Column(type="float", ...)`.

More info: http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#decimal-types

**Comment by lcobucci** [comment]
Closing as `invalid` since it's a configuration issue.
