### ISSUE TITLE
generate:entities does not translate index associations

### ISSUE THREAD

**Issue by canaaerus** [doctrine/doctrine2#6375]
[Working with indexed associations](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/working-with-indexed-associations.html) explains the usage of the `indexBy` keyword.
For it to work, the insertion method needs to look as follows:

    public function addStock(Stock $stock)
    {
        $this->stocks[$stock->getSymbol()] = $stock;
    }

Now when executing `php bin/console doctrine:generate:entities`, the generated code is the same, as if no `indexBy` clause was used:

    public function addStock(Stock $stock)
    {
        $this->stocks[] = $stock;
    }

Furthermore the `getStock` method is not generated at all.

I am using the current doctrine/orm v2.5.6

**Comment by Ocramius** [comment]
Meh, this is a detail that is up to your domain, not to the ORM... It also assumes that you are re-generating all entities, and that the getter exists on the associated entity.
