### ISSUE TITLE
Get entity change sets - do not change internal unit of work state

### ISSUE THREAD

**Issue by vasekjares** [doctrine/doctrine2#6385]
It would be great to have a method to get entity change set without changing internal unit of work state:

`$user = $em->find(User::class, 1);`
`$user->setAge(10);`
`$user->setName('John');`
`$em->getUnitOfWork()->recomputeChangeSets();`
`$logger->log(User::class, 1, $em->getUnitOfWork()->getEntityChangeSet($user));`
`$em->flush();`

Code above works great, but issue is that it changes internal state of UoW. (updates original snapshots). So if I change code to:

`$user = $em->find(User::class, 1);`
`$user->setAge(10);`
`$user->setName('John');`
`$em->getUnitOfWork()->recomputeChangeSets();`
`$logger->log(User::class, 1, $em->getUnitOfWork()->getEntityChangeSet($user));`
`$user->setEnabled(true); //previous value was false`
`$em->flush();`

Only "enabled" property is persisted. Changes of age and name are forgotten (unless I recompute change sets manually again)

It would be great to have method which just calculates change sets and returns them (with not internal changes to UoW)

**Comment by Ocramius** [comment]
This would require substantial effort in the UoW re-design. I had started such a project in https://github.com/Ocramius/ChangeSet, but never got around to continue work on it, sorry.

**Comment by vasekjares** [comment]
Thats great idea to generalize change set calculations! Anyway this behaviour changed in one of latest releases, I will try to find out which one was that.

**Comment by vasekjares** [comment]
It can make a lot of troubles to other doctrine based projects

**Comment by Ocramius** [comment]
> Anyway this behaviour changed in one of the latest releases, I will try to find out which one was that.

Please report a separate issue for that. Meanwhile, I'm closing this one as `won't fix`, since it's mostly asking for a second unit of work, which is out of scope for most of the ORM operations.

That's a completely separate project, IMO, and if someone wants to take over, follow the link above.
