### ISSUE TITLE
OneToMany dependent property is being persisted in the reverse order

### ISSUE THREAD

**Issue by chris-fa** [doctrine/doctrine2#6391]
I have an entity `Order` and `Item` as a `1:N`  (this is an example, I know in reality it'd be N:M).

I'm using the following method to add items to an order:

```php
// Order.php
/* (...doctrine stuff...,  cascade={"persist"}) */
protected $items;

public function addItem(Item $item) {
    $item->setOrder($this);
    $this->items[] = $item;
}

// Item.php
public function setOrder(Order $order) {
   $this->order = $order;
}

// Somewhere else in the code
$order->addItem($item1);
$order->addItem($item2);
$order->addItem($item3);

$em->persist($order);
$em->flush();
```

The problem is the items are being persisted in the order `$item3, $item2, $item1` rather than `1,2,3`.

How can I solve this?

**Comment by Ocramius** [comment]
You can't: there is no guarantee on persistence order here, as long as it
is valid. If you need an incremental sequence, then add one to your code,
and do not rely on auto-incremental identifiers here.

**Comment by Ocramius** [comment]
Closing as `can't fix`, `invalid`
