### ISSUE TITLE
Doctrine Proxies Hydration not works in local

### ISSUE THREAD

**Issue by christiancannata** [doctrine/doctrine2#6398]
Hi,
I don't know why this code return null suddenly, in production I have not this problem, only in local:

`$companyName= $application->getVacancy()->getCompany()->getName() //return null in local but in production works`

now in local I have changed with:
`$vacancy=$application->getVacancy();
$vacancy = $this->em->getRepository('<repo>')->find($vacancy->getId());
$company=$vacancy->getCompany()->getId();
$company = $this->em->getRepository('<repo>')->find($company->getId()); //return company object
$companyName=$company->getName() //now it works!
`
Why it doen't work suddenly in local? I remember that the code on top works correctly and I have not problem in production.

**Comment by theofidry** [comment]
@christiancannata could you help by providing more info? There's no way we can tell the issue just from that :/

For example:

- which version you are using
- how is your environment defined
- what DB are you using
- did you check your DB?

**Comment by Ocramius** [comment]
Closing as `incomplete`.

As much as I'd like digging into this, information is missing, and no debugging has been attempted.
Please try reproducing the results locally with a test case or similar, then report again should this be a failure on the ORM side.
