### ISSUE TITLE
PDO::__construct(): Server sent charset (255) unknown to the client. Please, report to the developers

### ISSUE THREAD

**Issue by Napas** [doctrine/doctrine2#6401]
MySQL version: `8.0.1`
PHP version: `7.1.3`
Driver: `pdo_mysql`
charset: `UTF8`
dsn: `"mysql:host=mysql;dbname=pets;charset=UTF8;"`

Error message: `PDO::__construct(): Server sent charset (255) unknown to the client. Please, report to the developers`

Any ideas?

**Comment by Ocramius** [comment]
Closing, not an ORM bug. Please report this on https://bugs.php.net/ after some research.
