### ISSUE TITLE
Custom entity generator templates

### ISSUE THREAD

**Issue by szymach** [doctrine/doctrine2#6418]
Hello,
I have a question - would you consider adding an option to provide custom class templates for the entity generator?

**Comment by Ocramius** [comment]
We are actually in the process of dropping the entity generator, which
should be moved either out of the organisation or maintained by third
parties as a separate optional component. We definitely won't add features
to it.

**Comment by szymach** [comment]
OK ;_;

**Comment by Ocramius** [comment]
@szymach to give you some more background,  the entity generator is **AB**used 90% of the time to generate entities over and over, making the usage of the ORM moot. At that point, it's better to use a record abstraction library, instead of a data mapper.

**Comment by szymach** [comment]
I simply like writing YAML mapping and then generate classes out of them. I had to always adjust the generated files, so I was wondering if it could be modified. I can do without, anyway, was just curious.

**Comment by Ocramius** [comment]
@szymach the process should be the opposite: mappings to be written *AFTER* the entities were *DESIGNED*.

Entity generation is overall an anti-pattern that leads to extremely anemic domain-related code.

The idea of the generator has always been to allow quick migration from legacy/existing databases: nothing more than that.

**Comment by szymach** [comment]
OK I understand.
