### ISSUE TITLE
SchemaTool: Allow overriding table definitions

### ISSUE THREAD

**Issue by lxg** [doctrine/doctrine2#6419]
When working with entity interfaces and the target entity resolver, it would be nice to be able to override entity classes.

I understand that an entity superseding a different entity is currently not supported by Doctrine. However, if we could just address the “duplicate target tables” problem, it would be fine and at the same time offer a huge benefit.

As we know, when two entity classes have the same class name, the SchemaTool will throw an exception complaining that the table exists. Of course, I could give the new entity implementation a different table name (`@Table(name='Foobar')`), but this would leave me with a dead table in my database for the actually unused entity class.

My idea would be to allow overriding table definitions in SchemaTool while deriving the table name from the entity definition. Instead of creating tables one by one, I would collect all table names in an array, where the table names are the keys. When all names are registered, the tables would be created. Duplicate table names would no longer occur.

```
@@ -152,6 +152,7 @@ class SchemaTool
 
         $addedFks = array();
         $blacklistedFks = array();
+        $tableNames = array();
 
         foreach ($classes as $class) {
             /** @var \Doctrine\ORM\Mapping\ClassMetadata $class */
@@ -159,7 +160,12 @@ class SchemaTool
                 continue;
             }
 
-            $table = $schema->createTable($this->quoteStrategy->getTableName($class, $this->platform));
+            $tableNames[$this->quoteStrategy->getTableName($class, $this->platform)] = $class;
+        }
+
+        foreach ($tableNames as $name => $class)
+        {
+            $table = $schema->createTable($name);
 
             if ($class->isInheritanceTypeSingleTable()) {
                 $this->gatherColumns($class, $table);
```

This works for me, although of course I have the very narrow perspective of my own projects.

EDIT: However, one problem remains: When inheriting the definitions of an entity in another entity, the associations are lost while the scalar fields are copied. :/

**Comment by Ocramius** [comment]
I don't understand this issue: what do you mean by "overriding entity classes"?

**Comment by lxg** [comment]
Consider a Symfony project where a bundle ships a set of entity interfaces. The implementations (i.e. the actual entity classes) are shipped by the bundle, too. The interfaces are mapped to the implementations through ResolveTargetEntityListener. So far, so good.

Those entities are usable on their own – they should not be MappedSuperclasses. But it should also be possible to create a derived entity class and map an interface to that class. But this is currently not possible for two reasons:

1. SchemaTool will choke on trying to create the same table for two separate entity classes,
2. Entity classes derived from other entities do not inherit their associations for some reasons.

The underlying problem here is that Doctrine registers entities only by a directory path; while there is AFAIK no way to register/unregister a single entity class.

**Comment by Ocramius** [comment]
This is extremely specific, and it should be handled either by:

 * overriding mappings completely (write your own definition for the shipped entity)
 * copying the entity into your domain (actually the safest solution)
 * creating event listeners that change the metadata on load, and do the very incredibly specific thing you want doctrine to be doing

Replacing entire entities has more side-effects and pitfalls than the advantages of this approach, and allowing this, while possible, is mostly wrong.
If you want to use an entity from `Bundle X`, and import it as `MySpecialEntity`, then just copy it from the bundle and re-map it. Having two named references to the same underlying entity object (or conditionally different) is a mess for you and for us.

This certainly shouldn't be supported explicitly by the ORM.

**Comment by alcaeus** [comment]
I agree with @Ocramius here. To offer an example of how it can be done, look at [Sylius](https://github.com/sylius/sylius).

They provide default implementations of entities which can be overridden if you need to make changes. To aid with this, their default entities are all mapped as `MappedSuperclass`. Then, there's an event subscriber that converts the default entities from mapped superclasses to entities if they haven't been overridden (see [ORMMappedSuperClassSubscriber](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/EventListener/ORMMappedSuperClassSubscriber.php)). This may or may not work for every project, but that's exactly why this shouldn't be in ORM.

**Comment by lxg** [comment]
@Ocramius although I don’t think that you really understood the use case, I agree that this may be too specific and to error-prone to be implement in Doctrine itself. I’m closing this issue.

@alcaeus Thanks for the pointer to Sylius, their approach looks promising.

**Comment by lxg** [comment]
@Ocramius Thanks for your explainations. Although I don’t think that you really understood the use case, I agree that this may be too specific and to error-prone to be implement in Doctrine itself. I’m closing this issue.

@alcaeus Thanks for the pointer to Sylius, their approach looks promising.
