### ISSUE TITLE
Change repository model for 3.0

### ISSUE THREAD

**Issue by Koc** [doctrine/doctrine2#6420]
Have you considered switching from multi-repositories to one monolith repo + git subtree split (like in Symfony) for 3.0? https://www.tomasvotruba.cz/blog/2017/01/31/how-monolithic-repository-in-open-source-saved-my-laziness/

**Comment by Ocramius** [comment]
@Koc we had a single repository, but it was actually more trouble for us than anything else, and the stability constraints of the different repositories are different.

@beberlei has an entire talk about it at https://qafoo.com/talks/15_08_froscon_monorepos.pdf
