### ISSUE TITLE
Compile Error - Proxy not compatible with entity class on PHP 7.1

### ISSUE THREAD

**Issue by ktrzos** [doctrine/doctrine2#6421]
>   [Symfony\Component\Debug\Exception\FatalErrorException]                                                                            
  Compile Error: Declaration of Proxies\__CG__\Project\UserBundle\Entity\Role::__construct($initializer = NULL, $cloner = NULL) must be compatible with Project\LocaleBundle\Locale\EntityExt\LocalesInterface::__construct(?Project\LocaleBundle\Locale\EntityExt\Locales $locale = NULL)  

Proxy:

```php
<?php

namespace Proxies\__CG__\Project\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Role extends \Project\UserBundle\Entity\Role implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }


//  [...]
}
```

Entity:

```php
/**
 * @ORM\Entity
 * @ORM\Table(name="users_roles")
 */
class Role extends EntityWithLocales implements RoleInterface
{
//  [...]

    /**
     * Role constructor.
     *
     * @param Locales|null $locale
     */
    public function __construct(Locales $locale = null)
    {
        $this->users   = new Collections\ArrayCollection();
        $this->locales = new Collections\ArrayCollection();

        parent::__construct($locale ?? new RoleLocale());
    }
//  [...]
}
```

Above occurs when I'm using Doctrine Fixtures and method `getReference()`. Everything is okay (no errors like above) when I just traverse trough the project pages or do not use above method in Fixtures.

I got similar problem in other case:
https://stackoverflow.com/questions/43521985/symfony-3-doctrine-proxy-error-after-entity-magic-method-change-with-php-7-t

PHP 7.1 here.

**Comment by Ocramius** [comment]
What's your `doctrine/common` version? Please upgrade to latest.

**Comment by ktrzos** [comment]
@Ocramius 

Part of my composer.json file:

```
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "doctrine/orm": "^2.5",
```

In my composer.lock there is `v2.7.2` of `doctrine/common`.

**Comment by Ocramius** [comment]
Wait, your `LocalesInterface#__construct()` is interfaced? I'm afraid there's nothing we can do for this right now. The only solution will be to switch to ProxyManager at some point (https://github.com/doctrine/doctrine2/pull/1241).

This is a limitation of the library that can't be fixed in 2.x

**Comment by ktrzos** [comment]
So I presume, that this also applies for all magic methods?
In [THIS](https://stackoverflow.com/questions/43521985/symfony-3-doctrine-proxy-error-after-entity-magic-method-change-with-php-7-t) example I tried to define PHP7 types in `__get`.

**Comment by Ocramius** [comment]
@ktrzos magic methods are usually fixed/predefined, so even if you interface them, usually everything is fine. 

In general, #1241 fixes all these concerns, but it won't be ready for a while...

**Comment by Ocramius** [comment]
@ktrzos for the magic method definitions, https://github.com/Ocramius/ProxyManager/pull/350 is relevant.

**Comment by Majkl578** [comment]
Doctrine 3.0 will be switching to ProxyManager so this issue could be closed.
