### ISSUE TITLE
HHVM support

### ISSUE THREAD

**Issue by lcobucci** [doctrine/doctrine2#6424]
We're struggling to support HHVM properly on our projects:

- https://github.com/doctrine/doctrine2/pull/1149, https://github.com/doctrine/doctrine2/pull/6286, https://github.com/doctrine/doctrine2/pull/6288
- https://github.com/doctrine/dbal/pull/2550
- https://github.com/doctrine/common/pull/785
- https://github.com/doctrine/collections/pull/104
- https://github.com/doctrine/collections/pull/110
- https://github.com/doctrine/cache/pull/203

So it's time to rethink if we still want to guarantee HHVM support, the reasons are:

1. Even though we managed to run HHVM 3.15 on travis it was impossible to install the dependencies (we should give it a try on [HHVM 3.18](https://docs.travis-ci.com/user/languages/php/#HHVM-versions-on-Trusty) however I'm not sure how often HHVM users upgrade stuff)
2. We want to use new PHP features but HHVM is not being able to keep up the pace updates and they still have a list of [PHP 5 and 7 incompatibilities](https://github.com/facebook/hhvm/issues)

**Comment by Ocramius** [comment]
Overall, I feel bad for dropping HHVM support, but lack of latest versions by default on CI, as well as incompatibilities with PHP 5, 7, 7.1 are starting to become an issue. Community usage is also very low, since PHP 7 made most interactions as fast as on HHVM.

We need to drop it though, as we need to bump the minimum version to PHP 7.1 anyway.

**Comment by alcaeus** [comment]
Pinging @Seldaek - he did publish some HHVM stats from Packagist a while back and mentioned in IRC he'd post some current numbers soon. Quote:
> last I checked it was less hhvm than php5.3 IIRC

**Comment by Majkl578** [comment]
Here: https://github.com/composer/composer/issues/6230#issuecomment-284426560
> last time I checked there was less HHVM than PHP 5.3 users of composer, about 0.4% or smth IIRC, so not really worth the trouble I would say.

-----

Maybe someone from Facebook could share their vision regarding compatibility, but it's been years and even many PHP 5 bugs are still unfixed, not even taking 7.0/7.1 into consideration. There is still ~250 open issues marked _PHP 5 incompatibility_ and another ~75 marked _PHP 7 incompatibility_. There are also 43 issues marked _wontfix_ which are _PHP 5 incomatiblities_.
I initially sent [some bugfixes](https://github.com/facebook/hhvm/commits/master?author=majkl578) and another [bunch of issues](https://github.com/facebook/hhvm/issues?q=is%3Aissue+author%3AMajkl578+is%3Aclosed) to HHVM, but now I just have a feeling that HHVM has its own path with PHP compatibility not being a priority.

Btw Symfony still seems to actively ship HHVM support, it'd be interesting to know their point of view, regarding HHVM + Symfony 4.

**Comment by theofidry** [comment]
@Majkl578 Symfony doesn't provide any guarantee for HHVM, but accept fixes for it. Cf. https://github.com/symfony/symfony/issues/18922

**Comment by Majkl578** [comment]
@theofidry: Thanks for the link; Symfony doesn't have HHVM in allowed failures so they apparently still do care enough. :)

**Comment by lcobucci** [comment]
@Ocramius since we had a [blogpost about the HHVM roadmap](http://www.doctrine-project.org/2013/12/23/our-hhvm-roadmap.html) should we write something again?

**Comment by Seldaek** [comment]
Here you go https://seld.be/notes/php-versions-stats-2017-1-edition

**Comment by KennedyTedesco** [comment]
Laravel doesn't follow HHVM since: https://github.com/laravel/framework/pull/14530

**Comment by szymach** [comment]
It could be dropped for version 3 and reintroduced if there really will be a demand. Something I highly doubt, of course.

I believe this project does not need things dragging it down and that what HHVM support currently is - a minor feature requiring a lot of work, postponing important features.

**Comment by Majkl578** [comment]
I actually don't think this would have to wait for next major. Similarly to the PHP versions which are dropped/bumped in minor versions too...

**Comment by Ocramius** [comment]
Handled in #6507 (for ORM)
