### ISSUE TITLE
Cannot establish connection (PDO, mysqli)

### ISSUE THREAD

**Issue by DestructionOfPlanetJupiter** [doctrine/doctrine2#6427]
I am currently digging through the documentation here:
http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html

From my composer.json
 "doctrine/orm": "v2.5.6",
 "doctrine/dbal": "v2.5.12",

PHP version is 5.6.30 with a current xampp on a linux machine.

Bootstrap and cli-config taken from the homepage and completed with my data.

$dbParams = array(
    'driver'   => 'mysqli',
    'user'     => 'root',
    'password' => '',
    'host'     => 'localhost',
    'dbname'   => 'dbName',
);

with pdo (extension exists according to phpInfo()):
[Doctrine\DBAL\Exception\DriverException]              
  An exception occured in driver: could not find driver  
                                                                                                
  [Doctrine\DBAL\Driver\PDOException]  
  could not find driver                
                                       
  [PDOException]         
  could not find driver  
                         
or with mysqli
PHP Fatal error:  Call to undefined function Doctrine\DBAL\Driver\Mysqli\mysqli_init() in /opt/lampp/htdocs/w/workspace/blablabla/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php on line 64
PHP Stack trace:
PHP   1. {main}() /opt/lampp/htdocs/w/workspace/blablabla/vendor/doctrine/orm/bin/doctrine:0
PHP   2. include() /opt/lampp/htdocs/w/workspace/blablabla/vendor/doctrine/orm/bin/doctrine:4
PHP   3. Doctrine\ORM\Tools\Console\ConsoleRunner::run() /opt/lampp/htdocs/w/workspace/blablabla/vendor/doctrine/orm/bin/doctrine.php:66
PHP   4. Symfony\Component\Console\Application->run() /opt/lampp/htdocs/w/workspace/blablabla/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/ConsoleRunner.php:60
PHP   5. Symfony\Component\Console\Application->doRun() /opt/lampp/htdocs/w/workspace/blablabla/vendor/symfony/console/Application.php:124
PHP   6. Symfony\Component\Console\Application->doRunCommand() /opt/lampp/htdocs/w/workspace/blablabla/vendor/symfony/console/Application.php:200
PHP   7. Symfony\Component\Console\Command\Command->run() /opt/lampp/htdocs/w/workspace/blablabla/vendor/symfony/console/Application.php:835
PHP   8. Doctrine\ORM\Tools\Console\Command\SchemaTool\AbstractCommand->execute() /opt/lampp/htdocs/w/workspace/blablabla/vendor/symfony/console/Command/Command.php:264
PHP   9. Doctrine\ORM\Tools\SchemaTool->__construct() /opt/lampp/htdocs/w/workspace/blablabla/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/AbstractCommand.php:63
PHP  10. Doctrine\DBAL\Connection->getDatabasePlatform() /opt/lampp/htdocs/w/workspace/blablabla/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:74
PHP  11. Doctrine\DBAL\Connection->detectDatabasePlatform() /opt/lampp/htdocs/w/workspace/blablabla/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:328
PHP  12. Doctrine\DBAL\Connection->getDatabasePlatformVersion() /opt/lampp/htdocs/w/workspace/blablabla/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:389
PHP  13. Doctrine\DBAL\Connection->connect() /opt/lampp/htdocs/w/workspace/blablabla/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:429
PHP  14. Doctrine\DBAL\Driver\Mysqli\Driver->connect() /opt/lampp/htdocs/w/workspace/blablabla/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:360
PHP  15. Doctrine\DBAL\Driver\Mysqli\MysqliConnection->__construct() /opt/lampp/htdocs/w/workspace/blablabla/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/Driver.php:36

##################

Now what?

**Comment by lemartin** [comment]
It looks like you are missing the required PHP extensions for mysqli and pdo, see: http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#driver

**Comment by DestructionOfPlanetJupiter** [comment]
Nope they are there. That is the puzzling part of it all. I use the extensions in other scripts/classes and they work with a charm. Yet doctrine refuses to do so. That is why I even go to length and set up a new xampp version today, because I had the same suspicion; that it what a driver issue. I even checked via phpInfo() ... all necessary drivers are there.

**Comment by Ocramius** [comment]
Make sure there are no differences between your php-cli and the web-facing
one. You can add `"ext-mysqli": "*"` to your `composer.json` as well, and
run a `composer update`

**Comment by DestructionOfPlanetJupiter** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-mysqli * is missing from your system. Install or enable PHP's mysqli extension.

**Comment by lcobucci** [comment]
@DestructionOfPlanetJupiter `mysqli` and `pdo_mysql` are two different extensions. Are you sure you don't want to use `pdo_mysql`?

**Comment by DestructionOfPlanetJupiter** [comment]
pdo_mysql and mysql do not work either way ... and I do not know why.

**Comment by lcobucci** [comment]
Can you run `php -i | grep mysql` on your CLI?

You must see things like "MysqlI Support => enabled", "mysqlnd => enabled" or "PDO Driver for MySQL => enabled". If you don't it means that your PHP installation is not correct and you should review it.

**Comment by lcobucci** [comment]
Closing the issue as `invalid` since it's related to the environment rather than DBAL/ORM.
