### ISSUE TITLE
date interval

### ISSUE THREAD

**Issue by licarigianluca** [doctrine/doctrine2#6428]
When I run this command 
php bin/console doctrine:schema:validate

 the system print this message

Unknown database type interval day(3) to second(6) requested, Doctrine\DBAL  
  \Platforms\OraclePlatform may not support it.

I have an Oracle database schema that i cannot change. I need to import some tables into entities but the command fails and print the message above. There is a way to ignore that check? I used the filter argument but the check fails everytime.

Thanks

**Comment by Ocramius** [comment]
>  There is a way to ignore that check?

You can map the type as a DBAL type manually. See http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/custom-mapping-types.html

You want to do `$platform->registerDoctrineTypeMapping(...)`
