### ISSUE TITLE
Doctrine can't read annotation

### ISSUE THREAD

**Issue by mikaelit** [doctrine/doctrine2#6430]
I described my issue hear: http://stackoverflow.com/questions/43794498/symfony-how-to-solve-the-doctrine-issue-of-the-missing-annotations/43825184#43825184
I think it's locale problem, but I can't find solution.

**Comment by Ocramius** [comment]
Closing: this is not a doctrine issue, but rather a configuration issue in a complex symfony setup. It needs to be isolated before we can look at it, sorry.
