### ISSUE TITLE
Coalesce in JoinColumn

### ISSUE THREAD

**Issue by Michal-sk** [doctrine/doctrine2#6432]
Do we at this moment have a way to use coalesce in the join column for relations?

For example a car has many parts. A car can have a relation to itself. I want to make demo cars, which refer to another car (the original car). But i do not want to copy all the parts of the car. So i would like to join using Coalesce. `join part.car_id = coalesce(car.car_id, car.id)` So we would use the coalesce to first check if the car as a car_id, referring to the original car, if so, its a demo car and we use the car id of the original car. If not than use the car's own id. For example when calling the original car.

If this would not be possible using the Annotations. Would it be possible in a different way?

**Comment by Michal-sk** [comment]
Maybe have DemoCar, and use the Overwrite annotation to overwrite the join column? Guess that would be the best way to do this.

**Comment by Ocramius** [comment]
@Michal-sk I don't understand the scenario: what would this look like, in entities?
Also, maybe I'm naive, but I've never seen a coalesce join. The ORM always builds associations towards identifiers only, so `car_id`, being a foreign key, and not an identifier, is an invalid referenced column.

**Comment by Michal-sk** [comment]
> The ORM always builds associations towards identifiers only, so car_id, being a foreign key, and not an identifier, is an invalid referenced column.

Got it.
