### ISSUE TITLE
Why is sql conversion not allowed for identifiers?

### ISSUE THREAD

**Issue by soyuka** [doctrine/doctrine2#6435]
Hi,

This might be an edge case, though I'd like to ask why is sql conversion not allowed for identifiers?

I understand that it's not possible for generated identifiers to be altered (makes no sense) but if the identifier is not auto generated is there a reason to deny sql conversion?

Would a patch be accepted were we add a check on `usesIdGenerator`? Therefore, we could allow the sql conversion even if it's an identifier.

[Origin pull request](https://github.com/doctrine/doctrine2/pull/198) doesn't mention why it has been implemented like this. 
[ref of the code line in ClassMetadataInfo](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php#L1431).

Thanks!

**Comment by Ocramius** [comment]
> why is sql conversion not allowed for identifiers?

It is? Can you make an example?

**Comment by soyuka** [comment]
Yes of course.

Say that you want your entity to have a `DateTime` as identifier. In this case, because doctrine types need the `__toString()` method you have something like this:

```php
<?php

class IdxDateTime extends \DateTime
{
    public function __toString()
    {
        return $this->format(\DateTime::ATOM);
    }

    public static function createFromFormat($format, $time, $object = null)
    {
        $d = \DateTime::createFromFormat($format, $time);

        $t = new self();
        $t->setTimestamp($d->getTimeStamp());

        return $t;
    }
}
```

Then, because of **insert reason there** you want to alter this identifier with SQL, the custom Type will look like this:

```php
<?php

use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\DateTimeType;

class IdxDateTimeType extends DateTimeType
{
    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {
        if (null === $value) {
            return $value;
        }

        return $value->format('Y-m-d H:i:s.u');
    }

    public function convertToDatabaseValueSQL($sqlExpr, AbstractPlatform $platform)
    {
        return "TO_TIMESTAMP($sqlExpr, 'YYYY-MM-DD HH24:MI:SS.FF6')";
    }

    public function canRequireSQLConversion()
    {
        return true;
    }

    public function getName()
    {
        return 'idxdatetime';
    }
}
```

Now, just try to persist an entity that looks like this:
```php
<?php

/**
 * @ORM\Entity
 */
class SomeDateIdentifiedEntity
{
    /**
     * @ORM\Id
     * @ORM\Column(type="idxdatetime", name="id")
     */
    private $id;
}
```

And you'll get:

```
  [Doctrine\ORM\Mapping\MappingException]
  It is not possible to set id field 'id' to type 'idxdatetime' in entity class 'MyClass'. The type 'idxdatetime' requires conversion SQL which is not al
  lowed for identifiers.
```

**Comment by Ocramius** [comment]
Ah, I see the problem. This is because SQL generated by the ORM will just generate a placeholder for identifiers (usually `?`) to bind parameters to it, but it won't concatenate the identifier into the query string.[

**Comment by soyuka** [comment]
Not sure to follow you on this, the following query will work fine:

```sql
INSERT INTO foo (id) VALUES (TO_TIMESTAMP(?, 'YYYY'));
```

Maybe I'm missing something.

**Comment by Ocramius** [comment]
Yes, but doctrine will not do it for simple fetches:

```sql
SELECT * FROM yourTable WHERE id = ?
```

That `?` is hardcoded somewhere, I suppose, and not just in a single ORM component.

**Comment by soyuka** [comment]
According to https://github.com/doctrine/doctrine2/pull/198 there is no conversion on where clauses.

**Comment by soyuka** [comment]
So, I've resolved myself not to do such thing. Indeed, it's bad for performances, even if you can index your identifier column with index functions you should avoid the above :).

I think that if you need to alter the identifier with some SQL, that using an alternative solution is better. For example, use something else as index and put the Type that needs alteration in another field.

Thanks @Ocramius for the quick answers!
