### ISSUE TITLE
Doctrine referenced objects inserting null instead of value

### ISSUE THREAD

**Issue by smilesrg** [doctrine/doctrine2#6437]
Here is a complex case. I have an RabbitMQ consumer, which processes messages using Doctrine2. Here is the steps:

1. Consumer processes messages and saving to database. It saves several entities, using EntityManager:getReference() to set up referenced ids and not to execute redundant queries. For example, set user_id but not to execute "SELECT..." to get User entity from database. EntityManager::clear() is executed after this procedure.
2. Record dissapears from database (I am deleting it manually but other consumer could delete it too).
3. When Consumer tries to save new record to database, exception appears: 
```Error "An exception occurred while executing 'INSERT INTO address_activity (last_send_datetime, last_delivery_datetime, last_read_datetime, last_click_datetime, address_id, user_id) VALUES (?, ?, ?, ?, ?, ?)' with params [null, null, "2017-05-10 15:52:50", "2017-05-10 15:52:50", null, null]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'address_id' cannot be null"```

address_id and user_id are the columns that I am referencing:

```php
$addressReference = $this->entityManager->getReference(Address::class, $object->contactId);
$userReference = $this->entityManager->getReference(User::class, $object->userId);
$addressActivity->setAddress($addressReference);
$addressActivity->setUser($userReference);
```

It is okay that entity is being inserted, but it is not okay that address_id and user_id values are null, while var_dump() showing that they are actually not null:

```php 
var_dump($addressActivity->getAddress()->getId(), $addressActivity->getUser()->getId());
```

**Comment by Ocramius** [comment]
Can you check whether those values are also not `null` when reading via
reflection?

**Comment by smilesrg** [comment]
@Ocramius Not a doctrine bug, closing this issue.

**Comment by avlima** [comment]
Hello @smilesrg , what did you to to fix this

**Comment by gabrielebarchiesi** [comment]
I have experienced same issue, UnitOfWork::executeInserts($class) is called instead of nothing. Only for very particular issues, maybe when repository uses useQueryCache(true) and/or useResultCache(true). I changed some logic and now seems to be ok.

**Comment by smilesrg** [comment]
I guess the problem was that I used different entity managers

**Comment by gianluca78** [comment]
Hey guys, I am experiencing the same problem when trying to import from an old database some data into a new one. I have two connections and for the first 9000 records everything is fine but then a query like this is generated:

'An exception occurred while executing 'INSERT INTO planned_course_module_date (id, module_date, start_time, end_time, planned_course_module_id, classroom_id) VALUES (?, ?, ?, ?, ?, ?)' with params [null, null, null, null]:

Of course, I checked and there is no null data. Do you have any suggestions for me since you guys have solved it? thanks!
