### ISSUE TITLE
Can't Export/Dump Base Data of Single-Table Inheritance Entity

### ISSUE THREAD

**Issue by msypes** [doctrine/doctrine2#6454]
I think this is a bug, but it could be I don't know what I'm doing: 
I have a single-table inheritance table specifying a pair of related entities. There's an abstract class for the base of shared data, discriminator column, and concrete entities extending the base with their unique properties - No problem.
I tried getting an output display of an entity and found that with either `\Doctrine\Common\Util\Debug::export()` or `\Doctrine\Common\Util\Debug::dump()` but the shared data doesn't come through, only what's specific to the child class.

**Comment by Ocramius** [comment]
This should be reported on doctrine/common, as that's where the issue is: https://github.com/doctrine/common/blob/6ecbf690141c581be33415d1c4f08f75c7eed3e0/lib/Doctrine/Common/Util/Debug.php#L94

Also, a test case is needed.

**Comment by msypes** [comment]
Thanks. Will do.

**Comment by Ocramius** [comment]
Linking https://github.com/doctrine/common/issues/795
