### ISSUE TITLE
Getting embeddable should trigger entity initalization

### ISSUE THREAD

**Issue by mkosiedowski** [doctrine/doctrine2#6460]
Getting public embeddables on lazy-loaded entity which is not initialized does not trigger entity initialization.

Common ProxyGenerator in `\Doctrine\Common\Proxy\ProxyGenerator::getLazyLoadedPublicProperties` uses code:
```
if (($class->hasField($name) || $class->hasAssociation($name)) && ! $class->isIdentifier($name)) {
    $properties[$name] = $defaultProperties[$name];
}
```
The interface `\Doctrine\Common\Persistence\Mapping\ClassMetadata` cannot be extended without breaking backward compatibility so ORM has to return `true` for embeddables either in `hasField` or in `hasAssociation`. In my opinion this should be `hasField`

**Comment by Ocramius** [comment]
Handled in #6462
