### ISSUE TITLE
How do I use insert ignore?

### ISSUE THREAD

**Issue by imsheng** [doctrine/doctrine2#6486]
How do I use insert ignore?

**Comment by AlessandroMinoccheri** [comment]
Can you please explain well your problem with a simple example?

**Comment by imsheng** [comment]
I want to insert unique data，the solution now is to query first and then insert.
But (insert ignore) can solve my problem.

`                $xxxxx= $this->em->getRepository('AppBundle:xxxxxx')->findOneBy([
                    'xxxx' => $xxxx,
                    'xxxx' => $xxxxx
                ]);
                if ($xxxxx== null) {
                    $xxxxxxx= new xxxxxxx();
                    $xxxxxxx->setTitle($xxxxxx);
                    $this->em->persist($xxxxxxx);
                    $this->em->flush();
                }`

**Comment by Ocramius** [comment]
@imsheng that is the correct approach: `INSERT IGNORE` is not supported. What you maybe want is `UPSERT` support, but the DBAL does not yet implement this.

[`INSERT IGNORE` is not a standard modifier](http://hermanradtke.com/2009/03/05/crutching-on-mysqls-insert-ignore.html)

**Comment by yasincetintas** [comment]
This problem answer. Symfony >=4.0 and Doctrine >= 2.0

My Entity Uniq Fields **phone** and **channel**

Import this class on your entity class 

    use Doctrine\Persistence\NotifyPropertyChanged;
    use Doctrine\Persistence\PropertyChangedListener;

After implements NotifyPropertyChanged class

    class TblPersonPhonePermission implements NotifyPropertyChanged

After addPropertyChangedListener methods

    public function addPropertyChangedListener(PropertyChangedListener $listener)
    {
        $insertBatch = $listener->getScheduledEntityInsertions();
        foreach ($insertBatch as $entity) {
            if (
                (get_class($entity) === get_class($this)) &&
                $this->getId() !== $entity->getId() &&
                $this->getPhone() === $entity->getPhone() &&
                $this->getChannel() === $entity->getChannel()
            ) {
                $listener->remove($this);
            }
        }
    }

**Comment by Ocramius** [comment]
The ORM does not support `INSERT IGNORE`: you will need to check the data
before calling `flush()`, in your biz domain.

Avoid deferring this responsibility to the ORM: an `INSERT IGNORE` is
inherently incompatible with the ORM design, since it would assume that
some entities get de-duplicated in memory, which is not feasible, within a
valid UnitOfWork.

Marco Pivetta

https://twitter.com/Ocramius

https://ocramius.github.io/

**Comment by yasincetintas** [comment]
> 
True but this code -> https://github.com/doctrine/orm/issues/6486#issuecomment-1103973750

flush method before trigger. This code persist method is also triggered and deletes the duplicate object.

**Comment by Ocramius** [comment]
@yasincetintas the duplicate object remains in memory, and therefore can damage other parts of the application: **do not do this**, the end.
