### ISSUE TITLE
Mysql @ManyToMany useless index

### ISSUE THREAD

**Issue by tmbdrogba** [doctrine/doctrine2#6495]
Let's say I have this basic @ManyToMany relationship:

```
// Entity A
/**
* @ManyToMany(targetEntity="B")
*/
private $b;
```

Doctrine creates a relation table `a_b` with two fields, with a primary key on those two fields. That's the right way.

Things is : it also creates two more indexes, one on each field, for the foreign keys. Why not just one ?

Actually, if my primary key is composite with `A` (as the primary field of the primary key) and `B`, mysql requires only one more index for the foreign key on `B`, **no need for `A`.**

To resume, my table indexes should be :
- primary : A-B
- index : B

with two foreign keys on A and B
But it looks like :
- primary : A-B
- index : B
- **index : A**

with two foreign keys on A and B

**Comment by Ocramius** [comment]
what's the resolution here?

**Comment by tmbdrogba** [comment]
@Ocramius The point is to not create an index for nothing, here the index on `A`, because it's useless

**Comment by Ocramius** [comment]
Ah, I see: please remember to write down your thoughts when you change an issue.

Related: https://github.com/doctrine/dbal/pull/2470
