### ISSUE TITLE
lock table?

### ISSUE THREAD

**Issue by imsheng** [doctrine/doctrine2#6497]
```
$xxxxx= $this->em->getRepository('AppBundle:xxxxxx')->findOneBy([
      'xxxx' => $xxxx,
      'xxxx' => $xxxxx
]);
if ($xxxxx== null) {
    insert .....
}
```

my requirement is that if the result is empty, the data will be inserted and the data will remain unique, but the above method will not work. 
when the amount of access is high and the concurrency is high, return null for many people
causing data to be inserted many times, data cannot be unique, and then error.
I want to use the lock table, but I don't know how

**Comment by Ocramius** [comment]
You want to set your transaction isolation level to `serialized` and then
run the entire operation in a transaction: this will prevent shadow writes
at some write performance cost.
