### ISSUE TITLE
Feature request DQL IN/NOT IT (entity.x, entity.y, entity.z)

### ISSUE THREAD

**Issue by agirot** [doctrine/doctrine2#6520]
Hi, 
What do you think to add IN/NOT IN with field entity (like native mysql/pg) ?

`
SELECT a FROM AppBundle:A a INNER JOIN a.fk_b b WHERE a.c NOT IN (b.x, b.y)
`

Currently the result is a Doctrine\ORM\Query\QueryException :-)

**Comment by Ocramius** [comment]
@agirot you could modify `InParameter` parsing (http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html#literal-values) to support `ArithmeticExpression`

**Comment by lcobucci** [comment]
@Ocramius Isn't that being handled by #6476?

**Comment by Ocramius** [comment]
@lcobucci ah yes, indeed. Still, that PR requires checking, as I have no idea if/how the query parsing would react to that change :-\

**Comment by lcobucci** [comment]
@Ocramius sure thing, I was just referencing 😄
