### ISSUE TITLE
No single column hydration

### ISSUE THREAD

**Issue by MarekKarmelski** [doctrine/doctrine2#6521]
Doctrine don't have single column hydrator that return one dimensional array, doctrine return nested arrays with single column values. Can I create PR with new hydrator?

**Comment by Ocramius** [comment]
@MarekKarmelski is it worth doing that? Usually, `array_map(`reset`, $result)` does that...

**Comment by MarekKarmelski** [comment]
Yeap but in this case You need use php language to do this, I think better will be move this layer upper to db drive? What You think?

**Comment by Ocramius** [comment]
@MarekKarmelski the question is: "is it worth it"?

That single call is not going to be your bottleneck, so my opinion here is that this is not needed at all.

**Comment by MarekKarmelski** [comment]
@Ocramius One line of code less :) If You think that it isn't worth it, You can close this issue :).

**Comment by Ocramius** [comment]
> One line of code less :)

You'd have to write a lot more lines of code that would need maintenance, documentation and BC in the ORM ;-)
