### ISSUE TITLE
Consider PHP 7.2 for ORM.NEXT

### ISSUE THREAD

**Issue by Majkl578** [doctrine/doctrine2#6529]
Primary motivation:
* [**object** typehint](https://wiki.php.net/rfc/object-typehint) 
  * should eliminate lots of mixed types across whole code base
  * greatly improving type safety & avoid potential mixed-related bugs
  * clean-up public API
  * less BC breaks in future versions
* [parameter type widening](https://wiki.php.net/rfc/parameter-no-type-variance)
  * could ease migration
  * mostly theoretical benefitl? (added return types will still break user-land things)

As an example, [here](https://gist.github.com/Majkl578/9eb51ca704091074c603a732f61f5011)'s how EntityManagerInterface would look for 7.2. ☺️ 

PHP 7.2 is due to release before the end of year. There's already _alpha 2_ (without object typehint - should arrive in _alpha 3_ / _beta 1_).

Thoughts?

**Comment by Ocramius** [comment]
I think this is more than feasible, and yes, it would allow us to add type hints to interfaces without breaking existing implementations. We just need to enforce the PHP constraint to be `^7.2` there.

Overall :+1:

**Comment by alcaeus** [comment]
FWIW, ODM ng (the upcoming 2.0 version) will most likely also require PHP 7.2, so we could let this change trickle down to the common libraries as well.

**Comment by Majkl578** [comment]
Initial Doctrine\Common 7.2 (v. 3.x) migration here: https://github.com/doctrine/common/pull/805

**Comment by Majkl578** [comment]
PHP 7.2 is now BETA and Travis added support for it. 🎉

**Comment by eman1986** [comment]
this would be problematic for those who just got PHP 7 support, not everyone is on bleeding edge, just a thought.

**Comment by alcaeus** [comment]
That is ok. If they are not on bleeding edge php, they most likely won’t want to be on bleeding edge ORM either.

**Comment by Ocramius** [comment]
Pretty much what @alcaeus said: if you are developing new software, the target stable version should be the current one. If you are maintaining existing software, you are perfectly ok with using stable dependencies that won't get new shiny features, yet will receive security updates.

**Comment by eman1986** [comment]
True, though some people are stuck on web hosts that restrict their version. My webhost just got me on PHP 7, and they probably won't have 7.1 until next year. I'd love to work with 7.1, but my production environment prevents that unfortunately and I don't feel like babysitting my own server.

**Comment by Ocramius** [comment]
That's perfectly ok, but on the counter side, we aren't babysitting your
hosting provider either

On 15 Aug 2017 7:54 PM, "Ed Lomonaco" <notifications@github.com> wrote:

True, though some people are stuck on web hosts that restrict their
version. My webhost just got me on PHP 7, and they probably won't have 7.1
until next year. I'd love to work with 7.1, but my production environment
prevents that unfortunately and I don't feel like babysitting my own server.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/doctrine/doctrine2/issues/6529#issuecomment-322540095>,
or mute the thread

**Comment by eman1986** [comment]
fair enough, I said my piece :)

**Comment by Majkl578** [comment]
Merged into develop in 9f5fd3713fa0c8f34a47519ea78d2a6337d65a22.
