### ISSUE TITLE
Cannot insert data into table when schema is diferent of standard, but the entity has the schema annotation in @ORM\Table

### ISSUE THREAD

**Issue by vmunizphone2b** [doctrine/doctrine2#6532]
The problem could be simulated when command doctrine:fixture:load is executed, only the entity with standard schema has its data inserted.

```
/**
 * @ORM\Table(name="cnl.city", schema="cnl")
 */
class City extends Localization {
```

It is possible correct the problem, modifying the following code in the file  lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php in line 3180. 

```
public function getQuotedTableName($platform)
    {
        $tablename = isset($this->table['schema']) ? $this->table['schema'] .'.'. $this->table['name'] : $this->table['name'];

        return isset($this->table['quoted']) ? $platform->quoteIdentifier($tablename) : $tablename;
        //OLD RETURN -> return isset($this->table['quoted']) ? $platform->quoteIdentifier($this->table['name']) : $this->table['name'];
    }
```

**Comment by Ocramius** [comment]
> only the entity with standard schema has its data inserted.

Fixtures use the ORM to perform inserts, and that means that if no insert was performed, the entity didn't land in the `UnitOfWork` at all.
It is very likely that you are simply looking at the wrong schema when verifying inserted data.

Also, consider using an `SQLLogger` to check your issue in more detail

Closing here - please report this again once/if you have a reproducible test case.
