### ISSUE TITLE
Patch tag with accumulated bug fixes?

### ISSUE THREAD

**Issue by guiwoda** [doctrine/doctrine2#6537]
I'm again struggling with L2 cache and found that https://github.com/doctrine/doctrine2/pull/1552 is not yet tagged.
Is there any chance to release a patch version that includes fixes so far? I don't really want to depend on `dev-master` for a live project.

Thanks!

**Comment by guiwoda** [comment]
This PR got merged in 2015 BTW :sweat_smile:

**Comment by Majkl578** [comment]
There will be a 2.6 release with these bugfixes, but there are still some tasks for the 2.6 milestone. See https://github.com/doctrine/doctrine2/projects/2.

**Comment by guiwoda** [comment]
@Majkl578 I don't see #1552 in there :sob:

**Comment by Majkl578** [comment]
Don't worry, as long as it's in master and doesn't break BC, it will be there. :)

**Comment by Ocramius** [comment]
Closing as this one was answered by @Majkl578
