### ISSUE TITLE
missing count method in EntityRepository in php 5.4 branch

### ISSUE THREAD

**Issue by gianpaolodn** [doctrine/doctrine2#6541]
I've just installed version 2.5.5-DEV from composer for PHP 5.6 and I was trying to use the count function after getRepository, but after getting this error

The method name must start with either findBy or findOneBy

I investigated and noticed that in this branch the count method is not implemented in the EntityRepository.

How come?

ps: inserting the code 

```
    public function count(array $criteria)
    {
        return $this->_em->getUnitOfWork()->getEntityPersister($this->_entityName)->count($criteria);
    }
```

it just works.

**Comment by lcobucci** [comment]
@gianpaolodn that's a new feature on 2.6 (which is going to be released soon), that's why it's not there.
