### ISSUE TITLE
DiscriminatorMap: getRepository of child class works only with all models in the main model folder

### ISSUE THREAD

**Issue by JasperEm** [doctrine/doctrine2#6543]
### $entityManager()->getRepository(Child::class)->findAll() ###
 works only with all classes in the main model folder. 

## works: ##
Model/Parent.php
Model/ChildA.php
Model/ChildB.php

## not works: ##
Model/Parent.php
Model/Parent/ChildA.php
Model/Parent/ChildB.php

## not works: ##
Model/Parent/Parent.php
Model/Parent/ChildA.php
Model/Parent/ChildB.php

**Comment by Ocramius** [comment]
Closing as `incomplete`: "works" or "doesn't work" require a test case ;-)
