### ISSUE TITLE
Duplicate definition of column amount for Money embedded objects

### ISSUE THREAD

**Issue by mahbubkabir** [doctrine/doctrine2#6544]
I've got a model with multiple Money properties; everything in the model shares a common currency (for example's sake, let's assume an Order model with amount and tax Money properties)

I'm using **moneyphp/money** to store money information and doctrine embeddables to store them. Mapping as below 

        <embedded name="amount" class="Money\Money" use-column-prefix="false" />
        <embedded name="tax" class="Money\Money" use-column-prefix="false" />

And money embeddable as below 

    <embeddable name="Money\Money">
        <field name="amount" type="integer" nullable="true" column="amount" />
        <embedded name="currency" class="Money\Currency" use-column-prefix="false" />
    </embeddable>

This db table already exists on production and cannot be changed. This money lib has two properties amount and currency. So when Doctrine tries to hydrate the embedded objects it complains about duplicate … `Duplicate definition of column 'amount' on entity  in a field or discriminator column mapping.`.

I understand, doctrine is stopping us from redeclaring the same property but Money lib/object will always have the same property(i.e. amount and currency). Is there any way to tell doctrine to reuse the same field name without using prefix?

**Comment by Ocramius** [comment]
`use-column-prefix="false" />`

How is this supposed to work if both imports have no prefix? Of course the columns will collide...

 > Is there any way to tell doctrine to reuse the same field name without using prefix?

No, as this breaks the 1:1 mapping between entities and table definitions. I've seen this break in very unexpected ways in the past too.

 > This db table already exists on production and cannot be changed. 

You can just duplicate the column
