### ISSUE TITLE
Cascade remove with extra lazy doesn’t trigger PostRemove

### ISSUE THREAD

**Issue by aumel** [doctrine/doctrine2#6560]
I encounter a problem with extra lazy and postRemove (`doctrine/orm v2.5.6`)

Here a simple example. When I remove reference from group, the entity reference is removed from database but PostRemove is never called. If I remove the annotation `fetch="EXTRA_LAZY"`, the PostRemove is called. 

Is this the normal behavior? 
Or maybe, am I doing something wrong?

```
class Group
{  
    /**
     * @ORM\OneToMany(targetEntity="GroupReference", mappedBy="group", fetch="EXTRA_LAZY", cascade={"all"}, orphanRemoval=true)
     */
    protected $references;
}
```

```
class GroupReference
{
    /**
     * @ORM\ManyToOne(targetEntity="Group", inversedBy="references")
     * @ORM\JoinColumn(name="group_id", referencedColumnName="id")
     */
    protected $group;
}
```

```
class MyListener
{
    public function postRemove(LifecycleEventArgs $args)
    {
         var_dump('postRemove called');
    }
}
```

```
// PostRemove never called except if I remove annotation extra lazy in the group
$group->removeReference($groupReference);
$this->em->flush();
```

**Comment by Ocramius** [comment]
This is expected behavior, as the removal happens before the `EntityManager#flush()` call, directly in the persister, without any assumption about related objects.

This can't really be fixed for `EXTRA_LAZY`.

Closing as `Can't fix`

**Comment by aumel** [comment]
Thanks for the info!
