### ISSUE TITLE
[BUG] PrePersist + PreUpdate on datetime with sqllite

### ISSUE THREAD

**Issue by PyRowMan** [doctrine/doctrine2#6567]
Hello guys,

I am currently making my tests with a generated sqllite database.

I have a column "updatedAt" with a default at 'current_timestamp' and this function : 

```
    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preSetDefault() {
            $this->updatedAt = new \DateTime();
    }
```

On the dev environement everything is ok, since it is on mysql database.

But on the tests environnement, doctrine is trying to set as well as on the mysql the default to "CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP" 

Which is not possible on SQLite :/

**Comment by Ocramius** [comment]
That has nothing to do with the listener itself: what is the complete
mapping for that column?

**Comment by PyRowMan** [comment]
Hey @Ocramius Thanks for the reply.

I used Timestampable to go over but the mapping was this : 


```
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updatedAt", type="datetime", nullable=false, options={"comment"="date création ou modification de la ligne","default"="CURRENT_TIMESTAMP"})
     */
    private $updatedAt;
```

**Comment by Ocramius** [comment]
CURRENT_TIMESTAMP will be picked as the actual string, not what you think:
since MySQL is a lousy db it didn't fail to create the schema, but SQLite
is much stricter.

Also, default values are not read by the ORM after writes, so avoid them
anyway.

**Comment by PyRowMan** [comment]
What's failing is actually not the default value, it is really the default value created with the prepersist function.

It modifies the default value and set an "ON UPDATE CURRENT_TIMESTAMP" wich is ok for mysql but not with SQLite.

I'm not using this anymore, but since this functionnality is implemented on mysql 5.7, it could create a bug on anteriors versions of it AND on others Databases like SQLite.

**Comment by Ocramius** [comment]
It needs a failing test case: I am 99.9% positive that this has nothing to
do with the listener.

Even then, this mapping information is invalid due to the explanation above.

See also:
 * https://github.com/doctrine/doctrine2/issues/6346
 * https://github.com/doctrine/doctrine2/issues/6383
 * https://github.com/doctrine/dbal/issues/2582

**Comment by PyRowMan** [comment]
Well you should be right because i'm unable to reproduce the bug with the same config today, it must have been cache or something.

I'll let you know if it comes back.


Thank you for the support @Ocramius :)
