### ISSUE TITLE
PostLoad event on fetch joined entities - Lifecycle Callback not firing

### ISSUE THREAD

**Issue by stoccc** [doctrine/doctrine2#6568]
I have a problem with a [Lifecycle Callback of Doctrine ORM](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/events.html#lifecycle-callbacks): the callback is not executed on fetch-joined entities, while it's regularly executed on entities that are lazy-loaded.

Is there a bug in the ObjectHydrator, or it is a lack of documentation about that?

See [this question on stackoverflow](https://stackoverflow.com/questions/45211316/doctrine-postload-lifecycle-callback-not-executed-in-fetchjoin)

**Comment by Ocramius** [comment]
Any load operation should trigger postLoad events, so this is a bug. Can
you submit a test case to be added to our test suite?

**Comment by stoccc** [comment]
I'm not so expert, I hope I did the right thing!

**Comment by Ocramius** [comment]
@stoccc test looks good, thanks!

**Comment by stoccc** [comment]
@Ocramius 
I fixed the patch, and now all tests pass correctly.
I think you should remove Bug label, but you gained a test case :)

The problem was in my application, I was using in PostLoad of the root entity some informations setted in PostLoad of the fetchjoined entities, but certainly no one can guarantee me that one PostLoad is executed before or after some other PostLoad.

I close, thanks for your time.
