### ISSUE TITLE
Data type json doesn't work

### ISSUE THREAD

**Issue by RichardSouta** [doctrine/doctrine2#6571]
Hello,

even though you can find data type json in official documentation  [here](http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#json), it is not supported. I would use deprecated type  json_array insted, but it incorrectly converted to text in Mysql 5.7.18, even though json is native type in Mysql for 2 years already!

**Comment by Ocramius** [comment]
It is in DBAL master only for now.
