### ISSUE TITLE
Append a table prefixer

### ISSUE THREAD

**Issue by dorcyv** [doctrine/doctrine2#6576]
Everything is in the title.
Can we have a table prefixer. For example, I have an entity User. So the generated table is `user`. But in postgres for example, `user` is a reserved name so we can't have a `user` table.
I can of course specify change the table name but is more logical to have a automatic table prefixer for all entity (project prefix for example).

What do you think ?

**Comment by Ocramius** [comment]
see: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/basic-mapping.html#quoting-reserved-words
see: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/limitations-and-known-issues.html#identifier-quoting-and-legacy-databases

Also, what you want to do doesn't need to be in core: you can use a ``` event listener (see http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/events.html#lifecycle-events) to prefix the table name of each entity before the metadata is cached.
