### ISSUE TITLE
Making the QueryBuilder alias optional

### ISSUE THREAD

**Issue by JeroenDeDauw** [doctrine/doctrine2#6582]
A few years ago I made the table name alias in the DBAL QueryBuilder optional: https://www.entropywins.wtf/blog/2014/08/02/optional-table-alias-in-the-doctrine-querybuilder/

Today I was updating some code to use the ORM QueryBuilder instead of the DBAL one and noticed that such an alias is still required there.

Question 1: is it correct that an alias is currently required or is there a way to omit it?

Question 2: if the alias is currently required, would be a PR that makes it optional (like done in DBAL) be welcome?

**Comment by Ocramius** [comment]
The DQL syntax requires a selection root that is assigned an identification
variable ("alias"), so I don't see how removal could be possible

**Comment by JeroenDeDauw** [comment]
The main think I'd like to achieve is being able to do

```php
$queryBuilder->andWhere( 'paymentIntervalInMonths > 0' );
```

like possible in DBAL instead of 

```php
$queryBuilder->andWhere( 'forThisCaseNotUsefullPrefix.paymentIntervalInMonths > 0' );
```

Are you sure this is not possible somehow?

![image](https://user-images.githubusercontent.com/146040/28563342-fe4b5a54-7125-11e7-8cac-b4969e4fa570.png)

**Comment by Ocramius** [comment]
@JeroenDeDauw properties are never floating around on their own, sorry.

This cannot be fixed due to how the DQL language is [designed](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html#ebnf)

Sorry, gotta kill that kitten :-(
