### ISSUE TITLE
Select assocation id using IDENTITY function inline

### ISSUE THREAD

**Issue by rpander93** [doctrine/doctrine2#6583]
Hi,

I'm wondering why it isnt possible to fetch a foreign key inline with the rest of the results when hydrating to an array. Instead, it returns a mixed results as [found here in the docs](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html#pure-and-mixed-results). Would it not be possible to include the desired field along with the rest of the results rather than the current situation? Specifically when hydrating to an array, this shouldn't be a problem I'd think.

**Comment by Ocramius** [comment]
@rpander93 as soon as you have a scalar value added to object values, the result format will change.

If you want, you can try expanding on the expected results, but I don't think this is worth inspecting/improving, as changing the behavior would be a BC break.

Closing as `won't fix`
