### ISSUE TITLE
AnnotationExporter overriding EntityGenerator configuration

### ISSUE THREAD

**Issue by Thiryn** [doctrine/doctrine2#6587]
Hey there,
While generating entities from database, I noticed the generator did not generate the methods. I was wondering why and I found that the AnnotationExporter overrides the EntityGenerator configuration. [AnnotationExporter.php](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Tools/Export/Driver/AnnotationExporter.php) from line 53 to 57. I am just wondering why, and if it was a normal behaviour.

**Comment by Ocramius** [comment]
Referenced lines: https://github.com/doctrine/doctrine2/blob/97914c0f3eb66d169dd1d4f0e96a4fec5e262b12/lib/Doctrine/ORM/Tools/Export/Driver/AnnotationExporter.php#L53-L56

This is intended behavior.

The exporters, generators and so on are intended as a use-once utilities, so overwriting files is not a problem when importing a large legacy schema for the first time.
