### ISSUE TITLE
No matching package found -> instantiator ~1.0.1

### ISSUE THREAD

**Issue by tymon82** [doctrine/doctrine2#6604]
- doctrine/orm v2.5.6 requires doctrine/instantiator ~1.0.1 -> no match
  ing package found.

**Comment by alcaeus** [comment]
You only posted part of the error message. Please post the entire error message from composer as well as your platform information (PHP version)

**Comment by tymon82** [comment]
[Composer\DependencyResolver\SolverProblemsException]
    Problem 1
      - Installation request for doctrine/orm v2.5.* -> satisfiable by doctri
  ne/orm[v2.5.6].
      - doctrine/orm v2.5.6 requires doctrine/instantiator ~1.0.1 -> no match
  ing package found.
    Problem 2
      - doctrine/orm v2.5.6 requires doctrine/instantiator ~1.0.1 -> no match
  ing package found.
      - fess/admin-bundle dev-master requires doctrine/orm v2.5.* -> satisfia
  ble by doctrine/orm[v2.5.6].
      - Installation request for fess/admin-bundle dev-master -> satisfiable
  by fess/admin-bundle[dev-master].
  Potential causes:
   - A typo in the package name
   - The package is not available in a stable-enough version according to you
  r minimum-stability setting
     see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for mor
  e details.
  Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further
  common problems.

PHP 7.1.7 

All subpackages if they need orm got 2.5.* as require

**Comment by alcaeus** [comment]
Could you please run `composer why-not doctrine/instantiator 1.0.1` and post the output here?

**Comment by tymon82** [comment]
$ composer why-not doctrine/instantiator 1.0.1
jms/serializer                dev-master  requires  doctrine/instantiator (^1.0.3)
phpspec/prophecy              dev-master  requires  doctrine/instantiator (^1.0.2)
phpunit/phpunit-mock-objects  3.4.x-dev   requires  doctrine/instantiator (^1.0.2)
doctrine/instantiator         1.0.1       requires  php (~5.3 but 7.1.7 is installed)

**Comment by Ocramius** [comment]
Are you using a composer.lock? 1.0.1 is quite old.

**Comment by tymon82** [comment]
In doctrine composer.json i got:

    "require": {
        "php": ">=5.4",
        "ext-pdo": "*",
        "doctrine/collections": "~1.2",
        "doctrine/dbal": ">=2.5-dev,<2.6-dev",
        "doctrine/instantiator": "~1.0.1",
        "doctrine/common": ">=2.5-dev,<2.8-dev",
        "doctrine/cache": "~1.4",
        "symfony/console": "~2.5|~3.0"
    },

**Comment by tymon82** [comment]
@Ocramius  this version is in json of doctrine: https://github.com/doctrine/doctrine2/blob/2.5/composer.json

So if its so old does need to be upgraded there?

**Comment by tymon82** [comment]
@alcaeus got same error even when deleted .lock file

**Comment by Ocramius** [comment]
That version is basically >=1.0.1,<1.1 in ORM 2.5.

On 4 Aug 2017 2:06 PM, "tymon82" <notifications@github.com> wrote:

@alcaeus <https://github.com/alcaeus> got same error even when deleted
.lock file

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/doctrine/doctrine2/issues/6604#issuecomment-320232446>,
or mute the thread

**Comment by Ocramius** [comment]
@tymon82 what is the resolution here?

**Comment by tymon82** [comment]
Cause of lack of time change in composer to dev-master of doctrine.
