### ISSUE TITLE
Cannot use keywords such as 'order'

### ISSUE THREAD

**Issue by nicolashardy** [doctrine/doctrine2#6605]
Hello

I can't use attributes named with sql key words, like 'order' , 'limit' etc... 
Do you know if there will be an evolution concerning this point in the future ?

edit : just found out an old post where, i'm quoting 'We will change this for Doctrine 3.x, but for 2.x, auto-quoting of identifiers is a no-go, mostly because of case sensitivity issues.'

Is this still in the pipe?

Regards

**Comment by IljaN** [comment]
You can quote reserved keywords like so
```@ORM\Table(name="`order`")```

I would assume that it also works on entity attributes.

**Comment by Ocramius** [comment]
See http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/basic-mapping.html#quoting-reserved-words
