### ISSUE TITLE
STARTS_WITH & ENDS_WITH criteria method

### ISSUE THREAD

**Issue by yalg** [doctrine/doctrine2#6611]
Hi,

I found in master branch new methods startsWith and endsWith, but Doctrine 1.5.6 didn't allows to use it.
https://github.com/doctrine/doctrine2/commit/a557c97a93adc1c7c0232e78290cce842a92a6bd

I think it's not a "new feature", because CONTAINS already exists, and it's just an improvement of CONTAINS.

Is there a reason this feature is not merged into 1.5.6?

**Comment by Ocramius** [comment]
@yalg because it is still a `new feature` for the ORM :-)

Additions to the API are never backported.

**Comment by yalg** [comment]
Ok good reason 😄 
have you an approximal "month" (year?) of release?

**Comment by Ocramius** [comment]
Nope - simply "when we have time"

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/
