### ISSUE TITLE
Documentation should link API

### ISSUE THREAD

**Issue by jkufner** [doctrine/doctrine2#6617]
All mentions of classes and methods in the documentation should link to API documentation.

For example, at http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/query-builder.html the `Doctrine\DBAL\Connection#createQueryBuilder` should link to http://www.doctrine-project.org/api/dbal/2.3/class-Doctrine.DBAL.Connection.html#_createQueryBuilder.

Such links make it much easier to understand and use the documented features in real applications.

**Comment by Ocramius** [comment]
Don't think we'd be able to do that automatically.

Closing here btw, this is a feature that could be built on https://github.com/doctrine/doctrine-website-sphinx

Consider reporting it there if you have a plan on how to implement this. Automation is *required* for that though.

**Comment by Ocramius** [comment]
doc

**Comment by jkufner** [comment]
Doxygen does this automatically, even in Markdown pages.
