### ISSUE TITLE
SINGLE_TABLE Inheritance breaks with optional ManyToOne relationship in subclass

### ISSUE THREAD

**Issue by GDIBass** [doctrine/doctrine2#6622]
When using single table inheritance with an optional ManyToOne relationship the referenced entity is loaded with no data whatsoever.  You have to reload the entity from the database in order to get it to load any of the appropriate data.  Here is a repository link with a working example:

https://bitbucket.org/GDIBass/relationalsingletableinheritancedoctrinebug/overview

**Comment by lcobucci** [comment]
@GDIBass thank you for submitting this issue with that working example but it would be far more helpful if you could send us a PR with a failing test case. This isolates everything and makes it easier to solve the problem.

You can find examples on https://github.com/doctrine/doctrine2/tree/388afb46d0cb3ed0c51332e8df0de9e942c2690b/tests/Doctrine/Tests/ORM/Functional/Ticket.

**Comment by GDIBass** [comment]
@lcobucci Will do.  Should I name mine DDC6622?

**Comment by GDIBass** [comment]
I can't get it to replicate with the tests.  Perhaps it's something with Symfony?  I'll get something on Stack Exchange

**Comment by Ocramius** [comment]
@GDIBass closing here - please re-open once reproduced only with the ORM.

**Comment by Ocramius** [comment]
Check also https://github.com/doctrine/doctrine2/pull/1194 meanwhile
