### ISSUE TITLE
Proxy generation for embedded/transient classes

### ISSUE THREAD

**Issue by bendavies** [doctrine/doctrine2#6625]
Due to https://github.com/doctrine/common/pull/771, proxy generation will now fail if a final class is used as an embedded.

We should skip proxy generation for abstract classes, mapped superclassesses, embeddables.

**Comment by Ocramius** [comment]
The criteria should be to skip generation on any transient/hack type (anything not directly instantiable). The example above is precisely about embeddables, which are perfectly fine to be mapped from `final` classes.

**Comment by Ocramius** [comment]
Handled in #6626
