### ISSUE TITLE
groupby substring doesn't work on SQL Server

### ISSUE THREAD

**Issue by shadiakiki1986** [doctrine/doctrine2#6629]
The following DQL `SELECT SUBSTRING(t.field,1,6) as subField from table GROUP BY subField`
translates to SQL as `SELECT SUBSTRING(t0_.Field,1,6) as sclr_0 from table GROUP BY sclr_0`
but SQL Server does not accept grouping by an alias ([ref](https://stackoverflow.com/a/3841804/4126114))

It would probably work on MySQL for example ([ref](https://stackoverflow.com/a/35596660/4126114))

Repeating the DQL with `GROUP BY SUBSTRING(t.field, 1, 6)` yields a doctrine semantical error

To bypass this, I'm getting the SQL query without the `groupby` operation, then just appending it

```
    $sql = $qb2->getQuery()->getSql();
    $sql .= " group by SUBSTRING(t0_.Field, 1, 6)";

    $connection = $bf->getConnection()->prepare($sql);                         
    // call any "$connection->bindParam" calls here
    $connection->execute();                                                    
    return $connection->fetchAll(\PDO::FETCH_ASSOC);
```

It would be nice if it were supported.

**Comment by Ocramius** [comment]
Given that SQL Server is the only platform that regularly screws up SQL semantics, I think this won't be fixed on our side, as it increases complexity massively just for one quite exotic vendor :-\

**Comment by shadiakiki1986** [comment]
Lol! No problem :+1:
