### ISSUE TITLE
createNativeQuery throws an error 'SQLSTATE[IMSSP]: The active result for the query contains no fields.' when there are no results to return.

### ISSUE THREAD

**Issue by dipens** [doctrine/doctrine2#6631]
I have this following piece of code in Symfony 3.3 Doctrine ORM version 2.5.5 on Ubuntu Ubuntu 16.04.3 LTS running PHP 7.1 with SQL Server 2012 using Microsoft PHP Drivers for SQL Server.
```
$rsm = new ResultSetMapping();
$rsm->addScalarResult('u', 'newPK', 'newPK');
$rsm->addScalarResult('u', 'msg', 'msg');
$query = $em->createNativeQuery('StoredProcedureName @a= :a, @b= :b, @c= :c', $rsm);
$query->setParameter('a', 'a');
$query->setParameter('b', 'b');
$query->setParameter('c', 'c');
$result = $query->getArrayResult();
var_dump($result);
```
Now the tricky part is this stored procedure returns or does not return a record based on the parameters passed. Whenever the stored procedure does not return anything, I get this error:

> SQLSTATE[IMSSP]: The active result for the query contains no fields.

I have already looked into [here](https://stackoverflow.com/questions/16735898/the-active-result-contains-no-fields-using-pdo-with-ms-sql), [here](https://stackoverflow.com/questions/17626897/the-active-result-for-the-query-contains-no-fields), [here](https://stackoverflow.com/questions/37457065/not-receiving-result-from-stored-procedure-mssql-db-using-php), and in issues here too but couldn't find a solution as most of them are related to PHP and not Doctrine. I have already set `SET NOCOUNT ON` in the beginning of the stored procedure.

Is there a workaround for this I have missed somewhere?

**Comment by Ocramius** [comment]
You are already in native SQL world: this is mssql, not something doctrine can fix for you.

**Comment by dipens** [comment]
Okay thank you and I apologize for posting it here then. I just wasn’t sure where the issue was. Will post on ms forums and close this one.
