### ISSUE TITLE
The documentation does not mention the nullable default value for @column

### ISSUE THREAD

**Issue by Kwadz** [doctrine/doctrine2#6632]
The [documentation](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/annotations-reference.html#column) should mention the nullable default value for `@column`. Currently there is only:

> nullable: Determines if NULL values allowed for this column.

**Comment by lcobucci** [comment]
@Kwadz would be lovely if you send us a PR with a suggestion :wink

**Comment by Ocramius** [comment]
Handled in #6636
