### ISSUE TITLE
[Syntax Error] Error: Expected known function, got 'json_contains'

### ISSUE THREAD

**Issue by fmonts** [doctrine/doctrine2#6634]
I can't find any way to use json functions, for example a basic search like this is not possible:

    $queryBuilder->andWhere('json_contains(a.json_field, :some_value)');

I'm using the latest stable versions of all the doctrine packages.

**Comment by Ocramius** [comment]
`json_contains()` is not defined in the ORM: this is something you'd do with either a [custom DQL function](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/dql-user-defined-functions.html) or a lower-level query, just using the DBAL.
