### ISSUE TITLE
cascadeDetach should initialize before unwrap

### ISSUE THREAD

**Issue by connorhu** [doctrine/doctrine2#6637]
If you detach an entity (because of session store or something) with an uninitialized persistent collection association you lost the data because unwrap gives an empty array.

https://github.com/doctrine/doctrine2/blob/ddccd42bb18bc5bd8345fdcf5295e85341ae0c8e/lib/Doctrine/ORM/UnitOfWork.php#L2145-L2148

**Comment by Ocramius** [comment]
Detach operations do not cause initialisation: they are just meant to
remove entities from the active UnitOfWork.

**Comment by connorhu** [comment]
I will create a test repository tonight. My project is a bit difficult.

**Comment by Ocramius** [comment]
Please don't bother with a test repository: we need tests integrated with
the ORM test suite.

**Comment by connorhu** [comment]
If you serialize and unserialize an entity with an uninitialized persistent collection nobody restores the properties of the collection:

PersistentCollection {#4861 ▼
  -snapshot: []
  -owner: null
  -association: null
  -em: null
  -backRefFieldName: null
  -typeClass: null
  -isDirty: false
  #collection: ArrayCollection {#4862 ▼
    -elements: []
  }
  #initialized: false
}

**Comment by Ocramius** [comment]
@connorhu what's the resolution here?

**Comment by connorhu** [comment]
Some rewrite of my code and a workround in UnitOfWork:
https://github.com/connorhu/doctrine2/commit/455c415361a3ab6f1e1fd6bf494cb649fc7e4d1e

I can't reproduce this bug in tests so I will make a proper ORM unit test. If I can create a test I will reopen this issue.

**Comment by bitwombat** [comment]
So you were unable to make an ORM unit test?  Just curious.  The devs would probably appreciate an update too, so they can close this.
