### ISSUE TITLE
Doctrine\Common\Cache\CacheProvider::getNamespaceVersion() could fail in case of corrupted cache entry

### ISSUE THREAD

**Issue by jocel1** [doctrine/doctrine2#6645]
Hi!

I'm hitting an issue with Doctrine\Common\Cache\CacheProvider::getNamespaceVersion() & a redis cache.
It seems at some point the redis cache has been corrupted, and the doFetch() returns a string instead of an int. In this case it throws an exception:

```Return value of Doctrine\Common\Cache\CacheProvider::getNamespaceVersion() must be of the type integer, string returned```

because the function is expected to return an int.
Why not adding an extra conversion like

```php
$this->namespaceVersion = ((int)$this->doFetch($namespaceCacheKey)) ?: 1;
```

?

Thanks!

**Comment by Ocramius** [comment]
If you can add a test case, this can be patched in quite quickly

**Comment by jocel1** [comment]
I've just quickly added a test here: https://github.com/doctrine/doctrine2/pull/6646
I would have prefered in the cache repo, but I haven't figure out yet how to run phpunit from their.

**Comment by lcobucci** [comment]
@jocel1 I've moved your test to doctrine/cache#231 and applied the fix, so I'll close this issue as `invalid` - since it's not related to the ORM. Thanks for your contribution!
