### ISSUE TITLE
Subquery in the SELECT clause with QueryBuilder ?

### ISSUE THREAD

**Issue by sebastiaanviaene** [doctrine/doctrine2#6660]
My question is simple , is it possible to do a subquery in the SELECT with QueryBuilder. I've tried looking this up but have gotten no success yet. Here's the code I have at the moment. : 

`      $qb = $this->getEntityManager()->createQueryBuilder();
        $qb ->select('count(t.id)')
            ->from('AppBundle:Talent','t')
            ->where('t.status = :active')
            ->setParameter('active', 'ACTIVE');
            

        $qb2 = $this->getEntityManager()->createQueryBuilder();
        $qb2 ->select('count(v.id)')
            ->from('AppBundle:Vacancy','v')
            ->where('v.status = :active')
            ->setParameter('active', 'ACTIVE');
            

        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('d')
            ->addSelect($qb->getDQL())
            ->addSelect($qb2->getDQL())
            ->from('dual', 'd');

        $query->getQuery()->getResult();`

But I get the error : 

"[Syntax Error] line 0, col 10: Error: Expected IdentificationVariable | ScalarExpression | AggregateExpression | FunctionDeclaration | PartialObjectExpression | \"(\" Subselect \")\" | CaseExpression, got 'SELECT'"

**Comment by Ocramius** [comment]
This is not supported as per the [EBNF](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html#ebnf)
