### ISSUE TITLE
Entity#parents is not an association with a single join column

### ISSUE THREAD

**Issue by bordeux** [doctrine/doctrine2#6693]
I wrote library to fetch geoNames to database for doctrine. It works fine, but when i want run tests i received this error:

> Doctrine\ORM\Mapping\MappingException: 'Bordeux\Bundle\GeoNameBundle\Entity\GeoName#parents' is not an association with a single join column.

Here is result from travis-ci: https://travis-ci.org/bordeux/geoname-bundle/jobs/270466374

I dont know what that message exactly means, because from my side everything is correct.

This is my definition of paretns field:
<pre code=php>
/**
 * @var Hierarchy[]
 *
 * @ORM\OneToMany(targetEntity="Bordeux\Bundle\GeoNameBundle\Entity\Hierarchy", mappedBy="child")
 */
protected $parents;
</pre>

And that is definition in hierarchy:
<pre>
/**
 * @var GeoName
 *
 * @ORM\ManyToOne(targetEntity="Bordeux\Bundle\GeoNameBundle\Entity\GeoName", inversedBy="parents")
 * @ORM\JoinColumn(name="child_id", referencedColumnName="id", nullable=true, onDelete="CASCADE")
 */
protected $child;
</pre>

Source: https://github.com/bordeux/geoname-bundle/tree/master/Entity

**Comment by Ocramius** [comment]
What's the full exception trace?

**Comment by bordeux** [comment]
<pre>
) Bordeux\Bundle\GeoNameBundle\Tests\Command\ImportCommandTest::testDownload
Doctrine\ORM\Mapping\MappingException: 'Bordeux\Bundle\GeoNameBundle\Entity\GeoName#parents' is not an association with a single join column.
/home/travis/build/bordeux/geoname-bundle/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php:600
/home/travis/build/bordeux/geoname-bundle/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php:2859
/home/travis/build/bordeux/geoname-bundle/Import/GeoNameImport.php:237
/home/travis/build/bordeux/geoname-bundle/Import/GeoNameImport.php:74
/home/travis/build/bordeux/geoname-bundle/Import/GeoNameImport.php:49
/home/travis/build/bordeux/geoname-bundle/vendor/guzzlehttp/promises/src/Promise.php:246
/home/travis/build/bordeux/geoname-bundle/vendor/guzzlehttp/promises/src/Promise.php:223
/home/travis/build/bordeux/geoname-bundle/vendor/guzzlehttp/promises/src/Promise.php:267
/home/travis/build/bordeux/geoname-bundle/vendor/guzzlehttp/promises/src/Promise.php:225
/home/travis/build/bordeux/geoname-bundle/vendor/guzzlehttp/promises/src/Promise.php:62
/home/travis/build/bordeux/geoname-bundle/Command/ImportCommand.php:218
/home/travis/build/bordeux/geoname-bundle/vendor/symfony/console/Command/Command.php:264
/home/travis/build/bordeux/geoname-bundle/Tests/Command/ImportCommandTest.php:40
</pre>

**Comment by Ocramius** [comment]
> `home/travis/build/bordeux/geoname-bundle/Import/GeoNameImport.php:237`

What is this doing?

**Comment by bordeux** [comment]
Yeah, that was my issue... , Thank you

**Comment by Ocramius** [comment]
So? What was it?

**Comment by bordeux** [comment]
I did foult here : 
<pre>

    /**
     * @return string[]
     * @author Chris Bednarczyk <chris@tourradar.com>
     */
    public function getFieldNames()
    {
        $metaData = $this->em->getClassMetadata("BordeuxGeoNameBundle:GeoName");
        $result = [];
        foreach ($metaData->getFieldNames() as $name) {
            $result[$name] = $metaData->getColumnName($name);
        }
        foreach ($metaData->getAssociationNames() as $name) {
                $result[$name] = $metaData->getSingleAssociationJoinColumnName($name);
        }
        return $result;
    }

</pre>

should be  : 
<pre> 

    /**
     * @return string[]
     * @author Chris Bednarczyk <chris@tourradar.com>
     */
    public function getFieldNames()
    {
        $metaData = $this->em->getClassMetadata("BordeuxGeoNameBundle:GeoName");
        $result = [];
        foreach ($metaData->getFieldNames() as $name) {
            $result[$name] = $metaData->getColumnName($name);
        }
        foreach ($metaData->getAssociationNames() as $name) {
            if($metaData->isSingleValuedAssociation($name)){
                $result[$name] = $metaData->getSingleAssociationJoinColumnName($name);
            }
        }
        return $result;
    }

</pre>

**Comment by Ocramius** [comment]
@bordeux thanks for clarifying!
