### ISSUE TITLE
FROM_BASE64 function is undefined

### ISSUE THREAD

**Issue by messam88** [doctrine/doctrine2#6694]
TO_BASE64 mysql function works fine but FROM_BASE64 function is undefined while executing row sql.

**Comment by Ocramius** [comment]
No such function: https://github.com/doctrine/doctrine2/tree/master/lib/Doctrine/ORM/Query/AST/Functions

**Comment by beberlei** [comment]
See the documentation about adding your own functions:

http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html#adding-your-own-functions-to-the-dql-language

Both `TO_BASE64` and `FROM_BASE64` would be custom functions and you need to add them yourself. In your project somebody might already have added just `TO_BASE64`.
