### ISSUE TITLE
OneToOne primary id

### ISSUE THREAD

**Issue by BuzzLeitinho** [doctrine/doctrine2#6697]
Hello
I'm trying to persist an entity to the database, when updating an integer field, but it doesn't do it so.
Before I state the rest, here is the query that doctrine does after persist and flush:
`UPDATE location_data SET sync_status = 0 WHERE id = NULL`

So, the original class has an id, uuid. And the new class uses this id as primary key, too. It is a one to one relation in which they have the same id as uuid

So, here's the original class:

```php
/**
 * @ORM\Entity
 * @ORM\Table(name="location")
 * @Form\Name("location")
 * @Form\Hydrator("Zend\Hydrator\ObjectProperty")
 * @ORM\HasLifecycleCallbacks
 */
class Location
{
    /**
     * @ORM\Id
     * @ORM\Column(type="uuid")
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
     * @Form\Attributes({"type":"hidden"})
     */
    public $id;

   //several stuf in between
    /**
     * @ORM\OneToOne(targetEntity="LocationData", mappedBy="id",  cascade={"persist"})
     */
    public $locationdata;
```

And the new class, that I want to update:

```php
/**
 * @ORM\Entity
 * @ORM\Table(name="location_data")
 */
class LocationData
{
    /**
     * @ORM\Id
     * @ORM\OneToOne(targetEntity="Location")
     * @ORM\JoinColumn(name="id", referencedColumnName="id")
     */
    public $id;

    /**
     * @ORM\Column(type="integer", nullable=true, options={"default": 0})
     */
    public $sync_status = 0;
}
```

And here's the code that persists the entity;

```php
$locationdata = $this->getEntityManager()->getRepository(LocationData::class)->find($data['location']);//data['location'] has a uuid string
if(!$locationdata){
		$locData = new LocationData();
		$location = $this->getEntityManager()->getRepository(Location::class)->find($data['location']);
		$locData->id = $location;
		$location->locationdata = $locData;
}
$locationdata->sync_status = 0;

$this->getEntityManager()->persist($locationdata);
$this->getEntityManager()->flush();
```

So, can anyone explain me why is the update query sending a NULL id?
I'm not sure this is an issue, or a problem with my code, but I need help anyway.

**Comment by Ocramius** [comment]
Can you turn this into a reproducible test scenario in the ORM test suite?

**Comment by vhenzl** [comment]
@BuzzLeitinho There is a typo in your code. You assign new `LocationData` object to `$locData` variable but then you persist `$locationdata`.

**Comment by lcobucci** [comment]
Closing as `invalid` as per @vhenzl's review
