### ISSUE TITLE
setParameter issue when mixing :name and ?0 syntax

### ISSUE THREAD

**Issue by Seb33300** [doctrine/doctrine2#6699]
Example:
```php
$queryBuilder

    ->andWhere("alias.field = :paramname")
    ->setParameter('paramname', $paramval)

    ->andWhere("alias.field = ?0")
    ->setParameter(0, $paramval)

;
```

If I call `getParameters()`, only 1 param is returned.

When executing the query, an exception is thrown:

> Too few parameters: the query defines 2 parameters but you only bound 1

This seems to happen only if the param is named `?0`.
With `?1`, it seems to be ok.

**Comment by beberlei** [comment]
Which version of Doctrine is this? It works on master with the following test-case:

```
<?php

namespace Doctrine\Tests\ORM\Functional\Ticket;

/**
 * @group GH-6699
 */
class GH6699Test extends \Doctrine\Tests\OrmFunctionalTestCase
{
    protected function setUp()
    {
        $this->useModelSet('cms');
        parent::setUp();
    }

    public function testMixedParametersWithZeroNumber()
    {
        $qb = $this->_em->createQueryBuilder()
            ->select('u')
            ->from('Doctrine\Tests\Models\CMS\CmsUser', 'u')
            ->andWhere('u.email = :email')
            ->andWhere('u.name = ?0');
        $query = $qb->getQuery();

        $query->setParameter(0, 0);
        $query->setParameter('email', 'bar');

        $result = $query->getResult();
    }
}
```

I am closing the ticket for now, please re-open if you can make this query fail with your copy of Doctrine and mention the version you are using.

**Comment by Seb33300** [comment]
I am using the latest stable doctrine version.

In order to reproduce the bug, you have to set parameter in the same order as my example.
By calling `$query->setParameter(0, 0);` after `$query->setParameter('email', 'bar');`.

**Comment by Majkl578** [comment]
Thanks for clarification, reopening, failing test here against master: #6705.
