### ISSUE TITLE
The reverse engineering command requires existing entities

### ISSUE THREAD

**Issue by Kwadz** [doctrine/doctrine2#6704]
The [documentation][1] sates that the first step is to create the metadata files:

> <img width="718" alt="screen shot 2017-09-16 at 12 55 10" src="https://user-images.githubusercontent.com/1472599/30511719-71bee4e6-9adf-11e7-98fc-2ec68db385bd.png">

This suggests we can start from scratch, without any existing entities in `AppBundle/Entity`. However with a fresh install of a symfony_demo project, created with `symfony demo`, when we execute the following command:

`php bin/console doctrine:mapping:import --force  AppBundle xml`

we get:

```
Fatal error: Symfony\Component\Debug\DebugClassLoader::loadClass(): Failed opening required 'xxx/symfony_demo/vendor/composer/../../src/AppBundle/Entity/Post.php' (include_path='.:') in xxx/symfony_demo/vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php on line 144
```

[1]: https://symfony.com/doc/current/doctrine/reverse_engineering.html

**Comment by Ocramius** [comment]
Please reproduce this with the plain ORM: with Symfony in the mix, we really can't help you. The specific exception even shows symfony specific details.

Closing here, please reopen once isolated the bug.

**Comment by Kwadz** [comment]
Sorry, wrong place...
