### ISSUE TITLE
convert-mapping with --namespace param doesn't output in correct directory

### ISSUE THREAD

**Issue by PeeHaa** [doctrine/doctrine2#6716]
I am trying to run `convert-mapping` from the database, but the generated files end up in the wrong location because of the namespace parameter.

Path of my project: `/var/www/someprojectname`.
Path I want my entities to end up in: `/var/www/someprojectname/src/Storage/Doctrine/Entity`.
Namespace of the project: `Gitlicious`.
Root of namespace `/var/www/someprojectname/src`.

**Command I run**

    vendor/bin/doctrine orm:convert-mapping --namespace="Gitilicious\\Storage\\Doctrine\\Entity\\" --force  --from-database annotation src/Storage/Doctrine/Entity

**Expected result**

The generated entities end up directly under `/var/www/someprojectname/src/Storage/Doctrine/Entity`.

**Actual result**

The generated entities instead end up under `/var/www/src/someprojectname/Storage/Doctrine/Entity/Gitilicious/Storage/Doctrine/Entity`.

*Note: When I don't pass the `--namespace` parameter the files end up where I expect them (without the namespace obviously).*

There is a (rather big) chance I am doing something stupid, but I don't see it.

**Comment by Ocramius** [comment]
Doctrine doesn't and won't support PSR-4 namespace prefixing: we're the one
of the projects that voted against PSR-4 specifically for the prefixing
quirkyness that requires a lot of additional work in multiple layers.

**Comment by PeeHaa** [comment]
Why are you touching the path at all instead of just dumping the files in the directory I tell to use with the namespace I use?

Where is the extra work? What am I missing?

**Comment by Ocramius** [comment]
The class will be generated with a PSR-0 compliant path structure

**Comment by lcobucci** [comment]
Closing as `Won't Fix` due to @Ocramius comments.
