### ISSUE TITLE
Issue with Reference in Doctrine DataFixtures

### ISSUE THREAD

**Issue by DD-Hussein** [doctrine/doctrine2#6727]
When loading the fixtures and adding the references the `ProxyReferenceRepository.php` on line `90` fails to get the reference due to the fact that the reference array differs from the rest of the generated fixture 
references. see image:
![image](https://user-images.githubusercontent.com/20520577/30815221-ce7f4830-a212-11e7-8d28-19155e6d748b.png)

I believe this is because the datafixture reference creation can't handle an entity that has multiple attributes as a primary key, after adding a simple Uuid and setting that as the lone primary key the issue is 'resolved' and my tests run successfully.

The error stack when unit testing is:

```
Array to string conversion
 /opt/project/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:105
 /opt/project/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2956
 /opt/project/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:488
 /opt/project/var/cache/test/appTestDebugProjectContainer.php:4779
 /opt/project/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/ProxyReferenceRepository.php:95
 /opt/project/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/ProxyReferenceRepository.php:122
 /opt/project/vendor/liip/functional-test-bundle/Test/WebTestCase.php:421
 /opt/project/tests/Name/ApiBundle/Controller/SubjectControllerTest.php:26
```

**Comment by Ocramius** [comment]
Could you add the test that does this to [`doctrine/data-fixtures`](https://github.com/doctrine/data-fixtures)?

**Comment by DD-Hussein** [comment]
@Ocramius 
```
    public function setUp()
    {
        $this->bootKernel();
        $this->fixtures = $this->loadFixtures(
            [
                LevelFixture::class,
                SubjectFixture::class,
                StudentFixture::class,
                StudentSubjectFixture::class
            ]
        )->getReferenceRepository();
    }

    public function test_get_subjects_success()
    {
        /** @var Student $student */
        $student = $this->fixtures->getReference('student-one');


        $data = [
            'student' => $student->getId()
        ];

        $client = static::createClient();

        $client->request('GET', '/v1/subjects/', $data);

        $response = $client->getResponse();

        $this->assertSame(200, $response->getStatusCode());
    }
```

**Comment by DD-Hussein** [comment]
@Ocramius I have diverted the issue by  adding a Uuid, but the error should be reproducable by creating for example; Subject and Student with a many to many relationship, and A StudentSubject entity that exists out of references to those two. I get the feeling that because it solely exists out of references that the code breaks.

**Comment by ostrolucky** [comment]
Given reproducer is incomplete and this is not a proper repository to report this issue. If you still have this issue, please post it to [`doctrine/data-fixtures`](https://github.com/doctrine/data-fixtures) with a proper reproducer. Thank you for understanding!
