### ISSUE TITLE
Partial query ignores where statement if not in select

### ISSUE THREAD

**Issue by escopecz** [doctrine/doctrine2#6730]
Following query examples are output of `getDql()` method with pasted parameters for easier understanding of the problem.

This query does what I'd expect. It returns all company fields:
```
SELECT f FROM Field f INDEX BY f.id WHERE f.object = 'company'
```

However this query returns ALL fields, not only company fields:
```
SELECT f.{id} FROM Field f INDEX BY f.id WHERE f.object = 'company'
```

It took me a while to find out what's going on there. If I specifically list the `object` column in the select clause, the where condition will work again and only company fields will be returned:
```
SELECT f.{id,object} FROM Field f INDEX BY f.id WHERE f.object = 'company'
```

I couldn't find any documentation on this topic nor any reported issue. Why does it work that way? Isn't it a bug?

**Comment by Ocramius** [comment]
@escopecz can you do a `->getSQL()` too?

**Comment by escopecz** [comment]
@Ocramius doesn't seem I can:
```
Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Doctrine\ORM\QueryBuilder::getSql()
```
We're on `"doctrine/orm": "~2.5.4"`

**Comment by Ocramius** [comment]
@ebernhardson you should do `$queryBuilder->getQuery()->getSql()` annd dump that to check if the condition is applied.

**Comment by escopecz** [comment]
Thanks for the guidance. Here is the SQL if I specify the id and object in the select clause which is returning the correct results:
```
SELECT l0_.id AS id_0, l0_.object AS object_1 FROM lead_fields l0_ WHERE l0_.object = ? LIMIT 30 OFFSET 0
```
This is without the object column specified which is returning all fields of all objects:
```
SELECT l0_.id AS id_0 FROM lead_fields l0_ WHERE l0_.object = ? LIMIT 30 OFFSET 0
```

**Comment by Ocramius** [comment]
@escopecz what is the result like, and what did you expect?

**Comment by escopecz** [comment]
Ok, I think it's nota doctrine bug. The entities will return the default value if the column isn't fetched from the database. So it is returning `company` fields, but object is `lead` because that's the default value.

@Ocramius Thanks for helping me realize that!
