### ISSUE TITLE
Unrestricted cli-config.php file location

### ISSUE THREAD

**Issue by kilab** [doctrine/doctrine2#6736]
I can't find any informations about inform CLI where should search cli-config.php file. 

In this moment I've got two options to place this file: `/` project directory or `/config`  directory in root. But what if I want store config file in eg. `/app/config/cli-config.php`?

Is this possible?

**Comment by Ocramius** [comment]
@kilab it will look in your `cwd` (current working directory).

See: https://github.com/doctrine/doctrine2/blob/53245e8a73cb16d5e9ba35ffa5bbb15cc417bb9f/bin/doctrine.php#L35-L44


The docs are indeed a bit confusing about it: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/tools.html#configuration

Could you maybe patch them, once you get it working for your local environment?

**Comment by kilab** [comment]
@Ocramius thanks for the hint! 

If I'll run CLI command in directory where cli-config is storing, everything is fine.

In my case command is:
`/app: ../vendor/bin/doctrine orm:schema-tool:update --force --dump-sql`
