### ISSUE TITLE
Improve MEMBER OF generated SQL for ManyToMany associations

### ISSUE THREAD

**Issue by Xymanek** [doctrine/doctrine2#6741]
Consider the following example:

```php
/**
 * Notification
 *
 * @ORM\Table(name="notifications")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\NotificationRepository")
 */
class Notification
{
    /**
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\User", fetch="EXTRA_LAZY", inversedBy="readNotifications")
     * @ORM\JoinTable(name="read_notifications")
     */
    private $readByUsers;
}

        $sql = $em
            ->createQuery('SELECT notifications.id FROM AppBundle:Notification notifications WHERE :user NOT MEMBER OF notifications.readByUsers')
            ->setParameter('user', $this->getUser())
            ->getSQL();
```

Right now this will result in the following:

```sql
SELECT n0_.id AS id_0 FROM notifications n0_ WHERE NOT EXISTS (SELECT 1 FROM read_notifications r1_ INNER JOIN users u2_ ON r1_.user_id = u2_.id WHERE r1_.notification_id = n0_.id AND u2_.id IN (?))
```

There are two problems:

* Useless join
* `IN (?)` instead of `= ?`

The "offending" code is [here](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Query/SqlWalker.php#L1947-L1979). It seems to allow for different types of mapping (instead of simple one like in my case) but I think it makes sense to make a special case to allow for faster resulting sql

**Comment by Ocramius** [comment]
What would the proper SQL query look like?

What would it look like for a complex condition, such as a JTI/STI?

**Comment by Xymanek** [comment]
> What would the proper SQL query look like?

```sql
SELECT * FROM notifications 
WHERE NOT EXISTS (
  	SELECT * FROM read_notifications WHERE read_notifications.user_id = ? AND read_notifications.notification_id = notifications.id
)
```

> What would it look like for a complex condition, such as a JTI/STI?

Never used them so don't know how they work (probably stay as they are now?)

**Comment by Ocramius** [comment]
Hmm... That `AND u2_.id IN (?)` is simplified to `AND u2_.id = ?` by the SQL optimizer (db-side), so it doesn't look like this is an improvement worth pursuing.

**Comment by Xymanek** [comment]
Is the useless join also negated db-side?

**Comment by Ocramius** [comment]
No, it is not, but you are filtering on `notifications.readByUsers`, which means that both `notifications` and `readByUsers` are needed, as one is the owning side of the association, and the other the actual resultset you want to filter on.

**Comment by lcobucci** [comment]
Closing as `Won't Fix` as per @Ocramius' comments
