### ISSUE TITLE
Type names with backslashes cause infinite upgrades

### ISSUE THREAD

**Issue by greg0ire** [doctrine/doctrine2#6752]
I'm planning ahead and starting to use FQCNs as custom doctrine type `getName` implementation, as well as registering them under that name with `Type::addType`. Sadly, it seems SQL comments with backslashes are somehow not matched with the desired value, and the upgrade command tries to change the type again and again with such queries:

```
ALTER TABLE transactions ALTER territory TYPE VARCHAR(255);
ALTER TABLE transactions ALTER territory DROP DEFAULT;
ALTER TABLE transactions ALTER price_value TYPE JSON;
ALTER TABLE transactions ALTER price_value DROP DEFAULT;
ALTER TABLE basic_metadata ALTER country_of_origin TYPE VARCHAR(255);
ALTER TABLE basic_metadata ALTER country_of_origin DROP DEFAULT;
```

The SQL comment is present, with double backslashes:

```
    Column  |     Type     | Modifiers | Storage | Stats target |                    Description                    
------------+------------------------+-----------+----------+--------------+-------------------------------------------------------------------------------------------
    alid    | character varying(255) | not null | extended |       | (DC2Type:TitlePublisher\\Infrastructure\\Persistence\\Doctrine\\Type\\AssetLogicalIdType)
 content_id | character varying(255) |      | extended |       | (DC2Type:EMA\\MD\\Doctrine\\Type\\SimpleType\\ContentIdType)
 avail_type | character varying(255) | not null | extended |       | (DC2Type:TitlePublisher\\Infrastructure\\Persistence\\Doctrine\\Type\\AvailTypeType)
```

**Comment by lcobucci** [comment]
@greg0ire this seems to be related to https://github.com/doctrine/dbal/pull/2850, apart from the JSON stuff which is probably related to https://github.com/doctrine/dbal/pull/2855.

But regardless of anything is a DBAL issue, can you please close it here and create a new issue there (if it's still happening on the latest DBAL release, sure).

**Comment by greg0ire** [comment]
I'll try to remember to test tomorrow at work :P

**Comment by greg0ire** [comment]
Ok so I still have an issue, but it is different. See https://github.com/doctrine/dbal/issues/2926
