### ISSUE TITLE
Remove auto-selection of Memcache and Redis caching

### ISSUE THREAD

**Issue by zerocrates** [doctrine/doctrine2#6754]
Setup::createConfiguration tries to automatically select the memcache and redis caches if their respective extensions are available. On systems that merely include those extensions but aren't using them, or aren't using them for the app using Doctrine, this causes an error that must be worked around by manually specifying another cache. Systems actually using Memcache or Redis but on different hosts or ports must also manually configure in this case (they of course would have to regardless).

Automatic selection seems appropriate for APC/APCu and Xcache, as merely the extension suffices, but as Memcache and Redis both require a running server to connect to, I think it makes more sense if they're opt-in rather than the current situation where they're opt-out.

**Comment by lcobucci** [comment]
@zerocrates `Setup::createConfiguration()` is a generic way to create an ORM configuration and (IMO) should be used only for setting things up quickly, if you want to define the configuration properly you should create it by yourself (which quite simple to be honest).

If you want to use it you can still specify which cache driver you want to use, so that's already flexible enough IMO.

**Comment by lcobucci** [comment]
Closing as `Won't Fix` as per my comment.

**Comment by duzenko** [comment]
Am I correct that the workaround for this issue is to instantiate `ArrayCache` manually?
```
		$config = Setup::createAnnotationMetadataConfiguration( $entityPaths, $isDevMode, null, new ArrayCache(), false );
```

**Comment by derrabus** [comment]
> Am I correct that the workaround for this issue is to instantiate `ArrayCache` manually?
> 
> ```
> 
> 		$config = Setup::createAnnotationMetadataConfiguration( $entityPaths, $isDevMode, null, new ArrayCache(), false );
> 
> ```

Everything in that line of code is deprecated. 🙈 

Apart from that: yes, if you're not happy with the cache that is selected for you, instantiate your own cache.
