### ISSUE TITLE
Doctrine 2 - Stored procedures MySql

### ISSUE THREAD

**Issue by zbyyna** [doctrine/doctrine2#6763]
Hello,
I apologize for new issue, but I don't know where to ask. I want to write to google group, but it is not possible add to new comment..

I am trying to work with stored procedures in Doctrine 2 in Symfony 3 and I have i problem with fetching data. This is my code in repository:

```php
public function getParentCategoryByTypeId($type_id, LoggerInterface $logger){

 $rsm = new ResultSetMapping;
 $rsm->addEntityResult('AppBundle\Entity\Category', 'c');

 $logger->info('CALL get_category_by_type (type_id) IN()',array('i_type_id' => $type_id));

 $qb = $this->getEntityManager()->createNativeQuery(
 'CALL get_category_by_type ('.':type_id'.')', $rsm
 );
 $qb->setParameters(
 array(
 'type_id' => $type_id
 ));

 $res = $qb->getResult();

 $logger->info('CALL get_category_by_type () OUT()', array('result' => $res));

 return $qb;

}
```

Here is my procedure:

```sql
{
CREATE PROCEDURE get_category_by_type(IN type_id INT)
  BEGIN
    SELECT * FROM category As c WHERE c.parent IN (SELECT ct.category_id FROM category ct WHERE ct.type = type_id);
END;
}

```
Problem is, that $res returns null data. Can I ask for help with work with stored procedure? I would like to call the mysql procedures and fetching data in repository, than transmit whole SQL statement through 
network. This solution is best for performance and organizability SQL code..It is possible working with stored procedures in Doctrine 2?

Thank you for any answer,
Zbyyna

**Comment by lcobucci** [comment]
@zbyyna there are differences between a `FUNCTION` and a `PROCEDURE`, procedures can't return values.

**Comment by lcobucci** [comment]
But maybe you're looking for a `VIEW` instead?

**Comment by lcobucci** [comment]
Closing as `Invalid` since it's not an ORM issue.
