### ISSUE TITLE
STARTS_WITH and ENDS_WITH 

### ISSUE THREAD

**Issue by mgoniwiecha** [doctrine/doctrine2#6769]
Hello,

I want to ask why the entries "Comparison::STARTS_WITH" and "Comparison::ENDS_WITH" in the $comparisonMap of the class "Doctrine\ORM\Persisters\Entity\BasicEntityPersister" are not included in the latest release (v2.5.11)? The changes are already in master and the commit is from April (https://github.com/doctrine/doctrine2/commit/a557c97a93adc1c7c0232e78290cce842a92a6bd#diff-25f5292f65d5536bb733559f15e0d37f).

https://github.com/doctrine/doctrine2/blob/aea970722ef91e7d7b042798371be867a397f7ee/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php#L100

**Comment by alcaeus** [comment]
master is the branch for the upcoming 2.6 version, as indicated by the `branch-alias` in composer. 2.5 will not get the feature as new features are only added in minor releases.

**Comment by mgoniwiecha** [comment]
Thx, for that information. In this repo it is a new feature. But not within the doctrine/collections repo. And that is why i thought that it could be a bug and not a feature. Sorry
