### ISSUE TITLE
= in order by for postgres query

### ISSUE THREAD

**Issue by AntonioCS** [doctrine/doctrine2#6770]
Hey,

I am trying to re-create the following query in doctrine:
```
SELECT 
	r1.resource_id, r1.age_group_id
FROM
	resource_age_groups r1
LEFT JOIN
	age_group e1
ON
	r1.age_group_id = e1.id
WHERE
	r1.age_group_id IN (2,3)	
ORDER BY 
	r1.age_group_id=2 DESC, r1.age_group_id=3 DESC
```

This is the part that is failing in my doctrine code

```
   $qb                    
                    ->addOrderBy($qb->expr()->eq('age_groups.id', 2), 'DESC')
```

I get the following exception: [Syntax Error] line 0, col 338: Error: Expected end of string, got '='

![image](https://user-images.githubusercontent.com/1086401/31502467-0b2fe91a-af65-11e7-817d-fce022084f70.png)

I also tried just adding a string instead of the expression but I got the same error.
Is there any way to bypass this?

**Comment by Ocramius** [comment]
DQL works with entities, not with table names - please check the
http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html

You probably want something like

SELECT
    r1.resource_id, r1.age_group_id, r1.age_group_id = 2 AS sort1,
r1.age_group_id = 3 AS sort2
FROM
    Resource\Age\Groups r1
LEFT JOIN
    r1.group e1
WHERE
    r1.id IN (2,3)
ORDER BY
    sort1 DESC, sort2 DESC

Although I think the equality isn't supported in `SELECT` (would need a
custom DQL function)

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by AntonioCS** [comment]
@Ocramius  Please re-read the ticket.
The first query is actually **just pure SQL**. It is just to give an idea of what I want and what I have already running.
I have the query created with DQL and what I am saying is that the 
`addOrderBy`
does not translate correctly into DQL.
This is valid SQL in PostgresSQL: `r1.age_group_id=2 DESC, r1.age_group_id=3 DESC`

**Comment by Ocramius** [comment]
Yes, expressions are simply not allowed in the `order by` clause.

**Comment by AntonioCS** [comment]
https://stackoverflow.com/questions/15257538/how-to-order-by-a-computed-value-in-dql
This is what I am referring to which seems not to be supported in doctrine.
