### ISSUE TITLE
[Feature Request] Increment update

### ISSUE THREAD

**Issue by wlzch** [doctrine/doctrine2#6789]
It will be a good addition to enable **increment update** because there is a problem with concurrent update now (I avoid using locking mechanism to provide a better experience for user).

For example:
I have a quantityLeft field in an Item entity which will be decremented on every purchase. But if there are 2 users purchasing the same Item on the same time, quantityLeft will be updated to the last successful update. If it is possible to specify a column as "increment update", then this will solve the problem as the update query will be "quantityLeft = quantityLeft - 1" instead of "quantityLeft = value".

If there's a pointer on how/where to add this feature, I'll try to make a PR. Thanks.

**Comment by Ocramius** [comment]
@wlzch running plain SQL is pretty much OK in this case - what kind of abstraction are you looking for?

**Comment by wlzch** [comment]
Probably adding it on Column annotation.

Running plain SQL is not possible for my case as I wrap multiple inserts and updates in 1 transaction. If I try to run the plain increment update, the ORM will still update the quantityLeft value when flushing.

**Comment by Ocramius** [comment]
Oh, you mean in ORM? That is not possible: ORM will only ever mirror in-memory state with DB state, as changing anything DB-side without performing another lookup that refreshes your entity state.

**Comment by Ocramius** [comment]
Closing as `can't fix`
