### ISSUE TITLE
Feature Request: Optimize queries

### ISSUE THREAD

**Issue by sazzabi** [doctrine/doctrine2#6795]
Hi, I'm working on a solution for optimizing search queries in a project I'm working on, and I want to open this issue to discuss it and know if it's a good idea or not. 

Actually, we created a search method called `ajaxTable` inside an entity repository which is used mostly by DataTables, that takes care of filtering, search, ordering, pagination, etc. I found that the query is getting very complexe and needed many joins (at many portions of the method) that are most of the cases needled. 

For example, **Article** have many **Category**. I can filter on categories, order by them, search articles for specific category, etc. So in my code, I add a leftJoin from the beginning (at the moment I create the query builder `createQueryBuilder('a')->leftJoin('a.category', 'c')`.

Here, if I do not filter on, order by, or use the `c` alias, the join is needless. 

Here is my solution:

```php
// Class LazyEntityRepository
class LazyEntityRepository extends EntityRepository
{
    public function createLazyQueryBuilder($alias)
    {
        $queryBuilder = new LazyQueryBuilder($this->_em);

        return $queryBuilder->select($alias)
                            ->from($this->_entityName, $alias)
            ;
    }
}

// Class LazyQueryBuilder
class LazyQueryBuilder extends QueryBuilder
{
    private $joins = [];

    private function clearJoins()
    {
        $this->joins = [];
    }

    public function leftJoin($join, $alias, $conditionType = null, $condition = null, $indexBy = null)
    {
        if (!array_key_exists($alias, $this->joins)) {
            $this->joins[$alias] = [
                'join'          => $join,
                'joinType'      => 'leftJoin',
                'conditionType' => $conditionType,
                'condition'     => $condition,
                'indexBy'       => $indexBy,
            ];
        }

        return $this;
    }

    public function innerJoin($join, $alias, $conditionType = null, $condition = null, $indexBy = null)
    {
        if (!array_key_exists($alias, $this->joins)) {
            $this->joins[$alias] = [
                'join'          => $join,
                'joinType'      => 'innerJoin',
                'conditionType' => $conditionType,
                'condition'     => $condition,
                'indexBy'       => $indexBy,
            ];
        }

        return $this;
    }

    public function doJoin($alias)
    {
        if (array_key_exists($alias, $this->joins)) {
            $join = $this->joins[$alias];
            /*
             * Check if join needs another join
             */
            $joinAlias = explode('.', $join['join'])[0];
            $this->doJoin($joinAlias);

            /*
             * Join current alias
             */
            switch ($join['joinType']) {
                case 'leftJoin':
                    parent::leftJoin(
                        $join['join'],
                        $alias,
                        $join['conditionType'],
                        $join['condition'],
                        $join['indexBy']
                    );
                    break;
                case 'innerJoin':
                    parent::innerJoin(
                        $join['join'],
                        $alias,
                        $join['conditionType'],
                        $join['condition'],
                        $join['indexBy']
                    );
                    break;
            }

            /*
             * Remove join from list so it cannot be joined twice
             */
            unset($this->joins[$alias]);
        }
    }

    public function checkJoins($part)
    {
        if (is_callable([$part, 'getName'])) {
            // getName is callable, parse getName
            $alias = explode('.', $part->getName())[0];
        } elseif (is_callable([$part, 'getParts'])) {
            // getParts is callable, loop on sub parts
            foreach ($part->getParts() as $subPart) {
                $this->checkJoins($subPart);
            }

            return;
        } elseif (false !== strpos($part, '.')) {
            // String that contains '.', explode it
            $alias = explode('.', $part)[0];
        } else {
            // The part itself is an alias
            $alias = $part;
        }
        if (array_key_exists($alias, $this->joins)) {
            $this->doJoin($alias);
        }
    }

    /**
     * Constructs a Query instance from the current specifications of the builder.
     *
     * <code>
     *     $qb = $em->createQueryBuilder()
     *         ->select('u')
     *         ->from('User', 'u');
     *     $q = $qb->getQuery();
     *     $results = $q->execute();
     * </code>
     *
     * @return Query
     */
    public function getQuery()
    {
        foreach ($this->getDQLPart('select') as $parts) {
            foreach ($parts->getParts() as $part) {
                $this->checkJoins($part);
            }
        }

        foreach ($this->getDQLPart('where')->getParts() as $part) {
            $this->checkJoins($part);
        }

        foreach ($this->getDQLPart('groupBy') as $parts) {
            foreach ($parts->getParts() as $part) {
                $this->checkJoins($part);
            }
        }

        if (null !== $this->getDQLPart('having')) {
            foreach ($this->getDQLPart('having') as $parts) {
                foreach ($parts->getParts() as $part) {
                    $this->checkJoins($part);
                }
            }
        }

        foreach ($this->getDQLPart('orderBy') as $parts) {
            foreach ($parts->getParts() as $part) {
                $this->checkJoins($part);
            }
        }

        return parent::getQuery();
    }
}

```

To explain my idea, whenever I call innerJoin or leftJoin, no joins are really performed, but the information is added in an array for later use. And when I call getQuery, I check for every alias used. If an alias 'a' is used, and I have a join with the alias 'a', it's only then that the join is  performed.

I tested this mechanism in my project, and I noticed a huge gain of time:

- Case 1: I have for example 4 joins but no one is really needed:
  - Execution time old method: ~26 sec
  - Execution time new method: ~2 sec. In this case, if I dump the getSQL, there is no joins
- Case 2 I have the same 4 joins, bu I only need one
  - Execution time old method: ~12 sec
  - Execution time new method: ~2 sec. In this case, if I dump the getSQL, there is only one join, the one that is needed only

So.. what do you think?

**Comment by Ocramius** [comment]
I really think the queries should be written manually rather than making
join conditions lazy...

**Comment by sazzabi** [comment]
@Ocramius yes, but when you have a search method in your repository, that you use with many Datatables, and which offers you a complexe search, filters, order, etc.. what can you do in this case?

**Comment by Ocramius** [comment]
> which offers you a complexe search, filters, order, etc.. what can you do
in this case?

I generally specialize the queries.

Generic methods are fantastic for simple solutions, but as soon as your
schema explodes in complexity, your only friend is the DB-side SQL
optimizer. Everything else needs manual tweaking.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

On Thu, Oct 26, 2017 at 12:52 PM, Seifallah Azzabi <notifications@github.com

**Comment by lcobucci** [comment]
@sazzabi I tend to agree with @Ocramius here. If you still want to proceed with this approach and think that more people can benefit from that, I suggest you to create a library out of these classes and make it available on packagist 👍

**Comment by lcobucci** [comment]
I'll close this as `won't fix` based on this conclusion.
