### ISSUE TITLE
Support for versions of Doctrine that work on PHP5.x and PHP7.0

### ISSUE THREAD

**Issue by alexpott** [doctrine/doctrine2#6799]
I was reading http://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html with interest and I was wondering what is the Doctrine policy for supporting doctrine-common and doctrine-annotations on these older versions of PHP? Will 2.7.x and 1.4.x get bug fixes, or just security fixes or no fixes at all?

The reason I'm asking is that Symfony 3.4 will be supported until 2021 and it'll not drop PHP5.x support till then. I work a lot on the Drupal project and we're trying to decide what to do with [PHP5.x support](https://www.drupal.org/node/2842431) and one of our concerns is security support on older versions of Doctrine. Like many PHP developers I'm always excited to be using the latest version but that excitement is not shared by every user and not every user has the ability to get new OS versions in production (Ubuntu will be support PHP5.x till 2019 probably - EOL of 14.04 LTS).

**Comment by Ocramius** [comment]
> one of our concerns is security support on older versions of Doctrine.

We fix security issues as far back as we can, so that's not a problem.

We don't do bug LTS support.

**Comment by alexpott** [comment]
Thanks!
