### ISSUE TITLE
getReference and typehinting in the Entity fail

### ISSUE THREAD

**Issue by Michal-sk** [doctrine/doctrine2#6806]
When i use `getReference` to use in a filter. I get a Exception because my `getId` is typehinted in the Entity but the value set for the property is a string.

`Return value of Foo\\Domain\\Entity\\Project\\Project::getId() must be an instance of Foo\\Domain\\Value\\Id\\ProjectId, string returned`.

**Comment by Ocramius** [comment]
Are you passing the appropriate values to `getReference`? The ORM won't
cast them for you, so you are responsible for using the correct types.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by Michal-sk** [comment]
Ok, wasn't aware of that. Tought the ProxyFactory would ue the anotations in my Entity. Thanks this will fix it than.
