### ISSUE TITLE
Let Entity use cache

### ISSUE THREAD

**Issue by Michal-sk** [doctrine/doctrine2#6813]
Can my Entity use the (second level cache) cache in some way? I have a very expensive set of functions which calculate the "amount spent" on a object. Now i would ik to cache this amount spent and only add and subtract options added or removed.

Would it be possible to do this trough the entity itself? or will i have to create a service for this?

**Comment by Ocramius** [comment]
It would be best to delegate caching to a service, rather than to the ORM/Entity.

**Comment by Michal-sk** [comment]
thank you
