### ISSUE TITLE
Discriminator "fieldName" is not set in ClassMetadata

### ISSUE THREAD

**Issue by matthias-z** [doctrine/doctrine2#6815]
When a discriminator column is defined with a field name (property "fieldName") the corresponding value in ClassMetadata is set to the column name (property "name") instead.
It is my understanding that this should only occur as a default when no field name is configured.

I observed this behavior using the `AnnotationDriver`:
```php
/**
 * @ORM\Entity
 * @ORm\DiscriminatorColumn(fieldName="discriminatorField")
 */
```
But from what I've seen in the code `XmlDriver` or `YamlDriver` should behave the same in that regard.

**Comment by Ocramius** [comment]
Closing as `invalid` as per https://github.com/doctrine/doctrine2/pull/6817#issuecomment-354667371
