### ISSUE TITLE
The old collection not deleted after a sequence of two flushes

### ISSUE THREAD

**Issue by vtsykun** [doctrine/doctrine2#6831]
When you in full rewrite a collection for an entity, sometimes an old collection is not removed from the database. 

Example
```
class Contact
{
    /**
     * @Id
     * @Column(type="integer")
     */
    public $id;

    /**
     * @Column(type="string")
     */
    public $name;

    /**
     * @ManyToMany(targetEntity="Source")
     */
    public $sources;
}
```
```
class Source
{
    /**
     * @Id
     * @Column(type="string")
     */
    public $id;
}
```
Origin entity

| id | name |  sources |
|:--:|:--:|:--:|
|1|name 1| cck |

```php
$contact->name = 'name 2';
$em->flush();

$sources = $contact->sources->toArray();
$contact->sources = new ArrayCollection($sources);
$em->flush();
```
After the first flush, the changes for the collection fields are no longer tracked and an [error](https://travis-ci.org/doctrine/doctrine2/jobs/303710005#L612) occurred during the second flush. 
```
SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "gh6829contact_gh6829source_pkey"
DETAIL:  Key (gh6829contact_id, gh6829source_id)=(1, cck) already exists.
```
If you remove the first flush then it works fine. 

```php
$contact->name = 'name 2';
$sources = $contact->sources->toArray();
$contact->sources = new ArrayCollection($sources);
$em->flush();
```

**Comment by Majkl578** [comment]
This is by design as it is now, changing collection itself is not supported and must be kept as PersistentCollection assigned by UnitOfWork.
