### ISSUE TITLE
Question: Why are all inserts executed when single entity is committed?

### ISSUE THREAD

**Issue by ossinkine** [doctrine/doctrine2#6835]
According to [UnitOfWork.php#L512](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/UnitOfWork.php#L512) the all insertions will be executed even I want to commit single entity.
It looks doubtful. See example:
```php
$user = $entityManager->find(User::class, $id);
foreach ($uris as $uri) {
    $document = new Document();
    $document->setUri($uri);
    $document->setUser($user);
    $entity->persist($document);
    $user->setDocumentCounter($user->getDocumentCounter() + 1);
}

$someData = $entityManager->find(SomeData::class, $id);
$someData->setFoo('bar');
$entityManager->flush($someData);
// It's unexpected for me that all documents will be persisted here, but user not.
// If this is done for reasons of data integrity, then obviously the integrity is violated.
// User should be commited with documents in single transaction.

$entityManager->flush();
```

**Comment by Ocramius** [comment]
`$entityManager->flush($someData);` is to be avoided. We removed support for the parameters being passed to `flush()` exactly because it was a performance optimisation that just caused more problems than what it solved.

**Comment by ossinkine** [comment]
Guys, you are guru of DDD and of other cool things, give me an advice.
I want to keep separately my Doctrine entities and Domain models according to persistence ignorance practice.
My business logiс should work with models and domain managers (which can create and update models), and domain managers should work with entities or documents or something else.
What is your opinion, is it a good way?
If yes, where flush method should be called considering that different domain managers can use different storage?

**Comment by lcobucci** [comment]
> If yes, where flush method should be called considering that different domain managers can use different storage?

@ossinkine if you're using a service bus to encapsulate the execution of handlers (what you're calling a "domain manager") you can use a middleware that would start the transaction and call the `flush()` after things were processed (if you don't have an exception, sure).

With that your handlers should simple use the repositories to fetch/append/remove objects and modify the object state to update data.

**Comment by lcobucci** [comment]
I'll be closing this issue since it has already been answered by @Ocramius =)
