### ISSUE TITLE
The orm:generate-repositories command still uses psr-0

### ISSUE THREAD

**Issue by jorygeerts** [doctrine/doctrine2#6837]
If you run `orm:generate-repositories src/`, repositories are generated in `src/Vendor/Package/`, psr-0 style.
Given the fact that psr-0 has been deprecated for over two years, I feel it would be a good step add support for psr-4.

The most straight forward way to do this would be an extra option to `orm:generate-repositories` called `psr4-prefix` or something in that spirit. `EntityRepositoryGenerator::writeEntityRepositoryClass()` could then be changed to remove that prefix from the start of `$fullClassName` before generating the `$path`.

If this is a change people would like to see, I'm more then willing to write the code and open a pull request.

**Comment by Ocramius** [comment]
Not gonna happen: Doctrine voted against the abbreviated PSR-4 directory prefixing approach ages ago, and still stands against it.

It is needless complexity that isn't needed.

In addition to that, code generators are likely targeted for removal in 3.x.

**Comment by jorygeerts** [comment]
> Doctrine voted against the abbreviated PSR-4 directory prefixing approach ages ago, and still stands against it.

I wasn't aware of that and a search of the issues didn't bring up anything; sorry for bringing it up again. :)
Thanks for the quick response.
