### ISSUE TITLE
Allow Class Table Inheritance to be used in relationships

### ISSUE THREAD

**Issue by acelaya** [doctrine/doctrine2#6840]
Hello.
The title is not very specific, so I'm going to expose the case.

I have a table structure like this:

```
product
|- card
|- account
|- loan
|- other
```

The product table contains all generic data about banking products, and the other tables contain data which is specific for them.
The other 4 tables have a one to one relationship with product, propagating the product id as a foreign key to all of them.

The product table has a "type" column that tells the table that contains the specific info. Products of type "card" have a related entry in card, products of type "account" have a related entry in account, and so on.

In the application we usually just work with Product collections, and it is rare that we need to access the rest of the tables, but when we do, we need to check the specific entity based on the product's type, and use the EntityManager/repository to find the element.
For example (this is pseudocode).

```
$product = Product {
    type: 'card'
}

// This will return Card::class
$concreteProductEntity = $this->getEntitySomehow($product->type);
$card = $em->getRepository($concreteProductEntity)->findOneBy(['product' => $product]);
```

It would be nice to have some way to define a reversed OneToOne relationship in Product that dynamically matches one class or another based on the type.
Something similar to what you have done with the inheritance mapping: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html#class-table-inheritance
Or maybe it can be done and I'm missing something :-)

**Comment by Ocramius** [comment]
Why not simply create associations to child entities, rather than to the root of the inheritance? Filtering by type can be done via DQL and the `INSTANCE OF` expression.

**Comment by acelaya** [comment]
I'm not sure if I follow you.

The entities `Card`, `Account` and such do not inherit from Product. We didn't design it that way because we usually work with mixed collections. Lists of products usually containe cards, accounts, loans...

What you are suggesting is making those entitis inherit from `Product`?

**Comment by Ocramius** [comment]
Ah, I see what is going on. No, this is a JTI (joined table inheritance) in doctrine (HASA structure in EER if I remember correctly). In doctrine, you would model it as an inheritance.

**Comment by acelaya** [comment]
I could make them extend from `Product`, and that would give me access to the product general information when I have a `Card` or `Account` object. However, that can still be done using a regular OneToOne relationship and colling getProduct().

The thing is that the application usually works with `Product` objects only. A collection of products is always composed by many `Product` objects, each one of them with its own type.

Sometimes I may need to get the concrete, account/card/loan from one of those `Products`, and currently, there's no other way to do it other than using the EntityManager, and having some logic that maps the value of the type property in that `Product` with the corresponding entity.

What I mean is that it might be useful being able to call `$product->getChild()` (or something like that), and get a `Card` object when the `Product` has type "card", or an `Account` object when the `product` has type "account", without having to manually define that logic and use the Repository/EntityManager.

I provided the link to the inheritance mapping because it looks similar to what I propose, (the annotation DiscriminatorMap, specifically, which maps values from one column to entity class names).

Of course, I'm open to change the approach, if there's some other way of doing this, but to be honest, I'm still not following you 😅 (I've even tried to google HASA and EER without much luck)

**Comment by Ocramius** [comment]
The inheritance mapping solves that at the cost of performance:

```php
class Base { private $id; }
class A extends Base {}
class B extends Base {}
class C extends Base {}

class SomethingElse {
    /* @var Base[]|Collection */
    private $things;
    public function __construct() {
        $this->things = new ArrayCollection();
    }

    public function getAs() {
        return $this->things->filter(function (Base $item) {
            return $item instanceof A;
        });
    }

    public function getBs() {
        return $this->things->filter(function (Base $item) {
            return $item instanceof B;
        });
    }

    public function getCs() {
        return $this->things->filter(function (Base $item) {
            return $item instanceof C;
        });
    }
}
```

**Comment by acelaya** [comment]
Ok, now I get it.

That might solve the problem for me. Thank you very much for your time, Marco :-)

Im' closing this for now.
