### ISSUE TITLE
Mapping types does not work with database url

### ISSUE THREAD

**Issue by clementtalleu** [doctrine/doctrine2#6842]
In the doctrine configuration, the property `database_url` seems not work correctly with the `mapping_types` config node.

I have to write each nodes host/port/dbname/user/password to use the mapping_types configuration

**Comment by lcobucci** [comment]
@clementtalleu I'm not sure of what exactly you're talking about. Is this about the configuration of the ORM using the module or bundle? If so, you should open the issue on https://github.com/doctrine/DoctrineBundle or https://github.com/doctrine/DoctrineORMModule

**Comment by lcobucci** [comment]
I'll close this issue as invalid since I think it doesn't belong here, feel free to reopen if this is not accurate.

**Comment by clementtalleu** [comment]
Sorry I just saw that I open this issue on the bad repository.
My bad. ;)

**Comment by lcobucci** [comment]
@clementtalleu no worries!
