### ISSUE TITLE
No default values for orphanRemoval on relation annotations

### ISSUE THREAD

**Issue by albe** [doctrine/doctrine2#6865]
Currently, the relation annotations specify a default value of `false` for the `orphanRemoval` attributes. Most other attributes don't have default values though. The default makes sense generally and is also checked and reestablished inside the ClassMetadataInfo methods, when the mapping information is validated.

**Here is the use case for different needs:**
In Neos Flow Framework, we implement our own AnnotationDriver, which applies some defaults matching DDD principles and takes type information from `@var` blocks. More specifically, we default `orphanRemoval` to `true` for all non-AggregateRoot entities. However, we normally allow the user to override those defaults by explicitly setting values in the doctrine annotations (see https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Persistence/Doctrine/Mapping/Driver/FlowAnnotationDriver.php#L612). This works nicely for most cases, but since the `orphanRemoval` attribute has a default value, we can not distinguish the case when this value was explicitly set or was just the default from the Annotation class. For the other properties, we do check against `null`. See https://github.com/neos/flow-development-collection/issues/1127 for a more detailed description.
As is we either can not allow the user to explicitly override the orphanRemoval default for non-AR or need to introduce own annotations.

**Request:**
Would it be plausible to remove the default values from the annotations themself and only rely on setting the default `false` inside ClassMetadataInfo, e.g. http://www.doctrine-project.org/api/orm/2.5/source-class-Doctrine.ORM.Mapping.ClassMetadataInfo.html#1646? What was the reason to specify the defaults for orphanRemoval in the Annotation class, but for example not for `cascade` which also applies a default value (empty array) in ClassMetadataInfo? Is there anything I miss which makes this impossible?

PS: The same could be applied for the `fetch` type attribute, only that we do not impose different defaults in this case, so it is not an issue.

I'm looking forward for any feedback.

**Comment by lcobucci** [comment]
@albe I don't think this should be changed on v2.x, we're almost done with `v2.6` which should be the last release with features. @guilhermeblanco is working on v3 and already refactored a lot on the mapping so maybe you could take a look on `develop` to see what's in there (maybe Guilherme applied something already)?

**Comment by guilhermeblanco** [comment]
@albe Thanks for integrating your framework with Doctrine! =)
Although we could modify the ORM 2.X code to integrate with your specific scenario, we are defining sensitive default values for 2.6 as a measure to prevent unexpected behavior. In 3.0 we've added more defaults and backporting some of them was a good strategy to ease migration path (I've read your code and apparently your framework will hit the nail with BC breaks, since the entire Mapping namespace have changed for next major).

We've considered and spoke internally if we should move the sensitive defaults to Annotation level or inside `validateAndComplete`. Our resolution was to maintain it at Annotation level, as it also conforms with JPA 2.0 definition.

**Comment by albe** [comment]
Thank you both for the elaborate responses! Highly appreciated, even though they're not in our favor ;) We'll try to solve our issue somehow differently then.

I'll also check the develop branch for v3 and see if the changes will affect us positively in this regard, or if we need to reconsider some things for our Doctrine integration. We have no issue with BC breaks in v3, since we need to adjust to every minor release anyway to make sure we didn't miss any important changes in the default Doctrine AnnotationDriver (the inevitable drawback of integrating so deeply such that inheritance or composition become virtually impossible).

Keep up the good work!

**Comment by kdambekalns** [comment]
❤️
