### ISSUE TITLE
Doctrine try to alter tables changing the case of data type (i.e. VARCHAR) every time

### ISSUE THREAD

**Issue by gremo** [doctrine/doctrine2#6866]
**Using Symfony 2.8 and Doctrine 2.5.5 on CentOS 7 x64 with MariaDB 10.2.**

If I run:

`php app/console doctrine:schema:update --dump-sql`

Doctrine generates a **lot of statements** like `ALTER TABLE change myfield VARCHAR(255)`. Well, myfield is already a `varchar(255)` (**note the case**).

If I force the update:

`php app/console doctrine:schema:update --force`

A lot of queries were executed. But data types aren't actually changed, so running again `php app/console doctrine:schema:update --dump-sql` will generate the same updates again.

Any help is much appreciated!

**Comment by Ocramius** [comment]
Please report this again (if applicable) after upgrading to the latest stable releases.

**Comment by gremo** [comment]
@Ocramius the lastest release I can use is 5.5 indeed...

**Comment by Ocramius** [comment]
@gremo [`2.5.13`](https://github.com/doctrine/doctrine2/releases)

**Comment by lcobucci** [comment]
@gremo also, MariaDB 10.2 is not fully supported and it will only be on DBAL v2.7 (or v3.0) which requires PHP 7.1.

**Comment by gremo** [comment]
@lcobucci yes, I figure it out a couple of hours after opening this issue. Too bad that I have to rebuild my entire server to support legacy sites (can't have multiple database versions). Thank you both anyways.
