### ISSUE TITLE
Schema tool doesn't play well with metadata caching

### ISSUE THREAD

**Issue by martixy** [doctrine/doctrine2#6876]
I was making changes to my model and had created a new entity, and was using the schema tool to dump the raw SQL.

I spotted a small mistake in my definition and after fixing it and dumping again, the change wasn't reflected.
Eventually I discovered that when you have metadata caching, only the first version of any new entity is recognised. Thereafter, no matter what changes you make to your entity, the schema tool not reflect those, since it has now cached the first version, and that's all it knows.

Given the function of this tool, would it not be better to force it to bypass caching altogether?

**Comment by Ocramius** [comment]
No - the schema tool just receives metadata: whether that requires cache
invalidation or not is to be decided on a case-by-case basis.
It is a generic tool and it should stay as such.

**Comment by martixy** [comment]
For me, this seems an easy pit to fall into. While I wouldn't know the best solution to this, I believe it's a good idea to address this somehow - be it in code or documentation.

**Comment by Ocramius** [comment]
Documentation patches are indeed welcome: just needed to clarify the design
decisions first 👍

**Comment by lcobucci** [comment]
I'll close this issue as per @Ocramius comments.

@martixy please do send a PR improving the docs!
