### ISSUE TITLE
Doctrine Inheritance: Two subclasses that reference the same record

### ISSUE THREAD

**Issue by AlexSayHello** [doctrine/doctrine2#6890]
In a platform of my company, I have the following use case.

Users of the platform can be: normal users who log in, users who buy products or users who write articles in a blog

So I've created three entities: `User`, `ShopUser` and `BlogAuthor`, each one in its respective module (module system of platform, a.k.a.  plugins). They are represented in the following diagram (Summarized)

![uml_model](https://user-images.githubusercontent.com/10273130/33992075-7eb371b6-e0d1-11e7-8e6e-68a07997a72d.png)

The mapping of entities would be like this

The entities of doctrine are registered thinking that each one is in separate modules, with which they have to be decoupled. For this, a listener was implemented ([following this article](https://medium.com/@jasperkuperus/defining-discriminator-maps-at-child-level-in-doctrine-2-1cd2ded95ffb)) in the doctrine mapping that allows declaring the `@DiscrimnatorEntry` annotation, which allows declaring the value of the discriminating field in each daughter entity, not in the parent entity.

Considering these aspects, he used a simple class inheritance

User class
```php
/**
 *
 * @Entity()
 * @InheritanceType("SINGLE_TABLE")
 * @DiscriminatorColumn(name="type", type="string")
 * @DiscriminatorEntry(value="basic_user")
 * @Table(name="users")
 */
class User
{
    //fields
}
```

ShopUser class
```php
**
 * ShopUser
 *
 * @Entity()
 * @DiscriminatorEntry('shop_user')
 *
 */
class ShopUser extends User
{
    //fields
}
```

BlogAuthor
```php
/**
 * Blog Author
 *
 * @Entity()
 * @DiscriminatorEntry(value="blog_author")
 */
class BlogAuthor extends User
{
}
```
The resulting table contains the fields: `id`, `name`, `email`, `password`, `fancyName` and the discriminator field.

The problem is that a single row can be two different entities, which in the inheritance model, are not children, but brothers.

So, when you register a user of the store:
```php
$entityManager->persist(new ShopUser('email', 'password', 'gatewayName'));
$entityManager->flush();
```

 It is created in the database with the discriminator field `blog_author`

Since, a user of the store can also be a user of the blog if I register an shop user with id 7, I can not get that user (with that id), as an instance of `AuthorBlog`

```php
class BlogManager
{
    //code...

    public function changeFancyName(int $userId, string $fancyName)    
    {
        $author = $this
                      ->entityManager
                      ->getRepository(BlogAuthor::class)->find($userId); //returns null
	/// some code...
    }
}
```

My goal is, based on the repository I am using, to obtain the correct entity, `ShopUser` or` BlogAuthor`, which can be from the same row.

I hope you can help me, thank you very much.

**Comment by Ocramius** [comment]
This is not supported, as it breaks the basic invariant that per entity type, at one point in time, you only have one identifier in memory. This creates two concurrent in-memory entities, and that breaks the ORM<->DB symmetricity.
