### ISSUE TITLE
Missing documentation for SchemaTool events

### ISSUE THREAD

**Issue by SenseException** [doctrine/doctrine2#6891]
Looking through the code of `SchemaTool`, I found out that there are undocumented events called `postGenerateSchema` and `postGenerateSchemaTable`. I want to add those events into the documentation of events.rst. Or should it be put into a new file?

**Comment by Ocramius** [comment]
Same file is 👌

**Comment by SenseException** [comment]
I've created the PR for the event documentation.

**Comment by Ocramius** [comment]
Handled in #6963
