### ISSUE TITLE
Reflection to Closure bind rework

### ISSUE THREAD

**Issue by KonstantinKuklin** [doctrine/doctrine2#6899]
Did anyone tried to move from reflection to ClosureBind in cases when we need to work with entity`s property?
Main reason of such refactoring is much better performance of closures.
BTW https://ocramius.github.io/blog/accessing-private-php-class-members-without-reflection/

**Comment by Ocramius** [comment]
Usually leads to worse performance, but please check
ocramius/generated-hydrator if your aim is improving ORM performance for 3.x

**Comment by KonstantinKuklin** [comment]
So, I got:

> **ClosureHydrator**: 		 		0.58397507667542	
> Zend\Hydrator\ArraySerializable: 0.59179091453552	(+1.3383855188826%)
> Zend\Hydrator\Reflection: 		0.63898396492004	(+9.419732184085%)
> Zend\Hydrator\ClassMethods: 	5.5945200920105	(+858.00665395863%)

hydrator code: https://gist.github.com/KonstantinKuklin/c44daa558dcdfb5cee8e0d89c778c5d3

environment: PHP 7.0.22 (cli) (built: Aug  7 2017 14:07:27) ( NTS )

is 5-10% boost enough to move from reflection?

**Comment by Ocramius** [comment]
No, needs to be much more to justify the change there. As I already
mentioned, the GeneratedHydrator project is where you might want to suggest
improvements.

After those are applied, we can work towards plugging in a (de-) hydration
abstraction in the ORM too.

**Comment by Majkl578** [comment]
We actually already have issue for generated hydrators: #2553. I'll close this one based on what @Ocramius said, but will add the other issue to 3.0 milestone so it doesn't get forgotten.
