### ISSUE TITLE
UuidGenerator::generate takes EntityManager parameter, not EntityManagerInterface

### ISSUE THREAD

**Issue by voff4eg** [doctrine/doctrine2#6907]
UuidGenerator::generate takes EntityManager parameter, not EntityManagerInterface
Thease causes problem using EntityManager decorator, because our $em parameter is instance of EntityManagerDecorator. In addition it is a violation of Dependency Inversion principle https://en.wikipedia.org/wiki/Dependency_inversion_principle

**Comment by lcobucci** [comment]
@voff4eg thanks for reporting, we're aware and already fixing this for v3 (since it's a BC-break)

**Comment by Majkl578** [comment]
Already fixed in develop (3.0): #6599.

**Comment by voff4eg** [comment]
@lcobucci, @Majkl578 thanx
