### ISSUE TITLE
$em->flush($entity) flushes all entities schedules for insert

### ISSUE THREAD

**Issue by Yuav** [doctrine/doctrine2#6915]
doctrine/orm: v2.5.12

I have an entity without any relations set that I pass to flush().

**Expected result**

INSERT of only this entity

**Actual result**

All entities scheduled for inserts are put into the database

---

Looking at the code, computing changesets for all insert changesets in `computeSingleEntityChangeSet` seems strange to me:

UnitOfWork.php -> `function computeSingleEntityChangeSet` contains the following:

    // Compute changes for INSERTed entities first. This must always happen even in this case.
    $this->computeScheduleInsertsChangeSets();

With computeScheduleInsertsChangeSets:

    /**
     * Computes the changesets of all entities scheduled for insertion.
     *
     * @return void
     */
    private function computeScheduleInsertsChangeSets()
    {
        foreach ($this->entityInsertions as $entity) {
            $class = $this->em->getClassMetadata(get_class($entity));

            $this->computeChangeSet($class, $entity);
        }
    }

**Comment by Ocramius** [comment]
This is normal: `EntityManager#flush($entity)` is deprecated, as it was initially only thought for performance optimisations, but does indeed perform any DB operations that were already scheduled.

Please don't use it, and just use `EntityManager#flush()` instead.
