### ISSUE TITLE
Decouple / _suggest_ the symfony/console dependency

### ISSUE THREAD

**Issue by afoeder** [doctrine/doctrine2#6926]
In short: I would like to check on that; is there anything why the console component is actually _required_ at the moment?

**Comment by Ocramius** [comment]
@afoeder all CLI commands implemented in [here](https://github.com/doctrine/doctrine2/tree/374e7ace49d864dad8cddbc55346447c8a6a2083/lib/Doctrine/ORM/Tools/Console) strictly depend on `symfony/console`
