### ISSUE TITLE
Allow Removing Fields within @AttributeOverrides (for Traits and Superclasses)

### ISSUE THREAD

**Issue by mattjanssen** [doctrine/doctrine2#6930]
We can currently use `@AttributeOverrides` to _modify_ fields brought in by traits and extended superclasses, but there's no way to _remove_ a field.

The use case is when a trait brings in a column that you don't want in the final entity. This happens if you want to handle a property differently than the general use case of that trait.

Maybe something like this?
```
@AttributeRemovals("foo", "bar", "baz")
```

**Comment by Majkl578** [comment]
This request sounds like a sign of bad design to me. Removing a field / methods is generally violation of LSP in OOP. Why don't you just refactor your traits and make them smaller so that you wouldn't need to _remove_ any fields?

**Comment by mattjanssen** [comment]
I totally get the code smell here. But what's happening is this entity still needs this property, but it's not stored in the DB. So the getter, setter and property still exist, but we don't want it persisted.

**Comment by Ocramius** [comment]
Looks like an edge case from here: the correct approach would be to remove
the field in a manually implemented class metadata postLoad event listener.

**Comment by mattjanssen** [comment]
Fair enough. One dev's feature request is another's edge case. And if you haven't heard anyone else wanting this, then you're probably right!

I'll just override the properties in the one extending class that behaves differently. That'll wipe out the @Column annotations. Unfortunately I'll have to duplicate the @Assert annotations for these props, as they get wiped, too.

I used to use the event listeners, but there often be dragons that way. At the very least, it was confusing to other developers on the project.

**Comment by Ocramius** [comment]
> I used to use the event listeners, but there often be dragons that way. 

Usually, yes, but that's a simple solution that doesn't need a new feature. We try to cover the 80/20 "Pareto" rule.
