### ISSUE TITLE
Better document addition of EntityRepository::count()

### ISSUE THREAD

**Issue by Majkl578** [doctrine/doctrine2#6933]
There are multiple reports about consumers being broken due to this new method. See https://github.com/doctrine/doctrine2/pull/6003#issuecomment-353442961 and linked issues.
Although adding new public method is not a BC break per se. we should at least document it somewhere in UPGRADE as a possible source of problems.

**Comment by Ocramius** [comment]
Moving to `2.6.2`

**Comment by lcobucci** [comment]
Addressed by #7276
