### ISSUE TITLE
SQL Function ROUND is not parsed in Query\Parser

### ISSUE THREAD

**Issue by cgardiennet** [doctrine/doctrine2#6942]
The SQL function ROUND is not parsed in Query\Parser.
Need to be added.

**Comment by cgardiennet** [comment]
Need this in a future 2.5 version

**Comment by Ocramius** [comment]
@cgardiennet this is available in [DoctrineExtensions](https://github.com/beberlei/DoctrineExtensions/blob/f592c495f1c43851f5e3418cf9c2514e61d67e64/src/Query/Mysql/Round.php)

**Comment by cgardiennet** [comment]
The solution to use DoctrineExtension is not good one for me :

**Comment by Ocramius** [comment]
> Round function class is not created for every database platform (ie : doesn't exist for PostgreSql ???!!!)

Yep, you should send a patch to `DoctrineExtensions` then :-)

Patches here also welcome, as long as behavior is consistent on all platforms.

**Comment by cgardiennet** [comment]
The most important annoying fact for me is that i have to declare a custom DQL function (ROUND) when this is a standard SQL function...

**Comment by Ocramius** [comment]
That holds true for most SQL functions. DQL is kinda like a subset of SQL, and we can only expand it where functionality applies to all DB vendors.

**Comment by cgardiennet** [comment]
ROUND exist in all DB !

**Comment by cgardiennet** [comment]
And most important, it is implemented in Doctrine DBAL for all platforms !

**Comment by Ocramius** [comment]
Send a patch then :+1:

**Comment by cgardiennet** [comment]
This is what i tried to do : https://github.com/doctrine/doctrine2/pull/6954
