### ISSUE TITLE
Bug by inserting data

### ISSUE THREAD

**Issue by infastra** [doctrine/doctrine2#6946]
I try to create a new database entry by using the class EntityManager with the method flush especially for one Entity. After call the method flush, I get the error SQLSTATE[HY093]: Invalid parameter number: no parameters were bound.

Here is my source code:

```php
class MyEntityRepository extends Doctrine\ORM\EntityRepository {
public function save($entityObject) {
    $this->persist($entryObject);
    $this->getEntityManager()->flush($this->_class->rootEntityName);
}
}

```

When I only want to update an entity, it works.

After debugging I found out that the class Doctrine\ORM\UnitOfWork didn't have the entity in its entityChangeSet array in line 530.

I'm using version 2.5.14 of Doctrine.

When I call the flush method without any parameter it works. So did I use the method in a wrong way? What could I do when I want to insert data in one entity?

**Comment by Ocramius** [comment]
[`EntityManager#flush()` expects a `object|object[]|null` as parameter](https://github.com/doctrine/doctrine2/blob/374e7ace49d864dad8cddbc55346447c8a6a2083/lib/Doctrine/ORM/EntityManager.php#L346).

Besides that, flushing single entities is deprecated and already removed in `develop`, which is going to be ORM 3.0. I strongly endorse not using `EntityManager#flush($entity)`, but only `EntityManager#flush()`.
