### ISSUE TITLE
automatic SQL alias on fields starting with numbers are not escaped

### ISSUE THREAD

**Issue by Sutefan** [doctrine/doctrine2#6965]
I work via symfony 3.3 and its doctrine-bundle on SQL Server database. Our users table has numerous fields starting with numbers. The problem is that, even though fields names are correctly escaped with square brackets, aliases aren't : 

```SELECT t0.[01_product_creation] AS 01_product_creation FROM users```

This fires an error everytime a select request is made on that table : 

```
SQLSTATE[HY000]: General error: 102 Incorrect syntax near '01'. [102] (severity 15) [(null)]
```

I have created a hint and a SqlWalker to manually correct this issue, by putting square brackets around aliases too : 

```
class NumericAliasesWalker extends SqlWalker
{
    /**
     * Walks down a SelectClause AST node, thereby generating the appropriate SQL.
     *
     * @param $selectClause
     * @return string The SQL.
     */
    public function walkSelectClause($selectClause)
    {
        $sql = parent::walkSelectClause($selectClause);
        $pattern = '/(?<=AS\s)(\d[\d\w]+)/';
        $sql = preg_replace($pattern, '[$1]', $sql);
        
        return $sql;
    }
}
```

But the problem is that find() methods execute themselves right away and can't be "hinted". Moreover they are used in the Symfony Security Component to refresh users on login which makes things a bit tricky : I can apply a patch/hint to correct this in the component itself, but it supposes that every update would erase it and force me to reapply it everytime.

Is it possible to apply the same rule (square brackets for fields names) on aliases too ?

**Comment by Ocramius** [comment]
Check if it is thrown through the quote strategy: https://github.com/doctrine/doctrine2/blob/f4eb8ca85ff90870e788291d697afdbe30d07e3e/lib/Doctrine/ORM/Mapping/QuoteStrategy.php#L107-L117

**Comment by Sutefan** [comment]
Hi,

Thank you for your answer !

If I add : `$columnName = $platform->quoteIdentifier($columnName);` just before the end of getColumnAlias function it solves the problem.

```
    /**
     * {@inheritdoc}
     */
    public function getColumnAlias($columnName, $counter, AbstractPlatform $platform, ClassMetadata $class = null)
    {
        // 1 ) Concatenate column name and counter
        // 2 ) Trim the column alias to the maximum identifier length of the platform.
        //     If the alias is to long, characters are cut off from the beginning.
        // 3 ) Strip non alphanumeric characters
        // 4 ) Prefix with "_" if the result its numeric
        $columnName = $columnName . '_' . $counter;
        $columnName = substr($columnName, -$platform->getMaxIdentifierLength());
        $columnName = preg_replace('/[^A-Za-z0-9_]/', '', $columnName);
        $columnName = is_numeric($columnName) ? '_' . $columnName : $columnName;
        _$columnName = $platform->quoteIdentifier($columnName);_

        return $platform->getSQLResultCasing($columnName);
    }
```

Is it possible to include that in an update if this do not break requests on other platforms in some other cases ?

**Comment by Ocramius** [comment]
@Sutefan write a test for it, then we can write/merge a patch :-)

**Comment by Sutefan** [comment]
Thanks a lot !

I already have a correction for this as it quotes everything and causes problems during hydratation ^_^;)

This is the right code to add : 
```
        if(preg_match('/^\d/', $columnName)){
            $columnName = $platform->quoteIdentifier($columnName);
        }
```
And the function once modified : 
```
    /**
     * {@inheritdoc}
     */
    public function getColumnAlias($columnName, $counter, AbstractPlatform $platform, ClassMetadata $class = null)
    {
        // 1 ) Concatenate column name and counter
        // 2 ) Trim the column alias to the maximum identifier length of the platform.
        //     If the alias is to long, characters are cut off from the beginning.
        // 3 ) Strip non alphanumeric characters
        // 4 ) Prefix with "_" if the result its numeric
        $columnName = $columnName . '_' . $counter;
        $columnName = substr($columnName, -$platform->getMaxIdentifierLength());
        $columnName = preg_replace('/[^A-Za-z0-9_]/', '', $columnName);
        $columnName = is_numeric($columnName) ? '_' . $columnName : $columnName;
        if(preg_match('/^\d/', $columnName)){
            $columnName = $platform->quoteIdentifier($columnName);
        }

        return $platform->getSQLResultCasing($columnName);
    }
```

**Comment by Ocramius** [comment]
Without an automated test, a fix is not considered

**Comment by Sutefan** [comment]
Ok, should write it here or do I have to make a pull request, and submit modifications ?

Sorry to ask you this question but I have never made a github participation until now, and it may take me some time to sort out what I have to do next.

**Comment by Ocramius** [comment]
@Sutefan give a pull request a stab. My strong suggestion is to have a PR with two commits:

 1. (first) a commit with the failing test
 2. a commit with the fix you suggested above

If you push these comments separately, we should see a red build followed by a green one, which validates the change :+1:

**Comment by Sutefan** [comment]
Giving the fact that all characters out of this range : '/[^A-Za-z0-9_]/' are erased in aliases, the best and easiest way to correct this problem is : 
```
    /**
     * {@inheritdoc}
     */
    public function getColumnAlias($columnName, $counter, AbstractPlatform $platform, ClassMetadata $class = null)
    {
        // 1 ) Concatenate column name and counter
        // 2 ) Trim the column alias to the maximum identifier length of the platform.
        //     If the alias is to long, characters are cut off from the beginning.
        // 3 ) Strip non alphanumeric characters
        // 4 ) Prefix with "_" if the result its numeric
        $columnName = $columnName . '_' . $counter;
        $columnName = substr($columnName, -$platform->getMaxIdentifierLength());
        $columnName = preg_replace('/[^A-Za-z0-9_]/', '', $columnName);
        $columnName = is_numeric($columnName[0]) ? '_' . $columnName : $columnName;
 
        return $platform->getSQLResultCasing($columnName);
    }
```

**Comment by KantinDG** [comment]
@Sutefan Hi, where is this issue ?

**Comment by ostrolucky** [comment]
Fixed in https://github.com/doctrine/doctrine2/commit/c1a46219ed096ac5a5c3c664d913a75f06013f0e#diff-0a43cebca85957a00f4b799624bdb29bR108
