### ISSUE TITLE
Document new bugfixing workflow in README.md

### ISSUE THREAD

**Issue by Ocramius** [doctrine/doctrine2#6966]
Since we moved `master` to be `3.x-dev`, we need to also update contributing guidelines so that users know where to send patches to.

So far, since `2.6` and `master` diverge quite a lot (architecturally), the suggestion is to let bugfixes flow into `2.6` or `2.7`, and have another separate patch for `master` once (and if) it is solved. 

Probably a good chance to add issue templates like in https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/ (see https://github.com/zendframework/maintainers/tree/59b7786ec5da9ba0dc1dab531e25873e3866f7be/template/docs by @xtreamwayz and @weierophinney, for example)

**Comment by Majkl578** [comment]
Documented by #7107.
