### ISSUE TITLE
How to mock IterableResult?

### ISSUE THREAD

**Issue by SergeC** [doctrine/doctrine2#6969]
After spending a few hours on Googling how to mock IterableResult I still don't have a clear answer.
I have a project Symfony 4 + Doctrine 2.6.

class CoinRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Coin::class);
    }

    public function getEnabledCoins(): IterableResult
    {
        return $this->createQueryBuilder('coin')
            ->where('coin.enabled = true')
            ->getQuery()
            ->iterate();
    }
}

This Repository injected into service

class Service
{
    private $coinRepository;

    public function __construct(CoinRepository $coinRepository)
    {
        $this->coinRepository = $coinRepository;
    }

    public function update(): void
    {
        foreach ($this->getCoinRepository()->getEnabledCoins() as $coin) {

        }
    }

    private function getCoinRepository(): CoinRepository
    {
        return $this->coinRepository;
    }
}

How can I make `getEnabledCoins()` to return a data generated by a test?

**Comment by Ocramius** [comment]
Return an ArrayIterator and you should be fine

**Comment by SergeC** [comment]
Due to PHP 7 return type definition, it doesn't work if I have `public function getEnabledCoins(): IterableResult` in repository while mocked repository returns `\ArrayIterator`.

Test:
    public const SYMBOL = 'XXX';

    public function testUpdate()
    {
        $coin = new Coin();
        $coin->setSymbol(self::SYMBOL);

        $repository = $this->createMock(CoinRepository::class);
        $repository->expects($this->once())
            ->method('getEnabledCoins')
            ->willReturn(new \ArrayIterator([$coin]));

        (new Service($repository))->update();
    }


There was 1 error:

1) App\Tests\Service\ServiceTest::testUpdate
TypeError: Return value of Mock_CoinRepository_6d6d8c3c::getEnabledCoins() must be an instance of Doctrine\ORM\Internal\Hydration\IterableResult, instance of ArrayIterator returned

**Comment by Majkl578** [comment]
> Due to PHP 7 return type definition

Then don't typehint internal IterableResult, but `iterable` only.

**Comment by SergeC** [comment]
@Majkl578 this way it works.
