### ISSUE TITLE
Bug in test suite on branch 2.5

### ISSUE THREAD

**Issue by Sutefan** [doctrine/doctrine2#6972]
Hi there,

When I launch PHPUnit on branch 2.5 I get the following message : 

`
Fatal error: Declaration of Doctrine\Tests\Mocks\HydratorMockStatement::fetch($fetchStyle = NULL) must be compatible with Doctrine\DBAL\Driver\ResultStatement::fetch($fetchMode = NULL, $cursorOrientation = PDO::FETCH_ORI_NEXT, $cursorOffset = 0) in /var/www/html/tests/Doctrine/Tests/Mocks/HydratorMockStatement.php on line 11
`

I don't really know how to fix this. Has anyone a solution to repair this please ?

**Comment by Ocramius** [comment]
DBAL 2.5 and ORM 2.5 diverged on interface implementations: please upgrade to 2.6.
