### ISSUE TITLE
There are no commands defined in the "orm:schema-tool" namespace

### ISSUE THREAD

**Issue by theoaks** [doctrine/doctrine2#6984]
I get this error when I try to run the command

`doctrine orm:schema-tool:create`

There are no commands defined in the "orm:schema-tool" namespace.

I've googled and I didn't find any issue like it

What am I doing wrong?

**Comment by Ocramius** [comment]
See https://github.com/doctrine/DoctrineModule/issues/618#issuecomment-357445760
