### ISSUE TITLE
ManyToManyPersister fails to remove join table entry if there is multiple join columns

### ISSUE THREAD

**Issue by NicolaF** [doctrine/doctrine2#6991]
this is due to a typo in `\Doctrine\ORM\Persisters\Collection\ManyToManyPersister::getDeleteSQLParameters`:

```
        foreach ($mapping['relationToSourceKeyColumns'] as $columnName => $refColumnName) {
            $params[] = isset($sourceClass->fieldNames[$refColumnName])
                ? $identifier[$sourceClass->fieldNames[$refColumnName]]
                : $identifier[$sourceClass->getFieldForColumn($columnName)];
        }

```

It should be `$sourceClass->getFieldForColumn($refColumnName)`, as `$columnName` is the join table column, not the entity table column.

**Comment by Ocramius** [comment]
Closing as duplicate of https://github.com/doctrine/doctrine2/pull/6992

**Comment by NicolaF** [comment]
Hi @Ocramius 
See #6997 for PR on the 2.6 branch

**Comment by Ocramius** [comment]
@NicolaF thanks!
