### ISSUE TITLE
Mysql: Is there possibility to create index for json field?

### ISSUE THREAD

**Issue by haegemon** [doctrine/doctrine2#6996]

**Comment by lcobucci** [comment]
@haegemon did you check https://dev.mysql.com/doc/refman/5.7/en/create-table-secondary-indexes.html#json-column-indirect-index?

**Comment by haegemon** [comment]
Yes. And I didn't find  at docs how can I create Generated column and index for this column at entity annotation. Is this possible?

**Comment by Ocramius** [comment]
Closing as `won't fix` here. This goes into fine-grained schema customisation details that are out of scope for the ORM. Please use an SQL/DDL migration management tool such as `doctrine/migrations` instead.

This kind of index definition will not be added to the ORM mappings.

**Comment by Ocramius** [comment]
Closing as `won't fix` here. This goes into fine-grained schema customisation details that are out of scope for the ORM. Please use an SQL/DDL migration management tool such as `doctrine/migrations` instead.

This kind of index definition will not be added to the ORM mappings.

**Comment by 4cc355-d3n13d** [comment]
@Ocramius If I created it with migration tool may I use this column value as usual model property? And doctrine could give me this possibility to do this way, isn't it?

**Comment by Ocramius** [comment]
Yep, it would look like any other entity field

**Comment by eduard-sukharev** [comment]
I can add required index with migration manually, but I would like SchemaTool to be able to generate (and track) proper index for the following annotation:
```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(indexes={
 *     @ORM\Index(columns={"metadata->>'account'"})
 * })
 */
class Statistics
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(name="id", type="bigint")
     */
    private int $id;

    /**
     * @ORM\Column(name="metadata", type="json", options={"jsonb"=true})
     */
    private array $metadata;
}
```
Am I getting it right that defining an Index annotation for JSONB preoprties is not possible now and is not going to be implemented?

P.S. Sorry for bringing up this old issue, but it's better than creating duplicate, I guess.
