### ISSUE TITLE
How do you query?

### ISSUE THREAD

**Issue by manishbathla** [doctrine/doctrine2#7016]
have never used doctrine or any other DAL for that matter but I need to switch. I need to know whether I can query something like this in doctrine
```
SELECT *
FROM category c
LEFT JOIN category_description cd ON (c.category_id = cd.category_id)
WHERE c.parent_id = '0' AND cd.language_id = '1' ORDER BY c.sort_order
```
?

**Comment by Ocramius** [comment]
Please refer to http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html for documentation of how the doctrine query language works. 

What you wrote there is SQL, which can be run on Doctrine DBAL, not in Doctrine ORM.

In Doctrine ORM, the query above would be translated (in DQL) to:

```
SELECT
    c,
    d
FROM
    My\Namespace\Category c
LEFT JOIN
    c.description d
WHERE
    c.parentId = 0
ORDER BY
    c.sortOrder ASC
```

If you wanted to select all records where `Description#languageId` is `1`, you'd do that after selecting your `Category` instances with the query above. See also https://groups.google.com/d/msg/doctrine-user/_1_Nh89--2A/D5CwzSwqDgAJ about why filtering of the association is not really possible without breaking the in-memory data structure.
