### ISSUE TITLE
Doctrine 2.5 - Entity Update Bug

### ISSUE THREAD

**Issue by nepster-web** [doctrine/doctrine2#7035]
I have the entity (this is simple example):
```php
class Record
{
    /**
     * @ORM\Column(type="ContentContext_RecordTranslationCollection")
     * @var RecordTranslationCollection
     */
    private $translations;

    public function __construct()
    {
        $this->translations = new RecordTranslationCollection();
    }

    public function getTranslations(): RecordTranslationCollection
    {
        return $this->translations;
    }

    public function addTranslation(RecordTranslation $translation): void
    {
        /** @var RecordTranslation $translation */
        foreach ($this->translations as $currentTranslation) {
            if ($currentTranslation->getLocale() === $translation->getLocale()) {
                $this->translations->removeElement($currentTranslation);
                break;
            }
        }
        $this->translations->add($translation);
    }
}
```

My **RecordTranslationCollection** extends \Doctrine\Common\Collections\ArrayCollection

And my **ContentContext_RecordTranslationCollection** type looks like this:
```php
class RecordTranslationCollectionType extends JsonType
{
    private $hydrator;

    public function setHydrator(Hydrator $hydrator)
    {
        $this->hydrator = $hydrator;
    }

    public function convertToDatabaseValue($collection, AbstractPlatform $platform)
    {
        $result = [];
        foreach ($collection as $entity) {
            $result[] = $this->hydrator->extract($entity);
        }

        return json_encode($result);
    }

    public function convertToPHPValue($json, AbstractPlatform $platform)
    {
        $data = json_decode($json, true) ?? [];
        $collection = new RecordTranslationCollection();
        foreach ($data as $translate) {
            $collection->add($this->hydrator->hydrate($translate, RecordTranslation::class));
        }
        return $collection;
    }

}
```

Ok, it all works when you create and save a new entity! But there is a problem when updating.
When I get the entity **Record** from the database to update the collection of translations, for example:

```php
$record = // query to db ;

$translate1 = new RecordTranslation(); // for convenience, let's skip the data
$translate2 = new RecordTranslation(); // for convenience, let's skip the data

$record->addTranslation($translate1);
$record->addTranslation($translate2);

$this->entityManager->persist($record);
$this->entityManager->flush();
```

And my new collection does not save.
Doctrine does not understand that the object **RecordTranslationCollection** has changed.
And the method **convertToDatabaseValue** is not called.

If you use a spike, for example:
```php
$r = new ReflectionProperty(get_class($record), 'translations');
$r->setAccessible(true);
$r->setValue($object, clone $record->getTranslations());

$this->entityManager->persist($record);
$this->entityManager->flush();
```

The entity will be saved correctly. So doctrine does not see the changes inside the object, but only see the object itself.

**Comment by Majkl578** [comment]
Changes to object properties are detected by reference so if the object (instance) does not change, it's deemed to be same. See description fo DateTime, it applies to objects in general: https://doctrine-orm.readthedocs.io/projects/doctrine-orm/en/latest/cookbook/working-with-datetime.html#datetime-changes-are-detected-by-reference

**Comment by Ocramius** [comment]
Also see https://stackoverflow.com/questions/15486402/doctrine2-orm-does-not-save-changes-to-a-datetime-field

**Comment by nepster-web** [comment]
I think littering in entities is doubtful. Maybe it's better to use a setting for example:
```
    /**
     * @ORM\Column(type="ContentContext_RecordTranslationCollection", updatable=true)
     * @var RecordTranslationCollection
     */
    private $translations;
```

In my case it will be easier to extend method **persist**, check properties of the entity on the availability of necessary objects and use **clone** there where it is should be.

**Comment by Ocramius** [comment]
"littering in entities"?

**Comment by nepster-web** [comment]
Sorry for my beginner's English.

I mean it's trash into entities.

**Comment by Ocramius** [comment]
No, it's just good practice to avoid sharing referentially kept mutable state by de-referencing via `clone`. See also https://ocramius.github.io/extremely-defensive-php/ and https://ocramius.github.io/doctrine-best-practices/ for further tips ;-)

**Comment by nepster-web** [comment]
Thank you very much!
