### ISSUE TITLE
getArrayResult or getSql not working properly ?

### ISSUE THREAD

**Issue by poolerMF** [doctrine/doctrine2#7036]
I got entity, that have manyToOne (user)
I made simple QB (select table) 

**$queryBuilder->getQuery()->getSQL():**

	SELECT 
	  c0_.id AS id_0, 
	  c0_.name AS name_1, 
	  c0_.user AS user_2 
	FROM 
	  client c0_ 
	ORDER BY 
	  c0_.id DESC 
	LIMIT 
	  20 OFFSET 0

I'm calling $queryBuilder->getQuery()->getArrayResult()

**real executed SQL from profiler:**

	SELECT 
	  c0_.id AS id_0, 
	  c0_.name AS name_1
	FROM 
	  client c0_ 
	ORDER BY 
	  c0_.id DESC 
	LIMIT 
	  20 OFFSET 0

where is problem ?  should getSql select user ? or should getArrayResult return user ?

**Comment by Ocramius** [comment]
@poolerMF what are the mappings involved in this query? Also, did you make sure there is no caching?

**Comment by poolerMF** [comment]
**query:**

    $em->getRepository(Client::class)->createQueryBuilder('t')->getQuery()->getArrayResult();

**mapping:**
    

    /**
     * @var ...\User
     *
     * @ORM\ManyToOne(targetEntity="...\User")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="user", referencedColumnName="id", nullable=true)
     * })
     */
    private $user;

**Comment by poolerMF** [comment]
@Ocramius association is not part of the entity ?
sorry what ? maybe I do not understand

can you send me example, when is it part of the entity ?

and still issue - is getSql returning correct SQL ? becose it is different from real one

**Comment by Ocramius** [comment]
I made a quick test to show how this works:

```php
<?php

declare(strict_types=1);

namespace Doctrine\Tests\ORM\Functional\Ticket;

use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\Annotation as ORM;
use function sprintf;

class DDC0000Test extends \Doctrine\Tests\OrmFunctionalTestCase
{
    protected function setUp()
    {
        parent::setUp();

        $this->schemaTool->updateSchema([
            $this->em->getClassMetadata(DDC0000Root::class),
            $this->em->getClassMetadata(DDC0000Association::class),
        ]);
    }

    public function testAssociationFieldsAreNotInArrayResult()
    {
        $root        = new DDC0000Root();
        $association = new DDC0000Association();

        $root->association = $association;

        $this->em->persist($root);
        $this->em->persist($association);
        $this->em->flush();

        $result = $this
            ->em
            ->createQuery(sprintf('SELECT r FROM %s r', DDC0000Root::class))
            ->getArrayResult();

        self::assertSame([['id' => DDC0000Root::class]], $result);
    }
}

/** @ORM\Entity() */
class DDC0000Root
{
    /** @ORM\Id @ORM\GeneratedValue(strategy="NONE") @ORM\Column(type="string") */
    public $id = self::class;

    /** @ORM\ManyToOne(targetEntity=DDC0000Association::class) */
    public $association;
}

/** @ORM\Entity() */
class DDC0000Association
{
    /** @ORM\Id @ORM\GeneratedValue(strategy="NONE") @ORM\Column(type="string") */
    public $id = self::class;
}
```

Also, yes, fields that do not need to be fetched are also removed from the `SELECT` clause.

If you still want the ID of the association, you should add it to your `SELECT` with the `IDENTITY()` function.

**Comment by poolerMF** [comment]
when I use 

    $qb->setHint(Query::HINT_INCLUDE_META_COLUMNS, true);

then I will get manyToOne columns

but getSql() **SHOULD NOT RETURN COLUMNS THAT WILL BE NOT FETCHED**
I still think, getSql is not working correctly

**Comment by Ocramius** [comment]
In the test above, try these two:

```php
            $this
                ->em
                ->createQuery(sprintf('SELECT r FROM %s r', DDC0000Root::class))
                ->setHydrationMode(AbstractQuery::HYDRATE_ARRAY)
                ->getSQL()
```

This one is the default:

```php
            $this
                ->em
                ->createQuery(sprintf('SELECT r FROM %s r', DDC0000Root::class))
                ->setHydrationMode(AbstractQuery::HYDRATE_ARRAY)
                ->getSQL()
```

**Comment by poolerMF** [comment]
I don't want to be rude, but you are not answering to my question/point
getSql is not returning real sql that will be executed

**Comment by Ocramius** [comment]
@poolerMF `getSql` returns the SQL for the matching hydration mode (https://github.com/doctrine/doctrine2/issues/7036#issuecomment-362796456)
