### ISSUE TITLE
HTTP 404 in a tutorial page

### ISSUE THREAD

**Issue by Cladis** [doctrine/doctrine2#7043]
Link to [http://www.doctrine-project.org/jira/browse/DDC-213](DDC-213) in /blob/master/docs/en/tutorials/working-with-indexed-associations.rst results in 404

**Comment by Cladis** [comment]
@Ocramius , I have no idea what the correct location is, so no. (Unless you want me to file a dummy pull request)

**Comment by Cladis** [comment]
Ah. Sorry being slow.

**Comment by Ocramius** [comment]
Handled in #7044
