### ISSUE TITLE
Pagination Query improvements

### ISSUE THREAD

**Issue by homersimpsons** [doctrine/doctrine2#7070]
I took a look at the pagination queries http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/pagination.html and still doesn't understand all the needs for those queries.
In my mind, in order to get correct pagination, the "simple" queries are:
1. Get all distinct IDs
2. In php take care of LIMIT and OFFSET (using array_slice)
3. Get only content of sliced IDs

In the upper link its wrote that this is necessary for -ToMany associations, I then do a fast design on [sqlfiddle.com](http://sqlfiddle.com), here is my schema
<details/>
  <summary>SQL DB</summary>

```
CREATE TABLE `docs` (
  `id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `docs_trans` (
  `id` int(11) NOT NULL,
  `docs_id` int(11) NOT NULL,
  `content` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `docs`
  ADD PRIMARY KEY (`id`),
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `docs_trans`
  ADD PRIMARY KEY (`id`),
  ADD KEY `DOCS_TRANS` (`docs_id`),
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,
  ADD CONSTRAINT `DOCS_TRANS` FOREIGN KEY (`docs_id`) REFERENCES `docs` (`id`);

INSERT INTO `docs` () VALUES ();

INSERT INTO `docs_trans` (`docs_id`, `content`) VALUES
(1, 'hello'),
(1, 'hola'),
(1, 'bonjour'),
(1, 'nihao');
```

</details>

So then steps are:
1. `SELECT DISTINCT docs.id FROM docs INNER JOIN docs_trans ON docs_trans.docs_id = docs.id;`
2. `$ids = array_slice($result, $offset, $limit)`
3. `SELECT * FROM docs INNER JOIN docs_trans ON docs_trans.docs_id = docs.id WHERE docs.id IN ($ids);`

Do you have any explanation of why it's not done like this (or resources) ?

**Comment by Ocramius** [comment]
This is actually what is being done internally. 

Ref: https://github.com/doctrine/doctrine2/blob/09266d5361ef9c659c1f665eeefa3d3de0f4e64b/lib/Doctrine/ORM/Tools/Pagination/Paginator.php#L145-L147

**Comment by homersimpsons** [comment]
But the resulting queries doesn't looks like this at all:
1. `SELECT COUNT(*) AS dctrn_count FROM (SELECT DISTINCT id_0 FROM (SELECT ...`
2. `SELECT DISTINCT id_0 FROM (SELECT DISTINCT id_0, start_time_1 FROM (SELECT e0_.id ...`
3. `SELECT ... WHERE e0_.start_time > ? AND e0_.id IN (?)` (Here the WHERE could be removed as it is fulfilled with previous request)

I wrote a simple paginator (which is not really easy to extend) that can explain my though:
```php
<?php
namespace App\Utils;

class Paginator implements \Countable, \IteratorAggregate
{
    protected $count;
    public function __construct($queryBuilder) // queryBuilder which need to be paginated on p.id field
    {
        $offset = $queryBuilder->getFirstResult();
        $limit = $queryBuilder->getMaxResults();
        $qIDs = clone $queryBuilder;
        $qIDs->setMaxResults(null)->setFirstResult(null); // Query to get resulting IDs
        $result = clone $qIDs;
        $qIDs->select('p.id');
        $qIDsResult = array_keys(array_flip(array_column($qIDs->getQuery()->getArrayResult(), 'id'))); // Get unique IDs
        $this->count = count($qIDsResult);
        if ($this->count == 0) {
            $this->result = new \ArrayIterator(array());
        } else {
            $IDs = array_slice($qIDsResult, $offset, $limit);
            print_r($IDs);
            $result->where("p.id IN (:ids)")->setParameters(array(':ids' => $IDs)); // query to get only page IDs
            $this->result = new \ArrayIterator($result->getQuery()->getResult());
        }
    }

    public function count()
    {
        return $this->count;
    }

    public function getIterator()
    {
        return $this->result;
    }
}
```
