### ISSUE TITLE
Need a way to set a default query cache TTL

### ISSUE THREAD

**Issue by Dadibom** [doctrine/doctrine2#7072]
I need to clear the query cache weekly to prevent redis from overflowing, as there's no TTL by default. I've looked for ways to set a global/default TTL but haven't found a way.
Willing to attempt a PR if someone gives me some pointers, I'm not sure where to begin with this one.

**Comment by Ocramius** [comment]
TTL is per-query by design. If some queries are cached indefinitely, then the cleanup task is on your side.

**Comment by Dadibom** [comment]
All queries are cached indefinitely, which is a huge problem. I've set a TTL on query builders to prevent this very issue but the cache still keeps growing at very fast rates (many gb per week). The biggest problem is that we use a (very sensible) redis eviction policy that will evict keys with TTL, but not without it, which means that eventually everything but doctrines query cache will be lost before the server finally just starts ignoring new writes. 

I think it'd make a lot of sense to add a default ttl, even if it's very long (like, a month or two?) because this is a problem that I don't think most people will notice until it's too late.

**Comment by Ocramius** [comment]
Check https://redis.io/topics/lru-cache

**Comment by Dadibom** [comment]
Yeah I'm using a volatile eviction policy, which I don't think is that uncommon
