### ISSUE TITLE
Doctrine paginator with sorting not proper with mysql 5.7 version

### ISSUE THREAD

**Issue by jigarpancholi** [doctrine/doctrine2#7083]
I have used doctrine paginator for pagination. With previous mysql version 5.5 it was working properly with order by. But after upgrading to mysql version 5.7 it doesn't work properly.
Doctrine orm version is v2.4.8.

**Comment by Ocramius** [comment]
Please do upgrade your ORM version: this was already fixed.

**Comment by jigarpancholi** [comment]
@Ocramius can you please let me know which version to upgrade?

**Comment by Ocramius** [comment]
`2.6.0`

**Comment by jigarpancholi** [comment]
2.6.0 is only for php version above 7.1. But I have php7.0 installed on my server.

**Comment by Ocramius** [comment]
Indeed, you will need to plan an upgrade of your PHP version.
