### ISSUE TITLE
Relationships with @Embedded column

### ISSUE THREAD

**Issue by ivaaaan** [doctrine/doctrine2#7094]
Environment: PHP 7.1.7
Doctrine: 2.6
Symfony: 4

I have `@Embeddable` class for id:

    /**
     * @ORM\Embeddable()
     */
    final class Id
    {
        /**
         * @ORM\Id()
         * @ORM\Column(type="string")
         */
        private $id;

        //getters, setters, etc
    }

And two classes that have `@ManyToOne` relationship:

    /**
     * @ORM\Entity()
     */
    final class Gist
    {
        /**
         * @var Id
         *
         * @ORM\Id()
         * @ORM\Embedded(class="App\Entity\Id")
         */
        private $id;
    
        /**
         * @var User
         *
         * @ORM\ManyToOne(targetEntity="App\Entity\User")
         */
        private $user;

        //getters, setters, etc
    }

And `User` class:

    /**
     * @ORM\Entity()
     */
    final class User implements UserInterface
    {
        /**
         * @var Id
         *
         * @ORM\Embedded(class="App\Entity\Id")
         *
         */
        private $id;

        //getters, setters, etc

    }

When I trying to create schema I got error: `No mapping found for field 'id' on class 'App\Entity\User'.`.

**Comment by Ocramius** [comment]
Support of identifiers within `@Embeddable` is not really there yet, sorry.

**Comment by ivaaaan** [comment]
@Ocramius so sad. any plans to realize that?

**Comment by Ocramius** [comment]
Nope, but you can attempt sending a patch :)

**Comment by IvoPereira** [comment]
Were there any developments on this meanwhile @Ocramius?

**Comment by Ocramius** [comment]
No, you would see a public issue/PR for it otherwise.

In open source, you pick it up yourself, @IvoPereira.
