### ISSUE TITLE
v2.6.1 not published on Packagist?

### ISSUE THREAD

**Issue by BenMorel** [doctrine/doctrine2#7101]
I can see that v2.6.1 has been published [8 hours ago](https://github.com/doctrine/doctrine2/releases/tag/v2.6.1), but is [still not available](https://packagist.org/packages/doctrine/orm) on Packagist at the moment:

> v2.6.0 2017-12-20 00:38 UTC

Is there a sync issue, or is this a manual process?

**Comment by Ocramius** [comment]
Known issue: license is malformed in composer.json, needs updating

**Comment by BenMorel** [comment]
How does it sync then?

**Comment by BenMorel** [comment]
Now synced (not sure how).

**Comment by Ocramius** [comment]
Related: https://twitter.com/seldaek/status/968770003477696512
