### ISSUE TITLE
Fatal error: Uncaught Doctrine\ORM\Mapping\MappingException

### ISSUE THREAD

**Issue by flik** [doctrine/doctrine2#7109]
**Here is generated entity code:**

```
<?php



use Doctrine\ORM\Mapping as ORM;

/**
 * User
 *
 * @ORM\Table(name="database_a.user", indexes={@ORM\Index(name="address_id", columns={"address_id"})})
 * @ORM\Entity
 */
class User
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="username", type="text", length=65535, nullable=false)
     */
    private $username;

    /**
     * @var \Address
     *
     * @ORM\ManyToOne(targetEntity="Address")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="address_id", referencedColumnName="id")
     * })
     */
    private $address;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set username
     *
     * @param string $username
     *
     * @return User
     */
    public function setUsername($username)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Get username
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set address
     *
     * @param \Address $address
     *
     * @return User
     */
    public function setAddress(\Address $address = null)
    {
        $this->address = $address;

        return $this;
    }

    /**
     * Get address
     *
     * @return \Address
     */
    public function getAddress()
    {
        return $this->address;
    }
}

<?php



use Doctrine\ORM\Mapping as ORM;

/**
 * Address
 *
 * @ORM\Table(name="database_b.address")
 * @ORM\Entity
 */
class Address
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="phone", type="text", length=65535, nullable=false)
     */
    private $phone;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set phone
     *
     * @param string $phone
     *
     * @return Address
     */
    public function setPhone($phone)
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * Get phone
     *
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }
}


```

**Here is my code I just made little change in generated entity and added database name before table name :**

```
<?php
require_once "vendor/autoload.php";

use Doctrine\ORM\Tools\Setup;
use Doctrine\ORM\EntityManager;

$paths = array(__DIR__."/scr");
$isDevMode = false;

// the connection configuration
$dbParams = array(
    'driver'   => 'pdo_mysql',
    'user'     => 'xxxxx',
    'password' => 'xxxxx',
    'dbname'   => 'database_a',
);

$config = Setup::createAnnotationMetadataConfiguration($paths, $isDevMode);
$em = $entityManager = EntityManager::create($dbParams, $config);

require_once "Entities/User.php";
require_once "Entities/Address.php";

$data = $em->getRepository('User');
$datax = $data->findAll();

foreach($datax as $d) {
  echo '<pre>'; print_r($d);
}
```

**error detail:** 
```
Fatal error: Uncaught Doctrine\ORM\Mapping\MappingException: Class "User" is not a valid entity or mapped super class. in D:\xampp\htdocs\docx\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\MappingException.php:346 Stack trace: #0 D:\xampp\htdocs\docx\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\Driver\AnnotationDriver.php(91): Doctrine\ORM\Mapping\MappingException::classIsNotAValidEntityOrMappedSuperClass('User') #1 D:\xampp\htdocs\docx\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\ClassMetadataFactory.php(151): Doctrine\ORM\Mapping\Driver\AnnotationDriver->loadMetadataForClass('User', Object(Doctrine\ORM\Mapping\ClassMetadata)) #2 D:\xampp\htdocs\docx\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory.php(332): Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata(Object(Doctrine\ORM\Mapping\ClassMetadata), NULL, false, Array) #3 D:\xampp\htdocs\docx\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\ClassMetadataFactory.php(78): Doctrine\Common\Persistence\Mapping\AbstractClassMetada in D:\xampp\htdocs\docx\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\MappingException.php on line 346
```

**Comment by flik** [comment]
without change in entity the error is same...

**Comment by Ocramius** [comment]
`$paths = array(__DIR__."/scr");` ;-)

**Comment by flik** [comment]
I have changed the path:  $paths = array(__DIR__."/Entities");

but still error is coming : 
Fatal error: Uncaught Doctrine\Common\Persistence\Mapping\MappingException: Class 'User' does not exist in D:\xampp\htdocs\docx\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\MappingException.php:96 Stack trace: #0 D:\xampp\htdocs\docx\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\RuntimeReflectionService.php(41): Doctrine\Common\Persistence\Mapping\MappingException::nonExistingClass('User') #1 D:\xampp\htdocs\docx\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory.php(281): Doctrine\Common\Persistence\Mapping\RuntimeReflectionService->getParentClasses('User') #2 D:\xampp\htdocs\docx\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory.php(311): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getParentClasses('User') #3 D:\xampp\htdocs\docx\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\ClassMetadataFactory.php(78): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata(' in D:\xampp\htdocs\docx\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\MappingException.php on line 96

**Comment by Ocramius** [comment]
Please don't paste messages with `#1`, `#2` and such in it, as they cause noise on early project issue :-)

Anyway, the autoloading is up to you: we only provide the metadata loading once a class can be loaded

**Comment by flik** [comment]
these numbers were coming with errors not pasted by me.

**Comment by flik** [comment]
i am unable to solve the problem

**Comment by Ocramius** [comment]
@flik first step (unrelated to ORM) is to make this work:

```php
var_dump(new User());
```

After that works, retry the snippet above.

**Comment by flik** [comment]
here is the output of above code: 
`
object(User)#27 (3) { ["id":"User":private]=> NULL ["username":"User":private]=> NULL ["address":"User":private]=> NULL }`

**Comment by Ocramius** [comment]
Right, now you need to make that same code work in the context of the script that raised:

```
Fatal error: Uncaught Doctrine\Common\Persistence\Mapping\MappingException: Class 'User' does not exist in
```

**Comment by flik** [comment]
**When I not include the entity files with** 
```
require_once "Entities/User.php";
require_once "Entities/Address.php";
```
**then error comes**
`Fatal error: Uncaught Doctrine\Common\Persistence\Mapping\MappingException: Class 'User' does not exist in
`
**other wise** 
`Fatal error: Uncaught Doctrine\ORM\Mapping\MappingException: Class "User" is not a valid entity or mapped super class. in D:\xampp\htdocs\docx\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\MappingException.php:346 Stack trace: #0 D:\xampp\htdocs\docx\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\Driver\AnnotationDriver.php(91): Doctrine\ORM\Mapping\MappingException::classIsNotAValidEntityOrMappedSuperClass('User') #1 D:\xampp\htdocs\docx\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\ClassMetadataFactory.php(151): Doctrine\ORM\Mapping\Driver\AnnotationDriver->loadMetadataForClass('User', Object(Doctrine\ORM\Mapping\ClassMetadata)) #2 D:\xampp\htdocs\docx\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory.php(332): Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata(Object(Doctrine\ORM\Mapping\ClassMetadata), NULL, false, Array) #3 D:\xampp\htdocs\docx\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\ClassMetadataFactory.php(78): Doctrine\Common\Persistence\Mapping\AbstractClassMetada in D:\xampp\htdocs\docx\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\MappingException.php on line 346`

**Comment by flik** [comment]
I have shared the full code of User class in first message in this thread.

**Comment by Ocramius** [comment]
I created a gist at https://gist.github.com/Ocramius/04e50ce818ecfc95c8e5649f7a39c111 with a working setup.

What changed is this:

```diff
diff --git a/test.php b/test.php
index 84bd2d8..4792364 100644
--- a/test.php
+++ b/test.php
@@ -17,7 +17,7 @@ $dbParams = array(
     'dbname'   => 'database_a',
 );
 
-$config = Setup::createAnnotationMetadataConfiguration($paths, $isDevMode);
+$config = Setup::createAnnotationMetadataConfiguration($paths, $isDevMode, null,null,false);
 $em = $entityManager = EntityManager::create($dbParams, $config);
 
 $data = $em->getRepository('User');
```

The problem is that `Setup` creates a simplified annotation driver, which recognizes `@Entity` and `@Table`, but not `@ORM\Entity` or such.

**Comment by flik** [comment]
Now, after the above changes. I am getting this output 

```
Warning: require(C:\Users\feb2018\AppData\Local\Temp\__CG__Address.php): failed to open stream: No such file or directory in D:\xampp\htdocs\docx\vendor\doctrine\common\lib\Doctrine\Common\Proxy\AbstractProxyFactory.php on line 209

Fatal error: require(): Failed opening required 'C:\Users\feb2018\AppData\Local\Temp\__CG__Address.php' (include_path='D:\xampp\php\PEAR') in D:\xampp\htdocs\docx\vendor\doctrine\common\lib\Doctrine\Common\Proxy\AbstractProxyFactory.php on line 209
```

**Comment by Ocramius** [comment]
Use `$isDevMode = true` for now. You will need to generate and properly configure proxies later.

**Comment by flik** [comment]
Bundle of thanks :) man
:+1:

**Comment by flik** [comment]
It is working now.

**Comment by Rakesh1581991** [comment]
Thanks mate !!! its working.
