### ISSUE TITLE
Criteria::expr()->contains() and defensive Type objects

### ISSUE THREAD

**Issue by Michal-sk** [doctrine/doctrine2#7115]
I have a value object for Email. This object checks for a valid email given. If not throws an exception.

Now when i try to use contains the query is build like ('%foo%'), which results in throwing the Email a InvalidArgumentException because %foo% is not a valid emailadres. Am i missing something?

**Comment by Ocramius** [comment]
Can you make a gist of what you are actually doing, and what you expect instead?

**Comment by Michal-sk** [comment]
@Ocramius here's the idea: https://gist.github.com/Michal-sk/d3d3389bdabd14653a7b10dff1e60632

I was thinking that the criteria builder would maybe omit or have a different way of creating the value objects as WHERE arguments. I'm aware that just 'foo' would result in an exception aswel. So would the right way here be to do a custom query?

**Comment by Ocramius** [comment]
It would be simpler to select the sub-field. Assuming your VO is mapped as `foo` inside an `EntityA`, then the field logical name would be something like `EntityA#foo.email`. Matching `foo.email` would suffice.

**Comment by Michal-sk** [comment]
The examples are a bit stripped down. This is all part of a API, in which we can define for what fields we want to search.

It all goes a bit deeper. The Account has a embeddable for a Couple, which has embeddable Persons which have a Email field. So my first question was a bit of. The Email it self is not a VO, but a column type.

```php
    /**
     * @var Email
     * @ORM\Column(name="user_email", type="email", length=64)
     */
    private $email;

**Comment by Ocramius** [comment]
Correct, and I'm suggesting that you compare it by string here. There is no way for you to represent a "partial email" and get past the VO rules anyway: that's specifically what the VO is for.

**Comment by Michal-sk** [comment]
So for http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#custom-mapping-types when we would like to search for 'where Money like 10.%' there would be no way to use the Criteria API?

**Comment by Michal-sk** [comment]
Ok, so this had to do with my Column Type begin converted to the object and than from the object we would get te string value. I fixed this by changing `convertToDatabaseValue()`.

```php
class Email extends Type
{

    /**
     * @param mixed $value
     * @param AbstractPlatform $platform
     * @return string
     */
    public function convertToDatabaseValue($value, AbstractPlatform $platform): string
    {
        // Used for searching.
        if (is_string($value) && $this->hasWildcards($value)) {
            return $value;
        }

        if (is_string($value)) {
            $value = new \Woonon\Domain\Value\Email($value);
        }

        if (!$value instanceof \Woonon\Domain\Value\Email) {
            return '';
        }

        return $value->email();
    }

    /**
     * hasWildcards returns if the given string starts and ends with the % wildcard for SQL.
     * This is used for contains queries.
     *
     * @param string $value
     * @return bool
     */
    private function hasWildcards(string $value)
    {
        $firstIsWildcard = $value[0] === '%';
        $lastIsWildcard = substr($value, -1) === '%';

        return $firstIsWildcard && $lastIsWildcard;
    }
}
```

So basically now when we do the Contains search it immediately returns the raw string value.

**Comment by Michal-sk** [comment]
I still think there should be a more decent way to get this working. But will close for this case,

**Comment by Ocramius** [comment]
@Michal-sk if you have a better definition of what to query for, I'd:

 1. define a VO with the search pattern, which defines what a search pattern looks like in your world
 2. define a read model (interface) that accepts the VO and other parameters
 3. perform the query with stringy stuff in the implementation (infrastructure)

**Comment by Michal-sk** [comment]
Im not sure i see exactly what you have in mind. Ill try to elaborate and what we are doing.

- We have search endpoint /search?resource=user&in_fields=users.person.email&query=michalsk
- There is a function which constructs the whole Criteria, based in the fields and values given.
- Than we grab the resource we want. The resource value maps to a repository class, so for above 'user', will give us the Account repository.
- We pass the Criteria to the Repo to filter.
- We always use a Contains for all the Critaria created, so for above the query will use %michalsk%
- But our Type (Email) has the method `convertToDatabaseValue()`. This method first creates the VO and than returns the string from that VO (see code above).

The problem was because `convertToDatabaseValue` was passing the value as %michalsk% which is not a valid emailadres. What i'm basically looking for is a way to 'just' return the raw string (%michalsk%) when `convertToDatabaseValue` is called beloning to a Critaria call. So for now i just check for %. If you have any suggestion im glad to hear them.

The above structure makes it simple for us to quicke deploy a search endpoint for Products or what ever additional entity we want to support in search.

**Comment by Michal-sk** [comment]
@Ocramius is there any benefit in creating the object when useing `convertToDatabaseValue` besides the obviouse that it's an extra check and the VO decides how to return the string representation.

Because looking at http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/advanced-field-value-conversion-using-custom-mapping-types.html#the-mapping-type i see that we just dump the raw value when the given parameter is not an instance of the VO.
