### ISSUE TITLE
Suggestion: EntityRepository::findChunksBy()

### ISSUE THREAD

**Issue by vaheshadunts** [doctrine/doctrine2#7118]
I understand that we have `AbstractQuery::iterate()`, however it is retrieving rows one by one, my suggestion is to have a chunk size, (i.e. 10000 by default) and `$iterator->next()` will trigger to load next 10000 rows from result.

Thanks.

**Comment by Majkl578** [comment]
I don't really see any benefit in such thing, what is your use case? Optimization?

You can simply implement your own user-land chunk iterator like this:
```php
<?php

declare(strict_types=1);

use Doctrine\ORM\EntityManagerInterface;

$data = new ArrayIterator(range(1, 100));

class ChunkIterator implements IteratorAggregate
{
    /** @var Iterator */
    private $inner;

    /** @var int */
    private $size;

    /** EntityManagerInterface */
    private $entityManager;

    public function __construct(Iterator $inner, int $size, EntityManagerInterface $entityManager)
    {
        $this->inner = $inner;
        $this->size = $size;
        $this->entityManager = $entityManager;
    }

    public function getIterator() : iterable
    {
        $counter = 0;
        $buffer = [];

        while ($this->inner->valid()) {
            $buffer[$this->inner->key()] = $this->inner->current();

            if (++$counter % $this->size === 0) {
                yield $buffer;
                $buffer = [];
                $this->entityManager->clear();
            }

            $this->inner->next();
        }

       if (count($buffer) === 0) {
           return;
       }

        yield $buffer;
        $this->entityManager->clear();
    }
}

foreach (new ChunkIterator($data, 5, $entityManager) as $chunk) {
    var_dump($chunk);
}
```

**Comment by vaheshadunts** [comment]
@Majkl578 I already implemented it in my use case :) wanted to discuss here, if it's smth usable and I can, write test cases and create PR for it.

**Comment by Ocramius** [comment]
I think we discussed this on twitter DM first: I also don't see a real
use-case for this, but you should look at
https://github.com/Ocramius/DoctrineBatchUtils

**Comment by quazardous** [comment]
My use case

loop over 5M+ rows.

what I want to achieve:

An BufferedIterableResult that triggers a SELECT only every 1000 rows (ie).

@Ocramius is it possible with your batch utils ?

**Comment by Ocramius** [comment]
Closing here: this shouldn't go to ORM core.

@quazardous yes, but looping over 5M+ rows will take a while with the ORM: are you sure it is a task for the ORM at all?

**Comment by quazardous** [comment]
@ocramius good question : what could be the overhead of orm ? Object hydration: not much ? I'm aware looping over 5M rows is slow but having chunk of 1000 rows will reduce Select queries from 5M to 5K. At this point readability and code sanity is much more important for me 😊

**Comment by Ocramius** [comment]
> Object hydration: not much ?

A lot.

If you are fine with a task running for a few hours, no big deal, but the ORM really isn't the best fit here.

**Comment by quazardous** [comment]
Even with orm cache on db schema etc ? And single table select ?
So ORM maps select results against entity and keeps track of modified fields. Something else ?

**Comment by Ocramius** [comment]
@quazardous the most efficient way to deal with huge amount of data is to not transmit it over the network in first place: an optimised SQL query wins over any kind of PHP abstraction here.

I'm not saying "don't try", I'm saying that the performance you will experience will be dreadful :-)

**Comment by glensc** [comment]
i'm using @Majkl578 snippet from https://github.com/doctrine/doctrine2/issues/7118#issuecomment-370816775

does the thing. pretty happy with it. previously loaded whole table to memory (2GiB memory usage) now just 1024 chunk having at (64MiB). also the `$em->flush(null);` is faster this way.

**Comment by Ocramius** [comment]
@glensc `ChunkIterator` is precisely what `ocramius/doctrine-batch-utils` does, btw :-)
