### ISSUE TITLE
Reason why EntityManager is closed

### ISSUE THREAD

**Issue by flohw** [doctrine/doctrine2#7124]
Hi there,

I get the famous exception "The EntityManager is closed". But I can't find a way to know why the entity manager has been closed without following the original thrown exception and dump it to know the exact reason.
Did I miss something ? Or is it really impossible without doing this ? The only response I found on the web is to create a resettable entity manager but I don't think this is a good idea.

Hope this is not a deplicate question.

**Comment by Ocramius** [comment]
>  I can't find a way to know why the entity manager has been closed without following the original thrown exception

Yeah, the original exception isn't retained: that's up to you to do in first place :-)

**Comment by flohw** [comment]
Thank you for the quick answer ! :open_mouth: 
I think it could be a good idea to add the original exception information. This could help to debug some times.

In my case I am in a transaction with a loop to insert multiple entities and the error is thrown because at some point it breaks a unique constraint in a many to many association table. And the exception is thrown on the commit. In my catch I execute a rollback then the exception is "transformed" to "The EntityManager is closed". Maybe I shouldn't have to call rollback ?

**Comment by Ocramius** [comment]
> I think it could be a good idea to add the original exception information. This could help to debug some times.

Not really - this is something you should do on your side with something like a breadcrumbs logger (see for example https://docs.sentry.io/learn/breadcrumbs/ )

 >  In my catch I execute a rollback then the exception is "transformed" to "The EntityManager is closed".

`EntityManager#flush()` already performs a `ROLLBACK;` internally

**Comment by Ocramius** [comment]
>  In my catch I execute a rollback 

Also, you have the original exception here: re-throw it.

**Comment by flohw** [comment]
This is what I've done but the rollback just above throw a "The EntityManager is closed". So bad designed code.

Thank you for your help :smiley:

**Comment by M-tower** [comment]
It happened to me too
After that I modify a database table.
The both instructions: modification of the table and creation of the EntityManager + dql (causing the closure of EntityManager) were in the same function.
I solved the problem at my level by separating them in 2 distinct functions.

If it can help...
