### ISSUE TITLE
results are empty ? what is wrong no error is coming ?

### ISSUE THREAD

**Issue by flik** [doctrine/doctrine2#7129]
I have configured database with doctrine 2 and trying this tutorial: [http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/native-sql.html](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/native-sql.html)

I can access the data by this way:
```php
$repo = $em->getRepository('users');
$users = $repo->findAll();
```

I can not access the data by this way:
```php
<?php
use Doctrine\ORM\Query\ResultSetMapping;

$rsm = new ResultSetMapping();
// build rsm here

$query = $entityManager->createNativeQuery('SELECT id, name, discr FROM users WHERE name = ?', $rsm);
$query->setParameter(1, 'romanb');

$users = $query->getResult();
```
what is wrong ?

**Comment by Ocramius** [comment]
You have an empty `ResultSetMapping` there.

**Comment by flik** [comment]
What should be in ResultSetMapping  ? It is same as in tutorial. @Ocramius

**Comment by Ocramius** [comment]
See `// build rsm here`. You'd need to map the entitoes and entity fields there.

I strongly suggest avoiding this API if you didn't get to explore further yourself, as it only gets more and more complex, so you need to be able to walk without any aid before attempting to run.
