### ISSUE TITLE
Joining on a table with condition ON not working  

### ISSUE THREAD

**Issue by benschumi** [doctrine/doctrine2#7193]
I want to do a particular ON on a innerJoin

I have a PROPERTIES table that has a relationship with an ADDRESSES table, which is linked to a CITY table.
A properties can have a real adresses and a fake adresses.
I want to retrieve all cities that come from real addresses or false addresses, but do not take real address cities if there is a false address.

This SQL work perfectly 

`
SELECT DISTINCT(city_name)
FROM city c 
INNER JOIN address a ON c.id = a.id_city
INNER JOIN property p ON a.id = t1_.id_address_fake OR (a.id = p.id_address AND p.id_address_fake IS NULL)
`

With doctrine i tried to do this

`                            $query->join('c.addresses', 'a')
                                ->innerJoin('a.properties', 'p', Expr\Join::ON,
                                    $query->expr()->orX(
                                        $query->expr()->eq('a.id', 'p.adresseFake'),
                                        $query->expr()->andX(
                                            $query->expr()->eq('a.id', 'p.adresseReal'),
                                            $query->expr()->isNull('t.adresseFake')
                                        )
                                    )
                                );
`

I got an errror 

> [Syntax Error] line 0, col 108: Error: Expected end of string, got 'ON'

`SELECT c FROM MyBundle\Entity\City c INNER JOIN c.addresses a INNER JOIN a.properties p ON a.id = p.adresseFake OR (a.id = p.adresseReal AND t.adresseFake IS NULL) `

If i use WITH instead of ON, i don't have error but Doctrine add an Extra ON and the result is wrong.

Did I do something wrong ?

**Comment by plfort** [comment]
Try Expr\Join::WITH instead

**Comment by Ocramius** [comment]
`ON` is designed to perform manual joins. In your case, you already have a well-defined association `a.properties`.

IMO, we should just drop `ON` at some point /cc @guilhermeblanco

**Comment by benschumi** [comment]
My bad, i copy paste the wrong SQL, i corrected my post.

This is the correct inner join that works with SQL 

`INNER JOIN property p ON a.id = t1_.id_address_fake OR (a.id = p.id_address AND p.id_address_fake IS NULL)`

If i use WITH with querybuilder, it create this innejoirn

`INNER JOIN a.id = p.id_address AND (property p ON a.id = t1_.id_address_fake OR (a.id = p.id_address AND p.id_address_fake IS NULL))`

This result is totally different.

I really need to make a manual join.

Thanks :)

**Comment by plfort** [comment]
Did you try something like this ?
$query->join('c.addresses', 'a') ->innerJoin(**Property::class**, 'p', Expr\Join::ON, ...

**Comment by benschumi** [comment]
`
$query = $er->createQueryBuilder('c');$query->join('c.addresses', 'a')
    ->innerJoin(Property::class, 'p', Expr\Join::ON,
        $query->expr()->orX(
            $query->expr()->eq('a.id', 'p.addressFake'),
            $query->expr()->andX(
                $query->expr()->eq('a.id', 'p.adress'),
                $query->expr()->isNull('p.addressFake')
                )
        )
    );
`

I got 
> An exception has been thrown during the rendering of a template ("[Syntax Error] line 0, col 137: Error: Expected Doctrine\ORM\Query\Lexer::T_WITH, got 'ON'").

**Comment by Ocramius** [comment]
Can you please just use plain DQL in this issue? Going through the `QueryBuilder` without a reason to do so just introduces a further layer of complexity in analysing the problem.

**Comment by benschumi** [comment]
The DQL result from the QueryBuilder :

> SELECT c FROM MyBundle\Entity\City c 
INNER JOIN c.addresses a 
INNER JOIN MyBundle\Entity\Property t ON a.id = t.addressFake OR (a.id = p.adresse AND p.addressFake IS NULL)

**Comment by Ocramius** [comment]
Yeah, that requires a `WITH` (not an `ON`) as per http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html#ebnf

**Comment by benschumi** [comment]
Thank you a lot.
It work with the Property::class and the WITH

**Comment by Ocramius** [comment]
Closing here: please do send a patch to the documentation if you can clarify your doubts based on discussion in here.
