### ISSUE TITLE
Passing tuples and 2d array parameters

### ISSUE THREAD

**Issue by tszymanek** [doctrine/doctrine2#7206]
I've got a similar issue to #6200 but regarding the DQL Parser.

I can't pass a tuple with f.i. `(e.id, e.revision)` in
`$qb->expr()->in('(e.id, e.revision)', ':idRevision')` 'cause it expects a `T_CLOSE_PARENTHESIS` but gets a comma.

Probably the evaluation of the parameter being an array of arrays won't work as well.
`$idRevision = array([1001, 1], [1002, 1], [1003, 2])`

**Comment by Ocramius** [comment]
> I can't pass a tuple with f.i. `(e.id, e.revision)` in
`$qb->expr()->in('(e.id, e.revision)', ':idRevision')` 'cause it expects a `T_CLOSE_PARENTHESIS` but gets a comma.

Indeed, `in()` works against a single field in DQL.

 > Probably the evaluation of the parameter being an array of arrays won't work as well.
`$idRevision = array([1001, 1], [1002, 1], [1003, 2])`

This is a limitation of the DBAL type system: it would require a new major version to re-design the type system to not rely on type strings, but rather a type DSL.

**Comment by Ocramius** [comment]
Closing as `can't fix` here - not something that we can work on in the near future.
