### ISSUE TITLE
Add default value for discriminator column in "SINGLE_TABLE" inheritance

### ISSUE THREAD

**Issue by yonisolo** [doctrine/doctrine2#7227]
### Feature Request
Add default value for discriminator column in "SINGLE_TABLE" inheritance

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no
| Environment | Symfony 4.0

#### Summary
Hi,
I implemented inheritance on an Entity with single table type in an existing table. 
There is no problem with new items but could we add a default value for this column for existing row.
because the old row are not retrieved because they are empty (not null) by default and this is quite a pain to discover it...
Presently we did it with migration but it could help if we can set it in the discriminatorColumn attribute.

Here is the annotations:

> InheritanceType("SINGLE_TABLE")
> DiscriminatorColumn(name="itype")
> DiscriminatorMap({"item" = "Item", "item2" = **"ItemPlusUltra"})
> SQL statement: ALTER TABLE item ADD itype VARCHAR(255) NOT NULL;

if the following or variant could be possible, it would be great:

> InheritanceType("SINGLE_TABLE")
> **DiscriminatorColumn(name="itype", default="item")**
> DiscriminatorMap({"item" = "Item", "item2" = "ItemPlusUltra"})
> SQL statement: ALTER TABLE item ADD itype VARCHAR(255) DEFAULT 'item';

It could be the top non abstract parent as default as well...
so it could set the default value in the database structure.
This may happen only with single table inheritance.
Thank you

**Comment by Ocramius** [comment]
> There is no problem with new items but could we add a default value for this column for existing row.

I clarified on `default` values last night: it's not going to be added here.

See https://github.com/doctrine/dbal/issues/3142#issuecomment-389698021
