### ISSUE TITLE
How do you map 2 objects into a table? The A object contains the B object

### ISSUE THREAD

**Issue by acodercat** [doctrine/doctrine2#7232]
|    Q        |   A
|------------ | -----
| Version     | 2.5.0

### Support Question

How do you map 2 objects into a table? The A object contains the B object

**Comment by acodercat** [comment]
please

**Comment by AlessandroMinoccheri** [comment]
Can you please describe more your problem with a proper example?

**Comment by Ocramius** [comment]
Please look at https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/inheritance-mapping.html then 👍
