### ISSUE TITLE
Incorrectly(?) generated table name for many-to-many relation.

### ISSUE THREAD

**Issue by shmigandrew** [doctrine/doctrine2#7233]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | x.y.z

#### Summary

many-to-many join table is named after class name + class name, but not as expected - table name + class name.

#### Current behavior

```php
/**
* @ORM\Entity(...)
* @ORM\Table(name="some_name")
*/
class A {
   /** @ORM\ManyToMany(targetEntity="B") */
   private $connectionToB;
}
```

```php
/**
* @ORM\Entity(...)
*/
class B {
   /** @ORM\ManyToMany(targetEntity="A") */
   private $connectionToA;
}
```
Many-To-Many join table name will be `a_b`.

#### Expected behavior

Many-To-Many join table name should be `some_name_b`.
If we specify table name it means that the final table name in DB should consider this option.

What if I already have a table with `a` name in my DB? This will definitely confuse, having a non related table name in many-to-many join table name.

**Comment by Majkl578** [comment]
That is actually correct behavior, just like entities have implicit table naming, join tables have too.
If you need custom name for your join table, you need to specify `@ORM\JoinTable`, as documented [here](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#many-to-many-unidirectional) and [here](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/annotations-reference.html#jointable).

> What if I already have a table with a name in my DB?

If you create two User entities in different namespaces, you end up in the same situation. Default naming strategy is mostly for convenience, it doesn't (and can't) cover conflicts etc.
