### ISSUE TITLE
how to do query json filed?

### ISSUE THREAD

**Issue by acodercat** [doctrine/doctrine2#7238]
|    Q        |   A
|------------ | -----
| Version     | 2.6.0

how to do query json filed?

### Support Question

how to do query json filed?

**Comment by Ocramius** [comment]
ORM does not have capabilities to operate on JSON fields: use your DB's specific SQL operators or design [custom DQL functions](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/cookbook/dql-user-defined-functions.html)
