### ISSUE TITLE
removeElement method doesn't remove element on EXTRA_LAZY collection

### ISSUE THREAD

**Issue by yurybykov** [doctrine/doctrine2#7246]
### Bug Report

| Version     | v2.6.1

#### Current behavior

The element of collection is not removed. If it check collection element's count, it won't change.

#### How to reproduce

Retrive parent entity from DB. Try to remove element from property (that collection).
$entity->some_collection->removeElement($element).

#### Expected behavior

removeElement must remove element from collection.

**Comment by flaushi** [comment]
Clear the EntityManager after removal, then refetch the entity.

**Comment by Ocramius** [comment]
Closing here due to missing tests: from what I can see, this is a possible (typical) owning/inverse side misconception.

```php
$entity->some_collection->removeElement($element).
```

This call only works when combined with `Doctrine\ORM\EntityManager#flush()` and if the `some_collection` is the owning side.

See also https://gist.github.com/Ocramius/3121916
