### ISSUE TITLE
Updating "migration_versions" to utf8mb4_unicode_ci

### ISSUE THREAD

**Issue by Syndesi** [doctrine/doctrine2#7247]
Hi,

I'm using Doctrine 2 as a part of Symfony (4.2) and therefore don't know where to put this idea, but because Doctrine manages the DB I think this is the right one.
Basically all my tables are automatically using the `utf8mb4_unicode_ci` collation but the `migration_versions` table just uses `utf8_unicode_ci`.
I know that the encoding formats aren't important at all because only numbers are stored, but I would find it nice if all tables would have the same encoding ;)

**Comment by jwage** [comment]
This belongs in the doctrine/migrations repository issue tracker. But this is fixed in master and will be released in 2.0

It was fixed here https://github.com/doctrine/migrations/pull/679

**Comment by jwage** [comment]
This belongs in the doctrine/migrations repository issue tracker. But this is fixed in master and will be released in 2.0

It was fixed here https://github.com/doctrine/migrations/pull/679
