### ISSUE TITLE
 Eliminate dependency on doctrine/common

### ISSUE THREAD

**Issue by Majkl578** [doctrine/doctrine2#7249]
What is used through `doctrine/common` dependency:
* `Doctrine\Common\Util\Debug` - likely to be dropped, only used in one console  command and one test
* `Doctrine\Common\Event*` to be extracted to `doctrine/event-manager` (for now)
* `Doctrine\Common\Persistence` -> needs `doctrine/persistence`
* `Doctrine\Common\Util\Inflector` -> should be switched to `doctrine/inflector`
* `Doctrine\Common\Lexer` -> should be switched to `doctrine/lexer` (later removed)
* `Doctrine\Common\{PropertyChangedListener,NotifyPropertyChanged}` -> likely to be merged into ORM

cross references:
DBAL: https://github.com/doctrine/dbal/issues/3176
Migrations: https://github.com/doctrine/migrations/issues/722

**Comment by Jean85** [comment]
Will this be feasible in the 2.x branch? Or are we forced to wait for 3.x due to BC?

**Comment by Ocramius** [comment]
Due to BC reasons, dropping the dependency on `Doctrine\Common` will be problematic here, so it will be done in such a way that the components are no longer used, but still added as dependency.

**Comment by Jean85** [comment]
So requiring the split packages and using Composer's `provide` will be a feasible upgrade path? Great!

**Comment by Majkl578** [comment]
I don't think it's possible in 2.x, especially because of the Doctrine\Common\Proxy dependency.

**Comment by Jean85** [comment]
Umh... Maybe we can write down a shim/polyfill that uses ProxyManager under the hood, but provides aliases for Doctrine\Common\Proxy? Or the behavior is too different?

**Comment by Ocramius** [comment]
That's *a lot* of work that really isn't worth it. I already tried working towards a BC-friendly way of doing it, and it is feasible, but its at least a couple of full days of work.

**Comment by Majkl578** [comment]
Handled in #7497.
