### ISSUE TITLE
GetOneOrNullResult() fails for joined collections using OneToMany

### ISSUE THREAD

**Issue by axelcho** [doctrine/doctrine2#7252]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.6.x

#### Summary

When I do getOneOrNullResult() for a joined collection for only one result, but it throws nonUnique exception. 

#### Current behavior

Full code:

        $qb = $this->_em->createQueryBuilder()
            ->select('u', 'i')
            ->from('User\Entity\Users', 'u')
            ->innerJoin('u.iraLoginGroup', 'i')
            ->where('i.enteredUserId=:repId')
            ->andWhere('u.id=:id')
            ->setParameter('repId', $repId)
            ->setParameter('id', $id);

        try {
            return $qb->getQuery()->getOneOrNullResult();
        } catch (NonUniqueResultException $e) {
        }

     the relationship between Users and IraLoginGroup is OneToMany.
    So there are multiple `IraLoginGroup` elements. But there is only one single Users entity.

  

#### How to reproduce

apply GetOneOrNullResult() on joined collections including OneToMany() relations. 

#### Expected behavior

It should pass UniqueResult(), as the top entity is unique.

**Comment by Ocramius** [comment]
This is normal: if your intent is to fetch-join, then you need to `->leftJoin()`. 

Also, **DO NOT** filter on a fetch-joined result, as that can lead to broken hydration that stays in memory after the query is performed, leading to broken application state.
