### ISSUE TITLE
Orm QueryBuilder returns private results

### ISSUE THREAD

**Issue by hsntngr55** [doctrine/doctrine2#7261]
version 2.4.8

QueryBuilder returns result with private visibility. I cant access them outside even if repository class
```php
public function getPostById($id)
    {
        $post = $this->findOneBy([
            "id" => $id
        ]);
        var_dump($post);
    }
```
it returns
```
private 'id' => int 78
private 'title' => string 'sample-title' (length=12)
private 'slug' => null
private 'content' => string 'sample content' (length=14)
private 'createdAt' => 
```
how can I change it as public ?

**Comment by jwage** [comment]
Your class has the properties defined as public. You need to either make the properties public in the class or access them with getters. It is best to use a public API with getters instead of making the properties public.

**Comment by hsntngr55** [comment]
how to make an public api include these getters  ? Could you give me a small example ?

**Comment by Ocramius** [comment]
@hsntngr55 that's part of the design of your entities - you'd have to add some interaction (`public function`) on the object.

A simplistic example:

```php
class User
{
    private $username;
    public function toUsername() : string { return $this->username; }
}
```
