### ISSUE TITLE
remove unique @JoinColumn  orm:schema-tool:update --force

### ISSUE THREAD

**Issue by phpbook-sources** [doctrine/doctrine2#7267]
when remove **unique** attribute from **@JoinColumn**  

the cmd **notation orm:schema-tool:update --force**  does not remove the database unique index

I'm using **PostgreSQL 9.6 Server** and   **doctrine/orm": "2.4.***

**Comment by Ocramius** [comment]
Doctrine ORM 2.4.x is *extremely* old: please upgrade to 2.6.x and re-open a new issue if applicable.

**Comment by phpbook-sources** [comment]
Sorry, its working perfectly well.
I was using @OneToOne relation and that creates the unique index
