### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by Ezypayne** [doctrine/doctrine2#7269]
|    Q        |   A
|------------ | -----
| Version     | x.y.z

### Support Question

Fatal error: Call to a member function evictAll() on null in  C:\wamp\www\hrm\symfony\lib\vendor\symfony\lib\plugins\sfDoctrinePlugin\lib\vendor\doctrine\Doctrine\Connection.php  on line 1239
--

1 | 1.9864 | 24971592 | sfContext->shutdown(  ) | ...\sfContext.class.php:0
2 | 2.0005 | 24963496 | sfDatabaseManager->shutdown(  ) | ...\sfContext.class.php:605
3 | 2.0005 | 24963624 | sfDoctrineDatabase->shutdown(  ) | ...\config_core_compile.yml.php:857
4 | 2.0006 | 24963816 | Doctrine_Manager->closeConnection(  ) | ...\sfDoctrineDatabase.class.php:165
5 | 2.0006 | 24964000 | Doctrine_Connection->close(  ) | ...\Manager.php:580
6 | 2.0006 | 24964800 | Doctrine_Connection->clear(  ) | ...\Connection.php:1268

**Comment by Ocramius** [comment]
This is for an unsupported and since long unmaintained version of the ORM: https://github.com/doctrine/doctrine1
