### ISSUE TITLE
Why doctrine does so many sql queries ?

### ISSUE THREAD

**Issue by niklass08** [doctrine/doctrine2#7299]
Why doctrine does so many sql queries ?

Hello guys,

 I'm new to doctrine and i'm working on an existing project that uses it. Im facing a performance issue : after fetching an entity from the database and doing some process on it's field I want to save it back. To do so I'm using the flush method. The issue is that in order to save the modification in the database doctrine does 4000+ queries including 3000+ delete and UPDATE to change the updated_at column on field that i didn't even modified. These 4000+ queries are taking up +3.5 sec. do you guys have any clue why doctrine does so much queries and why it is so long ?

 Thank in advance for your answers !

**Comment by Ocramius** [comment]
Sorry, on the road, so I can't browse for proper links, but you may need to:

 1. Read up on "the n+1 queries problem in ORMs
 2. Fetch joins in the doctrine-project.org website
 3. Read
https://ocramius.github.io/blog/doctrine-orm-optimization-hydration/

**Comment by ostrolucky** [comment]
Unfortunately I have to close this, as this is not a support forum and this is not an actual issue. Try to use some of our [community channels](https://www.doctrine-project.org/community/).
