### ISSUE TITLE
Switches instead of normal ifs and elseifs

### ISSUE THREAD

**Issue by ZielonyBuszmen** [doctrine/doctrine2#7311]
|    Q        |   A
|------------ | -----
| Version     | 2.5

### Support Question
I have small question about code and architecture.

In source code I found odd switches like that: https://github.com/doctrine/doctrine2/blob/2.5/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php#L399
```
switch (true) {
	case isset($this->class->fieldNames[$columnName]):
		$fieldName  = $this->class->fieldNames[$columnName];
		$column     = $this->quoteStrategy->getColumnName($fieldName, $this->class, $this->platform);
		if (isset($this->class->fieldMappings[$fieldName]['requireSQLConversion'])) {
			$type        = Type::getType($this->columnTypes[$columnName]);
			$placeholder = $type->convertToDatabaseValueSQL('?', $this->platform);
		}
		break;
	case isset($this->quotedColumns[$columnName]):
		$column = $this->quotedColumns[$columnName];
		break;
}
```

In newer version on master (3.0) there are similar occurences of switch, but a bit more civilized. Example:
https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php#L1533

```
 switch (true) {
	case ($property instanceof VersionFieldMetadata):
		// Do nothing
		break;
	case ($property instanceof LocalColumnMetadata):
		if (($property instanceof FieldMetadata
			...
```

Why do you use that tricky code? Is it faster than normal if()..elseif()?

**Comment by ostrolucky** [comment]
I'm sorry but I have to close this, as this is not an actual issue. Drop the question in one of our [community channels](https://www.doctrine-project.org/community/).

**Comment by Ocramius** [comment]
I think this was just a leftover - already fixed in `master` IIRC
