### ISSUE TITLE
Deprecate and remove UuidGenerator

### ISSUE THREAD

**Issue by Majkl578** [doctrine/doctrine2#7312]
Platform-specific GUIDs were deprecated in https://github.com/doctrine/dbal/pull/3212 since the format is inconsistent across platforms.

For the time being, consumers are encouraged to migrate to https://github.com/ramsey/uuid + https://github.com/ramsey/uuid-doctrine (preferably without using GeneratedValue, but passing/creating the Uuid object through/in the constructor).

Deprecate in 2.7, drop in 3.0.

**Comment by Ocramius** [comment]
Handled in #7330
