### ISSUE TITLE
Documentation: default version should be a stable one

### ISSUE THREAD

**Issue by niekbosch** [doctrine/doctrine2#7320]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

I am just starting with Doctrine, never used it in the past. So when I go to your website, I click on the big 'getting started' button and follow the instructions, but it does not work. Same problem as this issue: #7135 

So it turns out that the default documentation version (3.0 at this moment) is not the latest stable, but is a future release. And because the instructions themselves tell me to install the latest stable release, it does not work. I would rather start with the latest stable, but it would be really helpful if the default documentation version would be the same. As somebody who does not know Doctrine, even if the version button had caught my attention, I would not have known that 3.0 is not a stable, released version.

**Comment by Jean85** [comment]
This seems to have been solved in doctrine/doctrine-website#194
