### ISSUE TITLE
Documentation about Yaml, mention it as discouraged to use?

### ISSUE THREAD

**Issue by iltar** [doctrine/doctrine2#7321]
|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.6

#### Summary

The documentation page about [Yaml](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/yaml-mapping.html) does not mention anything about it being removed/unsupported in the future. I think it's a good idea to mention on here that it's discouraged to use Yaml as configuration.

Whenever I see people suggest to not use Yaml because it's going to be removed as core supported configuration, the response is usually "oh I did not know that".

**Comment by Ocramius** [comment]
@doctrine/team-documentation can we do something about this one?

**Comment by weaverryan** [comment]
I would be +1 for removing it on the latest minor version docs. Basically, because it *is* now deprecated, why show it at all? Older versions of the docs will still exist for existing users to reference. We can cleanup the new version right now.

**Comment by iltar** [comment]
It's already known to be deprecated and 2.6 is the current documentation. If a developer takes a look at the documentation, and doesn't see a deprecation, chances are that everything is going to be created in Yaml. This is a waste of time for the developer because it's already known to disappear with 3.0. Not letting the developer know this as soon as possible, will thus result in extra work while it was not necessary.

**Comment by SenseException** [comment]
@iltar I've created PR #7374. Does it cover this issue?

**Comment by Majkl578** [comment]
#7374 has been merged into 2.6.
https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/yaml-mapping.html#yaml-mapping
