### ISSUE TITLE
Using ManagerRegistry within commands

### ISSUE THREAD

**Issue by dominikzogg** [doctrine/doctrine2#7334]
### Feature Request

I would suggest to use the manager registry to get the entity manager within Commands.
For example: https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Tools/Console/Command/InfoCommand.php#L44

What do you think about that? Would make the instantiation

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | yes/no (depends on implementation)

**Comment by Ocramius** [comment]
I'd probably rather deprecate the manager registry, tbh...
