### ISSUE TITLE
IdentifierFlattener does not generate unique IDs

### ISSUE THREAD

**Issue by nreynis** [doctrine/doctrine2#7349]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.x & 3.x

#### Summary

When using composite identifier with CustomTypes the IdentitierFlatener does not generate correct ids.
It will use implicit to string conversion, which may result in identifier collision.

This is the same class of bug that https://github.com/doctrine/doctrine2/issues/7251

#### Current behavior

IdentitierFlatener generate ambiguous ids, which result in the wrong object being hydrated.

#### Expected behavior

The string representation of the identifier field must be the same that it's unique representation in database. Therefore IdentifierFlattener should use the `convertToDatabaseValue` method of the `Type`

https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Utility/IdentifierFlattener.php#L89

```
//$flatId[$field] = $id[$field];
$fieldType = $class->fieldMappings[$field]['type'];
$reflect = new \ReflectionClass($this->unitOfWork);
$prop = $reflect->getProperty('em');
$prop->setAccessible(true);
$platform = $prop->getValue($this->unitOfWork)->getConnection()->getDatabasePlatform();
$prop->setAccessible(false);
$flatId[$field] = \Doctrine\DBAL\Types\Type::getType($fieldType)->convertToDatabaseValue($id[$field], $platform);
```

Another solution would be to disallow using non native types in discriminator columns, primary keys, etc. Because the ORM internal state does not safely handle the values.

**Comment by Ocramius** [comment]
Due to performance issues, this was a conscious decision, and we do indeed know about the possible collisions.

An alternative would be to use `serialize()` on the identifier values (if they are not associations).

**Comment by nreynis** [comment]
So if one want to use Custom Types in identifier or discriminator column this is the responsability of the developper to make sure the type natural `toString` conversion is unique and unambiguous ?

**Comment by Ocramius** [comment]
Currently, yes.

As mentioned before, using `serialize()` would also work, but we need benchmarks, because this is at the very core of the ORM.

**Comment by nreynis** [comment]
Thank you for the answer. I'll adapt my code to this constraint.

**Comment by Ocramius** [comment]
If you still want to try a patch, it is a welcome improvement to the
codebase for 3.x 👍

**Comment by nreynis** [comment]
I modified my code as suggested and managed to workaround the issue.

However the workaround does not solve the related issue: https://github.com/doctrine/doctrine2/issues/7251

The object can not be hydrated back without patching ObjectHydrator.

I close this issue but leave theother one opened.
