### ISSUE TITLE
We need to add isset to this key

### ISSUE THREAD

**Issue by AndreyMashukov** [doctrine/doctrine2#7359]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | /no

#### Summary

We need to add isset to this key
![image](https://user-images.githubusercontent.com/24682497/44269429-2ad35d80-a23d-11e8-8930-1b6d5657a81d.png)

and in enable too. A can make it

**Comment by Ocramius** [comment]
@AndreyMashukov a failing test is required *FIRST*.

**Comment by delirehberi** [comment]
I review this file and run a test I think getFilter method already validate at line Doctrine/ORM/Query/FilterCollection.php:135. I still add a test for re-validate it. I send pull request, you can close my pull-request if not necessary test for this problem.

**Comment by AndreyMashukov** [comment]
![image](https://user-images.githubusercontent.com/24682497/45041659-82f9c480-b071-11e8-9965-a97fc212cff8.png)

types declarations was added for missing types

**Comment by AndreyMashukov** [comment]
And we never can to get line with unset with not enabled filter, because `getFilter` function checks filter, but we need to have test for it! :)

**Comment by AndreyMashukov** [comment]
oh, it's need for latest version (type hinting)

**Comment by AndreyMashukov** [comment]
@Ocramius It's good, we need more tests

**Comment by Ocramius** [comment]
@AndreyMashukov I integrated the test in `master`, but the test is passing without change, so it does not reproduce the issue in this ticket.

**Comment by AndreyMashukov** [comment]
@Ocramius I can't understand why we need this Exception? I think it will be simple if we ignore disabling if filter was not enable. I think it's better way. Then we will not need to check filter before disabling

**Comment by AndreyMashukov** [comment]
@Ocramius, something like this:

```php 
 /**
     * Disables a filter.
     *
     * @param string $name Name of the filter.
     *
     * @throws \InvalidArgumentException If the filter does not exist.
     */
    public function disable($name)
    {
        if (!$this->isEnabled($name)) {
            return;
        }

        unset($this->enabledFilters[$name]);

        // Now the filter collection is dirty
        $this->filtersState = self::FILTERS_STATE_DIRTY;
    }
```

**Comment by Ocramius** [comment]
First, it is a BC break to remove the exception, as other code may rely on it, second it is correct that you shouldn't blindly enable/disable stuff that is not there, as these filters are not just a collection, but alter the behaviour of everything in the ORM.

**Comment by AndreyMashukov** [comment]
If not enabled - do nothing. but always I need to check it, why!?
