### ISSUE TITLE
PR#7291 Incorrectly made transaction required for EntityManager::find() with optimistic locking

### ISSUE THREAD

**Issue by timdev** [doctrine/doctrine2#7366]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.6.2

#### Summary

2.6.2 introduced a BC break when using OPTIMISTIC locking.

See: https://github.com/doctrine/doctrine2/pull/7291#issuecomment-415106167

#### Previous behavior

EntityManager::find() with LockMode LockMode::OPTIMISTIC worked outside of a transaction.

#### Current behavior

Calling EntityManager::find() with LockMode::OPTIMISTIC outside of a transaction throws a TransactionRequiredException

#### How to reproduce

```
// In ORM 2.6.2
$entityManager->find(MyEntity::class, $id, \Doctrine\DBAL\LockMode::OPTIMISTIC);
```

**Comment by Majkl578** [comment]
Fixed by #7367, will land in 2.6.3.
