### ISSUE TITLE
Referenced column name forced to be "id" in ManyToMany relationships

### ISSUE THREAD

**Issue by rayvar** [doctrine/doctrine2#7369]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.5.4

#### Summary
Trying to define a bidirectional manyToMany relationship using YML format as documented in https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#many-to-many-bidirectional does not work when the User entity does not have an id column specifically named "id". My column is named "username" and I've specified it so.

#### Current behavior
In SchemaTool.php line 656:
                                                                                                                           
  [Doctrine\ORM\ORMException]                                                                                              
  Column name `id` referenced for relation from AppBundle\Entity\User towards AppBundle\Entity
\UsersGroup does not exist. 

I've inspected the execution and it seems that the ORM is trying to create a table called "users_group_user"  where the join column names are always "id".
If I change the "username" field to match the name "id" the correspondent table and an EXTRA, NON REQUIRED, table gets created.
I ignore why this table is being created if I've set the join table name as "App_UserGroupMembers" (see further).

DESCRIBE users_group_user;
+----------------+--------------+------+-----+---------+-------+
| Field          | Type         | Null | Key | Default | Extra |
+----------------+--------------+------+-----+---------+-------+
| users_group_id | varchar(255) | NO   | PRI | NULL    |       |
| user_id        | varchar(255) | NO   | PRI | NULL    |       |

#### How to reproduce

[User]
id:
        username:
            type: string
            length: 255
....
manyToMany:
        groups:
            targetEntity: AppBundle\Entity\UsersGroup
            inversedBy: members
            joinTable:
                    name: App_UserGroupMembers
                    joinColumns:
                        user:
                            referencedColumnName: username
                    inverseJoinColumns:
                        group:
                            referencedColumnName: id
[UsersGroup]
id:
        id:
            type: string
            length: 255
[....]
manyToMany:
        members:
            targetEntity: AppBundle\Entity\User
            mapppedBy: groups

#### Expected behavior
App_UserGroupMembers table should be created correctly. No extra tables should be created

**Comment by Ocramius** [comment]
The YAML driver is deprecated: please try to move to annotations or XML, which are validated statically.

Also, please upgrade your ORM version to at least 2.6.x

Closing as `won't fix`

**Comment by rayvar** [comment]
Correction: version was 2.6.1.
I'll migrate to XML and try again.
