### ISSUE TITLE
Does doctrine support multi-databases ?

### ISSUE THREAD

**Issue by waghanza** [doctrine/doctrine2#7384]
|    Q        |   A
|------------ | -----
| Version     | 2.5.11

### Support Question

Hi,

I can read in `symfony` **documentation** that we can use `doctrine` to connect differents sources (my use case is **2** distinct database, ideally one `postgresql` and one `mysql) => https://symfony.com/doc/current/doctrine/multiple_entity_managers.html

However, I've made https://github.com/waghanza/multidb-sf/tree/54c9bf2b9aaccf4860b0b42ac89b52cff0f11583 to use **2** different database (`mysql` for **now**), but I face
~~~php
 (3/3) TableNotFoundException

An exception occurred while executing 'SELECT t0.id AS id_1, t0.firstname AS firstname_2, t0.lastname AS lastname_3 FROM user2 t0':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db1.user2' doesn't exist
~~~

db2 is the second database, the non-default one

Has anyone face this trouble with `symfony` (**4**) or `doctrine` (**2**) ?

**Comment by Ocramius** [comment]
No, doctrine ORM cannot connect to separate DBs (not schemas) at the same time: it is possible to do so by designing a higher abstraction around a `Doctrine\DBAL\Connection`, but a `JOIN` will never work.

**Comment by waghanza** [comment]
@Ocramius I do not want to JOIN database, just read schemas as described on symfony documentation https://symfony.com/doc/current/doctrine/multiple_entity_managers.html

**Comment by Ocramius** [comment]
You would still need to implement your own abstraction for that: a `Doctrine\DBAL\Connection` abstracts a connection to only one database at a time.

**Comment by waghanza** [comment]
@Ocramius understood. Seems to be a mistake on symfony documentation then

**Comment by waghanza** [comment]
@Ocramius just to be sure ... my goal is not to have the **same** _entity_ in two databases, but **two distinct** entities (no relation between then) in **two** separated databases

**Comment by Ocramius** [comment]
The problem is still the same: one `Doctrine\DBAL\Connection` per `Doctrine\ORM\EntityManager`.

**Comment by waghanza** [comment]
yes, I have two distinct manager, one per connection

**Comment by Ocramius** [comment]
Which simply means that the wrong `EntityManager` is handling the query in the OP.

**Comment by waghanza** [comment]
So your assertion is false
> No, doctrine ORM cannot connect to separate DBs

**Comment by Ocramius** [comment]
Still holds: https://github.com/doctrine/doctrine2/issues/7384#issuecomment-418641454

One ORM instance, one database.

**Comment by waghanza** [comment]
ok, I think there is a misunderstanding due to **wording** ^^
`doctrine` instantiate one ORM per `database`, but can use **several** ORM
right ?

**Comment by Ocramius** [comment]
Yes, there are almost no singletons in the ORM, so you can use multiple instances, each configured differently.

**Comment by waghanza** [comment]
ok, glad we found a "solution"

**Comment by waghanza** [comment]
we can the close this issue
