### ISSUE TITLE
Add support to convert enum through orm:convert-d1-schema command

### ISSUE THREAD

**Issue by maidmaid** [doctrine/doctrine2#7393]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

When we run `orm:convert-d1-schema`, it's yet not possible to convert an [enum of Doctrine 1](https://doctrine.readthedocs.io/en/latest/en/manual/yaml-schema-files.html?highlight=schema#enums) to [an enum of Doctrine 2](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/cookbook/mysql-enums.html#mysql-enums) : 

```
In ToolsException.php line 44:

  [Doctrine\ORM\Tools\ToolsException]
  Could not map doctrine 1 type 'enum()'!
```

Would it be possible to do it ?

**Comment by Ocramius** [comment]
The `orm:convert-d1-schema` command is removed in `master` and won't be tweaked any further for stable releases.
