### ISSUE TITLE
Class 'Doctrine\Common\Persistence\Mapping\Driver\AnnotationDriver' not found

### ISSUE THREAD

**Issue by ekosynth** [doctrine/doctrine2#7394]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.4.8

#### Summary

Can't find AnnotationDriver class when running tutorial

#### Current behavior

Can't find AnnotationDriver class when running tutorial

#### How to reproduce

[Follow all tutorial steps,](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/tutorials/getting-started.html) then run 

` vendor/bin/doctrine orm:schema-tool:create`

This error is returned:

`Fatal error: Class 'Doctrine\Common\Persistence\Mapping\Driver\AnnotationDriver' not found in C:\Workspace\xxx\doctrine2-tutorial\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\Driver\AnnotationDriver.php on line 40
`
#### Expected behavior

Schema create will run without error

**Comment by ekosynth** [comment]
So I've just got it working by upgrading to doctrine/orm 2.6.

The tutorial says to include this composer.json requiring 2.4 :
`{
    "require": {
        "doctrine/orm": "2.4.*",
        "symfony/yaml": "2.*"
    },
    "autoload": {
        "psr-0": {"": "src/"}
    }
}`

Maybe the tutorial should be updated to include whatever fixed this

**Comment by Majkl578** [comment]
Yes, it should be `^2.6` and YAML reference removed completely.
cc @SenseException

**Comment by SenseException** [comment]
In case of 2.6, YAML ist still in use but needs a deprecation note. This is a fitting change for #7374.

_Getting Started_ needs to be tested with the current and the upcoming versions and the documentation needs an update with the resulting changes of the tests in a new PR.

**Comment by Majkl578** [comment]
#7412 has been merged which fixes the ORM version in the tutorial.

**Comment by tsz1412** [comment]
Still got this problem with symfony 4.4.
I am using Docker and installed Doctrine 2.6 with maker-bundle 1.30.2
