### ISSUE TITLE
Ordering by array column

### ISSUE THREAD

**Issue by MassiveHiggsField** [doctrine/doctrine2#7403]
I couldn't find any documentation on this. How are serialized array columns sorted? Is it just a normal text order on the serialized string? Is it the first value in the array which determines the order? 

To clarify, i don't mean how are the values in the array sorted, but what happens if i add an orderBy clause on an array column.

**Comment by Ocramius** [comment]
> How are serialized array columns sorted?

By their serialized DB state, which is a PHP serialized string, hence unreliable.

**Comment by MassiveHiggsField** [comment]
Alright thanks for the info.
