### ISSUE TITLE
Join a property only if it has not been joined already

### ISSUE THREAD

**Issue by technetium** [doctrine/doctrine2#7408]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

My repository has several methods that add joins to a query. I want to only add a join if it's not already added with a previous method.

Pull request #7409 has been created to implement such a function. If there is a better method to accomplish this result, please let me know.

**Comment by Ocramius** [comment]
> My repository has several methods that add joins to a query. I want to only add a join if it's not already added with a previous method.

Since this is `private` API, it is trivial to do so in the repository directly, and it is not up to lower layers (in this case the ORM) to handle the scenario.
