### ISSUE TITLE
ArrayHydrator.php 123 Warning: key() expects parameter 1 to be array, null given

### ISSUE THREAD

**Issue by mrAndersen** [doctrine/doctrine2#7410]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.6.2

#### Summary

Notice during Array hydration
/var/www/symfony/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ArrayHydrator.php 123 Warning: key() expects parameter 1 to be array, null given

#### Current behavior

Notice (which leads to incorrect array hydration)

Debug screen - https://prnt.sc/kyhevg
Qb joins and where - https://prnt.sc/kyhgfo
Qb selects - https://prnt.sc/kyhh49

#### How to reproduce

SQL generated during query - https://pastebin.com/tV59wVjz
Entity schema - https://pastebin.com/BCbCfA0r
Database schema - https://prnt.sc/kyheay

#### Expected behavior

Correct hydration of result

**Comment by Ocramius** [comment]
Can you reproduce this in isolation in a test such as in https://github.com/doctrine/doctrine2/tree/b40c2c6b7893c929f754150d480c20f9b22e0afe/tests/Doctrine/Tests/ORM/Functional/Ticket ?

**Comment by mrAndersen** [comment]
@Ocramius actually no, because application is too complex, issue seems to be solved by removing duplicate selectes of same aliases from query, therefore Exception should be thrown is i think, and as code todo said ))
