### ISSUE TITLE
Allow PgSQL enums for discriminator columns

### ISSUE THREAD

**Issue by root-talis** [doctrine/doctrine2#7417]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

At this moment DiscriminatorColumn values are converted into SQL in `SingleTablePersister::getSelectConditionDiscriminatorValueSQL` like this:

`return $tableAlias . '.' . $discColumn . ' IN (' . $values . ')';`,
where `$values` is an comma-separated list of `$this->conn->quote`ed values of discriminatorMap.

Thus, it is impossible to turn it into a PgSQL-valid filter like `t0.type IN ('type_a'::my_type_enum, 'type_b'::my_type_enum)` without changing `SingleTablePersister`.

It would be great to add support for PgSQL enums for discriminator columns.

**Comment by root-talis** [comment]
My bad. If you make the descriminator column values in the upper case, PgSQL will automatically convert strings to enums.

**Comment by Ocramius** [comment]
This seems to already be fixed in `master`: https://github.com/doctrine/doctrine2/blob/b40c2c6b7893c929f754150d480c20f9b22e0afe/lib/Doctrine/ORM/Persisters/Entity/SingleTablePersister.php#L167
