### ISSUE TITLE
Inherited Entity with self-referencing ManyToMany: EXTRA_LAZY fetch mode not working

### ISSUE THREAD

**Issue by flaushi** [doctrine/doctrine2#7424]
I have one parent entity with several derived ones.
The derived ones hold references to the parent, with fetch="EXTRA_LAZY".
Still, when find'ing a derived one from the database, the references are fully fetched as well.
In case of a ManyToMany with 5000 references, this becomes costly.

I have illustrated my problem in detail on SO, https://stackoverflow.com/questions/52686088/inherited-entity-with-self-referencing-manytomany-extra-lazy-fetch-mode-not-wor (with bounty ;-))

Thank you for your help in advance!

**Comment by Ocramius** [comment]
Was this supposed to be closed?
