### ISSUE TITLE
Pass thru context to a datatype definition

### ISSUE THREAD

**Issue by ONiAd** [doctrine/doctrine2#7433]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Currently a datatype definition does not have context of the other fields to be converted.
Make case of DatatypeTZ definition on Mysql (which currently does not support), but could be achieved at database level using a datetime field and a timezone varchar field.

Current implementation of Datetime datatype cannot get the timezone field to hydrate a full fledged DatetimeTZ. passing a context as third parameter, could retrieve timezone field.

Using Lifecycle callbacks provoke the field to be reconstructed, and leading to trigger updatings without need.

**Comment by Ocramius** [comment]
@ONiAd this is a scenario where an embeddable would be better suited. ORM v3 will probably have better support for N-fields-to-M-properties, but this is not to be solved with DBAL types for now, and won't be approached until we have the ORM v3 details required.
