### ISSUE TITLE
New transaction is not allowed because there are other threads running in the session

### ISSUE THREAD

**Issue by martinepic** [doctrine/doctrine2#7446]
Hello, I'm trying to run a procedure, and then an update to a table, however the following error occurs: "New transaction is not allowed because there are other threads running in the session", follow the code below:

   `
     
    public function update(TestEntity $testEntity) {
        $sql = "EXEC TEST_PROC 1, 1";

        $entityManager = $this->getEntityManager();
        $stmt = $entityManager->getConnection()->prepare($sql);

        if ($stmt->execute ()) {
            $this->getEntityManager()->merge($testEntity);
            $this->getEntityManager()->flush();
        }
    }
`

Any suggestions and / or solutions?

**Comment by Ocramius** [comment]
> New transaction is not allowed because there are other threads running in the session

What's the RDBMS? Nested transactions are quite normal in ORM context.

**Comment by Ocramius** [comment]
Googled a bit, and this may be because the same PHP process has a second
open DB connection. Not really a DBAL or ORM issue: seems more like one of
the usual "SQL server being special" issues...

**Comment by martinepic** [comment]
@Ocramius 
I agree with you, but do you have any solutions and / or suggestions for this case?

**Comment by Ocramius** [comment]
Look for the second connection: this is not a bug in this tooling.

**Comment by martinepic** [comment]
@Ocramius 
I solved it as follows, follow the code below:

`public function update(TestEntity $testEntity) {
    $sql = "EXEC TEST_PROC 1, 1";

    $entityManager = $this->getEntityManager();
    $stmt = $entityManager->getConnection()->prepare($sql);
    $stmt->execute();
    $stmt->closeCursor();

    $entityManager->merge($testEntity);
    $entityManager->flush();
}`
