### ISSUE TITLE
Postgres: change of an entity's primary table schema during runtime doesn't affect sequence name

### ISSUE THREAD

**Issue by tdierolf** [doctrine/doctrine2#7462]
**doctrine/orm: v2.6.2**

If an Postgres entity's primary table schema is changed during runtime like this (so it gets created in another table schema):

```
/** @var ClassMetadataInfo $metadata */
$metadata = $myEntityManager->getMetadataFactory()->getMetadataFor($myEntityClass);
$metadata->setPrimaryTable(['name' => $myNewSchema.'.'.$metadata->table['name']]);
```
it doesn't affect the an existing sequence name:

```
$sequenceGeneratorDefinition = $metadata->sequenceGeneratorDefinition;
```
`$sequenceGeneratorDefinition` still contains the previous name and thus the sequence gets created in another (the wrong) table schema (apart from the table itself).

I wrote a workaround like this:

```
// fix sequence generator schema
$sequenceGeneratorDefinition = $metadata->sequenceGeneratorDefinition;
$orgSchema = $metadata->table['schema'];
$sequenceGeneratorDefinition['sequenceName'] = str_replace(
    $orgSchema.'.',
    $myNewSchema.'.',
    $sequenceGeneratorDefinition['sequenceName']
);
$metadata->setSequenceGeneratorDefinition($sequenceGeneratorDefinition);
```

Please consider correctly changing also the sequence name when the table name gets changed via metadata during runtime, so the sequence gets created in the correct table schema alongside the table.

Here's my complete method which creates tables for entities in a different table schema:

```
protected function createTables(): bool
    {
        /** @var EntityManagerInterface $entityManager */
        $entityManager = $this->managerRegistry->getManager();
        $schemaTool = new SchemaTool($entityManager);
        $versionSchema = $this->payload['schema'];

        try {
            $metadataClasses = [];

            foreach ($this->payload['entities'] as $entityClass) {
                /** @var ClassMetadataInfo $metadata */
                $metadata = $entityManager->getMetadataFactory()->getMetadataFor($entityClass);
                $orgSchema = $metadata->table['schema'];

                $metadata->setPrimaryTable(['name' => $versionSchema.'.'.$metadata->table['name']]);

                // fix sequence generator schema
                $sequenceGeneratorDefinition = $metadata->sequenceGeneratorDefinition;
                $sequenceGeneratorDefinition['sequenceName'] = str_replace(
                    $orgSchema.'.',
                    $versionSchema.'.',
                    $sequenceGeneratorDefinition['sequenceName']
                );
                $metadata->setSequenceGeneratorDefinition($sequenceGeneratorDefinition);

                $metadataClasses[] = $metadata;
            }

            $schemaTool->createSchema($metadataClasses);
        } catch (\Exception $ex) {
            return false;
        }

        return true;
    }
```

Cheers! Tim

**Comment by Ocramius** [comment]
Changing metadata after the ORM has booted is not supported, and cannot be supported due to metadata caching happening at multiple levels for performance reasons.

**Comment by rbrecht** [comment]
any suggestions for a workaround to get this solved? got into this problem a few weeks ago, too

**Comment by Ocramius** [comment]
> to get this solved?

There is no solution: modifying metadata at runtime cannot be done.

If you need to do it, you need a fresh `EntityManager` and make sure that no metadata is shared across multiple EM instances.

**Comment by tdierolf** [comment]
OK, fair enough. I came across the Doctrine lifecycle events. Can the event 'loadClassMetadata' be used for such purposes?

**Comment by Ocramius** [comment]
Only once, when the metadata is being loaded (and before it is cached).
