### ISSUE TITLE
Change the entities collection to each side of Many to Many relationship

### ISSUE THREAD

**Issue by blacestorm** [doctrine/doctrine2#7464]
|    Q        |   A
|------------ | -----
| Version     | 2.5.11
| Symfony Version | 4.1.7

hi!

I created a Many to Many relationship with two entities convention <-> profil.

Entity Convention

```
/**
     * Many convention have Many profil.
     * @ORM\ManyToMany(targetEntity="Profil", mappedBy="conventions")

     */
    private $profils;
```

Entity Profil

```
    /**
     * Many profil have many convention
     * @ORM\ManyToMany(targetEntity="Convention", inversedBy="profils")
     * @ORM\JoinTable(name="asso_profil_convention",
     *      joinColumns={@ORM\JoinColumn(name="profil_id", referencedColumnName="profil_id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="convention_id", referencedColumnName="convention_id")})
     */
    private $conventions;
```

My problem when i try to set profil in the convention the insert in my association table does'nt work but the invers yes. 

I have tried many thing and I solved my problem with that:

```
    /**
     * Many convention have Many profil.
     * @ORM\ManyToMany(targetEntity="Profil", inversedBy="conventions")
     * @ORM\JoinTable(name="asso_profil_convention",
     *      joinColumns={@ORM\JoinColumn(name="convention_id", referencedColumnName="convention_id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="profil_id", referencedColumnName="profil_id")})
     */
    private $profils;
```

But I get this error "The field App\Entity\Acces\Convention#profils is on the owning side of a bi-directional relationship, but the specified mappedBy association on the target-entity App\Entity\Acces\Profil# does not contain the required 'inversedBy' attribute."

**Comment by Ocramius** [comment]
You need something like this:

```php
class Profil
{
    // ... 
    /** @ORM\ManyToMany(targetEntity=Convention::class, inversedBy="profils") */
    private $conventions;
    // ...
}
```

```php
class Convention
{
   // ... 
    /** @ORM\ManyToMany(targetEntity=Profil::class, mappedBy="conventions") */
    private $profils;
    // ...
}
```

The `@JoinTable` (if needed) should be on the association that has the `inversedBy` attribute

**Comment by blacestorm** [comment]
Thanks for your answer,

I need the `@JoinTable`  without I have one error who specify  write the `@JoinTable`,
For define the targetEntity the ` : : class` doesn't expected in Symfony 4 

I suposed the problem doesn't come from this.
If you need more element for uderstand my problem ask me.

Thanks to take your time to answer me

**Comment by Ocramius** [comment]
You can either use `::class` or the FQCN (fully qualified class name) of the referenced class between quotes. If you use `::class`, then it must be imported or in the same namespace.

**Comment by blacestorm** [comment]
Hi

I try your tow method but I have the same problem when I try to modify profil in my CRUD Convention 
no change is operated 
And when I look the trace of sql,  I saw the select of all profil but no one insert in my association table

My entitys are in the same namespace
