### ISSUE TITLE
ResultSetMappingBuilder and name conflict in mapper

### ISSUE THREAD

**Issue by michalhlavka** [doctrine/doctrine2#7477]
|    Q        |   A
|------------ | -----
| Version     | 2.6.1

### Support Question
Hello,

I've got entity A with two ManyToOne relations. And both join columns with same name. When I am creating query based on entity A with ResultSetMappingBuilder and setting this entity to method `addRootEntityFromClassMetada` it results in `InvalidArgumentException` `The column 'created_by' conflicts with another column in the mapper.`. 

Here is quick sample for entity A

```
	/**
	 * @var B
	 * @ManyToOne(targetEntity="B")
	 * @JoinColumn(name="created_by", referencedColumnName="id")
	 */
	private $a;

	/**
	 * @var C
	 * @ManyToOne(targetEntity="C")
	 * @JoinColumn(name="created_by", referencedColumnName="id")
	 */
	private $b;
```

How can I avoid to conflict? I tried almost everything that I found on stack. But there are not many problems with this. 

Thanks for you answers,
Michal

**Comment by Ocramius** [comment]
You'd pick separate column names: this kind of association doesn't really work with DB foreign keys either, so there's something broken in the DB schema structure.

Closing as `invalid`
