### ISSUE TITLE
[MySQL] [YML] Can I alter table with new charset (not collation) for one column?

### ISSUE THREAD

**Issue by 4n70w4** [doctrine/doctrine2#7485]
Hi all! I use MySQL server.

I already have enitites and tables generated on this entities.
But I need change charset for one field in one table.
I declare entities on YML format.

What I need change in my entities yml files to alter charset (from utf8 to utf8mb4) for one column in one table?

I use command:

`php bin/console doctrine:schema:update --force --dump-sql`

I try add

```
    fields:
        field_name:
            type: string
            length: 120
            nullable: true
            options:
                collation: utf8mb4_general_ci
                charset: utf8mb4
```
But this change only column collate but not change column charset.
I can not insert in this field a value containing emoji.

```
composer info | grep doctrine
doctrine/annotations                  v1.6.0             Docblock Annotations Parser
doctrine/cache                        v1.8.0             Caching library offering an object-orient...
doctrine/collections                  v1.5.0             Collections Abstraction library
doctrine/common                       v2.10.0            PHP Doctrine Common project is a library ...
doctrine/dbal                         v2.8.0             Database Abstraction Layer
doctrine/doctrine-bundle              1.9.1              Symfony DoctrineBundle
doctrine/doctrine-cache-bundle        1.3.5              Symfony Bundle for Doctrine Cache
doctrine/doctrine-migrations-bundle   v1.3.1             Symfony DoctrineMigrationsBundle
doctrine/event-manager                v1.0.0             Doctrine Event Manager component
doctrine/inflector                    v1.3.0             Common String Manipulations with regard t...
doctrine/instantiator                 1.1.0              A small, lightweight utility to instantia...
doctrine/lexer                        v1.0.1             Base library for a lexer that can be used...
doctrine/migrations                   v1.8.1             Database Schema migrations using Doctrine...
doctrine/orm                          v2.6.3             Object-Relational-Mapper for PHP
doctrine/persistence                  v1.1.0             The Doctrine Persistence project is a set...
doctrine/reflection                   v1.0.0             Doctrine Reflection component
```

**Comment by Ocramius** [comment]
The schema tool won't do this for you, since you are deep in vendor-specific options.

This is where you'd need to start writing manual migrations.

**Comment by 4n70w4** [comment]
@Ocramius why did you close the request? I have not confirmed the decision of the question. You do not want to discuss it? This is a demanded functionality in 2018+ years.

**Comment by Ocramius** [comment]
We do not implement detailed schema support for vendor-specific functionality, and most of what is in `options:` is vendor-specific.

The project focuses on what is common across various RDBMSs.

It is correct that this is where we cut a line and tell consumers of the library to rely on hand-crafted migrations instead.

**Comment by 4n70w4** [comment]
@Ocramius

I manually execute:

`ALTER TABLE mytable MODIFY title varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;`

But after next update schame by entity yml file:

`php bin/console doctrine:schema:update --force --dump-sql`

`ALTER TABLE mytable CHANGE title title VARCHAR(120) NOT NULL;`

Schema-update command reset my manually setted charset for column!

**Comment by Ocramius** [comment]
Yes, that is to be expected: the schema tool cannot deal with all the nuances of platform-specific options, as the complexity for that is too high, compared with just using and maintaining proper migrations.
