### ISSUE TITLE
The identifier id is missing for a query when is present and not null value

### ISSUE THREAD

**Issue by mrljaime** [doctrine/doctrine2#7502]
|    Q        |   A
|------------ | -----
| Version     | 2.5

### Support Question

Hello people. 
I have an issue and I don't know if is a bug or something bad I'm doing. 
I need update some row without losing data and that's why my query is inside a transaction. Also I try to make a test without transactions and the result is the same. 

The query that I ran that give me the error: 

` SELECT t0.key AS key_1, t0.label AS label_2, t0.sort AS sort_3, t0.config AS config_4, t0.concept AS concept_5, t0.status AS status_6, t0.created_at AS created_at_7, t0.deleted_at AS deleted_at_8, t0.payment_period_id AS payment_period_id_9, t0.type AS type_10, t0.apply AS apply_11, t0.display AS display_12, t0.qty_amount AS qty_amount_13, t0.id AS id_14, t0.unique_id AS unique_id_15, t0.afterall_callback AS afterall_callback_16, t0.element_id AS element_id_17 FROM paysheet_group_element_concepts t0 WHERE t0.id = ? FOR UPDATE ["54565"] `

As you can see the id parameter is not missing. I try to replicate the issue passing null value to the `find()` method and this throws the exception even without run the sentence. 

There's someone that can help me with this one?

Thank you. 
Cheers.

**Comment by Ocramius** [comment]
@mrljaime please upgrade to 2.6.x first.

**Comment by mrljaime** [comment]
Hello @Ocramius. 
`- Updating doctrine/orm (v2.5.14 => v2.6.3): Downloading (100%)`

The result still the same. 
`SELECT t0.key AS key_1, t0.label AS label_2, t0.sort AS sort_3, t0.config AS config_4, t0.concept AS concept_5, t0.status AS status_6, t0.created_at AS created_at_7, t0.deleted_at AS deleted_at_8, t0.payment_period_id AS payment_period_id_9, t0.type AS type_10, t0.apply AS apply_11, t0.display AS display_12, t0.qty_amount AS qty_amount_13, t0.id AS id_14, t0.unique_id AS unique_id_15, t0.afterall_callback AS afterall_callback_16, t0.element_id AS element_id_17 FROM paysheet_group_element_concepts t0 WHERE t0.id = ? FOR UPDATE ["54565"] `

I got this.

`Uncaught PHP Exception Doctrine\ORM\ORMException: "The identifier id is missing for a query of AppBundle\Model\Entity\PaysheetConceptConfiguration`

I looked at the release and fix a bug with `EntityManager::find` method with optimistic lock without transactions. Like information, I'm using `LockMode::PESSIMISTIC_WRITE` inside the transaction.

**Comment by Ocramius** [comment]
@mrljaime do you have a code sample of what is being passed to the method? Maybe also a stack trace?

**Comment by mrljaime** [comment]
@Ocramius 
Thanks to your comment I realize that the problem comes in another query that I have a few lines later. :( 
Sorry for not take care with it and thanks for your time. 

Here's the error line:
`$configuration = $em->getRepository("AppBundle:PaysheetConceptConfiguration")->find($configurationId);`

The error trace says that entity is PayseetConceptConfiguration, if you see the query before is for PaysheetGroupElementConcept entity (paysheet_group_element_concepts table). 

Thanks and sorry again to open an issue the issue.

**Comment by Ocramius** [comment]
I suppose `$configurationId` is `null` there :-)

Closing here.
