### ISSUE TITLE
Can't get data from ArrayCollection on Inverse Side

### ISSUE THREAD

**Issue by marcelolima381** [doctrine/doctrine2#7525]
|    Q        |   A
|------------ | -----
| Version     | 2.6

### Support Question

I can't get data from the ArrayCollection on the Inverse Side of a \One to Many - Many to One/ relationship. I tried literally everything and I'm starting to think there's no way to do that. Does anyone have ever done such thing?

**Comment by Ocramius** [comment]
Closing, since this is not an issue, but a question.

 >  I tried literally everything

Please write down what you are trying to do, specifically this bit:

 > get data from the ArrayCollection

Also add some examples of what you tried so far.

**Comment by marcelolima381** [comment]
It was just a misconception. Sorry to bother.
