### ISSUE TITLE
console orm:convert-mapping case sensitive fields

### ISSUE THREAD

**Issue by yzobairi** [doctrine/doctrine2#7529]
Hi,

I'm trying to generate entities from my database with the console and orm:convert-mapping command.
Here is the command I'm using: 

`php vendor/doctrine/orm/bin/doctrine.php orm:convert-mapping --from-database annotation ./src/Entities`

The problem is that the generated fields in my entities classes are not case sensitive.
For example, I have a validationCode field in a table in my database and the generated field in the corresponding entity is : 

```
    /**
     * @var string|null
     *
     * @ORM\Column(name="validationCode", type="string", length=16, nullable=true)
     */
    private $validationcode;
```

and I would like to have : 

```
    /**
     * @var string|null
     *
     * @ORM\Column(name="validationCode", type="string", length=16, nullable=true)
     */
    private $validationCode; // HERE validationCode with an uppercase C
```

How can I do that using the command-line? thank you

**Comment by Ocramius** [comment]
@yzobairi entity generators were deprecated and are no longer present in `master`, nor will be improved further on. If you need this to import a legacy schema, I suggest debugging and hacking a fix into your own version until you need it, then forgetting about that CLI command entirely.

Closing as `won't fix` here. 

See also https://github.com/doctrine/doctrine2/pull/6870
