### ISSUE TITLE
Add symfony expression syntax to collection relations annotation

### ISSUE THREAD

**Issue by rpodwika** [doctrine/doctrine2#7535]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

To use indexBy with foreign key you need to add the key as class property which is considered to be a bad practice.

Imagine situation when you have class Foo that hass class Related with relation type one to many

`@ORM\OneToMany(targetEntity="Foo", mappedBy="foo", indexBy="relatedId")`

I would like to use doctrine expression or be able to index by a foreign key.

`@ORM\OneToMany(targetEntity="Foo", mappedBy="foo", indexBy="$related->getId()")`

**Comment by SenseException** [comment]
Your current entity relation is: One `Related` entity can have one or more `Foo` entities and you want the collection of `Foo` use the id of `Related`? `indexBy` is supposed have a unique key.

`indexBy` is supposed to get a property with a unique value like in this example:

``` php
/**
 * @ORM\Entity
 */
class Foo
{
    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id()
     * @ORM\GeneratedValue()
     */
    public $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    public $name;

    /**
     * @var Bar[]
     *
     * Use Bar.id as key.
     * @ORM\OneToMany(targetEntity="Bar", mappedBy="foo", indexBy="id")
     */
    public $bars;
}
```

``` php
/**
 * @ORM\Entity
 */
class Bar
{
    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id()
     * @ORM\GeneratedValue()
     */
    public $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    public $name;

    /**
     * @var Foo
     *
     * @ORM\ManyToOne(targetEntity="Foo", inversedBy="bars")
     */
    public $foo;
}
```

Can you please elaborate your use case?

**Comment by Ocramius** [comment]
This:

 > `indexBy="$related->getId()"`

Is absolutely too complex, and an edge case too.

Closing as `won't fix`, since this logic is trivially implemented in userland with collection operations, without having to introduce massive complexity, pseudo-code in mappings, nor potential code parsing and evaluation facilities that are not worth building unless they are an evident game changer.
