### ISSUE TITLE
Use query expression in indexBy.

### ISSUE THREAD

**Issue by I70l0teN4ik** [doctrine/doctrine2#7536]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Would be very useful to pass query expression to indexBy. Especially if you have a relation to entities with a composite primary key.
Let's say we have an entity Foo with a collection of Bar. But Bar actually has a unique and potentially a primary key on: foo_id + baz_id + quux_id. So simply passing the concat expression  would give a guaranteed unique index for collection inside one Foo. 
This would help to avoid issues in unit of work during the update of Foo.

@ORM\OneToMany(targetEntity="Bar", mappedBy="foo", indexBy="CONCAT(baz_id, quux_id)")

**Comment by Ocramius** [comment]
Closing as `won't fix`: same reasoning as https://github.com/doctrine/doctrine2/issues/7535#issuecomment-449188277

What could be done (in my opinion) is implementing surrogate read-only entity fields that are only hydrated, and never considered by the `UnitOfWork`. Once that's done,  this becomes a trivial operation.
