### ISSUE TITLE
Call to undefined method Doctrine\ORM\Mapping\FieldMetadata::getSchemaName()

### ISSUE THREAD

**Issue by simPod** [doctrine/doctrine2#7547]
|    Q        |   A
|------------ | -----
| Version     | master

### Support Question

When running tests, I'm getting
> Error : Call to undefined method Doctrine\ORM\Mapping\FieldMetadata::getSchemaName()

 eg. in `lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:329`

The method indeed is not in `FieldMetadata`. Am I doing something wrong? How to make tests pass when the method is not there?

**Comment by Ocramius** [comment]
@simPod this is for `master`, which is still under active development.
