### ISSUE TITLE
Many To Many without unique

### ISSUE THREAD

**Issue by WarGeneration** [doctrine/doctrine2#8513]
Hi all, i have one trouble with my mapping

I have entity A and B which are joined by manyToMany. But entity A can be joined to B multiple times like:

```
a_id  | b_id
 1    |   1   
 1    |   1
```

So what i expected?
I want to get all B entities from $a->getBs(), but i got only unique Collection.

I can add new entity AB and i will get all entities from $a->getABs().
But i need to add PK for this thing.

Maybe doctrine have another option to handle this?

**Comment by beberlei** [comment]
Yes, you can do this by making the `a_b` table an entity as well using assocations as the IDs:

```
/** @Id @ManyToOne(targetEntity="A") */ public $a;
/** @Id @ManyToOne(targetEntity="B") */ public $b;
```
