### ISSUE TITLE
Timeline for DBAL v3 support?

### ISSUE THREAD

**Issue by rotdrop** [doctrine/doctrine2#8526]
Hi,
are there plans or even a tentative timeline for DBAL v3 support?

Thx.

**Comment by beberlei** [comment]
The plan is to support DBAL 2 + 3 in ORM 2.10 (after 2.9 which is next). No definite timeline

**Comment by rotdrop** [comment]
Thx :)

**Comment by mvorisek** [comment]
What is the reason to not support DBAL v3 in v2.9?

**Comment by beberlei** [comment]
@mvorisek time :)
