### ISSUE TITLE
No support for rolling back partial changes on the managed entities 

### ISSUE THREAD

**Issue by GuiEloiSantos** [doctrine/doctrine2#8535]
A issue that I have been having lately is that doctrine does not offer a way to rollback changes on the managed entities partially.

ie:

```php
        $entity = $this->entityManager->find(SomeEntity::class, 1);
        /**
         * @var SomeEntity $entity
         */
        $entity->setAverageProfit(20);
        try {
            $this->someManager->updateEntityWithSomethingElse(
                $entity
            );
        } catch (Exception $exception) {
            // log
        }

        $this->entityManager->flush();
```

Let's assume that `updateEntityWithSomethingElse` does a few updates on `$entity` some validation, and some updates again, but if at any point this method throws an exception we want to discard every update done inside of this method, but keep the updates done outside, ie: `$entity->setAverageProfit(20);`. 
I couldn't find a way to do that.

If I refresh or do a transaction/flush/rollback I will loose both changes as refreshing would get the database version that has none of those, and flushing would discard the update query on rollback.

I found a hacky way of achieving that and it is pretty much that:

```php
       $entity = $this->entityManager->find(SomeEntity::class, 1);
        /**
         * @var SomeEntity $entity
         */
        $entity->setAverageProfit(20);

        $unityOfWork = $this->entityManager->getUnitOfWork();
        $originalIdentityMap = $unityOfWork->getIdentityMap();
        
        try {
            $this->someManager->updateEntityWithSomethingElse(
                $entity
            );
        } catch (Exception $exception) {
            // log
            $prop = new ReflectionProperty($unityOfWork, 'identityMap');
            $prop->setAccessible(true);
            $prop->setValue($unityOfWork, $originalIdentityMap);
        }

        $this->entityManager->flush();
``` 

But I'm not aware of the impacts of messing with the identityMap, so I wanted to check here if this is something that could be done, and potentially we could have something like:

```php

    /**
     * Records the current version of the identity map
     *
     * @psalm-return void
     */
    public function recordCurrentIdentityMap()
    {
        $this->lastRecordedIdentityMap = $this->getIdentityMap();
    }

    /**
     * Revert identity map changes to the last recorded identity map if any
     *
     * @psalm-return void
     */
    public function revertIdentityMap()
    {
        if(!empty($this->lastRecordedIdentityMap)) {
            $this->identityMap = $this->lastRecordedIdentityMap;
        }
    }
```

In the UnitOfWork to allow us to rollback partial changes on entities.

I'm not sure of the instance of the entities diverging from the identityMap would be a problem or if there is other issues with this approach that I'm not aware of so I thought about creating this issue to get some feedback on it.

**Comment by beberlei** [comment]
You need to flush after setting the price to capture this change, then do the try/catch block and flush twice. Second time will do no datavase changes if nothing happened.
