### ISSUE TITLE
Replace some usages of func_get_args() with variadics

### ISSUE THREAD

**Issue by greg0ire** [doctrine/doctrine2#8537]
See https://github.com/doctrine/orm/search?q=func_get_args

This will be a breaking change, and as such should target 3.0.x

**Comment by VincentLanglet** [comment]
This will fix the issues psalm is currently throwing when the following stubs are not used 

https://github.com/weirdan/doctrine-psalm-plugin/blob/master/stubs/QueryBuilder.phpstub
https://github.com/weirdan/doctrine-psalm-plugin/blob/master/stubs/Expr.phpstub

To bad we have to wait for the next major ^^'
