### ISSUE TITLE
Option to configure credentials retrieval from CyberArk

### ISSUE THREAD

**Issue by c-schinzer** [doctrine/doctrine2#8542]
Hello,

I am not sure by which other path I should drop a feature request here.
I am using the DoctrineBundle with Symfony and will need to migrate the DB credentials (account and password) to CyberArk, i.e. a central password store with dynamic password update. Hence instead of storing the password part of the credential locally on my environment (or dotenv file) I now need to retrieve it at runtime and possibly cache it locally for a certain TTL.

The first question is of course: Are you aware of any such requirement being on the development roadmap already?
Second question: Should I join the dev community here and support the development myself, i.e. do you feel this is a local need or is there room for potential re-use, so is it worth to contribute such a feature?

Thanks for a reply :)
Warm regards

Carsten

**Comment by beberlei** [comment]
Hi Carsten,

Yes such requirements also exist with Hadhicorp Vault for example, but they are outside the scope of Doctrine. Just always pass the current password to Doctrine upon initialization. A deeper integration would require too much coupling and code in Doctrine that we don‘t want to be responsible for
