### ISSUE TITLE
Doctrine unexpected remove behavior

### ISSUE THREAD

**Issue by salirzv** [doctrine/doctrine2#8549]
There is an OneToOne relation between my `User` class and a class called `UserPreChangePhone`.
 
Imagine we want to free `User` from it's already existing record, so I run  these commands:

> if ($previous_change_phone !== null){
>             $em->remove($previous_change_phone);
>             $em->flush();
>         }

then I bound `User` to it's new record like this:

> $pre_change_phone = new UserPreChangePhone();
> $pre_change_phone->setOwner($user);
> $this->getDoctrine()->getManager()->persist($pre_change_phone);
> $this->getDoctrine()->getManager()->flush();
 
even though `User` should be freed from it's previous record, I still get this error for duplicate entry:
`Integrity constraint violation: 1062 Duplicate entry '15' for key`

15 is my example user Id that was used in the deleted record so it should be free now to be used in the new record.

it looks like the new record is being inserted before the previous one is deleted, I has a similar problem with nodejs because of it's asynchronous nature, but I don't think such a thing should happen in PHP.

**Comment by salirzv** [comment]
So Apparently using query builder solves the issue:

> if ($previous_change_phone !== null){
>             $dql = ($em->createQueryBuilder())
>                 ->delete('App:UserPreChangePhone', 'u')
>                 ->where('u.id = :id')
>                 ->setParameter('id', $previous_change_phone->getId())
>                 ->getQuery()
>                 ->execute();
>         }

**Comment by stof** [comment]
during a flush, insertions are performed before deletions IIRC.
