### ISSUE TITLE
What about detach deprecation?

### ISSUE THREAD

**Issue by edezacas** [doctrine/doctrine2#8559]
Is not clear detach deprecation, at doctrine 2.8, detach method is marked as deprecated for Doctrine 3, but I've just seen [Introduce doctrine/deprecations](https://github.com/doctrine/orm/pull/8466) where @beberlei say:

> This PR also undeprecates EntityManager::detach for now, because unless we find some kind of replacement API it cannot be removed as relied on heavily by the batch processing use-cases with AbstractQuery::toIterable.

Also I've checked at branch 2.9.x and 3.0.x deprecation annotation has been removed.

So, anybody may be clarify this?

Thanks,

**Comment by greg0ire** [comment]
> unless we find some kind of replacement API it cannot be removed as relied on heavily by the batch processing use-cases with AbstractQuery::toIterable.

Hi! What's unclear about this?
