### ISSUE TITLE
toIterable() Exception -  Iterating a query with mixed results (using scalars) is not supported

### ISSUE THREAD

**Issue by sergeysrabionyan** [doctrine/doctrine2#8562]
When I try to iterate over the queryBuilder toIterable() method I get an error "Iterating a query with mixed results (using scalars) is not supported", when I use the "deprecated" method iterate () I get the correct result.

 Can I repeat the behavior of the iterate () method and make it not deprecated?

**Comment by beberlei** [comment]
We have not managed to find a way to support it yet, but if you do of course we will accept it.

**Comment by eigan** [comment]
Duplicate of #8520
