### ISSUE TITLE
Deprecated Named Native and DQL Queries

### ISSUE THREAD

**Issue by beberlei** [doctrine/doctrine2#8592]
Named native and DQL queries should be deprecated, because:

1. They add a lot of mapping driver complexity and code, lately that we cannot support them in Attribute Driver because of missing nested support in 8.0
2. They add a lot of documetation complexity for something that can be done programatically much easier and with better auto-completion
3. This feature can trivially be built at the EntityRepository level by a user that wants to work with queries this way.
4. They add a lot of weight to the cached metadata and make the deserialization of metadata more expensive, even when the named query is not used in the request. This is contrary to the DQL cache, which is only deserialized when the query is actually used.

**Comment by realjjaveweb** [comment]
@beberlei Will it be possible to map a joined entity based on more columns than just the join column? (e.g. AND deleted=0)? If this allowed this and it won't be possible - it should at least have a replacement what do you think?

Creating a repository method for a basic get operations like this beats the purpose of ORM in my pov.
