### ISSUE TITLE
Wrong return type for UnitOfWork::getOriginalEntityData

### ISSUE THREAD

**Issue by NicoHaase** [doctrine/doctrine2#8599]
In #8521, a new return type for `getOriginalEntityData` has been introduced (see https://github.com/doctrine/orm/blob/2.8.x/lib/Doctrine/ORM/UnitOfWork.php#L2992). `array<string, array<string, mixed>>` does not look correct to me: when calling that method, it returns `array<string, mixed>`

**Comment by greg0ire** [comment]
I think you are correct. Can you please send a PR against 2.8.x?

It looks like I have blindly copied the annotation for the property: https://github.com/doctrine/orm/blob/5ac036de0273c6fc819d1e1835ab4f548dc24727/lib/Doctrine/ORM/UnitOfWork.php#L149-L151

**Comment by NicoHaase** [comment]
@greg0ire I've linked a PR. What surprises me: I've adjusted the annotation, but nothing else. Is this such a special case that no code in the testsuite calls this method? I had expected that I also had to change other things anywhere else in the code

**Comment by tjveldhuizen** [comment]
The tests directory is not analyzed by PHPStan, and PHPUnit does not do anything with the annotations. So it doesn't surprise me that it was not discovered before.

**Comment by NicoHaase** [comment]
The annotation I've changed is not part of any test directory

**Comment by tjveldhuizen** [comment]
But if the method where the annotation relates to is used in a test (which it doe, I assume), PHPStan would analyze it if it would analyse the tests.

**Comment by greg0ire** [comment]
I think the actual reason is that we run Psalm and PHPstan at a too lenient level for them to detect this ATM:

https://github.com/doctrine/orm/blob/2a87821b28d017b1b718c481f39d95b32894aa47/phpstan.neon#L2

https://github.com/doctrine/orm/blob/2a87821b28d017b1b718c481f39d95b32894aa47/psalm.xml#L3

If you want to work on this, be my guest :slightly_smiling_face:
