### ISSUE TITLE
Doctrine console commands em default should be null

### ISSUE THREAD

**Issue by simPod** [doctrine/doctrine2#8643]
Doctrine console commands now have a default value as `default` instead of `null`.

When `em` is set to `null`, the `AbstractManagerRegistry`'s functionality kicks in and uses real default EntityManager (`$this->defaultManager`) https://github.com/doctrine/persistence/blob/2.2.x/lib/Doctrine/Persistence/AbstractManagerRegistry.php#L143-L146

Now's it looking for EM with name `default` which does not guarantee it's the default one.

https://github.com/doctrine/orm/blob/22413453daa872e121514bab1fe4c5fa982623ea/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/UpdateCommand.php#L50

> Doctrine ORM Manager named "default" does not exist.

**Comment by beberlei** [comment]
Fixed by #8646
