### ISSUE TITLE
Deprecate using doctrine/cache for metadata caching

### ISSUE THREAD

**Issue by alcaeus** [doctrine/doctrine2#8650]
With doctrine/cache being sunset, and doctrine/persistence supporting PSR-6 caches in metadata factories, it's time to update the ORM configuration class to also accept PSR-6 caches. When setting up the metadata factory, the adapters provided in doctrine/cache should be used to avoid calling deprecated methods in doctrine/persistence.

**Comment by nataniel** [comment]
https://www.doctrine-project.org/projects/doctrine-orm/en/2.9/reference/advanced-configuration.html

The documentation says to use:
```
$cache = new \Doctrine\Common\Cache\ArrayCache;
$config->setMetadataCacheImpl($cache);
```

but the dependency on doctrine/orm 2.9.3 is:
`"doctrine/cache": "^1.11.3|^2.0.3",`

and 2.0.3 removed ArrayCache.

So I'm not really sure what is the current state and I cannot find any proper documentation on how to configure EntityManager :(

**Comment by StrikeAgainst** [comment]
Same goes for `PhpFileCache`, which has also been removed, but the [documentation](https://www.doctrine-project.org/projects/doctrine-orm/en/2.9/reference/caching.html#caching) still suggests to use it for caching. Supposedly `symfony/cache` is a recommended substitute, but I can find no documentation on how to get it working with Doctrine. I hope someone fixes the current documentation soon... For now I'll downgrade `doctrine/cache` I guess.

**Comment by ghdi** [comment]
@nataniel / @StrikeAgainst 

This worked for me: 

```
$cache = new \Symfony\Component\Cache\Adapter\ApcuAdapter();

$cacheProvider = \Doctrine\Common\Cache\Psr6\DoctrineProvider::wrap($cache);

$doctrineConfig->setMetadataCacheImpl($cacheProvider);
```
