### ISSUE TITLE
Predis Issue Undefined array key 0

### ISSUE THREAD

**Issue by ndoulgeridis** [doctrine/doctrine2#8653]
I am using doctrine and class metadata caching. All is fine except I get this warning 

`PHP Warning:  Undefined array key 0 in /app/vendor/predis/predis/src/Command/Command.php on line 107`

This is a normal warning because when I go through this line of code I see for example:

![image](https://user-images.githubusercontent.com/3415953/115801543-acfc8280-a3e5-11eb-9038-a9d8a3907e51.png)

So there is no $arguments[0]:

![image](https://user-images.githubusercontent.com/3415953/115801459-7cb4e400-a3e5-11eb-96b7-c5463478800c.png)

This is the call stack:

![image](https://user-images.githubusercontent.com/3415953/115801696-111f4680-a3e6-11eb-872c-627a3caa81e8.png)

Is this an error of Doctrine or Predis? It can be fixed by checking if isset first.

**Comment by greg0ire** [comment]
`vendor/predis/predis`

It is clearly an error in Predis. Indeed, there can be a check first, and that would be the responsibility of Predis.
