### ISSUE TITLE
#[JoinColumn] changes nullability of a relation

### ISSUE THREAD

**Issue by Nemo64** [doctrine/doctrine2#8680]
I'm still experimenting with the 2.9.x branch (6753b26) and noticed a strange schema difference.

```php
class Order {
    #[ORM\ManyToOne]
    #[ORM\JoinColumn]
    public ProductVariant $productVariant;
}
```

```php
class Order {
    #[ORM\ManyToOne]
    public ProductVariant $productVariant;
}
```

These 2 definitions create a different schema. The `JoinColumn` definition creates a `NOT NULL` column definition while the slimmer schema is `DEFAULT NULL`.

I also tested it with a `2.8.4` and there I have to explicitly use `@JoinColumn(nullable=false)` to make that column not nullable. The pure presence of the annotation does not change the schema.

I think that's not intended.

**Comment by beberlei** [comment]
Yes this is already known, see #8678  please if that works for you.

**Comment by Nemo64** [comment]
I tested the new version and I still have strange behavior.

```php
class A {
    #[ORM\ManyToOne]
    public Region $region; // DEFAULT NULL

    #[ORM\ManyToOne]
    #[ORM\JoinColumn]
    public Region $region; // NOT NULL

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable=true)]
    public Region $region; // NOT NULL
}
```

- It seems like the type hint logic only runs when the join column definition exists.
- If there is at least 1 indicator of nullable=false (be it php type hint or metadata) it always assumes nullable false.

What I would expect:
- If the metadata specifies `nullable`, that should overrule everything else. There are some circular situations where it is necessary to have the relation nullable.
- If I understand #8678 correctly, then a none nullable php property should default to a none nullable schema property
- and if nothing is specified, it should be nullable.
