### ISSUE TITLE
mapping:import not setting nullable=false on Join columns

### ISSUE THREAD

**Issue by echantigny** [doctrine/doctrine2#8681]
I'm trying to map a large database to php annotations (but also tried yaml with same result) and I found out that the created code does not contain the nullable=false on the JoinColumn description.

Example:

```
    /**
     * @var \Partner
     *
     * @ORM\ManyToOne(targetEntity="Partner")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="partner_id", referencedColumnName="partner_id")
     * })
     */
    private $partner;

```

What this definition should contain is this:
 ```
    /**
     * @var \Partner
     *
     * @ORM\ManyToOne(targetEntity="Partner")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="partner_id", referencedColumnName="partner_id", nullable=false)
     * })
     */
    private $partner;
```

**Comment by beberlei** [comment]
We have deprecated mapping imports for the next release of ORM, so we are realistically not going to fix this anymore.

**Comment by echantigny** [comment]
@beberlei Is there an alternative to create the annotations from a database structure?
