### ISSUE TITLE
Doctrine\Persistence\Mapping\AbstractClassMetadataFactory::setCacheDriver is deprecated. Use setCache() with a PSR-6 cache instead.

### ISSUE THREAD

**Issue by fkolcu** [doctrine/doctrine2#8697]
https://github.com/doctrine/orm/blob/3a194ad69946ec3e4289e50a877f96b8aad8b223/lib/Doctrine/ORM/EntityManager.php#L169

After updating version of "doctrine/orm" it's started to give error as in the title.
After checking which method/class is using the deprecated method, I found that it is being used in constructor of EntityManager.

Details of error is like the following:

Doctrine\Persistence\Mapping\AbstractClassMetadataFactory::setCacheDriver is deprecated. Use setCache() with a PSR-6 cache instead. on line 80 in file ../vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php.

**Comment by beberlei** [comment]
We will deal with deprecations in time, this one is being worked on already for next release.

**Comment by mohshinobi** [comment]
I had the same issue and i when i fixed the current version in my composer of **doctrine/orm**  **^2.8**  to **2.8.4** i bypassed this deprecation, and it's not showing anymore,  i am using **Symfony4** with **php8**
`php composer.phar require doctrine:orm:2.8.4` 
hope it can help you.
