### ISSUE TITLE
The class ClassMetada is not correctly inferring the constructor of ClassMetadaInfo

### ISSUE THREAD

**Issue by VincentLanglet** [doctrine/doctrine2#8709]
Hi

Currently
- `new ClassMetadataInfo(\DateTime::class)` is inferred as `ClassMetadataInfo<\DateTime>` by both psalm and phpstan
- `new ClassMetadata(\DateTime::class)` is inferred as `ClassMetadata<\DateTime>` by psalm but as `ClassMetadata<object>` by phpstan

This is related to this phpstan issue https://github.com/phpstan/phpstan/issues/5057
I don't know how and when the issue will be fixed so one way to fix it temporary would be to repeat the constructor:
```
        /**
	 * @psalm-param class-string<T> $class
	 **/
	public function __construct(string $class)
	{
		parent::__construct($class);
	}
```

Since you're using phpstan in this project, you might end with this issue while bumping the phpstan level.
Do you prefer I create a PR here or in https://github.com/phpstan/phpstan-doctrine ?
(The second solution won't fix the issue here since you're not using the library here)

**Comment by VincentLanglet** [comment]
I saw you did a lot of static analysis on this repository @greg0ire, maybe you can tell me (or ping the right person) to decide if I should do a PR here or in phpstan repository ? :)

**Comment by greg0ire** [comment]
:thinking: isn't that going to be fixed by https://github.com/doctrine/orm/pull/8708 ?

**Comment by VincentLanglet** [comment]
Sorry, my first post wasn't clear because I played with my vendor.

Currently
- new ClassMetadataInfo(\DateTime::class) is not inferred
- new ClassMetadata(\DateTime::class) is not inferred

After https://github.com/doctrine/orm/pull/8708
- new ClassMetadataInfo(\DateTime::class) will be inferred as ClassMetadataInfo<\DateTime> by both psalm and phpstan
- new ClassMetadata(\DateTime::class) will be inferred as ClassMetadata<\DateTime> by psalm but as ClassMetadata<object> by phpstan.

So an issue will still be present with ClassMetadata and phpstan.

**Comment by greg0ire** [comment]
I see. I think it should be fixed  here, with the repetition you suggested. In order for that constructor not to get removed, please also add something similar to what Marco did in https://github.com/doctrine/dbal/pull/4638

It was already suggested here BTW: https://github.com/doctrine/orm/pull/8633#issuecomment-841678603

**Comment by VincentLanglet** [comment]
Solved in https://github.com/doctrine/orm/pull/8734
