### ISSUE TITLE
 Attempted to load class "Assert"

### ISSUE THREAD

**Issue by ben29** [doctrine/doctrine2#8711]
after upgrade to ORM 2.9

> 
> Attempted to load class "Assert" from namespace "Webmozart\Assert".
> Did you forget a "use" statement for "Assert\Assert"?

https://github.com/doctrine/orm/blob/99d67cb77d3626c52f4d5feb5caed58948ea5577/lib/Doctrine/ORM/Query/Parser.php#L81

I think this Line should be removed...

**Comment by beberlei** [comment]
Fixed in #8713
