### ISSUE TITLE
Cannot clear Metadata cache

### ISSUE THREAD

**Issue by snapshotpl** [doctrine/doctrine2#8716]
I have use Doctrine with DoctrineORMModule but probably not releated.
When clear cache script fails:
```
$ php public/index.php orm:clear-cache:metadata --flush
No Metadata cache driver is configured on given EntityManager.
```

Clear result and query cache works fine. Started in 2.9

**Comment by mmarton** [comment]
https://github.com/doctrine/orm/blob/2.9.x/UPGRADE.md#removed-flushing-metadata-cache
