### ISSUE TITLE
Class "xxx" is not a valid entity or mapped super class.

### ISSUE THREAD

**Issue by ThibaultVlacich** [doctrine/doctrine2#8718]
I'm trying to use the new [PHP 8 Attributes coming with ORM 2.9](https://www.doctrine-project.org/2021/05/24/orm2.9.html), but as soon as I modify 

```php
/**
 * @ORM\Entity(repositoryClass="App\Repository\VideoRepository")
 */
```
for
```php
#[ORM\Entity(repositoryClass: VideoRepository::class)]
```

I'm getting this error `In MappingException.php line 378: Class "App\Entity\Video" is not a valid entity or mapped super class.` when trying to generate diffs (`php bin/console doctrine:migrations:diff`).

Is the migration bundle incompatible with those new PHP8 attributes, or is there a bug with the implementation (because the error, MappingException, comes from ORM).

**Comment by saxap** [comment]
got same issue

**Comment by michaljusiega** [comment]
Because:
1.) In your configuration to Doctrine Bundle you are using AnnotationDriver to mapping your entities.
2.) ORM 2.9 has AttributeDriver.
3.) DoctrineBundle will be soon release marked as 2.4 to make full compatibility with ORM 2.9

**Comment by ben29** [comment]
> Because:
> 1.) In your configuration to Doctrine Bundle you are using AnnotationDriver to mapping your entities.
> 2.) ORM 2.9 has AttributeDriver.
> 3.) DoctrineBundle will be soon release marked as 2.4 to make full compatibility with ORM 2.9

When the bundle will release? Any ETA?

**Comment by michaljusiega** [comment]
> 
> 
> > Because:
> > 1.) In your configuration to Doctrine Bundle you are using AnnotationDriver to mapping your entities.
> > 2.) ORM 2.9 has AttributeDriver.
> > 3.) DoctrineBundle will be soon release marked as 2.4 to make full compatibility with ORM 2.9
> 
> When the bundle will release? Any ETA?

References:
https://github.com/doctrine/DoctrineBundle/pull/1354
https://github.com/doctrine/DoctrineBundle/pull/1353

**Comment by ThibaultVlacich** [comment]
I'm closing since this is related to doctrine-bundle, and will soon be released it seems like
