### ISSUE TITLE
No identifier/primary key specified for Entity with php 8 attributs

### ISSUE THREAD

**Issue by TheKassaK** [doctrine/doctrine2#8735]
Hi,

I tried to update an entity with orm php 8 attributes, like : 

```
    #[ORM\Id, ORM\Column(type: "integer")]
    #[ORM\GeneratedValue(strategy: "AUTO")]
    protected ?int $id = null;
```

But when I doctrine:schema:update I have this error : 

**No identifier/primary key specified for Entity "App\Entity\XXXXX". Every Entity must have an identifier/primary key.**

What is the problem ?

Edit : 

In doctrine.yaml, if I switch from type: annotation to type: attribute I have this error : 

**The service "doctrine.orm.default_attribute_metadata_driver" has a dependen  
!!    cy on a non-existent parameter "doctrine.orm.metadata.attribute.class". Did  
!!     you mean one of these: "doctrine.orm.metadata.driver_chain.class", "doctri  
!!    ne.orm.metadata.annotation.class", "doctrine.orm.metadata.xml.class", "doct  
!!    rine.orm.metadata.yml.class", "doctrine.orm.metadata.php.class", "doctrine.  
!!    orm.metadata.staticphp.class", "doctrine.orm.validator.unique.class"?**

**Comment by beberlei** [comment]
It seems that you do not have DoctrineBundle version 2.4-dev installed? Thats currently required for `type: attribute` to work.
