### ISSUE TITLE
DiscriminatorColumn constructor is missing fieldName?

### ISSUE THREAD

**Issue by Webonaute** [doctrine/doctrine2#8737]
DiscriminatorColumn constructor is missing fieldName?

```
 * @ORM\DiscriminatorColumn(name="type", type="string", length=255, fieldName="type")
```

produce error like:

```
In AnnotationException.php line 52:
                                                                               
  [Creation Error] The annotation @ORM\DiscriminatorColumn declared on class   
  App\Entity\Tier\Rule\Rule does not have a property named "fieldName"         
  that can be set through its named arguments constructor.                     
  Available named arguments: name, type, length, columnDefinition              
```

**Comment by beberlei** [comment]
This field is not used in code: https://github.com/doctrine/orm/blob/2.9.x/lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php#L299 - you should remove it and we should remove this field.

**Comment by Webonaute** [comment]
Why closing this straight away. its a BC between 2.8.4 and 2.9.2.

We used this fieldName since ages and now broking our code. why that change? why no deprecation warning?

**Comment by beberlei** [comment]
@Webonaute what are you using it for? It has no functionality from looking at the code.
