### ISSUE TITLE
It seems that this option is not handled by Doctrine : #[OneToOne( cascade: ["persist","remove"])].

### ISSUE THREAD

**Issue by jonascarfantan** [doctrine/doctrine2#8761]
Trying to update an entity schema mapped with php8 attributes but the cascade option isn't passed on the DB

**Comment by beberlei** [comment]
Cascade option is a php level feature and not using cascade in the database. If you want cascade in the database see the options on JoinColumn attribute

**Comment by jonascarfantan** [comment]
Thank you for the explanation.
