### ISSUE TITLE
Typed Property Defaults: problem with nullable properties

### ISSUE THREAD

**Issue by adpeyre** [doctrine/doctrine2#8770]
Hi,

Since the 2.9.2 release, my nullable php typed properties are not correctly taken into account by Doctrine.
For example, this attribute is not nullable in database:

``` php
 #[ORM\Column]
 public ?\DateTimeImmutable $canceledAt = null;
```

I needed to downgrade to 2.9.1.

Thx

**Comment by greg0ire** [comment]
Hi! Have you read https://github.com/doctrine/orm/pull/8732 ?

**Comment by adpeyre** [comment]
Thanks @greg0ire. I missed that. (I had deleted all my null constraints lol).
Merci :D
