### ISSUE TITLE
Missing contructor for AttributeOverride Mapping

### ISSUE THREAD

**Issue by adpeyre** [doctrine/doctrine2#8772]
Hi,

I think a constructor is missing for php8 attributes in Doctrine\ORM\Mapping\AttributeOverride.
https://github.com/doctrine/orm/blob/2.9.x/lib/Doctrine/ORM/Mapping/AttributeOverride.php

Thx

**Comment by beberlei** [comment]
AttributeOverride is not yet supported as an Attribute

**Comment by adpeyre** [comment]
Ok.
I thought it was supported because there is the attribute annotation.

**Comment by adpeyre** [comment]
I need to set a different inversedBy value on my ManyToOne relation in Single Table Inheritance child context.
At this time, you confirm me I'm blocked if I'm working with the attribute mapping ?

**Comment by beberlei** [comment]
@adpeyre you can workaround it by registering a load metadata listener and setting the data there.

**Comment by adpeyre** [comment]
Thanks @beberlei , it works ;)
