### ISSUE TITLE
Don't define Doctrine annotations as a hard dependency?

### ISSUE THREAD

**Issue by javiereguiluz** [doctrine/doctrine2#8785]
In #8266 @beberlei added support for defining mapping with PHP attributes. However, `doctrine/annotations` is still defined as a required dependency of this project:

https://github.com/doctrine/orm/blob/f233e4cf6b62a90a9d3ce5c5cad055dce944ce7c/composer.json#L22

Is there any technical reason to keep it as is, or is it just that we need to find someone willing to contribute this change? Thanks!

**Comment by alcaeus** [comment]
There is no hard requirement with attributes, and there shouldn't have been one in the first place. I believe a solution as implemented in doctrine/persistence#197 would make sense here.
