### ISSUE TITLE
Deprecate Foo:Bar entity short syntax

### ISSUE THREAD

**Issue by beberlei** [doctrine/doctrine2#8818]
We want to deprecate and remove the short alias naming of entities in manager, repository and DQL. This feature is available through the following configuration:

```php
$configuration->addEntityNamespace('MyBundle', 'App\Entity');
$entityManager->find('MyBundle:User', $id);
$entityManager->createQuery('SELECT u FROM MyBundle:User');
```
Using short alias naming prevents Psalm/PHPStan static analysis from working and also generally is confusing for people to see that are only used to the fully qualified class name syntax.

The short alias syntax was invented when PHP did not have the magic class constant yet, so we recommend all users to change their code using short aliases to use them:

```diff
-  $entityManager->find('MyBundle:User', $id);
+  $entityManager->find(User::class, $id);
-  $entityManager->createQuery('SELECT u FROM MyBundle:User');
+  $entityManager->createQuery('SELECT u FROM ' . User::class');
```

This deprecation should be triggered only on using the aliases, not on configuring them. This way it does not get triggered if the alias is just defined but never used.

**Comment by Herz3h** [comment]
I have been using `getRepository($bundleName:$entityName);` what is the alternative now that this is not working anymore ?

Error says: `Solution: See the doctrine/deprecations logs for new alternative approaches.` but can't seem to find where that solution is.

**Comment by derrabus** [comment]
Use the FQCN of the entity class.
