### ISSUE TITLE
Nullable property type does still not translate to nullable SQL column

### ISSUE THREAD

**Issue by fridde** [doctrine/doctrine2#8834]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.9.3

#### Summary

It seems like making a property type nullable like this
```
 #[ORM\Column]
    protected ?string $Location = null;
```
does *not* translate to the SQL column being nullable, contrary to what [the docs say](https://www.doctrine-project.org/projects/doctrine-orm/en/2.9/reference/basic-mapping.html#php-types-mapping). It still has to be declared in the attribute as ```#[ORM\Column(nullable: true)]```.

#### How to reproduce

1. Create an entity using attributes, for example
```
#[ORM\Table(name: "users")]
class User
{
    #[ORM\Id, ORM\Column, ORM\GeneratedValue]
    protected int $id;

    #[ORM\Column]
    protected ?string $Name = null;
}
```
2. Set your mapping driver to "attribute".
3. Create a migration with ```.\bin\console make:migration```
4. Inspect the created migration and see that within the up()-method you see ```[...] Name VARCHAR(255) NOT NULL [...]```

#### Expected behavior
The last step should have contained ```[...] Name VARCHAR(255) DEFAULT NULL [...]```.

I think that @beberlei has been working on the implementation?

**Comment by beberlei** [comment]
Its not a bug, we had to remove it due to problems. The docs should have been updated though

**Comment by fridde** [comment]
Ah, okay. That's too bad.

But no, I can't find any change in the docs: [see here](https://github.com/doctrine/orm/blob/3c805b22b473a8599ebe7fc89d4f15c95b7bee89/docs/en/reference/basic-mapping.rst#L221) for the relevant line in the docs for 2.9.x.

I might be missing something though.
