### ISSUE TITLE
Rework sequence-based identity generation

### ISSUE THREAD

**Issue by morozov** [doctrine/doctrine2#8850]
Sequence-based identity values will be deprecated in DBAL `3.2.0` (https://github.com/doctrine/dbal/pull/4688) and removed in `4.0.x` (https://github.com/doctrine/dbal/pull/4691). See the details in https://github.com/doctrine/dbal/issues/4687.

The ORM currently uses this API: https://github.com/doctrine/orm/blob/f3e55fae9fdbdbc23897006bdbf016c20e11f6e9/lib/Doctrine/ORM/Id/IdentityGenerator.php#L52-L55

Please consider not relying on this API.

**Comment by greg0ire** [comment]
@beberlei I think this should go in a "DBAL 4" support project, shouldn't it? :smile:

**Comment by morozov** [comment]
In fact, this functionality in the ORM could be salvaged, if necessary. I updated the subject and the description.

The DBAL doesn't support using sequence values to implement `lastInsertId()` because it's not thread-safe but the sequences themselves are. The ORM could generate the identity value using a sequence explicitly and pass to the `INSERT` w/o relying on the `lastInsertId()` API in the same way as it does with UUIDs, for example:
```php
$id = $conn->execute('SELECT ' . $seqName . '.NEXTVAL FROM DUAL');
$conn->insert($table, ['id' => $id]);
```

In this case, the ORM should _not_ declare the column as `autoincrement` and should own the sequence, unlike the current implementation when the DBAL owns it.

It is also possible to leave the sequence ownership to the DBAL and have the column always auto-incremented via a trigger. In this case, the ORM should use a query like:
```sql
INSERT INTO table VALUES (...) RETURNING id INTO :id;
```
And then use an out parameter to get the id.

**Comment by stof** [comment]
This is about using a SequenceGenerator instead of a IdentityGenerator then (as that's what the SequenceGenerator does)

**Comment by stof** [comment]
I suggest instead deprecating the support for sequence-based IdentityGenerator, so that projects using a platform that does not support identity columns have to use something else (for instance the SequenceGenerator)

**Comment by onurkose** [comment]
Hello, today I changed the id columns' strategy from IDENTITY to SEQUENCE in my entities after reading the deprecation messages, and now all the insert statements have `null` id field values if the entity is using JOINED type entity inheritance.

`setIdentifierValues` method of `ClassMetadataInfo` class sets the new ids to reflection class, but then it turns into `null` somehow.
