### ISSUE TITLE
Get PHPUnit to run with DBAL 3

### ISSUE THREAD

**Issue by greg0ire** [doctrine/doctrine2#8886]
[Recently, a CI job was added on the 2.10.x branch to run the test suite this project after forcing the installation of `doctrine/dbal` v3](https://github.com/doctrine/orm/pull/8874).

In order not to disrupt contributors, we made sure it would not fail the build although it really does not pass at all:

https://github.com/doctrine/orm/blob/e09f126abfec0add53dc1ed8d4e3708117032fc1/.github/workflows/static-analysis.yml#L52

Right now, we get a crash without PHPUnit actually running, so we don't even know how many errors and failures there will be in the end. A good first step would be to fix that crash and get to a state where you can see the whole test suite running (with errors and failures)
If you want to help us fix it or get closer to fixing it, you can reproduce the issue locally by running (from the 2.10.x branch)

```shell
composer require doctrine/dbal ^3.0
vendor/bin/phpunit
```

When this issue is fixed, we should create a new one about making the tests pass.

**Comment by derrabus** [comment]
The "crash" happens because the test suite contains mock versions of various DBAL classes that simply don't fit anymore. I have a half-baked solution that allowed me to run the tests to a certain degree. But we should rethink if mocking internal DBAL class structures is really the way to go. It's going to be hard to create a set of mocks that works with both DBAL 2 and 3.

**Comment by greg0ire** [comment]
Getting rid of mocks of classes from an external package sounds good to me 👍
If it's not possible, then maybe the solution would be to have the mocks in question be provided by `doctrine/dbal` itself, I don't know if it makes sense yet.

**Comment by derrabus** [comment]
I can look into reducing the mocks on the weekend, maybe. If nobody else wants to pick this ticket before that, of course. 😁

**Comment by greg0ire** [comment]
To anyone reading this: consider starting with #8884 / #8885 first, they might be easier :slightly_smiling_face:
