### ISSUE TITLE
Move `getSQLResultCasing` code into ORM from DBAL

### ISSUE THREAD

**Issue by beberlei** [doctrine/doctrine2#8887]
DBAL 2 deprecates and DBAL 3 removes the `getSQLResultCasing` API, which we use to work around Oracle, PostgreSQL and MySQL differences in the default result casing. 

To avoid a larger refactoring and be forwards compatible, we need move this functionality into ORM and provide a strategy pattern with different implementations based on DBAL 2 or 3.

```php
interface ResultCasingStrategy
{
    public function getSQLResultCasing(string $string) : string;
}
class DBAL2ResultCasingStrategy implements ResultCasingStrategy {
     public function getSQLResultCasing(string $string) : string {
         return $this->platform->getSQLResultCasing($string);
     }
}
class UpperCaseResultCasingStrategy implements ResultCasingStrategy {}
class LowerCaseResultCasingStrategy implements ResultCasingStrategy {}
class NullCasingStrategy implements ResultCasingStrategy {}
```
A factory method at some point in the ORM should select the right strategy based on DBAL version and database platform and make the service available to everyone who needs sql result casings.

**Comment by greg0ire** [comment]
Actually, I don't think the factory part has been done. @beberlei , can you please review #8934 and tell us if more work is necessary?

**Comment by beberlei** [comment]
@greg0ire its flexible enough that I believe this issue can be closed for now.
