### ISSUE TITLE
ResultSetMappingBuilder creates a life of it's own and starts querying the database without being asked to, resulting in errors

### ISSUE THREAD

**Issue by ghost** [doctrine/doctrine2#8970]
I have a very simple code:

        $rsm = new ResultSetMappingBuilder($this->_em);
        $rsm->addRootEntityFromClassMetadata('App\Entity\Order', 'o');
        $query = $this->_em->createNativeQuery('CALL usp_order_s_orders()', $rsm);
        $orders = $query->getResult();

This code works at first. It calls the procedure and populates an array of Order entities.

However, if I add a one-to-one relation between the table Order and another table, say, OrderData, then the above code start QUERYING THE ORDERDATA TABLE.

Now, first of all this should NEVER happen. All queries going into and from the database in my application are controller via procedures, and are appropriately logged. No "SELECT" query should be emitted by Doctrine without me knowing about it. It is doing that under the hood, this behavior is completely undocumented, and this is a very, very bad security and design issue and makes me very worried about using Doctrine at all.

Second, this insane behavior also leads to a bug. The select query looks something like this

"SELECT t0.everyfieldintheworld WHERE t0.order_id = ? [1] FROM order_data"

Leading to this error message:

request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing Giant Query: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute." at path/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 128 {"exception":"[object] (Doctrine\DBAL\Exception\DriverException(code: 0): An exception occurred while executing Giant Query:\n\nSQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute. at path/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:128)\n[previous exception] [object] (Doctrine\DBAL\Driver\PDO\Exception(code: HY000): SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute. at path/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute. at path/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:112)"} []

**Comment by lcobucci** [comment]
@davidmoseler the behaviour is documented in https://www.doctrine-project.org/projects/doctrine-orm/en/2.9/reference/faq.html#why-is-an-extra-sql-query-executed-every-time-i-fetch-an-entity-with-a-one-to-one-relation

(As far as I remember - it's been a while) this extra query will be executed during hydration when the result set and the result set map doesn't reference the associated entity. Try updating the query to perform a join and adding the joined entity to the RSM, that should be enough to solve your issue. 

I agree that the docs could detail this better - it's OSS, though, so you may also help us with improving things.

More details on eager loading: https://www.doctrine-project.org/projects/doctrine-orm/en/2.9/reference/working-with-objects.html#by-eager-loading

It's also good to highlight: this behaviour assumes that the project uses buffered queries (which is PHP's defaults).

**Comment by lcobucci** [comment]
@derrabus @greg0ire this looks like a good candidate for a Q&A discussion instead of an issue 😁
