### ISSUE TITLE
Documentation for PSR-6 caches

### ISSUE THREAD

**Issue by derrabus** [doctrine/doctrine2#9003]
In 2.10, we will be able to configure all ORM caches through PSR-6 (#9002). We should update the documentation accordingly.

**Comment by SenseException** [comment]
Do you suggest a rewrite of https://www.doctrine-project.org/projects/doctrine-orm/en/2.10/reference/caching.html because the Cache component is completely deprecated? I don't think we should keep the old caching docs for ORM in > 2.10.

**Comment by derrabus** [comment]
I would remove the section about the various drivers. That section does not make sense anymore since Doctrine Cache is not the recommended solution anymore. And the cache library the app developer chooses will certainly document their cache adapters in their own documentation.

The "Integrating with the ORM" part is pretty much still valid, I guess. I was thinking about using Symfony Cache in the examples with a prior not that we recommend Symfony Cache, but any other PSR-6 implementation would work as well.
