### ISSUE TITLE
Type error in Query.php

### ISSUE THREAD

**Issue by akosphp** [doctrine/doctrine2#9086]
After upgrading to version 2.10.0 we are facing with the following error:

TypeError in file: Query.php on line 692
Message: Return value of Doctrine\ORM\Query::getMaxResults() must be of the type int or null, string returned

**Comment by derrabus** [comment]
Most likely, this means that you call `setMaxResults()` with a string somewhere.

**Comment by YetiCGN** [comment]
I think in most cases it's not userland code but another library. At least that's our problem with 2.10.0 and Sulu 2.3 at the moment. Or maybe it's a driver thing?

`setMaxResults()` isn't type-safe and doesn't throw a deprecation or other warning so I see why they would happily continue to set  the property as a string.

Edit: oic, #9079 is on the way to mitigate the problem. Thanks!
