### ISSUE TITLE
Return value of Doctrine\ORM\Query::getFirstResult() must be of the type int or null, string returned

### ISSUE THREAD

**Issue by knallcharge** [doctrine/doctrine2#9089]
### Bug Report

Calling getFirstResult() results in an error:
Return value of Doctrine\ORM\Query::getFirstResult() must be of the type int or null, string returned

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.10.0

#### Summary

After updating from 2.9.6 to 2.10.0 I'm getting this error, reverting back to 2.9.6 resolves this.

#### Current behavior

The above error is shown.

#### How to reproduce

Can't really build a stub to reproduce, the error is a result of a query by sg/datatablesbundle, it calls getIterator() in the Paginator which calls getFirstResult().

#### Expected behavior

Not seeing an error as with version 2.9.6, maybe related to #9086?

**Comment by derrabus** [comment]
Yes, the issues seems related and I would expect that a similar fix would help. Up for a PR?

**Comment by knallcharge** [comment]
see #9090

**Comment by derrabus** [comment]
Awesome, thanks!
