### ISSUE TITLE
Regression: abstract entities in the middle of a hierarchy need to be part of discriminator map

### ISSUE THREAD

**Issue by BenMorel** [doctrine/doctrine2#9095]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.9.x, 2.10.x

#### Summary

As mentioned in https://github.com/doctrine/orm/issues/8771#issuecomment-933454924, there is a regression that affects both `2.9` and `2.10`:

If an entity hierarchy has an abstract entity class in the middle of the hierarchy, Doctrine complains that it must be part of the discriminator map. Example:

- abstract class `A`
    - abstract class `B`
        - class `C`

`bin/console doctrine:schema:validate` reports:

>  [FAIL] The entity-class B mapping is invalid:
> * Entity class 'B' is part of inheritance hierarchy, but is not mapped in the root entity 'A' discriminator map. All subclasses must be listed in the discriminator map.

This doesn't make sense, as there cannot be an entry in the database for an abstract entity class.

**This was working fine up to Doctrine `2.8`.**

The quick fix for those affected is to add "fake" entries to the discriminator map for abstract child entities, that do not have an equivalent in the database `ENUM`; which is rather ugly.

**Comment by derrabus** [comment]
Do you want to work on a fix?

**Comment by BenMorel** [comment]
@derrabus Yes! I opened a PR in #9096, building on top of #8903.

I'm dubious as to whether it makes sense to have both `! $class->reflClass->isAbstract()` and `! $class->isMappedSuperclass` now though: does it make sense to have a non-abstract `@MappedSuperclass`? Isn't it enough to check if the class is abstract?

**Comment by derrabus** [comment]
Looks good to me. 🙂

**Comment by BenMorel** [comment]
Be careful that this has been reverted in #9262.

**Comment by mpdude** [comment]
#10420 suggests to fix this again; it should now be possible due to #10411.
