### ISSUE TITLE
[2.10] Unable to persist entites while using PrimaryReadReplicaConnection

### ISSUE THREAD

**Issue by lp-contentplus** [doctrine/doctrine2#9112]
Issue introduced in:
https://github.com/doctrine/orm/commit/afa837a3611490adbcf559fa9ea9db9dc04397a9

```
$this->_nextValue = (int) $conn->query($sql)->fetchColumn();
```
Deprecated method query() calls ensureConnectedToPrimary() inside. 
executeQuery() does not.

```
An exception occurred while executing 'SELECT NEXTVAL('...')':
SQLSTATE[25006]: Read only sql transaction: 7
```

**Comment by beberlei** [comment]
Good catch. This should maybe use `$conn->executeStatement($sql)` instead?

**Comment by lp-contentplus** [comment]
`executeStatement` also won't work (it returns the number of affected rows instead of the query result)
There is no direct replacement for `query()`

**Comment by anarxistkot** [comment]
Are there any solution options?
We need doctrine/dbal version 3.2 :(

**Comment by derrabus** [comment]
Does 2.10.4 fix your issue?

**Comment by ottaviano** [comment]
I just tested `2.10.4` and it works on my side, thanks

**Comment by derrabus** [comment]
All right, closing then. Thanks for verifying!
