### ISSUE TITLE
`spl_object_hash()` vs `spl_object_id()`

### ISSUE THREAD

**Issue by franmomu** [doctrine/doctrine2#9141]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.10

#### Summary

After https://github.com/doctrine/orm/pull/8837, there are some UoW methods that the parameter has changed:

https://github.com/doctrine/orm/blob/81d472f6f96b8b571cafefe8d2fef89ed9446a62/lib/Doctrine/ORM/UnitOfWork.php#L3243-L3254

https://github.com/doctrine/orm/blob/81d472f6f96b8b571cafefe8d2fef89ed9446a62/lib/Doctrine/ORM/UnitOfWork.php#L3025-L3040

Because the OID is different, [at first I thought they were internal](https://github.com/doctrine-extensions/DoctrineExtensions/pull/2271#issuecomment-948600889), but apparently it is some kind of [internal notes.](https://github.com/doctrine/orm/pull/1334) 

#### Previous behavior

Before this, for calling these method you should generate the oid with `spl_object_hash()`

#### Current behavior

Now that oid is not valid anymore.

#### How to reproduce

Tests started to fail in https://github.com/doctrine-extensions/DoctrineExtensions

**Comment by greg0ire** [comment]
Hi! Can you please link to the failing tests?

**Comment by franmomu** [comment]
Sure! 

- Failing: https://github.com/franmomu/DoctrineExtensions/runs/3968379322?check_suite_focus=true
- Here the `spl_object_hash` calls were changed to `spl_object_id`: https://github.com/franmomu/DoctrineExtensions/runs/3968449631?check_suite_focus=true (there are still some other failing test that I'll try to figure it out why, **update**: I guess it's because the failing ones are from ODM and there UoW uses `spl_object_hash`)

**UPDATE 2**: with an ugly fix to call `spl_object_hash()` for ODM and `spl_object_id()` for ORM tests pass: https://github.com/franmomu/DoctrineExtensions/pull/9

**Comment by greg0ire** [comment]
Great job! Since you are not stuck, I think it's fine not to revert this, and to document the minor BC-break.
