### ISSUE TITLE
AttributeOverride annotation is also an attribute but that is not reachable

### ISSUE THREAD

**Issue by brzuchal** [doctrine/doctrine2#9174]
### Bug Report

Annotation `AttributeOverride` carry `#[Attribute]` attribute unreasonably.

|    Q        |   A
|------------ | ------
| BC Break    |no
| Version     | 2.10.x

#### Summary

Currently `AttributeOverride` is an annotation but the class declaration also consists of `#[Attribute]` attributes.
This implies a false impression for the attribute to be usable while it's false because there is no way to apply it nor class constructor which could be used on entity class as an attribute.

**Comment by beberlei** [comment]
Planing this for 2.11 as a larger improvement to `AttributeDriver` with PHP 8.1 and nested attributes.

**Comment by beberlei** [comment]
Fixed in #9240
