### ISSUE TITLE
Column Hydrator

### ISSUE THREAD

**Issue by ThomasLandauer** [doctrine/doctrine2#9179]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

I'm using @ostrolucky 's Column Hydrator from https://gist.github.com/ostrolucky/f9f1e0b271357573fde55b7a2ba91a32
However, since DBAL 3, it's deprecated. So I'm suggesting to integrate its functionality directly into Doctrine:

Example:
 * ArrayHydrator: [['id' => 1], ['id' => 2]]
 * ColumnHydrator: [1, 2]

I could try if I can create a PR, but I'd need somebody to help me!

If you don't want to integrate this into Doctrine, then please update (or help me updating) the docs chapter "Custom Hydration Modes" at https://www.doctrine-project.org/projects/doctrine-orm/en/2.10/reference/dql-doctrine-query-language.html#custom-hydration-modes, cause (as far as I can see) this is outdated too.

**Comment by ostrolucky** [comment]
It was already added here https://github.com/doctrine/orm/pull/8919

**Comment by ThomasLandauer** [comment]
Great! Here are the docs: https://www.doctrine-project.org/projects/doctrine-orm/en/2.10/reference/dql-doctrine-query-language.html#scalar-column-hydration
