### ISSUE TITLE
BIGINT ids cause wrong ORM UPDATE statements against PostGreSQL

### ISSUE THREAD

**Issue by gnito-org** [doctrine/doctrine2#9503]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.11.1

#### Summary

Declaring an entity's id as BIGINT causes Doctrine ORM, during a ``flush`` operation, to update all unchanged managed entities (that happen to be in UnitOfWork at that point in time) with ``UPDATE table_name SET id = ? WHERE id = ?`` when operating against a PostGreSQL database. 

The same code works correctly when operating against a MySQL database. The erroneous ``UPDATE`` statements are not issued for MySQL.

This issue does not occur when the entity id is declared as INT.

#### How to reproduce

See the replicator at https://github.com/gnito-org/orm-postgresql-replicator.

**Comment by beberlei** [comment]
Bigints have to use a string php type, declaring them as property type int can cause type juggling to fail
