### ISSUE TITLE
Outdated doc

### ISSUE THREAD

**Issue by nimasdj** [doctrine/doctrine2#9562]
### Bug Report

Documentation is outdated here: https://www.doctrine-project.org/projects/doctrine-orm/en/2.11/reference/advanced-configuration.html#sql-logger-optional as EchoSQLLogger doesn't exist anymore in latest version. which class should I use?

**Comment by greg0ire** [comment]
In fact, the `SQLLogger` interface itself is deprecated in favor of using [a logging middleware](https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/architecture.html#logging)

**Comment by nimasdj** [comment]
Could you please provide a sample code line how to use this middleware instead of EchoSQLLoger?

**Comment by greg0ire** [comment]
Sure! 

```php
use Doctrine\DBAL\Logging as LoggingMiddleware;

$logger = new MyLogger(); // use your favorite psr/log instance here
$this->_em->getConnection()->getConfiguration()->setMiddlewares([new LoggingMiddleware($logger)]);
```

EDIT: actually this is wrong, changing the middlewares at runtime has no effect.

**Comment by nimasdj** [comment]
How can I use simple print instead of psr/log?

**Comment by greg0ire** [comment]
You can't, but you can extend https://github.com/php-fig/log/blob/master/src/AbstractLogger.php and implement `log()` with "simple print".

```php
$this->_em->getConnection()->getConfiguration()->setMiddlewares([new LoggingMiddleware(new class extends AbstractLogger {
    public function log($level, $message, array $context = []): void
    {
        var_dump(func_get_args());
    }
})]);
```

**Comment by raziel057** [comment]
@greg0ire While I was trying to fix a deprecation by replacing the usage of SQLLogger by a Logging Middleware in a Symfony command, I encountered an issue related here https://github.com/symfony/symfony/issues/46158

Can you please advice on the way to proceed. Or maybe you should allow to replace a the logger in the connection decorator created by the middleware?

**Comment by greg0ire** [comment]
I think you should open a feature request on `doctrine/dbal` clearly explaining why you need the logger to be different in some contexts.

**Comment by nimasdj** [comment]
> 

If I want to use https://github.com/php-fig/log/blob/master/src/AbstractLogger.php as you gave it in your sample code, do I need to have "use" line for this AbstractLogger.php? If yes, how should this "use" line be?

**Comment by greg0ire** [comment]
@nimasdj `use Psr\Log\AbstractLogger;`

**Comment by nimasdj** [comment]
> Sure!
> 
> ```
> use Doctrine\DBAL\Logging as LoggingMiddleware;
> 
> $logger = new MyLogger(); // use your favorite psr/log instance here
> $this->_em->getConnection()->getConfiguration()->setMiddlewares([new LoggingMiddleware($logger)]);
> ```
> 
> EDIT: actually this is wrong, changing the middlewares at runtime has no effect.

@greg0ire What is exactly wrong in your code above as you mentioned in "edit" area? How to improve the wrong thing you said?

**Comment by greg0ire** [comment]
It's too late, and I'm not only talking about your answer, which is 2 years late. I mean calling `setMiddlewares()` here is too late, the connection has already been built.

**Comment by nimasdj** [comment]
> It's too late, and I'm not only talking about your answer, which is 2 years late. I mean calling `setMiddlewares()` here is too late, the connection has already been built.

@greg0ire So how the code should be to fix it?
