### ISSUE TITLE
Memcached detection broken by Symfony/Cache 6.0.5

### ISSUE THREAD

**Issue by flack** [doctrine/doctrine2#9571]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.11.1

#### Summary

With `symfony/cache` 6.0.5, calling

```php
\Doctrine\ORM\Tools\Setup::createConfiguration();
```

causes the following exception:

```
Symfony\Component\Cache\Exception\CacheException: Memcached > 3.1.5 is required. in vendor/symfony/cache/Adapter/MemcachedAdapter.php on line 59
Doctrine\ORM\Tools\Setup::createConfiguration()	.../connection.php:182
Doctrine\ORM\Tools\Setup::createCacheConfiguration()	.../Setup.php:153
Doctrine\ORM\Tools\Setup::createCacheInstance()	.../Setup.php:169
Symfony\Component\Cache\Adapter\MemcachedAdapter->__construct()
```

#### Current behavior

See exception above

#### How to reproduce

- have `memcached` extension installed
- don't have `apcu` extension installed

#### Expected behavior

This happens due to symfony/symfony#45601. I guess a workaround would be to call `MemcachedAdapter::isSupported` before instantiating

**Comment by derrabus** [comment]
see symfony/symfony#45601

**Comment by flack** [comment]
Are you sure about the "Can't fix" resolution? Wouldn't something like this be enough to fix it?

```diff
diff --git a/lib/Doctrine/ORM/Tools/Setup.php b/lib/Doctrine/ORM/Tools/Setup.php
index f6c09f608..274218843 100644
--- a/lib/Doctrine/ORM/Tools/Setup.php
+++ b/lib/Doctrine/ORM/Tools/Setup.php
@@ -193,11 +193,13 @@ class Setup
             throw new RuntimeException('Setup tool cannot configure caches without doctrine/cache 1.11 or symfony/cache. Please add an explicit dependency to either library.');
         }
 
+        $memcachedAvailable = extension_loaded('memcached') && (class_exists(MemcachedCache::class) || MemcachedAdapter::isSupported());
+
         if ($isDevMode === true) {
             $cache = class_exists(ArrayCache::class) ? new ArrayCache() : new ArrayAdapter();
         } elseif (extension_loaded('apcu')) {
             $cache = class_exists(ApcuCache::class) ? new ApcuCache() : new ApcuAdapter();
-        } elseif (extension_loaded('memcached')) {
+        } elseif ($memcachedAvailable) {
             $memcached = new Memcached();
             $memcached->addServer('127.0.0.1', 11211);
```

**Comment by derrabus** [comment]
That "fix" would silently downgrade you from Memcached to an array cache after updating Symfony Cache to the latest version. Is that what you want? This is an issue that should be fixed upstream.

**Comment by flack** [comment]
IMHO, if you call `createConfiguration` without explicitly passing in the `$cache` that means "give me whatever configuration works" (I mean, that is the point of the autodetection, no?). Currently, the application will just die until you change something in your PHP installation (which may be shared by different apps), I don't see how that is better.

But well, at least it looks like there is going to be a new memcached release soonish, so the problem doesn't look so severe anymore :-)

**Comment by derrabus** [comment]
Yeah, you've got a point here. Do you want to work on a PR that implements the check you're proposing?

**Comment by flack** [comment]
alright, I've sent a PR: #9574

**Comment by derrabus** [comment]
Thanks!
