### ISSUE TITLE
Hydrating `enumType` as array gives *string* instead of Enum

### ISSUE THREAD

**Issue by janedbal** [doctrine/doctrine2#9622]
### Bug Report

As discussed in original topic: https://github.com/doctrine/orm/discussions/9588, but I see this as a bug as it behaves differently than any custom type. So migrating from enums used as custom types to this native form is impossible. Tested version: 2.11.2

#### Summary

```php
$queryBuilder = $this->createQueryBuilder('f')
    ->select('f.id, f.suit')
    ->getQuery()
    ->getResult() // suit is string, not Suit enum
;
```

#### Current behavior

Column defined as enumType gets hydrated as string when array hydration occurs.

#### How to reproduce

Use entity as [described](https://www.doctrine-project.org/2022/01/11/orm-2.11.html) and fetch from query builder as array.

#### Expected behavior

To be hydrated as enum.

**Comment by michnovka** [comment]
Ok, so given this some debugging and thought, this is a bit more difficult than it seemed. The reason why `find()`/`findAll()` methods hydrate the Enum type correctly is, that this is handled on the UoW level inside `createEntity()` through `ClassMetadata::reflFields[]->setValue()`. When using select of individual fields OR when using `getArrayResult()`, then hydration is done on individual fields and entity itself is not created.

**Comment by michnovka** [comment]
@derrabus I think that the issue here is that `AbstractHydrator::hydrateAll()` gets `$resultSetMapping` with `scalarMappings` set to `string` for `suit` column. I dont think I can access the `enumType` of the column from there. What would be the proper way? Can we leverage some other "mapping", like `fieldMapping`?

**Comment by michnovka** [comment]
So I see the `$resultSetMapping` is set inside `SqlWalker` here https://github.com/doctrine/orm/blob/f4d5283f705f6ac51e81c8299ace074a619b40d7/lib/Doctrine/ORM/Query/SqlWalker.php#L1335-L1352

Now the question is - do we introduce `enumMappings`? like

```php
if(!empty($fieldMapping['enumType'])) {
    $this->rsm->addEnumMapping($columnAlias, $fieldMapping['enumType']);
}
```

then when walking `$resultSetMapping->scalarMapping` check for `$resultSetMapping->enumMappings` and if present cast to enum.

Or do you have another idea? Can we leverage something already present in the `resultSetMapping`?
