### ISSUE TITLE
Schema tool does not dump correct sql after upgrade from 2.11 to 2.12

### ISSUE THREAD

**Issue by jaroslavlibal** [doctrine/doctrine2#9690]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.12.0

#### Summary

The new "listing" mode for SQL statements dumping removes semicolons at the end of the statements and adds an asterisk prefix to each line. 

https://github.com/doctrine/orm/pull/9019/files#diff-7579891fde50fb7e38d285004486c0210492efdbdc00815a978e053ff3cb0017R93

This new type of output significantly complicates the possibility of copying SQL statements.

#### Previous behavior

    The following SQL statements will be executed:
    
    CREATE TABLE authorized_identity (id UUID NOT NULL, identity_id UUID NOT NULL, PRIMARY KEY(id));

#### Current behavior

    The following SQL statements will be executed:
    
    * CREATE TABLE authorized_identity (id UUID NOT NULL, identity_id UUID NOT NULL, PRIMARY KEY(id))

**Comment by derrabus** [comment]
See #9679
