### ISSUE TITLE
sql_require_primary_key on mysql 8

### ISSUE THREAD

**Issue by wiseguy1394** [doctrine/doctrine2#9768]
### Bug Report
|    Q        |   A
|------------ | ------
| Version     | 2.12.2

#### Summary

We are running a managed database on DigitalOcean.
We are using a class table inheritance. If we now try to update one entity from this inheritance the `Doctrine\ORM\Query\Exec\MultiTableUpdateExecutor::class` is  called and creates a temporary table but the mysql option **sql_require_primary_key** is default **true**. So we are getting an SQL Exception that no primary key exists on this table.

We work around this issue setting **sql_require_primary_key** to **false** but the recommendation from DigitalOcean is:
*"For clusters with more than one node, we strongly recommend keeping sql_require_primary_key as True. Setting it to False may severely impact replication and cause issues."*

#### Current behavior
With **sql_require_primary_key** set to **true** we are getting a SQL Exception.

#### How to reproduce

Use a mysql8 Database, create an entity with  class table inheritance and try update an entity.

#### Expected behavior

Entity update works with **sql_require_primary_key** set to **true**.

**Comment by derrabus** [comment]
This setting really creates more problems than it solves, but I know that DigitalOcean is really stubborn about disabling it. Having a PK on a temporary table is often pointless and might even slow down the whole operation, but this option would force us to create a PK just to make MySQL happy.

Okay, that was my rant. Nevermind.

I agree that the ORM should be able to operate on MySQL databases that have this option enabled. Would you be willing to work on a fix?

**Comment by wiseguy1394** [comment]
I'll give it a try.

**Comment by wiseguy1394** [comment]
I have a working fix, but I don't know how to create a PR.
I would introduce a new method in `Doctrine\DBAL\Platforms\AbstractPlaform::class`  returning an empty string and then override it in `Doctrine\DBAL\Platforms\MySQL80Platform::class`. And in `Doctrine\ORM\Query\Exec\MultiTableUpdateExecutor::class` I would use it.

Do I need to add 2 PRs? One for each repo?
Or how does it work?
Thx.

**Comment by derrabus** [comment]
Let's try to not involve the DBAL in this.

**Comment by wiseguy1394** [comment]
Ok, than I have to hard code the SQL Snippet?!

All SQL statements are actually fetched from AbstractPlatform.

**Comment by derrabus** [comment]
The ORM is allowed to produce its own SQL, yes. 🙂
