### ISSUE TITLE
Delayed fetch eager

### ISSUE THREAD

**Issue by antman3351** [doctrine/doctrine2#9771]
### Feature Request

|    Q        |   A |
|------------ | ------|
| New Feature | yes |
| BC Break    | no |

#### Summary

Hi, 

Would it be possible to implement a delayed fetch eager for a query ?
The idea is, for a result of a query all associations are eager loaded but only when accessed ( a mix between lazy and eager ).

I have some use cases where the used associations are read at runtime ( user defined exports / print templates ). 

Because the data is being listed in a table format if the association is accessed once, it will be accessed for all the rows so eager loading the association would be best.

But because the templates are defined by the user, the association may also never be accessed, so eager loading all the associations is over-kill.

Also this would prevent the issue when in a "listing" view an associated column is added without adding FETCH_EAGER to the query possibly creating performance issues.

**Comment by derrabus** [comment]
I believe this would be difficult to implement, but if you want to give it a shot, go ahead.

**Comment by beberlei** [comment]
There is a PR for this called #8391 where I discuss that this could replace fetch eager.

**Comment by antman3351** [comment]
Super! I'll close this then 👍
