### ISSUE TITLE
Cached proxy classes have no data loaded

### ISSUE THREAD

**Issue by jarrettj** [doctrine/doctrine2#9882]
Using:

doctrine/orm 2.7.5
doctrine/doctrine-orm-module 1.1.8

SImply writing results to cache and then reading them. WhenI try to use the objects returned though, it seems that the lazy loaded objects have no data associated with them anymore.

```
// Register proxy class path for autoloading
// https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/advanced-configuration.html#autoloading-proxies
$proxyDir = __DIR__ . '/src/Application/Proxy';
$proxyNamespace = "Application\Proxy";
Autoloader::register($proxyDir, $proxyNamespace);
```

Then my cache is simply
```
// Get it it exists and cache if not found
$mattersAll = $this->cache->fetch('matters-all');
if (!$mattersAll) {
    $mattersAll = $this->getActiveMatters($summary);
    $this->cache->save('matters-all', $mattersAll);
}
```

It saves and reads it back fine, but for some reason if I try to use the related lazy loaded class to get data it fails and returns null for the data, instead of the values.

Any help would be much appreciated. Thanks.

Regards,
Jarrett

**Comment by greg0ire** [comment]
Closing in favor of #9881
