### ISSUE TITLE
Attribute breaking self-joining table

### ISSUE THREAD

**Issue by steveclifton** [doctrine/doctrine2#9898]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.3.7

#### Summary

Attributes breaking self-joining entity 

#### Current behaviour

Error message
```
"An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'geo_display_suburb_neighbour.display_suburb_source' in 'where clause'"
```

Query
```
SELECT [...fields] FROM geo_display_suburb t0 INNER JOIN geo_display_suburb_neighbour ON t0.id = geo_display_suburb_neighbour.display_suburb_target WHERE geo_display_suburb_neighbour.display_suburb_source = 56;
```

When switching BACK to Annotations, It works fine. However using Attributes I get the error message
```
/**
 * @ORM\ManyToMany(targetEntity="DisplaySuburb", cascade={"persist"})
 * @ORM\JoinTable(name="geo_display_suburb_neighbour",
 *     joinColumns={@ORM\JoinColumn(name="suburb_id", referencedColumnName="id")},
 *     inverseJoinColumns={@ORM\JoinColumn(name="suburb_id_neighbour", referencedColumnName="id")}
 * )
 */
private $neighbours;
```

```
#[ORM\ManyToMany(targetEntity: self::class, cascade: ['persist'])]
#[ORM\JoinTable(
    name: 'geo_display_suburb_neighbour',
    joinColumns: [new JoinColumn(name: 'suburb_id', referencedColumnName: 'id')],
    inverseJoinColumns: [new JoinColumn(name: 'suburb_id_neighbour', referencedColumnName: 'id')]
)]
private $neighbours;
```
#### How to reproduce
Using a selfjoining table

#### Expected behaviour

Returning DisplaySuburb neighbours

**Comment by beberlei** [comment]
This is not an error, you need to move the join column and inverse join column to the top level as shown here:

https://www.doctrine-project.org/projects/doctrine-orm/en/2.11/reference/attributes-reference.html#attrref_joincolumn

**Comment by b1rdex** [comment]
@beberlei I think the docs should be corrected then:

> A notable difference to the annotation metadata support, #[JoinColumn] and #[InverseJoinColumn] can be specified at the property level and are not nested within the #[JoinTable] attribute.

Notice the *can* there. There is no way to guess it means must :D

Spent an hour digging the problem here, moving `joinColumns` and `inverseJoinColumns` to attributes works.

<img width="903" alt="image" src="https://user-images.githubusercontent.com/312855/179755948-f31e2d07-308b-4948-a3ca-4e6dbfd2e8d6.png">

Also, I think this is a BC and the code should throw an error when `joinColumns` and `inverseJoinColumns` are used on `JoinTable` attribute.
