### ISSUE TITLE
create generic EntityInterface

### ISSUE THREAD

**Issue by arderyp** [doctrine/doctrine2#9901]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | ?
| BC Break    | probably

#### Summary

For those of us who use PHPStan/Psalm, which are increasing in popularity, there should be an EntityInterface. It could be blank, or maybe have a single `getId()` method.  This would resolved a lot of the `mixed` typing with Doctrine.  I have done this myself, and all of my entities implement it, and I've created a stub to get around some of the `mixed` mess, for example:

```
<?php

declare(strict_types=1);

namespace Doctrine\ORM;

use App\Entity\EntityInterface;


abstract class AbstractQuery
{
    public const HYDRATE_OBJECT = 1;

    /**
     * @param string|int|null $hydrationMode
     * @phpstan-ignore-next-line [STUB] we are overriding the return type
     */
    public function getOneOrNullResult($hydrationMode = null): ?EntityInterface;

    /**
     * see: https://github.com/phpstan/phpstan-doctrine/issues/301
     * @param string|int $hydrationMode
     * @phpstan-ignore-next-line [STUB] we are overriding the return type
     */
    public function getResult($hydrationMode = self::HYDRATE_OBJECT): array;

    /**
     * @param string|int|null $hydrationMode
     * @phpstan-ignore-next-line [STUB] we are overriding the return type
     */
    public function getSingleResult($hydrationMode = null): EntityInterface;
}
```

**Comment by greg0ire** [comment]
> some of the mixed mess

What are you talking about?

Implementing an interface owned by Doctrine inside your domain is not the right direction.

**Comment by arderyp** [comment]
The `mixed` mess is the copious amounts of `mixed` type all over doctrine that result, in part, from using POPO entities.  The general trend in PHP, like many other dynamically typed languages, is to slowly faze in stronger typing.  Static analysis tools are a major part of this.  Its a really beneficial trend, in my opinion.  That said, implementing typing by simply using `mixed` everywhere kind of defeats the purpose. It's like migrating one's code from vanilla JavaScript to TypeScript, and simply defining everything as `any` just to get their code compiled and working. Yes, this works, but it seems to diverge from the intentions of strong typing.  Maybe there's a more valid reason Doctrine does it, given it's highly dyanmic nature, but I thought it was a pretty obvious conversation worth having.

> Implementing an interface owned by Doctrine inside your domain is not the right direction.

Not I must reflect your own wording back to you and ask, what are _you_ talking about?  Are you talking about the stub, or the idea of me implementing a theoretical, Doctrine-owned `EntityInterface` object? If the later, isn't this what all of us do every day as we consume and use third party libraries? Symfony, for example, provides a lot of very handy interfaces that I implement within my own domain.  Yes, this is coupling, but that's not always a huge concern in all contexts.

**Comment by arderyp** [comment]
I appreciate the feedback by the way. Maybe I'm thinking about this wrong. I've found it hugely helpful for typing in my app though.

**Comment by greg0ire** [comment]
> the idea of me implementing a theoretical, Doctrine-owned EntityInterface object

This is what I'm talking about.

> If the later, isn't this what all of us do every day as we consume and use third party libraries?

Hopefully not. Hopefully, you couple your application or your infrastructure layer to third party libraries, but not your domain.

Doctrine1, with its active records forced you to extend a Doctrine-owned class. With Doctrine 2, the only thing that ties you to Doctrine inside your domain is the usage of collections, which tie you to `doctrine/collections`, a much smaller library than Doctrine 1.

Also, it would be wrong to have the above return an interface, because they might not even return an object, in case you use the array hydration mode, for instance.

And even if we followed your suggestion, there wouldn't be much benefit for the calling code, besides knowing you could call a method `getId()`. And take note that the identifier for a Doctrine entity does not have to be called `id`, so that would be an extra constraint.

**Comment by arderyp** [comment]
fair enough, thanks for the insight
