### ISSUE TITLE
Wrong parameter passed to the registerManaged method of AbstractHydrator

### ISSUE THREAD

**Issue by antonioturdo** [doctrine/doctrine2#9944]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | Found on 2.8.2, but code seems unchanged until 2.12.x

#### Summary

The registerManaged method of AbstractHydrator is receiving wrong parameters when called from ObjectHydrator. 

#### Current behavior

When the HINT_REFRESH_ENTITY hint is used the second parameter of the call is the hint value:

```
if (isset($this->_hints[Query::HINT_REFRESH_ENTITY]) && isset($this->rootAliases[$dqlAlias])) {
    $this->registerManaged($this->_metadataCache[$className], $this->_hints[Query::HINT_REFRESH_ENTITY], $data);
}
```

but the method implementation second parameter is an entity object. This obviously results in an error when the parameter is treated as an object.

#### How to reproduce

Use the HINT_REFRESH_ENTITY hint in a query.

#### Expected behavior

Get the query results, instead of an error!

**Comment by derrabus** [comment]
Would you be able to work on a PR that reproduces the bug with a test and fixes it?

**Comment by antonioturdo** [comment]
Sorry, i was just using the wrong hint. I wasn't supposed to use HINT_REFRESH_ENTITY, but HINT_REFRESH. So there is no bug, I close the issue.
