### ISSUE TITLE
Command `orm:validate-schema` doesn't take `#[Table(schema: 'my_schema')]` into account

### ISSUE THREAD

**Issue by Aerendir** [doctrine/doctrine2#9991]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | About since 2020/07

#### Summary

On PostgreSQL, when specifying the `schema` in which to create the table, the command `orm:validate-schema` always returns an error saying the schema is not in synch. Removing the `schema` parameter from the attribute solves the problem and the command correctly says the schema is in sync.

Version of PostgreSQL used: 12

#### Current behavior

Tested through Symfony, each time I run `symfony console doctrine:schema:validate` it says the schema is not in sync.
It started with this error around 2020/07 but I never put too much attention to the issue.
Now I have started to work again on the app and faced this issue again.

After many hours of debugging, I found that the problem is the `schema` property of the `Table` attribute/annotation.

It seems the command doesn't take into account the schema when evaluating the syncing of the schema.

#### How to reproduce

1. Create a Symfony app
2. Create an entity with this attribute: `#[Table(name: 'yuor_name', schema: 'a_custom_schema')]`
3. `symfony console doctrine:database:create`
3. `symfony console doctrine:schema:create`
4. `symfony console doctrine:schema:validate`

The error should appear.

#### Expected behavior

The command return `0` (Success) as the database is correctly in synch.

**Comment by aleho** [comment]
I started having this issue with DBAL 3.4.0.

After a bit of debugging I was able to trace it to the `SEARCH_PATH` implementation.
Apparently the comparator cannot handle search paths correctly if there are multiple schemas involved.

Changing the search path to all schemas involved breaks 3.3 and doesn't fix the issue on 3.4.

**Comment by aleho** [comment]
@Aerendir Does `doctrine/dbal:^3.4.1` solve this for you? Because for me it does.

**Comment by Aerendir** [comment]
@aleho , yes, it solved the issue for me, too! 🎉
Thank you for your support!
